### ISSUE TITLE
Support for IKEA TRADFRI bulb E27 WS opal 980lm

### ISSUE THREAD

**Issue by mkan1512** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#10]
**MQTT message:** 
zigbee2mqtt/Led1545G12 {'state': 'ON', 'device': {'type': 'Router', 'modelId': 'TRADFRI bulb E27 WS opal 980lm', 'friendlyName': 'Led1545G12', 'manufId': 4476, 'ieeeAddr': '0xd0cf5efffe216e85', 'nwkAddr': 54317, 'manufName': 'IKEA of Sweden', 'powerSource': 'Mains (single phase)', 'status': 'online'}}

zigbee2mqtt/<DEVICE_ID>/set

```
{
  "state": "ON",   "brightness": 255,   "transition": 3, "color_temp": 50
}
```

**Comment by Gemies** [comment]
Is it possible to add this bulb.

**Comment by Gemies** [comment]
Here are the lines from configuration database.db from zigbee2mqtt. Maybe this will help. This is the data from the 2 bulbs i have of this type of tradfribulb.

{"id":9,"type":"Router","ieeeAddr":"0xd0cf5efffe1dd78e","nwkAddr":18886,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E27 WS opal 980lm","epList":[1],"status":"online","joinTime":1541364192,"endpoints":{"1":{"profId":49246,"epId":1,"devId":544,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"10":{},"65533":1,"zclVersion":1,"appVersion":17,"stackVersion":87,"hwVersion":1,"manufacturerName":"IKEA of Sweden","modelId":"TRADFRI bulb E27 WS opal 980lm","dateCode":"20170331","powerSource":1}},"genIdentify":{"dir":{"value":1},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genScenes":{"dir":{"value":3},"attrs":{"65533":1,"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"65533":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"15":0,"16384":254,"65533":1,"currentLevel":254,"remainingTime":0,"onOffTransitionTime":5,"onLevel":255}},"genOta":{"dir":{"value":2},"attrs":{}},"genPollCtrl":{"dir":{"value":2},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{"15":0,"16397":0,"16398":370,"65533":1,"remainingTime":0,"currentX":30138,"currentY":26909,"colorTemperature":370,"colorMode":2,"numPrimaries":0,"enhancedColorMode":2,"colorCapabilities":16,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}},"haDiagnostic":{"dir":{"value":1},"attrs":{"65533":1,"numberOfResets":0,"macRxBcast":0,"macTxBcast":0,"aPSRxBcast":0,"aPSTxBcast":0,"nwkFcFailure":0,"packetBufferAllocateFailures":0,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":124,"lastMessageRssi":-69}},"lightLink":{"dir":{"value":3},"attrs":{"65533":1}}}}},"_id":"6LZdmmw4Jx81oUef"}

{"id":8,"type":"Router","ieeeAddr":"0x90fd9ffffe08d3ba","nwkAddr":61515,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E27 WS opal 980lm","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":49246,"epId":1,"devId":544,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"10":{},"65533":1,"zclVersion":1,"appVersion":17,"stackVersion":87,"hwVersion":1,"manufacturerName":"IKEA of Sweden","modelId":"TRADFRI bulb E27 WS opal 980lm","dateCode":"20170331","powerSource":1}},"genIdentify":{"dir":{"value":1},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genScenes":{"dir":{"value":3},"attrs":{"65533":1,"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"65533":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"genPollCtrl":{"dir":{"value":2},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}},"haDiagnostic":{"dir":{"value":1},"attrs":{}},"lightLink":{"dir":{"value":3},"attrs":{}}}}},"_id":"RXM01kAtFU2MVyg8"}

**Comment by Gemies** [comment]
This is Koen Kanters says:

IKEA TRADFRI LED bulb E27 980 lumen, dimmable, white spectrum, opal white (LED1545G12)

{
  "state": "ON",
  "brightness": 215,
  "color_temp": 325
}

**Comment by Gemies** [comment]
Can you explain how?

**Comment by Gemies** [comment]
I am not sure if it is reaching the ultimate level of opal colour. Maybe the color temp should be higher?

**Comment by stas-demydiuk** [comment]
Any ideas what is the maximum value?

**Comment by Gemies** [comment]
@stas-demydiuk 

This is what i found on a home assistent forum it says something about brightness and color_temp

[zigatelog.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/2573680/zigatelog.txt)

this is from my domoticz log when i switch brightness and color temp. The color temp does not change.

2018-11-12 22:32:07.643 Status: User: Admin initiated a switch command (10/Zigbee - tradfribulbcol_2/Set Level)
2018-11-12 22:32:09.402 Status: User: Admin initiated a switch command (10/Zigbee - tradfribulbcol_2/On)
2018-11-12 22:32:13.033 Status: setcolbrightnessvalue: ID: a, bri: 99, color: '{m: 2, RGB: 000000, CWWW: 2bd4, CT: 212}'
2018-11-12 22:32:18.084 Status: setcolbrightnessvalue: ID: a, bri: 99, color: '{m: 2, RGB: 000000, CWWW: 1ee1, CT: 225}'
2018-11-12 22:32:18.598 Status: setcolbrightnessvalue: ID: a, bri: 99, color: '{m: 2, RGB: 000000, CWWW: 04fb, CT: 251}'

**Comment by stas-demydiuk** [comment]
@Gemies I've increased the range to 500, could you please check now

**Comment by Gemies** [comment]
@stas-demydiuk Now it works perfectly. Thanks for your time and effort.
