### ISSUE TITLE
Double devices

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#100]
**Issue description**
Recently (last week) I have (had?) some trouble with zigbee2mqtt
**Additional information**
Zigbee2MQTT version:  version 1.2.1 (commit #91bc56a)
Python version: Python 2.7.13 and Python 3.5.3
Domoticz version: 4.10533
Plugin version: 0.0.18

For a week ago everything was working fine. Then I got in to trouble https://github.com/Koenkk/zigbee2mqtt/issues/1337 in that time that I have trouble, the plugin wants to create the existing devices again. I opened ' add new devices' in Domoticz. The errors from the plugin are gone, but now I am left every devices duplicated. only difference is the Unit number.
846 | Zigbee | 0x00158d0002b7d689_light | 2 | Zigbee - Overlooplamp | Color Switch | WW | Off
819 | Zigbee | 0x00158d0002b7d689_light | 46 | Overloop lamp | Color Switch | WW | Off

Both devices (at least I tested the switches) are working fine and the same.
How can this be solved?

**Comment by stas-demydiuk** [comment]
That's very strange, I would suggest to manually remove duplicated devices with higher unit number

**Comment by SargonofAssyria** [comment]
I suppose that the unit numbering is done by the plugin and done in order that a device is coming in.
The order is totally different from the initial setup. I also suppose that the Domoticz ID is the link to device.
In this example '0x00158d0002b7d689_light' that ID was there and should be found by the plugin.
Why delete the higher unit number? This way I get a mixture of 'old' and 'new' devices. Is the unit number used by the plugin?

**Comment by stas-demydiuk** [comment]
@SargonofAssyria you are right, plugin uses ID field to find proper device. I see that both devices you've provided have the same ID, that's why I suggested to remove newer device because old one might already have some log. But actually if log doesn't important for you, you can remove any device

**Comment by SargonofAssyria** [comment]
Oke, I removed the newer devices, and it seems that everything is working OK.
Still strange that this happened.
