### ISSUE TITLE
TemperatureHumidityBarometerSensor does not create right devices in Domoticz

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#102]
**Issue description**
TemperatureHumidityBarometerSensor : this devices creates a Pressure sensor in Domoticz, despite the "Barometer" in the name. In fact it is a barometer reading which comes out of the sensor. So I think that the created subtype is incorrect. Advantage is also that the Barometer device is positioned in the Weather Tab of Domoticz instead of the Utility Tab as the Pressure device is.
I am talking about the Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM) where the word pressure is misleading and should be barometer.

**Comment by stas-demydiuk** [comment]
@SargonofAssyria could you please explain difference between pressure and barometer in this case?

**Comment by SargonofAssyria** [comment]
https://en.wikipedia.org/wiki/Pressure and https://en.wikipedia.org/wiki/Barometer
Main difference is that Barometer only covers 'Air' pressure. In case of WSDCGQ11LM we only measure air (pressure). This is (can be) used in Weather prediction.
In Domoticz there is a difference where the device is visible.
Pressure is visible in the Utility tab and Barometer is visible in the Weather tab.

**Comment by stas-demydiuk** [comment]
Available in latest master branch

**Comment by SargonofAssyria** [comment]
Tnx, but unfortunately NOT fully correct. nValue is incorrectly filled.
The nValue should be 0 and the sValue should be 1003;3
Where the 1003 is the barometric pressure and the 3 is the Prediction

**Comment by stas-demydiuk** [comment]
@SargonofAssyria Ok, I will add. Are you sure about the numbers, I have these descriptions for forecast, but don't remember where I found them:
Forecast (0 - None, 1 - Sunny, 2 - PartlyCloudy, 3 - Cloudy, 4 - Rain)

And I guess it is also applicable for #110

**Comment by SargonofAssyria** [comment]
Yes, it's also  applicable for #110
It is an approximation, real formula might be to complex.
You can find it in the code here:  https://www.domoticz.com/forum/viewtopic.php?t=10822
And more detailed here: http://www.freescale.com/files/sensors/doc/app_note/AN3914.pdf

**Comment by stas-demydiuk** [comment]
@SargonofAssyria could you please update and check?

**Comment by SargonofAssyria** [comment]
Tnx, for the update, it works perfectly.
