### ISSUE TITLE
Gledopto S-004Z support wanted

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#103]
**Device description**
GLEDOPTO GL - S - 004Z ZIGBEE Smart GU10 5W LED Spotlight Bulb for Home - White WW/CW

Reported by Zigbee@MQTT as S-004Z

{"id":7,"type":"Router","ieeeAddr":"0x00124b001b9223a2","nwkAddr":49254,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-S-004Z","epList":[11,13],"status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}}}},"13":{"profId":49246,"epId":13,"devId":544,"inClusterList":[4096],"outClusterList":[4096],"clusters":{"lightLink":{"dir":{"value":3},"attrs":{}}}}},"_id":"2Tg9cVjyrg0iQm33"}

**Comment by stas-demydiuk** [comment]
@ArJay60 I don't see this device in [supported devices list](https://www.zigbee2mqtt.io/information/supported_devices.html) at the moment

**Comment by ArJay60** [comment]
SUbmitted request to add it to Zigbee2MQTT. Keep you posted on progress there.

**Comment by ArJay60** [comment]
@stas-demydiuk : Device is added to devices.js . see https://github.com/Koenkk/zigbee-shepherd-converters/issues/390. But still not added tot supported devices page. Can you add while still not being seen officialy on supported devices list for zigbee2mqtt?

**Comment by stas-demydiuk** [comment]
Done, should be available with latest plugin

**Comment by ArJay60** [comment]
And working. Thanks for the super service.
