### ISSUE TITLE
JTYJ-GD-01LM/BW	Xiaomi MiJia Honeywell smoke detector (smoke)

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#107]
**Issue description**
Status info should be send to Domoticz.
See: https://github.com/Koenkk/zigbee2mqtt/issues/1413
And: https://github.com/Koenkk/zigbee2mqtt/issues/391

**Additional information**
Zigbee2MQTT version: 1.3.0 (commit #da94252)
Python version: 3.5.3
Domoticz version: 4.10602
Plugin version: 0.0.18

**Comment by stas-demydiuk** [comment]
@SargonofAssyria could you please explain what behavior do you expect?

**Comment by SargonofAssyria** [comment]
At least that the 'Last Seen' is updated.
It would be nice if a status button is created and updated if the test button has been pressed.
This way a message can be produced every month that a device is tested or not.
Or at least that the Smoke device it self is triggered.

**Comment by stas-demydiuk** [comment]
@SargonofAssyria  the issue should be fixed with plugin in the latest master branch. Plugin now updates "Last Seen" when receive messages from devices (this feature is supported only by last betas of Domoticz)

**Comment by SargonofAssyria** [comment]
Tnx, My smoke sensors updates the "Last Seen" now.
