### ISSUE TITLE
Errors in log fle 

### ISSUE THREAD

**Issue by HJKLMN** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#109]
**Issue description**
Put general information here

**Additional information**
Zigbee2MQTT version:  Latest
Python version: Python 2.7.15rc1
Domoticz version: 
2019-04-14 20:52:02.639  Status: Domoticz V4.10532 (c)2012-2019 GizMoCuz
2019-04-14 20:52:02.639  Status: Build Hash: 414dfe3d, Date: 2019-02-28 15:51:54
Plugin version: Latest

**Logs**
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) 'onMessage' failed 'KeyError'.
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) ----> Line 193 in '/opt/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) ----> Line 106 in '/opt/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) ----> Line 167 in '/opt/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) ----> Line 166 in '/opt/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-04-14 20:32:58.985 Error: (Zigbee2mqttC2530) ----> Line 64 in '/opt/domoticz/plugins/zigbee2mqtt/adapters/ikea/tradfri_remote_control.py', function handleMqttMessage

**Comment by salopette** [comment]
your Python version is too old

Python Version: 3.5.3 is current

**Comment by HJKLMN** [comment]
python3 -V
Python 3.6.7

Still same errors.

**Comment by stas-demydiuk** [comment]
@HJKLMN could you please provide your MQTT message after what this error appears

**Comment by Timon48** [comment]
Hi Satas,
I have the same issue, maybe my log coud help you to rsolve it.

> 2019-04-28 17:34:38.675 Error: (ZigBee) 'onMessage' failed 'KeyError'.
> 2019-04-28 17:34:38.675 Error: (ZigBee) ----> Line 193 in /domoticz/plugins/domoticz-zigbee2mqtt-plugin/plugin.py, function onMessage
> 2019-04-28 17:34:38.675 Error: (ZigBee) ----> Line 106 in /domoticz/plugins/domoticz-zigbee2mqtt-plugin/plugin.py, function onMessage
> 2019-04-28 17:34:38.675 Error: (ZigBee) ----> Line 167 in /domoticz/plugins/domoticz-zigbee2mqtt-plugin/mqtt.py, function onMessage
> 2019-04-28 17:34:38.675 Error: (ZigBee) ----> Line 146 in /domoticz/plugins/domoticz-zigbee2mqtt-plugin/plugin.py, function onMQTTPublish
> 2019-04-28 17:34:38.675 Error: (ZigBee) ----> Line 47 in /domoticz/plugins/domoticz-zigbee2mqtt-plugin/device_storage.py, function update

> 2019-04-28 17:33:35.565 Status: Domoticz V4.9700 (c)2012-2018 GizMoCuz
> 2019-04-28 17:33:35.566 Status: Build Hash: a3a45906, Date: 2018-06-23 18:24:51
> 2019-04-28 17:33:35.566 Status: Startup Path: /domoticz/
> 2019-04-28 17:33:35.664 Status: EventSystem: reset all events...
> 2019-04-28 17:33:35.769 Status: PluginSystem: Started, Python version '3.5.3'.
> 2019-04-28 17:33:41.376 Status: (ZigBee) Started.
> 2019-04-28 17:33:41.493 Status: Python EventSystem: Initalizing event module.
> 2019-04-28 17:33:41.935 Status: (ZigBee) Entering work loop.
> 2019-04-28 17:33:41.935 Status: (ZigBee) Initialized version 0.0.17
> 2019-04-28 17:33:42.385 Status: MQTT: Connecting to localhost:1883
> 2019-04-28 17:33:42.486 Status: MQTT: connected to: localhost:1883
> 2019-04-28 17:33:42.586 Status: MQTT: Subscribed

MQTT message:

>  zigbee2mqtt:info 4/28/2019, 5:34:33 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-04-28.17-34-33'
>   zigbee2mqtt:info 4/28/2019, 5:34:35 PM Starting zigbee2mqtt version 1.3.1 (commit #39d6a8e)
>   zigbee2mqtt:info 4/28/2019, 5:34:35 PM Starting zigbee-shepherd
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM zigbee-shepherd started
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Coordinator firmware version: 'undefined'
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Currently 0 devices are joined:
>   zigbee2mqtt:warn 4/28/2019, 5:34:38 PM `permit_join` set to  `true` in configuration.yaml.
>   zigbee2mqtt:warn 4/28/2019, 5:34:38 PM Allowing new devices to join.
>   zigbee2mqtt:warn 4/28/2019, 5:34:38 PM Set `permit_join` to `false` once you joined all devices.
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Zigbee: allowing new devices to join.
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Connecting to MQTT server at mqtt://localhost
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM zigbee-shepherd ready
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Connected to MQTT server
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001936dc3a","type":"Coordinator"}]}'
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM Zigbee: allowing new devices to join.
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"39d6a8e","log_level":"info","permit_join":true}'
>   zigbee2mqtt:info 4/28/2019, 5:34:38 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"39d6a8e","log_level":"info","permit_join":true}'
> ^C  zigbee2mqtt:info 4/28/2019, 5:35:43 PM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
>   zigbee2mqtt:info 4/28/2019, 5:35:43 PM Disconnecting from MQTT server
>   zigbee2mqtt:info 4/28/2019, 5:35:43 PM zigbee-shepherd stopped

Thank you

**Comment by HJKLMN** [comment]
Thx, did not hav time yet to send logs, as I am currently abroad. When I arrive home, and mine are different, I will let you know

**Comment by Mayki07** [comment]
I have the same issue
`2019-05-02 17:04:37.544 Error: (Zigbee) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-05-02 17:04:37.544 Error: (Zigbee) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-05-02 17:04:37.544 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-05-02 17:04:37.544 Error: (Zigbee) ----> Line 146 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-05-02 17:04:37.544 Error: (Zigbee) ----> Line 47 in '/home/pi/domoticz/plugins/zigbee2mqtt/device_storage.py', function update`

**Comment by stas-demydiuk** [comment]
@Mayki07 could you please attach MQTT message which caused this error as it is impossible to identify root cause without it.

**Comment by Mayki07** [comment]
5/2/2019, 5:04:37 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b00193693db","type":"Coordinator"},{"ieeeAddr":"0x00158d0002d40e6c","type":"Router","model":"ZNLDP12LM","friendly_name":"0x00158d0002d40e6c","nwkAddr":29067,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02"},{"ieeeAddr":"0x00158d0002e8f6f2","type":"Router","model":"ZNLDP12LM","friendly_name":"0x00158d0002e8f6f2","nwkAddr":30819,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02"}]}'
5/2/2019, 5:04:37 PM - info: Zigbee: disabling joining new devices.
5/2/2019, 5:04:37 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"39d6a8e","coordinator_firmware":20180815,"log_level":"info","permit_join":false}'
5/2/2019, 5:05:33 PM - error: Failed to ping 0x00158d0002d40e6c
5/2/2019, 5:06:33 PM - error: Failed to ping 0x00158d0002d40e6c
5/2/2019, 5:06:57 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002e8f6f2', payload '{"state":"ON","brightness":168,"color_temp":274,"linkquality":47,"color":{"x":0.402,"y":0.392}}'

**Comment by Mayki07** [comment]
**Log of zigbee2mqtt :**

`-- Logs begin at Sat 2019-05-04 14:10:05 CEST. --
kvě 04 14:12:07 raspberrypi npm[487]:   zigbee2mqtt:info 5/4/2019, 2:12:07 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0002d40e6c', payload '{"state":"ON","brightness":183,"color_temp":245,"linkquality":10,"color":{"x":0.38,"y":0.38}}'
kvě 04 14:12:07 raspberrypi npm[487]:   zigbee2mqtt:info 5/4/2019, 2:12:07 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b00193693db","type":"Coordinator"},{"ieeeAddr":"0x00158d0002d40e6c","type":"Router","model":"ZNLDP12LM","friendly_name":"0x00158d0002d40e6c","nwkAddr":29067,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02"}]}'
kvě 04 14:12:07 raspberrypi npm[487]:   zigbee2mqtt:info 5/4/2019, 2:12:07 PM Zigbee: allowing new devices to join.
kvě 04 14:12:07 raspberrypi npm[487]:   zigbee2mqtt:info 5/4/2019, 2:12:07 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"39d6a8e","coordinator_firmware":20180815,"log_level":"info","permit_join":true}'
kvě 04 14:12:07 raspberrypi npm[487]:   zigbee2mqtt:info 5/4/2019, 2:12:07 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.1","commit":"39d6a8e","coordinator_firmware":20180815,"log_level":"info","permit_join":true}'
kvě 04 14:13:08 raspberrypi npm[487]:   zigbee2mqtt:error 5/4/2019, 2:13:08 PM Failed to ping 0x00158d0002d40e6c
kvě 04 14:14:08 raspberrypi npm[487]:   zigbee2mqtt:error 5/4/2019, 2:14:08 PM Failed to ping 0x00158d0002d40e6c
`

**Log of Domoticz :**

`2019-05-04 14:12:07.551 Error: (Zigbee) 'onMessage' failed 'KeyError'.
2019-05-04 14:12:07.551 Error: (Zigbee) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-05-04 14:12:07.551 Error: (Zigbee) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-05-04 14:12:07.551 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-05-04 14:12:07.551 Error: (Zigbee) ----> Line 146 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-05-04 14:12:07.551 Error: (Zigbee) ----> Line 47 in '/home/pi/domoticz/plugins/zigbee2mqtt/device_storage.py', function update`

**Comment by HJKLMN** [comment]
For my its also solved:
removed the plugin from plugins and reinstalled domoticz-zigbee2mqtt-plugin.
