### ISSUE TITLE
WSDCGQ11LM

### ISSUE THREAD

**Issue by cabraspower** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#110]
Hello!
I have the temperature sensor aqara (WSDCGQ11LM) working correctly in domoticz but the barometer prediction (sunny, cloudy, ...) only appears as "unknown", how can I solve it?

Thank you

**Comment by stas-demydiuk** [comment]
Unfortunately plugin doesn't calculate predictions on its own and always set forecast as "None". If you know how to calculate it, I could add it to the plugin

**Comment by stas-demydiuk** [comment]
@cabraspower  should be fixed with latest plugin

**Comment by cabraspower** [comment]
Thx!
