### ISSUE TITLE
Create device upon zigbee group creation

### ISSUE THREAD

**Issue by kireque** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#111]
Not sure if this has been asked before...

It would be neat if a switch is being created within Domoticz when a group is created in the Zigbee2Mqtt configuration. 

Also the state of a group member is not updated when a command has been sent to the group (or is this a zigbee2mqtt issue?)

**Comment by salopette** [comment]
Hi, I do not have a solution for you, but how do you create a group?
Can you explain that to me?

**Comment by HJKLMN** [comment]
http://www.zigbee2mqtt.io/information/groups.html

**Comment by stas-demydiuk** [comment]
@kireque it looks like currently it is isn't possible to receive group list from zigbee2mqtt gateway, so I don't see how support can be implemented

**Comment by kmccor** [comment]
Hi, would you consider looking at this again? I've just been reading up on the current state of group support and the capability to query for group lists has been added. I've done some manual testing with MQTT commands on a light group I have configured and it works well.

https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

"groups": a list of all groups, this message can be triggered by sending a message to zigbee2mqtt/bridge/config/groups (payload doesn’t matter).

**Comment by jstam84** [comment]
Any status update on this? Better user experience if this is implemented :)

**Comment by Luigi8723** [comment]
+1 I like also to see the groups as a device in Domoticz since Domoticz is not capable of creating a group dimmer.

**Comment by Anjerlaan** [comment]
Here the same problem with the IKEA GU10 Spots 1537R6 and an IKEA Remote 1524/1810 in domoticz/zigbee2mqtt.
I can pair the bulbs in Z2M and add them to a group
I can pair the IKEA Remote 1524/1810 in Z2M and bind it to the bulbs GroupID

The problem is with the remote that it has no converters according to Z2M, therefor Z2M can't set the remote to a certain a state, it only receives a state when one of the physical buttons of the remote are pressed.
The only thing that works is to set a state to the group of bulbs, 

This is the same in domoticz, when I click on the domoticz IKEA remote ON/OFF button which was created by your plugin, there is no respond, but when i click on the ON/OFF button of the remote itself the ON/OFF button in domoticz does respond to ON or OFF.

So the only way to let is work correctly is to get a Z2M group into Domoticz as a device or something.

**Comment by Anjerlaan** [comment]
For people who are interested, a programmer on the Domoticz site created an example dzVents script which controls a zigbee2mqtt group with a virtual dimmer switch. Works like a charm!
https://www.domoticz.com/forum/viewtopic.php?f=4&t=30077&start=40#top

**Comment by stas-demydiuk** [comment]
Basic support (get current state, on/off) for zigbee groups was added to plugin. I wonder if someone could test and provide feedback.

**Comment by Anjerlaan** [comment]
> Basic support (get current state, on/off) for zigbee groups was added to plugin. I wonder if someone could test and provide feedback.

I updated the plug-in and restarted Domoticz. Here is my Feedback:

Since I could not find a description, I assume Z2M groups are automaticcaly discovered and linked to an on/off switch?
Anyway, domoticz did not automatically discover a new (Group) ON/OFF switch in the devices tab.

I noticed in the branch **devices_manger.py**....filename typing error.
Renamed it to devices_manager.py, restarted Domoticz, but still no auto discovery

**Comment by stas-demydiuk** [comment]
Could you please rename file back and check what is in Domoticz log?

**Comment by Anjerlaan** [comment]
Okay I renaming **devices_manger.py** to **devices_manager.py**, and restart domoticz 
caused the error.

I renamed it back to **devices_manger.py**, deleted all existing zigbee devices in the devices list and restarted Domoticz.......and the group on/off switch popped up in the devices list:

![afbeelding](https://user-images.githubusercontent.com/18295963/73679563-f49cce80-46ba-11ea-9cd2-cc24b2104eaa.png)

I added the switch but it does not respond when using the switch ON/OFF button
The Wall Outlet icon (A) does not change state when clicking on it
The Switch Icon (B) can switch ON/OFF but does not change the state.

![afbeelding](https://user-images.githubusercontent.com/18295963/73680398-73463b80-46bc-11ea-86fa-a0ad98d22cc1.png)

...it only changes state (On/Off) when the zigbee2mqtt group is set to ON or OFF (when using my old script)

**Comment by stas-demydiuk** [comment]
Didn't expect that someone will use '_' in group name :)  Fixed

**Comment by Anjerlaan** [comment]
Well I am from the DOS generation: in file and directory names no spaces and special characters ;-)

**Comment by Anjerlaan** [comment]
Working!

**Comment by Anjerlaan** [comment]
Nice work!.....euhm...Virtual Dimmer Switch? ;-)

I posted a link a few posts up here.
This guy created a dzVents script based on my Keuken_Spots Group example.
My Group has these attributes `{"state": "ON", "brightness": 200, "color_temp": 350}`
It only uses state (ON/OFF) and brightness value to dim, the color_temp is fixed
But I guess users with Color Bulbs have different attributes, which is more difficult to implement?

**Comment by stas-demydiuk** [comment]
I can't come up with script how to get user an ability to choose what device should be created depending on particular group. That's why only On/Off is implemented because I guess it is available for all groups.

**Comment by Anjerlaan** [comment]
Maybe Domoticz "user variables" can be used here?

**Comment by stas-demydiuk** [comment]
Or maybe define some naming convention for group, for example "dimmer" keyword in the group name will force plugin to create Dimmer

**Comment by Anjerlaan** [comment]
Can't you assume that if there is a "brightness" attribute in the Group or Device of the group, that the user wants a dimmer switch? The Initial "brightness" value could be set/modified with a "user variable"

**Comment by stas-demydiuk** [comment]
Unfortunately group should be created before plugin receive first message from it

**Comment by Anjerlaan** [comment]
And if the created group is created, write a "user variable" in domoticz, with info something like this:

```
[["Zigbee Group Name 1", "Switchtype": "Dimmer/OnOff",{"idx": "xxx"}, "GroupDevices": "bulb1, bulb2,etc.", "detected group attributes: ", "initial brightness value"],
["Zigbee Group Name 2", "Switchtype": "Dimmer/OnOff",{"idx": "xxx"}, "GroupDevices": "bulb1, bulb2,etc.", "detected group attributes: ", "initial brightness value"],
["Zigbee Group Name 2", "Switchtype": "Dimmer/OnOff",{"idx": "xxx"}, "GroupDevices": "bulb1, bulb2,etc.", "detected group attributes: ", "initial brightness value"]]
```
Which can be modified afterwards?

**Comment by Anjerlaan** [comment]
> 
> 
> Or maybe define some naming convention for group, for example "dimmer" keyword in the group name will force plugin to create Dimmer

Well if Home Assistant users have to modify a config file first to make groups work, then it is not strange to make a helpfile for your domoticz plugin with a "add Z2M groups" section, which explains how to name friendly_name zigbee2mqtt Groups in order to get the correct switchtype

**Comment by stas-demydiuk** [comment]
@Anjerlaan I've extended groups support, not it recognizes 2 additional suffixes 
`_dimmer`  for dimmer switches 
`_ct` for dimmer + color temperature switches 

For example in your case, group name should be `Keuken_Spots_ct`

I wonder if you could check it.

**Comment by Anjerlaan** [comment]
I will...but if I rename the group in Z2M, I have to bind the remote and add the bulbs again I guess?

**Comment by Anjerlaan** [comment]
But binding is using friendly name

**Comment by Anjerlaan** [comment]
> 
> 
> @Anjerlaan I've extended groups support and added recognition of 2 additional suffixes:
> `_dimmer` for dimmer switches
> `_ct` for dimmer + color temperature switches
> 
> For example in your case, group name should be `Keuken_Spots_ct`

My group dimmer (dzVentz script) only changes state and brightness
color_temp is set to a fixed value, since the color_temp buttons (right-left) on the IKEA remote are not recognized in zigbee2mqtt...

should i call the group _dimmer or _ct then?

**Comment by Anjerlaan** [comment]
Works!:

1. Stop zigbee2mqtt
2. Rename zigbee2mqtt group friendly name in configuration.yaml to **group_name_ct**
3. Start zigbee2mqtt
4. Group is successfully renamed...everything still works, also bounded remote
5. Remove all Zigbee devices in domoticz
6. Stop Domoticz
7. Update domoticz-zigbee2mqtt-plugin
8. Start Domoticz
9.
![afbeelding](https://user-images.githubusercontent.com/18295963/73882352-2b611900-4862-11ea-8cc9-85081b6dcd9b.png)

10. Add Switch to domoticz
11.
![afbeelding](https://user-images.githubusercontent.com/18295963/73882476-6c592d80-4862-11ea-9378-d85cb00d3d80.png)

**Comment by Anjerlaan** [comment]
Nice Work!

**Comment by Anjerlaan** [comment]
What is the idea of this?:

![afbeelding](https://user-images.githubusercontent.com/18295963/73883127-a971ef80-4863-11ea-8c73-fb985fee9096.png)

**Comment by Anjerlaan** [comment]
Domoticz-->Controlicz-->Google Home (voice commands) also work like a charm

**Comment by Anjerlaan** [comment]
I notice one thing compared to my dzVents Script, that the dimming of the group in the dzvents script is smoother and more evenly

**Comment by Anjerlaan** [comment]
Maybe it is also nice to create a group icon (e.g. 3 bulbs) for this type of switch?

![Bulbs](https://user-images.githubusercontent.com/18295963/73934392-97816280-48de-11ea-8107-f1b440bc93d4.PNG)

**Comment by stas-demydiuk** [comment]
It is very strange as algorithm of calculating brightness is the same. What do you mean by `smoother`?

**Comment by Anjerlaan** [comment]
The transition between brightness levels in your algorythm is slower and a bit hiccuping...and the bulbs are not in sync during transition

**Comment by stas-demydiuk** [comment]
Groups support is available starting from plugin v.0.1.0
