### ISSUE TITLE
Aqara Honeywell isn't detected

### ISSUE THREAD

**Issue by diazovitch** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#113]
Hi,
I have two Aqara devices which work correctly : wireless smart switch and temperature and humidity sensor. They are detected automatically when i press the button to associate.
But the Honeywell is not detected when I press the button on the hood.
How should I do it ?
Thank you.

Domoticz version: 4.97

**Comment by stas-demydiuk** [comment]
I guess this device isn't supported yet

**Comment by stas-demydiuk** [comment]
Duplicates #87
