### ISSUE TITLE
Xiaomi Aqara double key wireless wall switch -  WXKG02LM

### ISSUE THREAD

**Issue by Tjilie** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#115]
**Issue description**
Since last update of domoticz and plugin switch does not work properly any more

**Additional information**
Zigbee2MQTT version:1.3.1
Python version:3.5.3
Domoticz version: 4.10693
Plugin version:0.0.18

**Logs**
I used the buttons to toggle the state of a relay on/off. since udate this does not work any more.
When I push the button for the second time the state wil not change. I will have to push the other button first. It looks like the button will hold his state untill I touch the otherone

What can I do to solve this

**Comment by stas-demydiuk** [comment]
I use the Domoticz event script to manually set device state to off after each use.

**Comment by Tjilie** [comment]
Oké this works also for me

**Comment by Tjilie** [comment]
Oké this works also for me
