### ISSUE TITLE
XIAOMI Aqara LLKZMK11LM Two-way Control Module

### ISSUE THREAD

**Issue by NE8XT** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#118]
Dear Stas, please add to the plugin - this is a relay.

5/22/2019, 10:18:44 AM - warn: Device with modelID 'lumi.relay.c2acn01' is not supported.
5/22/2019, 10:18:44 AM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/152

**Comment by TigroEHOT** [comment]
Probably, your device is not supported by the zigbee2mqtt, not the domoticz plug-in.
Try to use zigbee-shepherd-converters.

**Comment by schurgan** [comment]
It worked very well until recently.  There are Xiaomi sockets, temperature sensors and door contacts.  So everything is supported by zigbee2mqtt and your plugin

**Comment by bricamac** [comment]
Hi, I have also a problem with this device : "LLKZMK11LM" .I could see well into the  log of zigbee2mqtt .  But Even after  an update  of the plugin into Domoticz.. I didn't new device into domoticz... May you could help me ?

Thanks, best regards.

8/8/2019, 7:35:08 PM - info: Zigbee publish to device 'AQARA', genTime - readRsp - [{"attrId":0,"status":0,"attrData":618604509,"dataType":226}] - {"direction":1,"seqNum":238,"disDefaultRsp":1} - 1
8/8/2019, 7:35:19 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b0014b93b4f","type":"Coordinator"},{"ieeeAddr":"0x7cb03eaa0a070847","type":"Router","model":"AB3257001NJ","friendly_name":"PriseOSRAMtest","nwkAddr":51289,"manufId":48042,"manufName":"OSRAM","powerSource":"Mains (single phase)","modelId":"Plug 01","hwVersion":1,"swBuildId":"V1.04.90","dateCode":"20140331DEOS****"},{"ieeeAddr":"0x0017880104ac087e","type":"EndDevice","model":"324131092621","friendly_name":"0x0017880104ac087e","nwkAddr":55013,"manufId":4107,"manufName":"Philips","powerSource":"Battery","modelId":"RWL021","hwVersion":1,"swBuildId":"5.45.1.17846","dateCode":"20160302"},{"ieeeAddr":"0x00178801035e2085","type":"Router","model":"8718696449691","friendly_name":"0x00178801035e2085","nwkAddr":889,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","hwVersion":1,"swBuildId":"1.23.0_r20156","dateCode":"20170311"},{"ieeeAddr":"0x00158d00033ecd50","type":"Router","model":"LLKZMK11LM","friendly_name":"AQARA","nwkAddr":2718,"manufId":4151,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.relay.c2acn01","hwVersion":18,"dateCode":"09-20-2018"}]}

**Comment by stas-demydiuk** [comment]
Support was added in plugin v.0.0.19
