### ISSUE TITLE
Feature request - Join Battery voltage and Signal level to device

### ISSUE THREAD

**Issue by devrosx** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#119]
##Hello yesterday installed your plugin and replaced xiaomi gateway, allready all works great (better signal and faster response imho). One thing (feature request):
can you join device, battery and signal to have one id... (its supported in domoticz, for example my rflink devices use this)?
with this i can have one id device instead of three...
dunno how to handle this with device with multiple id actions (maybe copy signal and battery to all device ids)

thanks for your work :)

**Comment by stas-demydiuk** [comment]
Currently plugin adds information about battery and signal level to each device. Is it what you need or you meant something else?

![image](https://user-images.githubusercontent.com/2734836/58983747-3437b180-87e0-11e9-84bc-1201206fa729.png)

**Comment by devrosx** [comment]
oh i see its reporting now (maybe it take some time before its start reporting batery and signal). Extra idx with signal and idx is wasting memory imho if its allready reported in device. Maybe creating extra idx with signal and battery could be only option.

**Comment by devrosx** [comment]
noticed one more thing - when i remove signal and battery idx devices in list and Zigbee pairing:
and then when i use device with removed idxs (mem and signal) log is full of errors
`Error: (ZB) Device creation failed, Domoticz settings prevent accepting new devices.`
can we disable this warning (at least for subdevices, where is allready one idx used)
