### ISSUE TITLE
Support for OSRAM Smart+ Candle E14 Tunable White

### ISSUE THREAD

**Issue by MarcE85** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#12]
MQTT message:
MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_connected","message":"0x84182600000e2869"}'

Message in Domoticz Log:
{'type': 'Router', 'friendly_name': '0x84182600000e2869', 'ieeeAddr': '0x84182600000e2869', 'model': 'AB32840'}

**Comment by stas-demydiuk** [comment]
@MarcE85 looks like you've attached message for Xiaomi Cube which is already supported by plugin

**Comment by MarcE85** [comment]
> @MarcE85 looks like you've attached message for Xiaomi Cube which is already supported by plugin

sorry, should now be ok.

**Comment by MarcE85** [comment]
Sorry that i ask, but is this still under work?

regards and thank you for that awesome work
Marc

**Comment by stas-demydiuk** [comment]
@MarcE85 Yes, it is in my TODO list. The blocker right now is I can't figure out the dimmer device in Domoticz which supports brightness and color temperature control at the same time

**Comment by MarcE85** [comment]
Hey,

i've updated to the latest Version. But since this update the plugin isn't working anymore.
The only message i get is:

2018-11-12 20:48:38.207 Status: (Zigbee2MQTT) Stopping threads.
2018-11-12 20:48:38.207 Status: (Zigbee2MQTT) Stopped.
2018-11-12 20:48:41.329 Status: (Zigbee2MQTT) Started.

thats it :)

Regards Marc

**Comment by stas-demydiuk** [comment]
Most likely you need to manually specify `Zigbee pairing` option in plugin settings

**Comment by stas-demydiuk** [comment]
@MarcE85 Added error handling for this case, could you please update plugin and check

**Comment by MarcE85** [comment]
@stas-demydiuk Sorry i still get the same error. Maybe it has something todo with my python Version?

**Comment by stas-demydiuk** [comment]
Probably yes, what Python version do you currently have?

**Comment by MarcE85** [comment]
Version 3.4

**Comment by stas-demydiuk** [comment]
@MarcE85, as I see in #35 you were able to start plugin, could you please check if Osram device works as expected

**Comment by MarcE85** [comment]
Ahh beim Kino das Dinge

**Comment by MarcE85** [comment]
The Device is added. But it isn't working very good. On/Off is working but i have to wait between the Actions. Dimming and changing the color-temperatur isn't working.

**Comment by stas-demydiuk** [comment]
Are you able to do it using zigbee2mqtt without plugin?

**Comment by MarcE85** [comment]
Hey, sorry for the late reply. I know why the on/off works so slow. After the lamp turns on or off the zigbee2mqtt bridge crashes:

> Nov 26 23:00:54 rasp-w-zigbee2mqtt npm[13622]: #033[32m  zigbee2mqtt:info#033[39m 2018-11-26 23:00:54 Zigbee publish to '0x84182600000e2869', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: /opt/zigbee2mqtt/node_modules/q/q.js:155
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:                 throw e;
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:                 ^
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: TypeError: this.getDeviceInfoForMqtt is not a function
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at DevicePublish.mqttPublishDeviceState (/opt/zigbee2mqtt/lib/controller.js:470:42)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at zigbee.publish (/opt/zigbee2mqtt/lib/extension/devicePublish.js:136:34)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at callback_ (/opt/zigbee2mqtt/lib/zigbee.js:209:13)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at /opt/zigbee2mqtt/node_modules/q/q.js:2055:17
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at runSingle (/opt/zigbee2mqtt/node_modules/q/q.js:137:13)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at flush (/opt/zigbee2mqtt/node_modules/q/q.js:125:13)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! code ELIFECYCLE
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! errno 1
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! zigbee2mqtt@0.1.8 start: `node index.js`
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! Exit status 1
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR!
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! Failed at the zigbee2mqtt@0.1.8 start script.
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR! A complete log of this run can be found in:
Nov 26 23:00:55 rasp-w-zigbee2mqtt npm[13622]: npm ERR!     /home/pi/.npm/_logs/2018-11-26T22_00_55_172Z-debug.log
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: zigbee2mqtt.service: Unit entered failed state.
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: zigbee2mqtt.service: Service hold-off time over, scheduling restart.
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: Stopped zigbee2mqtt.
Nov 26 23:00:55 rasp-w-zigbee2mqtt systemd[1]: Started zigbee2mqtt.

**Comment by MarcE85** [comment]
It's working since the last update of zigbee2mqtt
