### ISSUE TITLE
Devices death query with script

### ISSUE THREAD

**Issue by schurgan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#121]
Hello Stas. A few days ago I updated the plugin and since then the following script does not work anymore. Did you change something in the plugin? I always get messages that the devices are dead, so no heartbeat. Under devices in Domoticz but you see that they send about every hour a heartbeat.

Thank you for your excellent work

```
local threshold = 60

return {
	on = {
		timer = {'every 10 minutes'}
	},
	logging = {
        level = domoticz.LOG_ERROR
    },
	execute = function(dz)

	     local Devices = dz.devices().filter({1095, 1168, 1189, 1220, 1265, 1322, 1396})  

 function notifyMe(iPriority, sTitle, sBody, sSound, sDevice)
    iPriority = '0'
    sTitle    = Title
    sBody     = Body
    sSound    = 'cave'
    sDevice   = 'mimix2s' -- Device name
    if sSound  == nil then sSound = '' end
    if sDevice == nil then sDevice = '' end
    local sUserKey  = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -- User Key
    local sToken    = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -- Pushover App
    sTitle = string.gsub(sTitle, '%%', '%%28')
    sBody  = string.gsub(sBody, '%%', '%%25')
    local sMsg = 'curl --data "token=' .. sToken .. '&user=' .. sUserKey .. '&title=' .. sTitle .. '&message=' .. sBody .. '&priority=' .. tostring(iPriority) .. '&sound=' .. sSound .. '&device=' .. sDevice .. '" https://api.pushover.net/1/messages.json'
    dz.utils.osExecute(sMsg)
 end 

	  Devices.forEach(function(device)
		 local minutes = dz.devices(device.name).lastUpdate.minutesAgo

		if (minutes > tonumber(threshold)) then
			Title = string.gsub(device.name, '', '')
			Body  = 'Сэнсор не отвечает уже'.. minutes .. ' минут.' 
			notifyMe()
		end
		
	  end)
	end
}
```

**Comment by schurgan** [comment]
It worked very well until recently.  There are Xiaomi sockets, temperature sensors and door contacts.  So everything is supported by zigbee2mqtt and your plugin

**Comment by stas-demydiuk** [comment]
Domoticz recently added ability to update devices "last seen" property and now plugin supports that and update devices once receive any message from them even if it is not a state change (previously plugin filtered all such messages). As I noticed Xiaomi devices send heartbeat message every hour. Maybe it is a root cause why you script stopped working.

**Comment by schurgan** [comment]
I have not changed anything about Domoticz. I still have the last stable version. Only after I have updated the plugin 3-4 days ago, the script does not work anymore. Although it is version 0.0.18, I was able to update something. Could you please provide me with the version without any changes so that I can test it?

**Comment by schurgan** [comment]
I have a feeling that now the script only responds to a change (signal or battery change) of a device. Because, with the Xiaomi sockets the problem occurs very rarely, as they every 5 min. Report and the signal strength often changes.

**Comment by schurgan** [comment]
With the script, it has been easy to monitor the sensors, as well with little change to check battery condition. And if a sensor did not answer, I got a message. Now I do not know how to do that if the "last seen" function does not work properly.

**Comment by schurgan** [comment]
Stas, is there really no idea?

**Comment by stas-demydiuk** [comment]
@schurgan I didn't catch what you mean by "last seen" function does not work properly". Could you please explain what is your desired behavior and what should be changed?

**Comment by schurgan** [comment]
Indeed, the "last seen" function does not work as it should.  That is, my script does not perceive this data and only reacts if the sensor itself has changed its value, for example, the value of the battery or the signal strength.  I query this script with the subdevice xxxx_signal, and although the last seen changes with domoticz every hour, I get a message that there is no signal from the sensor for more than an hour.  I realized you did some changes in this sector of the code.  Is it possible to return to the old version at least for subdevices xxxxx_signal?

**Comment by schurgan** [comment]
Can I contact you directly so that I can explain in our native language?  Because this translation probably makes everything even more incomprehensible

**Comment by stas-demydiuk** [comment]
@schurgan My 4pda profile https://4pda.ru/forum/index.php?showuser=894939

**Comment by schurgan** [comment]
Hello Stas, you are not so often at 4pda?

**Comment by schurgan** [comment]
Стас привет, чтото ты на канале телеги не правильно сделал. Нет возможности что либо ниписАть.
