### ISSUE TITLE
Ikea Tradfri on/off switch E1743 clicks not picked up in Domoticz

### ISSUE THREAD

**Issue by raqua** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#122]
**Issue description**
Hi. 
I have Ikea E1743 switch that supports these states, working fine in zigbee2mqtt:
hold pressed on: 
{"linkquality":7,"last_seen":"2019-06-06T22:39:33+02:00","battery":100,"click":"brightness_up"}

hold pressed on released: 
{"linkquality":0,"last_seen":"2019-06-06T22:39:34+02:00","battery":100,"click":"brightness_stop"}

click on:
{"linkquality":0,"last_seen":"2019-06-06T22:39:38+02:00","battery":100,"click":"on"}

click off:
{"linkquality":0,"last_seen":"2019-06-06T22:39:39+02:00","battery":100,"click":"off"}

hold pressed off: 
{"linkquality":5,"last_seen":"2019-06-06T22:39:41+02:00","battery":100,"click":"brightness_down"}

hold pressed off released: 
{"linkquality":5,"last_seen":"2019-06-06T22:39:42+02:00","battery":100,"click":"brightness_stop"}

This is not recognized in domoticz-zigbee2mqtt-plugin even though the button itself is.
When I click it, only the signal is published in domoticz in/out topic, switch is ignored:
{
   "Battery" : 100,
   "RSSI" : 1,
   "description" : "",
   "dtype" : "General",
   "id" : "0x000d6ffffeba7aa5_signal",
   "idx" : 114,
   "name" : "Obyvacka/Vypinac/Svetlo/Signal",
   "nvalue" : 0,
   "stype" : "Custom Sensor",
   "svalue1" : "0",
   "unit" : 28
}

**Additional information**
Zigbee2MQTT version: 1.3.1
Python version: 3.7.3
Domoticz version: 4.10717
Plugin version: Not sure, where to get that from, nut I pulled today 6.6.2019, last commit: b7576b6

Let me know if you need additional info please. 
Thanks.

**Comment by raqua** [comment]
![device](https://user-images.githubusercontent.com/1541886/59066417-4f252700-88af-11e9-859e-52ffa86857ff.jpg)

Here is how I see the switch in devices page of Domoticz.

**Comment by stas-demydiuk** [comment]
Are you sure you have E1743 switch, according to zigbee2mqtt device list it supports only on/off state?
https://www.zigbee2mqtt.io/information/supported_devices.html

**Comment by raqua** [comment]
![IMG_20190610_115559](https://user-images.githubusercontent.com/1541886/59189532-8f6bfa00-8b7a-11e9-90a2-14eaf9a7f49c.jpg)

That is what it says on the back. I believe that the supported devices list is not fully up to date. I wrote author of Zigbee2Mqtt about a new Ikea device working fine with his code and he updated the source code but not the documentation.

**Comment by wini83** [comment]
Simple on/off states are also not working

**Comment by wini83** [comment]
How to fix it? Should a new adapter be created that will create SelectorSwitch (on, off, brightness up / down / stop) instead of OnOffSwitch?

**Comment by stas-demydiuk** [comment]
Existed adapter should be modified to properly handle device state and actions. Unfortunately I don't have such device to make and test these modifications.

**Comment by raqua** [comment]
I have the device and I am happy to help/test. Let me know what you need from me.

**Comment by deennoo** [comment]
Running Zigbee2Mqtt 1.6

this switch give :

2019-09-21 22:33:18.152 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x90fd9ffffe663005 {'click': 'off', 'linkquality': 36, 'battery': 100}
2019-09-21 22:33:27.032 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x90fd9ffffe663005 {'click': 'on', 'linkquality': 60, 'battery': 100}

Actually widget only update Off Value

Generaly, it can be good to update Off/On even if widget is already Off or On
Goal : win some time and transforme this device to a simple physiqcal push using a script like : 

if devicechanged('ikeaswitche1743') changed then
  commandarray(my device) = 'Toggle'

usefull for night run when baby cry, just pres the button

**Comment by wini83** [comment]
I tried to create an adapter. It works well for me.  but i had to manually change the previously automatically created simple switch to selector switch. [https://github.com/wini83/domoticz-zigbee2mqtt-plugin/blob/master/adapters/ikea/tradfri_switch_on_off.py](url)

**Comment by diazovitch** [comment]
I have a samilar problem with Ikea E1743. I did the plugin update yesterday.
The widget was created on domoticz but it doesn't work. There is no reaction.

It's the same thing with TRADFRI motion sensor E1745.

However, i have no problem with KEA TRADFRI control outlet E1702, IKEA TRADFRI LED bulb E26/E27 and IKEA TRADFRI LED bulb GU10 LED1837R5.

![zigbee](https://user-images.githubusercontent.com/48931195/71623551-b0ab3b00-2bdd-11ea-8fdb-8593ec89905c.PNG)
