### ISSUE TITLE
Xiaomi Aqara Motion Sensor, Every 5 sec a signal if there's motion

### ISSUE THREAD

**Issue by tenback** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#124]
The Aqara motion sensor will by default only report a second motion, if the first motion detection timeout has finished. Sometimes this is handy, but sometimes I get a false positive, if for example some harse lighting is comming trought the window. That's why I use a counter in domoticz to see how many motions are detected in a certain time window.

But last time I had a burglar in my house and he was shorter then the motion timeout inside my room. So the motion alarm was not triggered.
I found a mod for the Aqara motion sensor here:
https://translate.google.com/translate?hl=&sl=ko&tl=en&u=https%3A%2F%2Flivebywant.tistory.com%2F13%3Fcategory%3D703455

Now the aqara will send from default (no motion) state the following command:
zigbee2mqtt/0x00158d00031b4e8c {'battery': 100, 'occupancy': False, 'illuminance': 187, 'linkquality': 89, 'voltage': 3055}
zigbee2mqtt/0x00158d00031b4e8c {'battery': 100, 'occupancy': True, 'illuminance': 187, 'linkquality': 89, 'voltage': 3055}

And when there's motion after the previous motion:
zigbee2mqtt/0x00158d00031b4e8c {'battery': 100, 'occupancy': True, 'illuminance': 185, 'linkquality': 89, 'voltage': 3055}
zigbee2mqtt/0x00158d00031b4e8c {'battery': 100, 'occupancy': True, 'illuminance': 185, 'linkquality': 89, 'voltage': 3055}

You see there is 2x the occupancy set to True. But domoticz doesn't see that as a devicechanged. Is there a way to support this behaviour?

Thanks

**Comment by stas-demydiuk** [comment]
It would be hard to add such support as most other users have the default behavior.
