### ISSUE TITLE
Xiaomi Vima Smart Lock

### ISSUE THREAD

**Issue by Gusimelo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#127]
**Device description**
Vima Smart Lock
https://www.zigbee2mqtt.io/devices/A6121

**MQTT message with device information**

7/19/2019, 2:22:07 AM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b0018e25e95","type":"Coordinator"},{"ieeeAddr":"0x00158d00028e2f60","type":"Router","model":"A6121","friendly_name":"0x00158d00028e2f60","nwkAddr":59041,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.lock.v1","hwVersion":37,"dateCode":"04-03-2018"}]}'

**MQTT messages from device**

7/19/2019, 1:55:37 AM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d00028e2f60","meta":{"modelID":"lumi.lock.v1"}}'

7/19/2019, 1:57:50 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"01","linkquality":26,"forgotten":"01"}'

7/19/2019, 1:58:11 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"01","linkquality":31}'

7/19/2019, 2:04:50 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"02","linkquality":0}'

7/19/2019, 2:04:37 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"04","linkquality":0}'

7/19/2019, 1:58:07 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"05","linkquality":39}'

7/19/2019, 2:03:17 AM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00028e2f60', payload '{"inserted":"strange","linkquality":15,"keyerror":true}'

**MQTT state change commands**

**Comment by AlbrtoSam** [comment]
It is not supported yet...  Same here

**Comment by Kalvisan** [comment]
Any update on this topic?

**Comment by stas-demydiuk** [comment]
I've added basic support for smart lock based on data in first message. I wonder if someone could update plugin, check and provide feedback

**Comment by AlbrtoSam** [comment]
It works great!!!!!
