### ISSUE TITLE
Xiaomi Aqara curtain motor ZNCLDJ11LM

### ISSUE THREAD

**Issue by pkoson** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#128]
**Device description**
Xiaomi Aqara curtain motor
[https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html](https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html)

**Comment by Exhortae** [comment]
Any news on this device ?

**Comment by stas-demydiuk** [comment]
Please recreate the issue using template for new device and with providing all necessary details.
