### ISSUE TITLE
fail to add devices on my adapter (nanoleaf NL08_0800)

### ISSUE THREAD

**Issue by JanJaapKo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#13]
Hi,

I created a new adapter based on the base adapter for the Nanoleaf smart ivy NL08_0800 (supported by Zigbee2Mqtt) and took the following stepos:

created folder "nanoleaf" in "adapters"
copied "base_adaper.py" and renamed to "NL08_0800.py"

```
from adapters.base_adapter import Adapter
from devices.dimmer_switch import DimmerSwitch

class NL08_0800(Adapter):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(DimmerSwitch(devices, 'dimmer', 'brightness'))

```
next, I updated 'plugin.py':
`from adapters.nanoleaf.NL08_0800 import NL08_0800`
onStart method:
 ```
       self.adapter_by_model = {
            'NL08-0800': NL08_0800,  # Nanoleaf Ivy smart bulb

```
Then, I create the hardware in Domoticz (logging to 'debug'). I see the messages coming in from MQTT with the (in my case 3) bulbs in the device list:
2018-10-16 21:53:55.583 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/log {'message': [{'type': 'EndDevice', 'friendly_name': 'Bar1', 'model': 'NL08-0800', 'ieeeAddr': '0x000d6f000b4ab0c5'}, {'type': 'EndDevice', 'friendly_name': 'Bar2', 'model': 'NL08-0800', 'ieeeAddr': '0x000d6f000b49be9a'}, {'type': 'EndDevice', 'friendly_name': 'Bar3', 'model': 'NL08-0800', 'ieeeAddr': '0x000d6f000b49880c'}], 'type': 'devices'}
But no devices are being created. What am I doing wrong?

I obviously copied all files to the correct location. I'm running Domoticz v4.10051 on a Raspberry Pi 3. I updated Raspian yesterday.

**Comment by stas-demydiuk** [comment]
Plugin creates devices when it receives the mqtt message with device status for the first time. Have you received any other messsages apart of /bridge/log?

**Comment by JanJaapKo** [comment]
I attached a file with logging, I started to update the device with the plugin as I made it.

Secondly, I updated the _self.adapter_by_model_ set to have the model of my bulbs point to one of the existing adapters. It still doesn't work, no devices added to domoticz.

On further inspection of the code, I do not find a call to create_device (except in _create_device) or _create_device in any of the classes. Where is this supposed to happen?

Any advice welcome.....

**Comment by JanJaapKo** [comment]
Hi,

I do not know of any way to trigger such a message. In the mean time, I did the following:
- went out to buy a set of IKEA TRADFRI LED bulb E27 600 lumen model LED1624G9
- paired them, works fine (added them to adapter_by_model set)
- used power cycles on both the IKEA and Nanoleaf bulbs

None of them gave any other then the initial message. I noticeds that the devices you have now, are all sensor style/input devices, no actuators/outputs like the lights. I did not study the Zigbee protocol, but could it be they do not send regular status updates (although it surprises me the do not send some sort of notification on power on)?

Later today (central european time) I'll try to force the devices into domoticz to see if I can actually control them. Any suggestion on where to create these? I'll give it a go in 'onStart' of the plugin.

**Comment by JanJaapKo** [comment]
Hi,

I've got it (roughly) working. I updated the following:
- the plugin's onMQTTPublish method (moved the part to handle the message which creates the device to create them on the log message) 
- the device.py's handle_message method to handle state changes (on top of brightness)

and some more minor stuff. Shall I create a pull request?

**Comment by stas-demydiuk** [comment]
@JanJaapKo yes, sure, feel free to create a PR if it adds support for new devices

**Comment by JanJaapKo** [comment]
Hi @stas-demydiuk  I've got it working so far:
both lights switch on/off
both lights can be dimmed
still working on the color setting of the IKEA's
But I'd like to merge this. However, I can't create a branch. Probably a rights issue. Can you grant me the rights to do so?

Thanks and looking forward to your review comments

**Comment by stas-demydiuk** [comment]
@JanJaapKo you need to fork this repo, push to your local copy and then you'll be able to create pull-request
