### ISSUE TITLE
Last update and device state is not updated when switch type changed to push on button

### ISSUE THREAD

**Issue by TomasWallflower** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#138]
**Issue description**
I don't know if it's related directly to plugin, but for me this problem occures only with zigbee devices. Normally, when devices are added by plugin, everything works fine, state of devices is updated normally.
But for scripting purposes I need to change type of some zigbee lights from Dimmer to Push On button (with delay off time). When I do this, lights still working, but state of these devices and its last update is not updated anymore.

**Temporary workaround**
Create virtual push on button and set zigbee device as slave device to this button.

**Additional information**
Zigbee2MQTT version: 1.5.1
Python version: 3.5.3
Domoticz version: 4.10902
Plugin version: latest

**Comment by stas-demydiuk** [comment]
Could you please explain your scenario a bit. Currently it doesn't look as smth that should be fixed on plugin side

**Comment by TomasWallflower** [comment]
As I wrote before, I don't know if this problem is related to this plugin as this is only plugin I have installed (all other devices are added as dummy virtual devices).

All my domoticz lights are set as "Push on button" with off delay function at least 120 seconds (because of xiaomis PIR sensor built in 1 minute blindness after detecting movement).
For switching lights I use python event scripts.
So if ie. PIR goes "On", script checks status of target light and if it's "Off", script pushes light "On" every minute. Until PIR is on during these 120 seconds, light will never go "Off". Essential for this script is to know status of light and it's last update time.
Lights added by Zigbee2Mqtt are dimmer type by default. When they are set to this type of switch, they are working properly, they are updating its status and therefore its last update time. But when I change them to Push On button type, state of lights will stop updating, they are always "Off" even if I push the button and physical light is working.

When status update of light is not updated, script always see this light as "Off" and trying it to turn on every second. So Zigbee2Mqtt still transmitting signal to bulb and I believe that this is cause of my CC2531 stop working after some time.

I could work with default dimmer type of light switch, but then if I set delay off timer, the light will switch off after first 120s no matter the fact that event script repeatedly turned it on every minute. It will immediately goes back on, but the blink is uncomfortable.

I hope that you understand to my description of problem.

**Comment by stas-demydiuk** [comment]
Most likely the issue is because you are changing device type while plugin expects to find original devices.

**Comment by TomasWallflower** [comment]
Yes, that's probably true. I just thought that type of switch if just Domoticz's internal thing and does not affect behavior of device variables. I solved it by adding hidden push button alongside to every zigbee2mqtt dimmer device as slave only for switch off timing purposes. Closing.
