### ISSUE TITLE
zigup enddevice

### ISSUE THREAD

**Issue by anshgh** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#141]
Hi,
**If your device is not listed here but zigbee2mqtt supports it, support can be added (fairly) easy by creating device adapter.**
How by creating device adapter?

I connect zigup enddevice.

Log Domoticz:
2019-08-13 16: 54: 20.568 (zigbee2mqtt) Device ZigUP 0x00124b001d6663ed (0x00124b001d6663ed)

I connect zigup enddevice. 
Additional information
Zigbee2MQTT version: 1.5.1 ?
Python version: 3.5.3
Domoticz version: 4.10717
Plugin version: 0.0.18 ?

**Comment by anshgh** [comment]
zigbee2mqtt:info 8/14/2019, 10:31:32 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b0018e263ee","type":"Coordinator"},{"ieeeAddr":"0x00124b001d6663ed","type":"EndDevice","model":"ZigUP","friendly_name":"0x00124b001d6663ed","nwkAddr":56363,"manufId":0,"manufName":"formtapez","powerSource":"Mains (single phase)","modelId":"ZigUP","hwVersion":1,"dateCode":"20190622        "}]}'

**Comment by anshgh** [comment]
zigbee2mqtt:info 8/14/2019, 10:31:32 AM MQTT publish: topic 'zigbee2mqtt/0x00124b001d6663ed', payload '{"state":"OFF","cpu_temperature":23.98,"external_temperature":null,"external_humidity":null,"s0_counts":0,"adc_volt":0.265,"dig_input":1,"reason":"timer","linkquality":134}'

**Comment by anshgh** [comment]
Hi
I creating device adapter to display the readings of the TEMP6000 sensor connected to the ADC.
I created the ZigUP.py file in /home/user/domoticz/plugins/zigbee2mqtt/adapters/lumi/

> from adapters.adapter_with_battery import AdapterWithBattery
> from devices.sensor.lux import LuxSensor
> 
> 
> class ZigUP(AdapterWithBattery):
>     def __init__(self, devices):
>         super().__init__(devices)
>         self.devices.append(LuxSensor(devices, 'lux', 'adc_volt'))


and in /home/user/domoticz/plugins/zigbee2mqtt/adapters/__init__.py  added 

> from adapters.lumi.ZigUP import ZigUP
>adapter_by_model = {
> # ZigUP
> 'ZigUP': ZigUP                      # ZigUP
>}

**Comment by stas-demydiuk** [comment]
Do you need any help with adapter?

**Comment by anshgh** [comment]
When will the plugin support with ZigUP device in domoticz?

**Comment by stas-demydiuk** [comment]
Someone needs to create adapter for this device to add its support to plugin

**Comment by prelude0000** [comment]
Hello, I try to do a plugin for ZigUP but seems that i need help.

message is: 
`zigbee2mqtt:info 8/23/2019, 7:27:37 PM MQTT publish: topic 'zigbee2mqtt/45_zigup_ilmastointi', payload '{"state":"OFF","cpu_temperature":24.26,"external_temperature":21.3,"external_humidity":null,"s0_counts":0,"adc_volt":32.354,"dig_input":1,"reason":"timer","linkquality":26,"B1000004D01FBF28":21.31,"82000004D0977C28":21.25,"4D000004D0DC8328":21.5}'`

And i can add all except ds18b20 sensor properly. There could be a 0-16 sensor connected so i want to do something like:

`
self.devices.append(CustomSensor(devices, 'temp00', 'B1000004D01FBF28', ' (B1000004D01FBF28)'))
self.devices.append(CustomSensor(devices, 'temp01', '82000004D0977C28', ' (82000004D0977C28)'))
...
self.devices.append(CustomSensor(devices, 'temp15', '1234567890123456', ' (1234567890123456)'))
`
But i cannot figure out how i can get device names from message.
Im not familiar with object-oriented programming so maybe you can help me in here.

**Comment by anshgh** [comment]
> But i cannot figure out how i can get device names from message.
device names ZigUP = ZigUP
My log Domoticz:
`2019-08-13 16: 54: 20.568 (zigbee2mqtt) Device ZigUP 0x00124b001d6663ed (0x00124b001d6663ed)`

in /home/user/domoticz/plugins/zigbee2mqtt/adapters/--init__.py added
```
from adapters.lumi.ZigUP import ZigUP
adapter_by_model = {
# ZigUP
'ZigUP': ZigUP                      # ZigUP
}

```

**Comment by fedor946** [comment]
Hi, any luck with this device ? 
At least the basic functions as relay toggle, pulse counter ?
Any info how to edit the *__init__.py to get as many as possible functions ?

**Comment by stas-demydiuk** [comment]
Added basic support for the device basing on provided by @anshgh message. I wonder if someone could check

**Comment by fedor946** [comment]
Hi Stas,
Yes, it shows the basic parameters correctly 

![domo sensor](https://user-images.githubusercontent.com/15854308/73498718-f6624b80-43b5-11ea-95d4-649b15f8dbe4.jpg)

Is there any chance to add few more parameters to output as "external temperature"- ds18b20 sensor and " s0 counts"- simple pulse counter ?

` zigbee2mqtt/0x00124b001f833d81 {'0000000000000000': None, 'adc_volt': 6.047, 'dig_input': 1, 's0_counts': 0, 'E70302977952E428': 18.81, 'linkquality': 120, 'external_temperature': 18.8, 'reason': 'timer', 'cpu_temperature': 30.04, 'external_humidity': None, 'state': `'OFF'}

Thank you for this great project !

**Comment by fedor946** [comment]
Just to update, I replaced the 'cpu_temperature' with 'external_temperature' and it did the trick. 
Now I'm struggling to create a 'counter' sensor in sensors folder based on existing ones... 
Any help would be appreciated

**Comment by stas-demydiuk** [comment]
@fedor946 You could try to use CustomSensor to achieve what you want or create new device for CounterSensor
