### ISSUE TITLE
New Device Innr RF 265

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#142]
Innr RF 265 is same as RB 265 from Innr. Only design, transparant glass bulb and led filament is different.

In think line below should be added to adapters/__init__.py

'RF 265': DimmableBulbAdapter,      # Innr E27 Bulb

**Comment by stas-demydiuk** [comment]
@ArJay60 could you please update plugin and check

**Comment by ArJay60** [comment]
@stas-demydiuk Everything is working fine.
