### ISSUE TITLE
How to add device with multiple sensor and dynamic naming?

### ISSUE THREAD

**Issue by prelude0000** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#144]
I cannot figure out how to add support for sensors what uses dynamic naming.

The use case is ZigUP and it's reporting it's temperature sensor reading (ds18b20) with device unique id, like:
`'{"state":"OFF","cpu_temperature":24.26,"external_temperature":21.3,"external_humidity":null,"s0_counts":0,"adc_volt":32.354,"dig_input":1,"reason":"timer","linkquality":26,"B1000004D01FBF28":21.31,"82000004D0977C28":21.25,"4D000004D0DC8328":21.5}'`

And i can add all except ds18b20 sensor properly. There could be a 0-16 sensor connected so i want to do something like:

`self.devices.append(CustomSensor(devices, 'temp00', 'B1000004D01FBF28', ' (B1000004D01FBF28)')) self.devices.append(CustomSensor(devices, 'temp01', '82000004D0977C28', ' (82000004D0977C28)')) ... self.devices.append(CustomSensor(devices, 'temp15', '1234567890123456', ' (1234567890123456)'))`

But i do not have glue how to do it. Any good pointer and/or hint on how to implement this feature is much appreciated.

A second minor issue is that i can add multiple "CustomSensor" into one device but seems that code only allows one "TemperatureSensor" per device. Is this planned functionality or should we fix it?

Ps. Sorry to create a new issue but seems when i ask it inside of "zigup enddevice #141" then no one notices it.

**Comment by stas-demydiuk** [comment]
I guess the only you need is deeper Python knowledge. You definitely need someone more experienced with it that me to help
