### ISSUE TITLE
Add Robb Smarrt dimmer module

### ISSUE THREAD

**Issue by snorro80** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#145]
Could you please add support for the Robb Smarrt Dimmer module.
This is possibly a rebranded Sunricher Universal Dimmer.

From Domoticz:
`2019-09-10 07:27:57.743 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x000d6f0013e899d0 {'brightness': 144, 'state': 'ON', 'linkquality': 99}
2019-09-10 07:27:57.744 (Zigbee2MQTT) Unsupported zigbee device type with model "ROB_200-004-0"`

From Zigbee2mqtt:
`Sep 10 07:27:57 raspberrypi npm[382]:   zigbee2mqtt:info 9/10/2019, 7:27:57 AM MQTT publish: topic 'zigbee2mqtt/0x000d6f0013e899d0', payload '{"state":"ON","linkquality":99,"brightness":144}'
`

**Comment by stas-demydiuk** [comment]
@snorro80 could you please update plugin and check if everything work as expected

**Comment by snorro80** [comment]
It's working prefectly. Thnx @stas-demydiuk
