### ISSUE TITLE
Gira Zigbee switch

### ISSUE THREAD

**Issue by toppe** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#146]
Anyone who can help me with a adapter for the Gira Zigbee switch?

This is the log's I've been seen:

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': 'on', 'linkquality': 49}`

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': 'off', 'linkquality': 49}`

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': '1', 'linkquality': 49}`

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': '2', 'linkquality': 49}`

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': '3', 'linkquality': 49}`

`2019-09-06 20:41:53.842 (Zigbee) MQTT message: zigbee2mqtt/0x000f1712410308dd {'action': '4', 'linkquality': 49}`

`2019-09-06 20:41:53.843 (Zigbee) Unsupported zigbee device type with model "2430-100"`

_Not for sure I've the select items are 1,2,3,4 or select1,select2,select3,select4 but Is should be easy to change it if necessary?_

Don't know where to begin...

**Comment by pcfreak1** [comment]
i would love for this one to be supported!

**Comment by stas-demydiuk** [comment]
@toppe / @pcfreak1 could you please update plugin and check

**Comment by pcfreak1** [comment]
how do i get them to pair?

**Comment by pcfreak1** [comment]
i got it working.
the gira has 6 buttons, on, off and 4 scene buttons. ufortunately the 4 scene buttons do not result in the selector setting 1-4 but the selector sets to off. this is a bug i think?

**Comment by stas-demydiuk** [comment]
Could you please provide examples of MQTT messages that device produces?

**Comment by pcfreak1** [comment]
sure,
the mqtt messages below:
off: {"linkquality":36,"action":"off"}
on: {"linkquality":86,"action":"on"}
1: {"linkquality":92,"action":"select_0"}
2: {"linkquality":89,"action":"select_1"}
3: {"linkquality":89,"action":"select_2"}
4: {"linkquality":89,"action":"select_3"}

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check, scene buttons should be properly handled

**Comment by pcfreak1** [comment]
works perfectly now! thanks!

**Comment by pcfreak1** [comment]
I would like some options to be added for this one
there is a dimming feature which has the following mqtt messages:
dim up > {"linkquality":0,"action":"up","step_mode":0,"step_size":65,"transition_time":10}
dim down > {"linkquality":0,"action":"down","step_mode":1,"step_size":65,"transition_time":10}
stop dimming > {"linkquality":0,"action":"stop"}

can the options dim up, dim down and stop dimming be added?
