### ISSUE TITLE
Zigbee2Mqtt plug-in does not show in hardware list (info)

### ISSUE THREAD

**Issue by jos301** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#148]
**Issue description**

When following installation instruction the zigbee2Mqtt is not visable in hardware list of Domoticz when using Raspberry PI3 software version 4.19.58 . 

This is because dev libarairies python are not installed by default : command sudo apt install dev-python3 Will solve this. 

Please include this in instruction as tip

When working this is a great peace of software. Thanks for the good work

**Additional information**
Zigbee2MQTT version: 1.5.1
Python version: 3.5
Domoticz version: 4.10717
Plugin version:  v0.0.19

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs
Not needed

**Comment by Sennik** [comment]
I am on buster, I had to use 
'sudo apt install python3-dev

But your tip helped me a lot.

**Comment by jos301** [comment]
Good to be of help. The Python3-dev depends on your version on python in my case version 3.
