### ISSUE TITLE
Support for Xiaomi Aqara (vibration, tilt, fall) Sensor DJT11LM

### ISSUE THREAD

**Issue by mkan1512** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#15]
MQTT message: zigbee2mqtt/0x00158d0002b435ed {'action': 'vibration', 'device': {'ieeeAddr': '0x00158d0002b435ed', 'friendlyName': '0x00158d0002b435ed', 'modelId': 'lumi.vibration.aq1', 'status': 'online', 'powerSource': 'Battery', 'manufName': 'LUMI', 'manufId': 4151, 'nwkAddr': 837, 'type': 'EndDevice'}, 'voltage': 3145, 'linkquality': 134, 'battery': '100.00'}

MQTT message: zigbee2mqtt/0x00158d0002b435ed {'action': 'drop', 'device': {'ieeeAddr': '0x00158d0002b435ed', 'friendlyName': '0x00158d0002b435ed', 'modelId': 'lumi.vibration.aq1', 'status': 'online', 'powerSource': 'Battery', 'manufName': 'LUMI', 'manufId': 4151, 'nwkAddr': 837, 'type': 'EndDevice'}, 'voltage': 3145, 'linkquality': 134, 'battery': '100.00'}

MQTT message: zigbee2mqtt/0x00158d0002b435ed {'action': 'tilt', 'angle_y_absolute': 60, 'linkquality': 139, 'angle_x_absolute': 90, 'angle_y': 30, 'angle_x': 0, 'angle_z': 60, 'angle': 46, 'device': {'ieeeAddr': '0x00158d0002b435ed', 'friendlyName': '0x00158d0002b435ed', 'modelId': 'lumi.vibration.aq1', 'status': 'online', 'powerSource': 'Battery', 'manufName': 'LUMI', 'manufId': 4151, 'nwkAddr': 837, 'type': 'EndDevice'}}

MQTT message: zigbee2mqtt/0x00158d0002b435ed {'angle_y_absolute': 90, 'angle_z': 90, 'linkquality': 134, 'angle_x_absolute': 90, 'angle_y': 0, 'angle_x': 0, 'battery': '100.00', 'voltage': 3145, 'device': {'ieeeAddr': '0x00158d0002b435ed', 'friendlyName': '0x00158d0002b435ed', 'modelId': 'lumi.vibration.aq1', 'status': 'online', 'powerSource': 'Battery', 'manufName': 'LUMI', 'manufId': 4151, 'nwkAddr': 837, 'type': 'EndDevice'}}

Unsupported zigbee device type with model "DJT11LM"

**Comment by stas-demydiuk** [comment]
@mkan1512 any thoughts how to represent this device in Domoticz, what is proper to use?

**Comment by mkan1512** [comment]
I think that a selector switch would be the best option. 
Do not know how to handle the angle-information (text ?)
You can place this device on (for example) a safe, a door, a window. 
(and whatever people can think of :) )

**Comment by salopette** [comment]
I think the selector should be enough!

**Comment by stas-demydiuk** [comment]
Added selector switch for vibration sensor, could someone please check?
