### ISSUE TITLE
Hardcore in Domoticz?

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#156]
Dear developers..
Is it not possible to build your oftware hardcore into domoticz?
Plugins are not always eyase to use with update etc..
Perhaps contact Rob from Domoticz..

**Comment by stas-demydiuk** [comment]
This software is just plugin for Domoticz and user have a choice to install it if have such hardware: that's the idea of any plugin. That's why it is not part of Domoticz core
