### ISSUE TITLE
Lingan DZ4743-00B

### ISSUE THREAD

**Issue by pimmernl** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#159]
Please add Lingan DZ4743-00B to the plugin (already supported by Zigbee2Mqtt)

I already modified and tested the following code locally and it works great.

Added the following code to /home/pi/domoticz/plugins/zigbee2mqtt/adapters/__init__.py

```
# Lingan
'DZ4743-00B': OnOffSwitchAdapter,     # Lingan Zigbee OnOff Controller
```

**Comment by stas-demydiuk** [comment]
Done
