### ISSUE TITLE
Error when adding LED1732G11

### ISSUE THREAD

**Issue by arjenanker** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#160]
Just receiverd my CC2531 Zigbee USB stick with 1.60 firmware installed. Installed Zigbee22MQTT-dev and this plugin in Domoticz. Currently, I have 1 Tradfri LED1732G11 lamp, sensor and remote that I can use (unwilling to remove everything from below my kitchen cabinets just to test).

This is what Domoticz gives as error when I reset and pair the LED1732G11:
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) 'onMessage' failed 'KeyError'.
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) ----> Line 193 in '/home/arjen/dev-domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) ----> Line 106 in '/home/arjen/dev-domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) ----> Line 167 in '/home/arjen/dev-domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) ----> Line 146 in '/home/arjen/dev-domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
> 2019-10-04 18:06:12.142 Error: (Zigbee2MQTT) ----> Line 37 in '/home/arjen/dev-domoticz/plugins/zigbee2mqtt/device_storage.py', function update

Though, Zigbee2MQTT seems fine:

> zigbee2mqtt:info  2019-10-04T16:06:12: Device '0x000d6ffffe4e2c25' joined
> zigbee2mqtt:info  2019-10-04T16:06:12: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x000d6ffffe4e2c25"}}'
> zigbee2mqtt:info  2019-10-04T16:06:12: Starting interview of '0x000d6ffffe4e2c25'
> zigbee2mqtt:info  2019-10-04T16:06:12: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x000d6ffffe4e2c25"}}'
> zigbee2mqtt:info  2019-10-04T16:06:12: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001949ee15","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack30x","dateCode":"20190425","lastSeen":1570205172092},{"ieeeAddr":"0x000d6ffffe4a793e","type":"EndDevice","networkAddress":49850,"model":"E1524/E1810","friendly_name":"0x000d6ffffe4a793e","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","modelID":"TRADFRI remote control","hardwareVersion":1,"softwareBuildID":"1.2.223","dateCode":"20190211","lastSeen":null},{"ieeeAddr":"0x000d6ffffe4e2c25","networkAddress":36921,"friendly_name":"0x000d6ffffe4e2c25","lastSeen":1570205172083}]}'
> zigbee2mqtt:info  2019-10-04T16:06:22: Successfully interviewed '0x000d6ffffe4e2c25', device has successfully been paired
> zigbee2mqtt:info  2019-10-04T16:06:22: Device '0x000d6ffffe4e2c25' is supported, identified as: IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white (LED1732G11)
> zigbee2mqtt:info  2019-10-04T16:06:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x000d6ffffe4e2c25","model":"LED1732G11","vendor":"IKEA","description":"TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white","supported":true}}'

Ik was planning on buying a bunch of these bulbs and ditch a bunch of my zwave dimmers, since I can't use them in my new house, but it doesn't seem to be working very well.

I could pair the remote, by the way, that worked just fine.

**Comment by arjenanker** [comment]
I managed to get the lamp in Domoticz with pairing the remote back to the lamp, turning the lamp off and on, a whole lot of restarting of zigbee2mqtt and Domoticz.

But I have no idea what those errors are though...

**Comment by stas-demydiuk** [comment]
Do you still need any help with your issue?
