### ISSUE TITLE
timeout  for Xiaomi temperature sensor

### ISSUE THREAD

**Issue by antoninocanta** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#162]
Dear demydiuk, 
I'm wondering if it is possible to configure manually a timeout for devices when we no longer receive data ?  (some device put its value in red bar when data is outdated)
I consider to make a LUA script but really don't like this approach :s
Thank you for your work, kind regards.

**Comment by stas-demydiuk** [comment]
Currently I don't see such ability in Domoticz, so most likely it is not possible
