### ISSUE TITLE
ptvo (create your own zigbee devices)

### ISSUE THREAD

**Issue by InvertedMinor** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#164]
With PVTO (http://ptvo.info/zigbee-switch-configurable-firmware-router-199/) one can create firmware for CC2530 a.o. to make your own Zigbee devices.

**MQTT messages from device**
{"state_bottom_left":"OFF","linkquality":41,"state_bottom_right":"OFF","state_center":"OFF","device":{"ieeeAddr":"0x00124b001d44d12b","friendlyName":"ptvo","type":"Router","nwkAddr":18923,"manufId":4447,"manufName":"ptvo.info","powerSource":"Mains (single phase)","modelId":"ptvo.switch","hwVersion":1,"swBuildId":"unknown","dateCode":"2019-06-21","status":"online"}}

A new adapter/device would be nice to use this in domoticz

**Comment by d-EScape** [comment]
Just submitted pull request #193 with support for ptvo.switch.

**Comment by stas-demydiuk** [comment]
Should be available in latest plugin version
