### ISSUE TITLE
Add Ikea LED1837R5	

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#165]
Please add Ikea LED1837R5 to supported list

This can be done by adding the line to __init__.py:
'LED1837R5': DimmableBulbAdapter,   # IKEA TRADFRI LED bulb GU10 400 lumen, dimmable

Already checked working by using a copy of the line (below) and replacing LED1650R5 by LED1837R5:
'LED1650R5': DimmableBulbAdapter,   # IKEA TRADFRI LED bulb GU10 400 lumen, dimmable

**Comment by stas-demydiuk** [comment]
Done
