### ISSUE TITLE
How to create domoticz device for ptvo.switch

### ISSUE THREAD

**Issue by maxt579** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#166]
**Device description**
[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)

**MQTT message with device information**
{"ieeeAddr":"0x00158d0001bd0e35","type":"EndDevice","model":"WXKG01LM","friendly_name":"0x00158d0001bd0e35"}
{"ieeeAddr":"0x00124b001d44c8e5","type":"Router","model":"ptvo.switch","friendly_name":"TestBoard","manufacturerID":4447,"manufacturerName":"ptvo.info","powerSource":"Mains (single phase)","modelID":"ptvo.switch","hardwareVersion":1,"dateCode":"2019-06-21","lastSeen":1570657960013}

**MQTT messages from device**
zigbee2mqtt:info  2019-10-10T18:48:17:  MQTT publish: topic 'zigbee2mqtt/TestBoard', payload '{"state_bottom_left":"OFF","linkquality":99,"state_bottom_right":"OFF","state_top_left":"OFF"}'
zigbee2mqtt:info  2019-10-10T18:49:28: MQTT publish: topic 'zigbee2mqtt/TestBoard', payload '{"state_bottom_left":"OFF","linkquality":63,"state_bottom_right":"OFF","state_top_left":"OFF","click":"top_right_single"}'

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

** Entries on zigbee2mqtt:
devices.js:
    {
        zigbeeModel: ['ptvo.switch'],
        model: 'ptvo.switch',
        vendor: 'Custom devices (DiY)',
        description: '[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)',
        supports: 'hold, single, double and triple click, on/off',
        fromZigbee: [fz.ptvo_switch_state, fz.ptvo_switch_buttons],
        toZigbee: [tz.on_off, tz.ptvo_switch_trigger],
        endpoint: (device) => {
            return {'bottom_left': 1, 'bottom_right': 2, 'top_left': 3, 'top_right': 4, 'center': 5};
        },
    },
fromZigbee.js:
    ptvo_switch_state: {
        cluster: 'genOnOff',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options) => {
            const key = `state_${getKey(model.endpoint(msg.device), msg.endpoint.ID)}`;
            const payload = {};
            payload[key] = msg.data['onOff'] === 1 ? 'ON' : 'OFF';
            return payload;
        },
    },
    ptvo_switch_buttons: {
        cluster: 'genMultistateInput',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options) => {
            const button = getKey(model.endpoint(msg.device), msg.endpoint.ID);
            const value = msg.data['presentValue'];

            const actionLookup = {
                1: 'single',
                2: 'double',
                3: 'tripple',
                4: 'hold',
            };

            const action = actionLookup[value];

            if (button) {
                return {click: button + (action ? `_${action}` : '')};
            }
        },
    },
toZigbee.js:
    ptvo_switch_trigger: {
        key: ['trigger', 'interval'],
        convertSet: async (entity, key, value, meta) => {
            value = parseInt(value);
            if (!value) {
                return;
            }

            if (key === 'trigger') {
                await entity.command('genOnOff', 'onWithTimedOff', {ctrlbits: 0, ontime: value, offwaittime: 0});
            } else if (key === 'interval') {
                await entity.configureReporting('genOnOff', [{
                    attribute: 'onOff',
                    minimumReportInterval: value,
                    maximumReportInterval: value,
                }]);
            }
        },
    },

**Comment by d-EScape** [comment]
Just submitted pull request #193 with support for ptvo.switch
