### ISSUE TITLE
Zemismart Curtain/roller blind switch (ZM-CSW032-D)

### ISSUE THREAD

**Issue by Exhortae** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#167]
**Device description**
Zemismart Curtain Switch (open, close, stop) position

**MQTT message with device information**
{"ieeeAddr":"0x14b457fffe24f46a","type":"Router","model":"ZM-CSW032-D","friendly_name":"0x14b457fffe24f46a","nwkAddr":10671,"manufId":4098,"manufName":"_TYZB01_dazsid15","powerSource":"Mains (single phase)","modelId":"TS0302","hwVersion":1,"dateCode":""}

**MQTT messages from device**
 zigbee2mqtt:info 10/12/2019, 11:22:47 PM MQTT publish: topic 'zigbee2mqtt/0x14b457fffe24f46a', payload '{"position":100,"linkquality":49}'
  zigbee2mqtt:debug 10/12/2019, 11:22:50 PM Received zigbee message of type 'attReport' with data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":50}}' of device 'TS0302' (0x14b457fffe24f46a) of endpoint 1
  zigbee2mqtt:info 10/12/2019, 11:22:50 PM MQTT publish: topic 'zigbee2mqtt/0x14b457fffe24f46a', payload '{"position":50,"linkquality":39}'
  zigbee2mqtt:debug 10/12/2019, 11:22:50 PM Received zigbee message of type 'devChange' with data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":50}}' of device 'TS0302' (0x14b457fffe24f46a) of endpoint 1
  zigbee2mqtt:debug 10/12/2019, 11:22:52 PM Received zigbee message of type 'attReport' with data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":0}}' of device 'TS0302' (0x14b457fffe24f46a) of endpoint 1
  zigbee2mqtt:info 10/12/2019, 11:22:52 PM MQTT publish: topic 'zigbee2mqtt/0x14b457fffe24f46a', payload '{"position":0,"linkquality":47}'
  zigbee2mqtt:debug 10/12/2019, 11:22:52 PM Received zigbee message of type 'devChange' with data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":0}}' of device 'TS0302' (0x14b457fffe24f46a) of endpoint 1

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Done! Could you please update plugin and check
