### ISSUE TITLE
Xiaomi Switch duration value mapping

### ISSUE THREAD

**Issue by pakosel** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#169]
**Device description**
It would be very useful to fetch the **duration** value in case of Long Click event for simple Xiaomi Switch device (_WXKG01LM_). It could be similar to fetching the value of Xiaomi Cube angle rotation which can be found as a CustomSensor in Domoticz. Please find below part of the zigbee2mqtt log:

**MQTT messages from device**
'10/19/2019, 1:53:46 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d00022ac3b8', payload '{"linkquality":44,"battery":100,"voltage":3042,"click":"long_release",**"duration":5404**}''
```

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
