### ISSUE TITLE
Xiaomi Aqara Double Switch - no "Power" device

### ISSUE THREAD

**Issue by TroLoos** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#173]
**Issue description**
I'm moving over all of my devices from Deconz / Xiaomi GW to Zigbee2mqtt. So far ... almost so good. I've moved all my Aqara single switches (lumi.ctrl_ln1.aq1), and each of them creates 4 devices in Domoticz: Link / Power / Voltage / Switch - and they all work well (apart from Voltage that is always 0 but I don't mind). It's not the case with double switches (lumi.ctrl_ln2.aq1), each creates only 3 devices in Domoticz: Link / Switch Left / Switch Right - no Power device at all. I've checked with 3 random, and they all behave the same. This information is present in MQTT message, can you please check and add support?

**Additional information**
Zigbee2MQTT version: 1.6.0
Python version: 2.7.13
Domoticz version: 4.10730
Plugin version: newest git pull

**Logs**
Sample MQTT with payload:
Oct 27 21:50:21 raspberrypi npm[29663]:   zigbee2mqtt:info 10/27/2019, 9:50:21 PM MQTT publish: topic 'zigbee2mqtt/light_boiler', payload '{"power":18.84,"linkquality":52,"last_seen":null,"state_left":"ON","state_right":"ON","consumption":17.87,"temperature":27}'
Oct 27 21:50:21 raspberrypi npm[29663]:   zigbee2mqtt:info 10/27/2019, 9:50:21 PM MQTT publish: topic 'zigbee2mqtt/light_boiler', payload '{"power":18.84,"linkquality":52,"last_seen":null,"state_left":"ON","state_right":"ON","consumption":17.87,"temperature":27}'
Oct 27 21:50:23 raspberrypi npm[29663]:   zigbee2mqtt:info 10/27/2019, 9:50:23 PM MQTT publish: topic 'zigbee2mqtt/light_boiler', payload '{"power":39.25,"linkquality":52,"last_seen":null,"state_left":"ON","state_right":"ON","consumption":17.87,"temperature":27}'
Oct 27 21:50:25 raspberrypi npm[29663]:   zigbee2mqtt:info 10/27/2019, 9:50:25 PM MQTT publish: topic 'zigbee2mqtt/light_boiler', payload '{"power":36.23,"linkquality":47,"last_seen":null,"state_left":"ON","state_right":"ON","consumption":17.87,"temperature":27}'
Oct 27 21:50:27 raspberrypi npm[29663]:   zigbee2mqtt:info 10/27/2019, 9:50:27 PM MQTT publish: topic 'zigbee2mqtt/light_boiler', payload '{"power":39.25,"linkquality":49,"last_seen":null,"state_left":"ON","state_right":"ON","consumption":17.87,"temperature":27}'

**Comment by stas-demydiuk** [comment]
Support of power meter was added to plugin
