### ISSUE TITLE
IKEA E27 filament bulb LED1842G3

### ISSUE THREAD

**Issue by GurbEHV** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#176]
IKEA has a new tradfri bulb with filament look, model number LED1842G3, as seen here:[https://www.ikea.com/be/nl/p/tradfri-led-lamp-e27-250-lumen-draadloos-dimbaar-warm-schijnsel-globe-bruin-helder-glas-70455676/](url)

It's supported in the dev branche of zigbee2mqtt as shown by the following snippet from devices.js:
`    {
        zigbeeModel: ['TRADFRI bulb E27 WW clear 250lm'],
        model: 'LED1842G3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 WW clear 250 lumen, dimmable',
        extend: generic.light_onoff_brightness,
    },
`

And I could get it to work with the plugin by adding this to __init__.py:
`
    'LED1842G3': DimmableBulbAdapter,   # IKEA TRADFRI LED bulb E27 250 lumen, dimmable, clear
`

**Comment by stas-demydiuk** [comment]
Thanks! Support was added to plugin.
