### ISSUE TITLE
Please, Add Support for: CR701-YZ - Oujiabao Gas and carbon monoxide alarm

### ISSUE THREAD

**Issue by TheArrow01** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#177]
**Device description**
Oujiabao Gas and carbon monoxide alarm

**MQTT message with device information**
{"ieeeAddr":"0x00124b00129e72f3","type":"EndDevice","model":"CR701-YZ","friendly_name":"0x00124b00129e72f3","nwkAddr":65311,"manufId":0,"manufName":"SZYCD.TEC.CO.LTD","powerSource":"Mains (single phase)","modelId":"OJB-CR701-YZ\u0000   ","hwVersion":19,"dateCode":"20160825        "}

**MQTT messages from device**
zigbee2mqtt:info 2019-11-5 3:20:17 PM MQTT publish: topic 'zigbee2mqtt/0x00124b00129e72f3', payload '{"carbon_monoxide":false,"gas":false,"tamper":false,"battery_low":false,"trouble":false,"ac_connected":true,"test":false,"battery_defect":false,"linkquality":55}'

zigbee2mqtt:info 2019-11-5 3:34:49 PM MQTT publish: topic 'zigbee2mqtt/0x00124b00129e72f3', payload '{"carbon_monoxide":false,"gas":false,"tamper":false,"battery_low":false,"trouble":false,"ac_connected":true,"test":false,"battery_defect":false,"linkquality":39}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by TheArrow01** [comment]
Have a look and made a device that gives me 5 objects for the most important functions of the CR701-YZ.
I don't know if I have done everything correctly, but this test object works for me. Possibly someone with a better look at the code wants to do something with this?

What have I done:

Added a line in domoticz/plugins/zigbee2mqtt/adapters/__init__.py
ad the end of the file.
    **# Test
    'CR701-YZ': CR701YZ                 # CR701-YZ gas leak detector**
I created a folder "domoticz/plugins/zigbee2mqtt/adapters/Test"
Created a file in this folder "Test" with the name "CR701_YZ.py"
In the file i have putin:
-------------------------
from adapters.adapter_with_battery import Adapter
from devices.sensor.smoke import SmokeSensor


class CR701YZ(Adapter):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(SmokeSensor(devices, 'gas', 'gas'))
        self.devices.append(SmokeSensor(devices, 'co', 'co1'))
        self.devices.append(SmokeSensor(devices, 'err', 'err'))
        self.devices.append(SmokeSensor(devices, 'ac', 'ac1'))
        
    def convert_message(self, message):
        message = super().convert_message(message)
        
        if 'carbon_monoxide' in message.raw:
            message.raw['co1'] = message.raw['carbon_monoxide']
        if 'trouble' in message.raw:
            message.raw['err'] = message.raw['trouble']
        if 'ac_connected' in message.raw:
            message.raw['ac1'] = message.raw['ac_connected']
        return message
-------------------------
After adding the device i'll get 5 devices for:

- CO Alarm
- GAS Alarm
- CO-GAS Device Error 
- AC Power
- CO-GAS Alarm (Sign)

Tested with the device and MQTT casting that the objects change with input from the device CR701-YZ.

**Comment by stas-demydiuk** [comment]
Thanks, added support to the plugin
