### ISSUE TITLE
Support wanted for Itead Sonoff BASICZBR3

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#179]
**Device description**
As supported by Zigbee2MQTT See https://www.zigbee2mqtt.io/devices/BASICZBR3.html 

**MQTT message with device information**
On state:

Nov 13 17:45:58 PI3_new_DOM npm[6767]: zigbee2mqtt:info  2019-11-13T16:45:58: MQTT publish: topic 'zigbee2mqtt/Sonoff', payload '{"state":"ON","linkquality":57}'

Off State:
Nov 13 17:46:41 PI3_new_DOM npm[6767]: zigbee2mqtt:info  2019-11-13T16:46:41: MQTT publish: topic 'zigbee2mqtt/Sonoff', payload '{"state":"OFF","linkquality":57}'

**Comment by ArJay60** [comment]
Hi Stanislav,

Adding section below to __init__.py does the job:

    # Itead
    'BASICZBR3': OnOffSwitchAdapter,        # ITEAD SONOFF ZigBee DIY Smart Switch (on/off)

**Comment by stas-demydiuk** [comment]
Added support to plugin, thanks!
