### ISSUE TITLE
Eurotronic Spirit SPZB0001 : only 4 devices

### ISSUE THREAD

**Issue by a20gard** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#180]
Hello

I'm writing here, not because of a "big issue" but more for a question for Eurotronic Zigbee users

I'm using 4 Eurotronic Spirit SPZB0001 thermostats that paired well into Domoticz but that are showing only 4 devices :

Link Quality
Battery Voltage
Temperature
Setpoint
Is it normal ? or should i find 11 devices as I could read in some forums ?

For information, I'm using :
'version': '1.6.0', 'coordinator': 20190425, 'commit': 'e26ad2a'

Should I update ? the coordinator ?

**Comment by stas-demydiuk** [comment]
Hi @a20gard. Current adapter for Eurotronic Spirit SPZB0001 has implementation for only these 4 devices you have, so no any further actions are required from your side.

Overall this Eurotronic device supports more settings to be configured through zigbee but other settings are not implemented yet in this plugin.

**Comment by a20gard** [comment]
Thanks a lot for your answer stas-demydiuk

And thanks a lot for all your job here :)

**Comment by salopette** [comment]
Hi Stas, can you maybe make a thermostat selector like Smanar did at Deconz?

On / Off / Auto

![sshot-1](https://user-images.githubusercontent.com/32480002/72208966-b3454480-34a9-11ea-9711-7514a9d2cd40.jpg)
