### ISSUE TITLE
('PluginMgr')) received fatal signal 6 (Aborted)

### ISSUE THREAD

**Issue by luckysession** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#183]
Hi guys,
one of 14 Xiaomi sensor devices seems to send wrong interpreted voltage, domoticz every time stops with fatal error until this unit send data.

**Issue description**
2019-11-17 19:21:13.266 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Temp_Hum_Gäste {'linkquality': 118, 'battery': 100, 'temperature': 26.15, 'humidity': 50.63, 'last_seen': 1574014873256, **'voltage': 3055**}
2019-11-17 19:21:13.277 Error: Domoticz(pid:19473, tid:19479('PluginMgr')) received fatal signal 6 (Aborted)
2019-11-17 19:21:13.278 Error: siginfo address=0x4c11, address=(nil)

**Additional information**
Zigbee2MQTT version: ="1.7.1"
Python version: - dont know
'DomoticzVersion':'4.11492'
Plugin version: "Zigbee2MQTT" version="0.0.19"

MQTT message: zigbee2mqtt/bridge/config {'log_level': 'info', 'permit_join': True, 'commit': 'b459c35', 'version': '1.7.1', 'coordinator': {'meta': {'minorrel': 6, 'transportrev': 2, 'majorrel': 2, 'product': 0, 'revision': 20190608, 'maintrel': 3}, 'type': 'zStack12'}}

Version of Zigbee2MqttAssistant (this software): 0.3.88 (0.3.88+Branch.master.Sha.a34fe059880e14ed9862286d6aa30d3853b87009) Release
Version of Zigbee2Mqtt: 1.7.1
Coordinator version: 20190608

**Comment by stas-demydiuk** [comment]
@luckysession Do you still have this issue?

**Comment by luckysession** [comment]
> @luckysession Do you still have this issue?

No, seems to be all fine @ the moment
