### ISSUE TITLE
Zigbee2MQTT Devices do not appear when shared with remote domoticz

### ISSUE THREAD

**Issue by brammp** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#188]
**Issue description**
Im trying to share the devices between my domoticz instances (using Domoticz - Remote Server)
I have tested the sharing by using a dummy device, and that seems to work.

I don't know if sharing devices in this way is actualy suported, but i could not find it being described in the documentation, or an issue with this question. 

**Additional information**
Zigbee2MQTT version: 1.7.1
Python version:  3.7.3 
Domoticz version: 4.10717
Plugin version: 0.0.19

**Comment by stas-demydiuk** [comment]
Try to ask this question on Domoticz forum, because there is nothing could be done from plugin side, it just integrates into existed Domoticz instance.

**Comment by brammp** [comment]
Thanks for the quick responce,

I have created a post on the Domoticz forum [https://www.domoticz.com/forum/viewtopic.php?f=68&t=30301](url)

I will close the issue.
