### ISSUE TITLE
Smart Smoke Sensor Heiman HS1SA / HS3SA

### ISSUE THREAD

**Issue by luckysession** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#192]
Device ist Type/subtype ist "Security devices" not only Switch/Light, please change to security devices!

**Comment by stas-demydiuk** [comment]
@luckysession could you please explain what do you mean?

**Comment by luckysession** [comment]
Okay, will try with my bad english...

In domoticz "allow new devices" the smoke detector will indicate only as normal switch, 
it would be better indentificate as "security device" 

![Unbenannt](https://user-images.githubusercontent.com/57873076/69993232-aef14780-154b-11ea-9931-87a3ae01d557.PNG)

In my case i´ve already change the zigbee device via phpmyadmin :-)

Hope you understand me...

**Comment by stas-demydiuk** [comment]
What is the benefit of such change?
