### ISSUE TITLE
Add support for new Xiaomi Aqara Opple 6-button switch

### ISSUE THREAD

**Issue by mbuurman78** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#195]
**Device description**
ZigbeeModel: ['lumi.remote.b686opcn01'],
Model: 'WXCJKG13LM',
Vendor: 'Xiaomi',
Description: 'Aqara OPPLE 6btn Switch',
Supports: '6 buttons, single, double and long click', (Only single-click is working in zigbee2mqtt version 1.7.1+dev)

**MQTT message with device information**
{"ieeeAddr":"0x04cf8cdf3c75b4c2","type":"EndDevice","networkAddress":65058,"model":"WXCJKG13LM","friendly_name":"0 - Woonkamer - TV-kast Drukknop 6x","manufacturerID":4447,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.remote.b686opcn01","hardwareVersion":1,"softwareBuildID":"2019\u0000www.","dateCode":"20190730","lastSeen":1575759060695}]}'

**MQTT messages from device**
Dec 08 00:00:57 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:00:57: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_1_single"}'
Dec 08 00:01:00 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:01:00: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_2_single"}'
Dec 08 00:01:02 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:01:02: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_3_single"}'
Dec 08 00:01:03 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:01:03: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_4_single"}'
Dec 08 00:01:04 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:01:04: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_5_single"}'
Dec 08 00:01:06 raspberrypi npm[3803]: zigbee2mqtt:info  2019-12-08 00:01:06: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_6_single"}'

**Comment by snorro80** [comment]
+1 for the 6 button switch.

**Comment by mbuurman78** [comment]
Update:
**MQTT messages from device:**

Dec 13 19:24:29 raspberrypi npm[1348]: zigbee2mqtt:info  2019-12-13 19:24:29: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":57,"battery":"100.00","voltage":3000,"action":"button_4_hold"}'
Dec 13 19:24:32 raspberrypi npm[1348]: zigbee2mqtt:info  2019-12-13 19:24:32: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":57,"battery":"100.00","voltage":3000,"action":"button_4_release","duration":2498}'
Dec 13 19:24:33 raspberrypi npm[1348]: zigbee2mqtt:info  2019-12-13 19:24:33: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":57,"battery":"100.00","voltage":3000,"action":"button_3_hold"}'
Dec 13 19:24:35 raspberrypi npm[1348]: zigbee2mqtt:info  2019-12-13 19:24:35: MQTT publish: topic 'zigbee2mqtt/0 - Woonkamer - TV-kast Drukknop 6x', payload '{"linkquality":60,"battery":"100.00","voltage":3000,"action":"button_3_release","duration":1728}'

**Comment by stas-demydiuk** [comment]
Ordered this switch for myself, so will be able to test and debug soon. But till that time I've updated plugin to add support basing on provided MQTT messages.

@snorro80, @mbuurman78 could you please update plugin and check

**Comment by mbuurman78** [comment]
Thank you!
Plugin updated, put some issues. 
Result is 'Link Quality' and 'Battery Voltage' are is Domoticz visible, but no 'Switch State':

`pi@raspberrypi:~/domoticz/plugins/zigbee2mqtt $ git pull
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 36 (delta 17), reused 21 (delta 11), pack-reused 0
Unpacking objects: 100% (36/36), done.
From https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
   e196e20..c4f95d5  master     -> origin/master
Updating e196e20..c4f95d5
Fast-forward
 CHANGELOG.md                            |   1 +
 README.md                               |   1 +
 adapters/__init__.py                    | 208 ++++++---------------------------------------------------------------
 adapters/adapter_with_battery.py        |   5 ++
 adapters/base_adapter.py                |  12 ++++
 adapters/heiman/__init__.py             |  18 ++++++
 adapters/ikea/__init__.py               |  43 +++++++++++++++
 adapters/ikea/tradfri_remote_control.py |   5 +-
 adapters/innr/__init__.py               |  38 +++++++++++++
 adapters/lumi/WXCJKG13LM.py             |   9 +++
 adapters/lumi/__init__.py               |  50 +++++++++++++++++
 adapters/lumi/aqara_opple_switch.py     |  44 +++++++++++++++
 adapters/osram/__init__.py              |  31 +++++++++++
 adapters/osram/smart_mini_switch.py     |  26 +++++++++
 adapters/philips/__init__.py            |  40 ++++++++++++++
 adapters/samsung/__init__.py            |  20 +++++++
 16 files changed, 359 insertions(+), 192 deletions(-)
 create mode 100644 adapters/lumi/WXCJKG13LM.py
 create mode 100644 adapters/lumi/aqara_opple_switch.py
 create mode 100644 adapters/osram/__init__.py
 create mode 100644 adapters/osram/smart_mini_switch.py
`
Domoticz log:
`2019-12-14 11:29:17.130 Status: (Zigbee2MQTT) Entering work loop.
2019-12-14 11:29:17.131 Status: (Zigbee2MQTT) Initialized version 0.0.19
2019-12-14 11:29:17.389 Error: (Zigbee2MQTT) 'onMessage' failed 'AttributeError':''NoneType' object has no attribute 'register''.
2019-12-14 11:29:17.389 Error: (Zigbee2MQTT) ----> Line 193 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-12-14 11:29:17.389 Error: (Zigbee2MQTT) ----> Line 106 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2019-12-14 11:29:17.389 Error: (Zigbee2MQTT) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2019-12-14 11:29:17.390 Error: (Zigbee2MQTT) ----> Line 146 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2019-12-14 11:29:17.390 Error: (Zigbee2MQTT) ----> Line 51 in '/home/pi/domoticz/plugins/zigbee2mqtt/device_storage.py', function update
2019-12-14 11:29:17.390 Error: (Zigbee2MQTT) ----> Line 30 in '/home/pi/domoticz/plugins/zigbee2mqtt/device_storage.py', function _register_device
2019-12-14 11:29:17.390 Error: (Zigbee2MQTT) ----> Line 15 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function register`

**Comment by stas-demydiuk** [comment]
Could you please update plugin and try again

**Comment by mbuurman78** [comment]
Great, no errors!
But only button 6 is not visible in Domoticz, the others are working!

**Comment by stas-demydiuk** [comment]
Now should be fixed

**Comment by mbuurman78** [comment]
Fixed! Thanks for the quick response
