### ISSUE TITLE
Support of Osram Smart+ Mini Switch 

### ISSUE THREAD

**Issue by nighthawkii** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#196]
**Device description**
Put general device information here

Hello, 

The Osram Smart + mini switch is in the list of supported devices but it is not the case in fact:
2019-12-09 00:08:32.510 (Zigbee2MQTT Connector) Unsupported zigbee device type with model "AC0251100NJ/AC0251700NJ"

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`,

{'type': 'EndDevice', 'manufacturerName': 'OSRAM', 'friendly_name': 'OSRAM_MINI_SWITCH_01', 'ieeeAddr': '0x000d6f00101d4df2', 'model': 'AC0251100NJ/AC0251700NJ', 'powerSource': 'Battery', 'modelID': 'Lightify Switch Mini', 'dateCode': '201711161925330', 'manufacturerID': 4364, 'softwareBuildID': 'e.1.11.0M', 'lastSeen': 1575847373947, 'networkAddress': 22184, 'hardwareVersion': 1}

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as 

MQTT message: zigbee2mqtt/OSRAM_MINI_SWITCH_01 {'battery': '100.00', 'voltage': 3000, 'linkquality': 49, 'action': 'circle_click'}

2019-12-09 00:08:32.510 (Zigbee2MQTT Connector) Unsupported zigbee device type with model "AC0251100NJ/AC0251700NJ"

Other actions:
up
up_hold
up_release 
circle_click
circle_hold
circle_release
down
down_hold
down_release

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Looks like a new revision of the device, updated. Could you please update plugin and check.

**Comment by nighthawkii** [comment]
Hi,

Thanks a lot for your reactivity !
Now the devices (I have 3) are well recognized by the plugin and are now added in Domoticz devices list.

But despite the plugin (mode debug) is correctly seeing the data from mqtt, the value in domoticz is not changing, the data field stays "off". Only the "last seen" date/hour is changing when I press a key.

The "signal" data is taking the value sent by mqtt, this works.

Any idea ?

**Comment by stas-demydiuk** [comment]
Yes, in this case it should be selector switch, not on/off one. Will update the plugin

**Comment by nighthawkii** [comment]
Hi,

I tried to create the class, but it did not work... I never coded on Python in fact
If you have time to update the plug-in, that would be very great, I will keep you informed as soon as tested

**Comment by stas-demydiuk** [comment]
@nighthawkii I've updated adapter. Could you please remove Osram Smart+ Switch device from Domoticz, update plugin and check if everything  will look ok?

**Comment by nighthawkii** [comment]
Hi,

I checked, everything is perfectly working now !

That's great, thanks a lot !

**Comment by gert3d** [comment]
I am using a recent zigbee2mqtt version (installed in march 2021)

I still have (again?) the same problem with this switch that is now sold in a box labelled: "Ledvance Switch mini" 
It shows up as model AC0251100NJ/AC0251700NJ in the zigbee2mqtt panel.

It is available in the device list, it can be seen as a switch, there the different settings can be choosen (up, up hold, up release, circle click etc) but when actually using the smart switch nothing happens.
What can be done about this?
