### ISSUE TITLE
Add Philips Aura and Philips Hue Iris

### ISSUE THREAD

**Issue by Roeliooo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#199]
Both lights are added in Zigbee2Mqtt, but not in the Domoticz Plugin

Add Philips Aura 

> {
>         zigbeeModel: ['LLC014'],
>         model: '7099860PH',
>         vendor: 'Philips',
>         description: 'LivingColors Aura',
>         extend: hue.light_onoff_brightness_colorxy,
>     }

and  Add Philips Hue Iris

> {
>         zigbeeModel: ['LLC010'],
>         model: '7199960PH',
>         vendor: 'Philips',
>         description: 'Hue Iris',
>         extend: hue.light_onoff_brightness_colorxy,
>     }

I'm not complety familair with the plugin so if you need more information, please ask and I will check! Thank you so much.

**Comment by stas-demydiuk** [comment]
Hi @Roeliooo, I added missing Philips devices to plugin. Could you please update it and check.

**Comment by Roeliooo** [comment]
Thanks mate, everything works! Great Job. Happy holidays.
