### ISSUE TITLE
Add support for Osram / Ledvance new smart+ plug (on/off) AC10691

### ISSUE THREAD

**Issue by tdn131** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#201]
**Device description**
The new OSRAM Smart+ plug (on/off) AC10691 loooks a lot like the old plug (AB3257001NJ), except in my case lower signal strength. 
new: https://www.zigbee2mqtt.io/devices/AC10691.html
old: https://www.zigbee2mqtt.io/devices/AB3257001NJ.html

Device is not recognized by latest domoticz 4.11579. 

**MQTT message with device information**

{"ieeeAddr":"0xf0d1b800001000a1","type":"Router","networkAddress":7650,"model":"AC10691","friendly_name":"Ledvance1","manufacturerID":4489,"manufacturerName":"LEDVANCE","powerSource":"Mains (single phase)","modelID":"Plug Z3","hardwareVersion":1,"softwareBuildID":"00103101","dateCode":"Dec 10 2018\u0000\u0000\u0000\u0000\u0000","lastSeen":null},

**MQTT messages from device**

zigbee2mqtt:info  2019-12-21 19:34:17: MQTT publish: topic 'zigbee2mqtt/Ledvance1', payload '{"state":"ON","linkquality":126}'

**MQTT state change commands**
On or Off

**Comment by stas-demydiuk** [comment]
Updated the plugin, should be available after update

**Comment by tdn131** [comment]
Thanks for the swift response. It works!
