### ISSUE TITLE
Add support for IKEA SYMFONISK Remote

### ISSUE THREAD

**Issue by hendryman** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#202]
**Device description**
Please add support for the IKEA SYMFONISK Remote. 
https://www.zigbee2mqtt.io/devices/E1744.html
It sends four commands:
"rotate_left" (turning dial leftwards)
"rotate_right" (turning dial rightwards)
"rotate_stop" (top turning)
"play_pause" (pressing the dial button)
**MQTT message with device information**
{"id":4,"type":"EndDevice","ieeeAddr":"0xccccccfffe99212a","nwkAddr":16083,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"SYMFONISK Sound Controller","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0,1,3,32,4096],"outClusterList":[3,4,6,8,25,4096],"clusters":{"genBasic":{"attributes":{"modelId":"SYMFONISK Sound Controller","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190312","swBuildId":"2.1.022"}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":74}}},"binds":[{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e1b09c","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e1b09c","endpointID":1}]}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190312","swBuildId":"2.1.022","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1}}

**MQTT messages from device**
Dec 22 12:27:08 raspberrypi npm[15550]: zigbee2mqtt:info  2019-12-22 12:27:08: MQTT publish: topic 'zigbee2mqtt/Sonos Remote', payload '{"battery":74,"linkquality":28,"rate":195,"brightness":255,"action":"**rotate_left**"}'
Dec 22 12:27:09 raspberrypi npm[15550]: zigbee2mqtt:info  2019-12-22 12:27:09: MQTT publish: topic 'zigbee2mqtt/Sonos Remote', payload '{"battery":74,"linkquality":28,"rate":195,"brightness":237,"action":"**rotate_right**"}'
Dec 22 12:27:09 raspberrypi npm[15550]: zigbee2mqtt:info  2019-12-22 12:27:09: MQTT publish: topic 'zigbee2mqtt/Sonos Remote', payload '{"battery":74,"linkquality":23,"rate":195,"brightness":255,"action":"**rotate_stop**"}'
Dec 22 12:27:10 raspberrypi npm[15550]: zigbee2mqtt:info  2019-12-22 12:27:10: MQTT publish: topic 'zigbee2mqtt/Sonos Remote', payload '{"battery":74,"linkquality":39,"rate":195,"brightness":255,"action":"**play_pause**"}'

**Comment by stas-demydiuk** [comment]
Done!

**Comment by hendryman** [comment]
Awesome. Thanks so much!
