### ISSUE TITLE
HGZB-01A device in __init__.py

### ISSUE THREAD

**Issue by pokeron** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#203]
**Issue description**
The device HGZB-01A in __init__.py is defined as "DimmableBulbAdapter", I think it has to be a 
"OnOffSwitchAdapter" 

**Additional information**
Zigbee2MQTT version:
Python version:3.5.3
Domoticz version:4.11590
Plugin version:0.0.19

**Logs**
After changing to :
zigbee2mqtt/adapters/__init__.py:    'HGZB-01A': OnOffSwitchAdapter,    # Nue ZigBee smart light controller

This is the result :
"ieeeAddr":"0x00158d000448c1e5","type":"Router","networkAddress":9432,"model":"HGZB-01A","friendly_name":"0x00158d000448c1e5","manufacturerID":4478,"manufacturerName":"FeiBit","powerSource":"Mains (single phase)","modelID":"FNB56-ZSW23HG1.1","hardwareVersion":1,"softwareBuildID":"1000-0001","dateCode":"20180614","lastSeen":1577028173465}]}

When I added the device the first time without the change in  __init__.py , the device was seen as a dimmer in Domoticz. Sliding the ruler could switch the device on and off, When I tried to sitch the dvice on in the devices tab, it did't work. Now with teh changeeverything works well.

**Comment by stas-demydiuk** [comment]
Thanks! Updated the plugin
