### ISSUE TITLE
Support for the Müller Tint light remote control MLI-404011

### ISSUE THREAD

**Issue by henkiejan1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#204]
Hi,

It should be very nice to support the Müller Tint light remote control MLI-404011. Müller Tint is sold by Aldi and is with the toggle button and brightness button supported by Zigbee2mqtt. I have sucessfully paired my remote. 

```
zigbee2mqtt:info  2019-12-26 14:03:11: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":0,"action":"on"}'
zigbee2mqtt:info  2019-12-26 14:03:14: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":39,"action":"off"}'
zigbee2mqtt:info  2019-12-26 14:03:17: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":15,"action":"brightness_up_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:19: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":18,"action":"brightness_up_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:20: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":28,"action":"brightness_up_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:21: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":28,"action":"brightness_up_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:22: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":31,"action":"brightness_up_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:24: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":39,"action":"brightness_down_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:25: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":39,"action":"brightness_down_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:26: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":39,"action":"brightness_down_click","step_size":43,"transition_time":10}'
zigbee2mqtt:info  2019-12-26 14:03:26: MQTT publish: topic 'zigbee2mqtt/0x00158d000341877c', payload '{"linkquality":39,"action":"brightness_down_click","step_size":43,"transition_time":10}'
```

**Comment by henkiejan1** [comment]
I see by all other requests for support the label new device. I see this not with this Mülller RC.?

**Comment by henkiejan1** [comment]
Is there any process with support? :) Or do i need to update something?

**Comment by stas-demydiuk** [comment]
I don't have such device and it doesn't look similar to what we already have in the plugin so I guess we are waiting for someone who owns this device and also have some Python knowledge to add support in the plugin

**Comment by henkiejan1** [comment]
Ok. Did you have any suggestions about details? I know that Zigbee2mqtt itself supported the device.[ See this.](https://www.zigbee2mqtt.io/devices/MLI-404011.html).

**Comment by stas-demydiuk** [comment]
First of all how do you see this device mapped to Domoticz devices, what features would you like to see?

**Comment by henkiejan1** [comment]
It should be fine you can get the brightness, color and on-off function see in Domoticz so you could controll other devices like the wled or something. But i discovered i could control the lights with zigbee with binding the remote control to them directly. I used the brandnew zigbee2mqtt webinterface therefore. That is also really nice!

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
