### ISSUE TITLE
Can you please add Ikea Leptiter (T1820) to the zigbee2mqtt-plugin

### ISSUE THREAD

**Issue by Plofkop1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#207]
I have a few Ikea Leptiter (T1820) lamps that are not supported by the zigbee2mqtt-plugin. The lamps are correctly identified by zigbee2mqtt only they don't appear as devices in domoticz.

Can you please add this device to the plugin?

Regards Henk

**Comment by stas-demydiuk** [comment]
Hi @Plofkop1, done! Could you please update plugin and check.

**Comment by Plofkop1** [comment]
Hi Stanislav,

I just checked. It works flawless. Thank you for the very quick response
and solution.

Regards Henk

Op ma 30 dec. 2019 om 14:35 schreef Stanislav Demydiuk <
notifications@github.com>:
