### ISSUE TITLE
Please add support for Innr SP222

### ISSUE THREAD

**Issue by 2N3819** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#208]
**Device description**
https://www.zigbee2mqtt.io/devices/SP_222.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
 /opt/zigbee2mqtt/data/log/2019-12-31.16-02-06/log.txt   [----]  0 L:[  1+ 0   1/ 29] *(0   /3132b) 0105 0x069                                                                            [*][X]
info  2019-12-31 16:02:06: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2019-12-31.16-02-06'
info  2019-12-31 16:02:07: Starting zigbee2mqtt version 1.8.0 (commit #da4d26a)
info  2019-12-31 16:02:07: Starting zigbee-herdsman...
info  2019-12-31 16:02:10: zigbee-herdsman started
info  2019-12-31 16:02:10: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
info  2019-12-31 16:02:10: Currently 1 devices are joined:
info  2019-12-31 16:02:10: 0x14b457fffe4b1117 (0x14b457fffe4b1117): SP 222 - Innr Smart plug (Router)
warn  2019-12-31 16:02:10: `permit_join` set to  `true` in configuration.yaml.
warn  2019-12-31 16:02:10: Allowing new devices to join.
warn  2019-12-31 16:02:10: Set `permit_join` to `false` once you joined all devices.
info  2019-12-31 16:02:10: Zigbee: allowing new devices to join.
info  2019-12-31 16:02:10: Connecting to MQTT server at mqtt://localhost
info  2019-12-31 16:02:10: Connected to MQTT server
info  2019-12-31 16:02:10: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2019-12-31 16:02:10: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.8.0","commit":"da4d26a","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":
warn  2019-12-31 16:05:54: Device '0x14b457fffe4b1117' left the network
info  2019-12-31 16:05:54: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x14b457fffe4b1117"}}'
warn  2019-12-31 16:05:55: Device '0x14b457fffe4b1117' left the network
info  2019-12-31 16:05:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x14b457fffe4b1117"}}'
warn  2019-12-31 16:05:55: Device '0x14b457fffe4b1117' left the network
info  2019-12-31 16:05:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x14b457fffe4b1117"}}'
info  2019-12-31 16:06:01: Device '0x14b457fffe4b1117' joined
info  2019-12-31 16:06:01: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x14b457fffe4b1117"}}'
info  2019-12-31 16:06:01: Starting interview of '0x14b457fffe4b1117'
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```

```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check?

**Comment by 2N3819** [comment]
Hi,
Thank you for adding the the SP222 to domoticz-zigbee2mqtt-plugin.

The 0x14b457fffe4b1117 appeared in the domoticz device list as two separate
devices.
See attached PNG and text version below:

Index              Hardware       ID
  Unit
108                 Zigbee_IO       0x14b457fffe4b1117_signal     1
109                 Zigbee_IO       0x14b457fffe4b1117_switch    2

This may be normal?
Turning on/off device 109 controls the socket (it works).
Device 108 always reports zero.



I also have a another SP_222 (0x14b457fffe4202d5) but that was not added to
domoticz as a device.
Domoticz log (with error) below:

2020-01-04 11:35:02.451 Status: (Zigbee_IO) Started.
2020-01-04 11:35:03.066 (Zigbee_IO) Connected to MQTT Server: 127.0.0.1:1883
2020-01-04 11:35:03.117 (Zigbee_IO) Zigbee2mqtt bridge is online
2020-01-04 11:35:03.118 (Zigbee_IO) Joining new devices is enabled on the
zigbee bridge
2020-01-04 11:35:03.169 (Zigbee_IO) Received available devices list from
bridge
2020-01-04 11:35:03.170 (Zigbee_IO) Device SP 222 0x14b457fffe4b1117
(0x14b457fffe4b1117)
2020-01-04 11:35:03.221 (Zigbee_IO) Joining new devices is enabled on the
zigbee bridge
2020-01-04 11:35:03.012 Status: (Zigbee_IO) Initialized version 0.0.20
2020-01-04 11:35:03.011 Status: (Zigbee_IO) Entering work loop.
2020-01-04 11:35:03.170 Error: (Zigbee_IO) Device creation failed, Domoticz
settings prevent accepting new devices.
2020-01-04 11:35:03.170 Error: (Zigbee_IO) Device creation failed, Domoticz
settings prevent accepting new devices.

2020-01-04 11:35:24.100 Status: New sensors allowed for 5 minutes...

2020-01-04 11:35:54.864 (Zigbee_IO) Received available devices list from
bridge
2020-01-04 11:35:54.864 (Zigbee_IO) Device SP 222 0x14b457fffe4b1117
(0x14b457fffe4b1117)
2020-01-04 11:35:54.869 (Zigbee_IO) Device 0x14b457fffe4202d5
(0x14b457fffe4202d5) doesn't have "model" attribute, skipped

Regards
Richard

**Comment by stas-demydiuk** [comment]
You have an error
```
2020-01-04 11:35:03.170 Error: (Zigbee_IO) Device creation failed, Domoticz
settings prevent accepting new devices.
```
You should enable device creation in domoticz settings

**Comment by 2N3819** [comment]
Agreed but the next line of the is:
2020-01-04 11:35:24.100 Status: New sensors allowed for 5 minutes...

Then the devices for 0x14b457fffe4b1117 were added:
Index              Hardware       ID
  Unit
108                 Zigbee_IO       0x14b457fffe4b1117_signal     1
109                 Zigbee_IO       0x14b457fffe4b1117_switch    2

But no device for 0x14b457fffe4202d5

2020-01-04 11:35:54.869 (Zigbee_IO) Device 0x14b457fffe4202d5
(0x14b457fffe4202d5) doesn't have "model" attribute, skipped

**Comment by stas-demydiuk** [comment]
Was you able to solve the issue?

**Comment by 2N3819** [comment]
The SP222 switches on/off OK I can control the SP222

but I have two devices for each SP222, for example (from domoticz device
list):

108 Zigbee_IO0x14b457fffe4b1117_signal1  Zigbee_IO - 0x14b457fffe4b1117
(Link Quality)  GeneralCustom  Sensor0 --
109 Zigbee_IO0x14b457fffe4b1117_switch2  Zigbee_IO - 0x14b457fffe4b1117
Light/SwitchSwitch   On--

The (Link Quality) devices are not working, always = zero.

Is this what you expect or is it a problem?

Regards

Richard

**Comment by stas-demydiuk** [comment]
It isn't an issue, it just depends on your zigbee network, sometimes it even could be 0 but devices will still work.
