### ISSUE TITLE
IKEA E1743 and E1745 : widgets are created but doesn't work

### ISSUE THREAD

**Issue by diazovitch** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#209]
I have a problem with Ikea switch E1743 and ikea motion sensor E1745.
I did the plugin update yesterday.
Widgets were created on domoticz but they doesn't work. There is no reaction.

However, i have no problem with :

- IKEA TRADFRI control outlet E1702
- IKEA TRADFRI LED bulb E26/E27
- IKEA TRADFRI LED bulb GU10 LED1837R5
- Aqara motion sensor
- Aqara switch
- Aqara door contact
- Aqara thermometer/Hygrometer...

Where can the problem come from?

**Additional information**
Zigbee2MQTT version: 1.8.0
Python version: 3.5.3 & 2.7.13
Domoticz version: 4.10717
Plugin version: How can i know it ?

![zigbee](https://user-images.githubusercontent.com/48931195/71630952-2cb97900-2c06-11ea-8e28-08167aa3eed7.PNG)

**Comment by stas-demydiuk** [comment]
Could you please provide MQTT messages from these devices.

**Comment by diazovitch** [comment]
Hi,

Could you say me how i can see messages MQTT.
Sorry i'm novice.
Thank you.

**Comment by diazovitch** [comment]
When i use this command : sudo journalctl -u zigbee2mqtt.service -f
There is no log of my new device E1743 when i put On or Off.
However the widget i is created.

**Comment by diazovitch** [comment]
I can see that on my domoticz log :

```
2020-01-31 19:43:22.732 (Zigbee2MQTT) MqttClient::ping
2020-01-31 19:43:22.733 (Zigbee2MQTT) Sending 2 bytes of data
2020-01-31 19:43:22.733 (Zigbee2MQTT) c0 00 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. �.
2020-01-31 19:43:22.733 (Zigbee2MQTT) Received 2 bytes of data
2020-01-31 19:43:22.733 (Zigbee2MQTT) d0 00 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. �.
```
