### ISSUE TITLE
IKEA SYMFONISK: Change Rotation Resolution

### ISSUE THREAD

**Issue by hendryman** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#210]
Is it possible to modify the rotation resolution to make the level changes per rotation step smaller? As of now, the level change seems to be 8 per rotation step. How could I change this to something like 2 or 1?

**Comment by stas-demydiuk** [comment]
Unfortunately Domoticz Dimmer Switch supports only 0..100 range while symfonisk uses 0..255. I could add custom sensor with native value if it will help.
