### ISSUE TITLE
Make Touch (heartbeat) a configurable option

### ISSUE THREAD

**Issue by bizziebis** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#211]
To my opinion **device.Touch()** should be configurable in the plugin settings (On/Off).

I like my switches to show the **last update** moment as the **Last Seen** timestamp. Now the **Last Seen** timestamp shows the time of the device heartbeat.

For a lot of people this will be the expected behavior as the **Last Seen** time is indeed the time the switch/sensor was last seen. But that is not how I used Domoticz for the past 7 years :)

**Comment by schurgan** [comment]
+1

**Comment by hughb8on** [comment]
+1

**Comment by kovainfo** [comment]
+1
for security sensors it is much more interesting to know the time of the last operation. for example, when a movement was detected, when the sensor stopped detecting movement, or when the door was closed. but currenlly, we see the sensor’s heartbeat time.
I'm for lastUpdate :)

**Comment by kovainfo** [comment]
Or even so: is it possible to change the date only for the device whose data has changed?
For example, the signal level of the "magnet" has changed - lastSeen only changes for the device "magnet (Link Quality)", and for the other  devices (battery level, open/closed state) - does not it change?

**Comment by anti-adblock-fan** [comment]
+1
any solution how to disable device.Touch() time on lastSeen ?

should i edit device.py ?

`else:
            self.touch_device(device)`

**Comment by schurgan** [comment]
I made the following changes back and everything worked as you want.  That is, heartbeat will only change the time and date for subdevices and not for sensors.

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/commit/136c1f84de2c945fc1bc329d6e5760f81801f6cb#diff-6ee30ccb8aa97070e5e898daf07c0f3bR95
