### ISSUE TITLE
Add eWeLink SA-003 (Already in Zigbee2mqtt)

### ISSUE THREAD

**Issue by Roeliooo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#214]
Hi Friend

Can you please add support for eWeLink SA-003 ? It is recognized by zigbee2mqtt but not in domoticz.

> jan 03 18:42:38 raspberrypi npm[461]: zigbee2mqtt:info  2020-01-03 18:42:38: Device '0x00124b001d436ada' is supported, identified as: eWeLink Zigbee smart plug (SA-003-Zigbee)

> jan 03 18:42:38 raspberrypi npm[461]: zigbee2mqtt:info  2020-01-03 18:42:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00124b001d436ada","model":"SA-003-Zigbee","vendor":"eWeLink","description":"Zigbee smart plug","supported":true}}'

Link:
https://www.zigbee2mqtt.io/devices/SA-003-Zigbee.html

Thanks!

**Comment by stas-demydiuk** [comment]
Done! Could you please update plugin and check?

**Comment by Roeliooo** [comment]
Thanks again! Works great! Best wishes!
