### ISSUE TITLE
Aqara Single Switch WXKG03LM not recognized correctly

### ISSUE THREAD

**Issue by HenriMatthijssen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#218]
For the Double Switch WXKG02LM you will notice that three devices are created when recognized by this plugin:
`<IEEEAddr>_cell`
`<IEEEAddr>_signal`
`<IEEEAddr>_switch`

For the Single_Switch WXKG03LM only two devices are created:
`<IEEEAddr>_cell`
`<IEEEAddr>_signal`

The WXG03LM is correctly recognized in zigbee2MQTT:
`jan 07 18:34:27 Domoticz_Slave npm[4290]: zigbee2mqtt:info  2020-01-07 18:34:27: Switch Enkel Zolder (0x00158d0002c974ff): WXKG03LM - Xiaomi Aqara single key wireless wall switch (EndDevice)
`

It also reacts correctly on clicks in zigbee2MQTT:
`jan 07 19:05:16 Domoticz_Slave npm[4290]: zigbee2mqtt:info  2020-01-07 19:05:16: MQTT publish: topic 'zigbee2mqtt/Switch Enkel Zolder', payload '{"battery":100,"voltage":3195,"linkquality":87,"click":"single"}'`

**Comment by HenriMatthijssen** [comment]
I already found the bug myself in the code.

File \Zigbee2MQTT\adapters\lumi\WXKG03LM.py

change line 6:
`    def init(self, devices): `

into

`    def __init__(self, devices): `

Then the WXKG03LM will be correctly recognized and 3 devices will appear (including switch).

**Comment by stas-demydiuk** [comment]
Thanks, fixed!
