### ISSUE TITLE
KADRILJ roller blind

### ISSUE THREAD

**Issue by hansoboe** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#219]
This should be similar to "IKEA FYRTUR roller blind", just different name and address:

{'powerSource': 'Battery', 'hardwareVersion': 1, 'ieeeAddr': '0x000d6ffffe8e92a2', 'model': 'E1926', 'softwareBuildID': '2.2.007', 'modelID': 'KADRILJ roller blind', 'lastSeen': 1578407730799, 'type': 'EndDevice', 'networkAddress': 61712, 'friendly_name': '0x000d6ffffe8e92a2', 'dateCode': '20190311', 'manufacturerID': 4476, 'manufacturerName': 'IKEA of Sweden'}

**Comment by pcurt** [comment]
This is done, can you please update the plugin and test ?

**Comment by hansoboe** [comment]
It is working perfect now.
Thanks!
