### ISSUE TITLE
Missing error, when zigbee device is out from network

### ISSUE THREAD

**Issue by kovainfo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#220]
When i try using switch device, plugin don't tell me about error with communications with tis device.  i.e. missing error in Domoticz, when device is out from network. at the same time, such an error is present in the zigbee2mqtt service logs.

also, Domotics can highlight in red color devices with which it has not been connected for a long time, but with plugin - devices always have normal state color.

**Comment by blooesky** [comment]
That is right in **domoticz don't show the offline devices** and you can to send an command(example for switch or plug) as if the device is online.

Device attribute "HaveTimeout" from domoticz must to change  when the device is not connected for a long time from false to true.

**Comment by stas-demydiuk** [comment]
Error now will be shown in Domoticz Log (#354)
