### ISSUE TITLE
Trust / KaKu ZYCT-202 [Working]

### ISSUE THREAD

**Issue by jjnh** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#222]
**Device description**
Battery operated remote control which can control 5 lights and a group
Functions are on, off, bright and dim.

**MQTT message with device information**
{'type': 'EndDevice',
 'friendly_name': '0x00158d0001313fb0',
 'swBuildId': '\x00\x00\x00\x00\x00\x00\x00\x00\x00',
 'hwVersion': 1,
 'powerSource': 'Battery',
 'manufId': 4151,
 'ieeeAddr': '0x00158d0001313fb0',
 'nwkAddr': 29741,
 'model': 'ZYCT-202',
 'manufName': '\x00\x00\x00',
 'modelId': '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
 'dateCode': '\x00\x00\x00\x00\x00\x00\x00\x00'}]}

**MQTT messages from device**
no regular messages are sent. Only when a button is pressed.

**MQTT state change commands**
 Examples are for Light 1:
 On button =             {'action_group': 145, 'linkquality': 18, 'action': 'on'}
 Off button =            {'action_group': 145, 'linkquality': 36, 'action': 'off'}
 Bright =                {'action_group': 145, 'linkquality': 31, 'action': 'up-press'}
 Dim =                   {'action_group': 145, 'linkquality': 31, 'action': 'down-press'}
 Release bright or dim = {'action_group': 145, 'linkquality': 31, 'action': 'stop'}
 
Other lights give different action groups.
 Light 2 = 'action_group': 146
 Light 3 = 'action_group': 147
 Light 4 = 'action_group': 148
 Light 5 = 'action_group': 149
 Group =   'action_group': 150

 When switching groups no information is sent.

**Comment by jjnh** [comment]
Could not help myself and started on the topic.

I created a 'trust' folder and made the references in the _init_.py files to find a ZYCT202 configuration.
The ZYCT202.py file contains the following code:


------------------
 from adapters.adapter_with_battery import AdapterWithBattery
 from devices.switch.selector_switch import SelectorSwitch


 class ZYCT202(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.switch = SelectorSwitch(devices, 'switch', 'action')
        self.switch.add_level('Off', 'off')
        self.switch.add_level('On', 'on')
        self.switch.add_level('Up', 'up-press')
        self.switch.add_level('Down', 'down-press')
        self.switch.add_level('Stop', 'stop')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_BUTTONS)
        self.switch.disable_value_check_on_update()


        self.devices.append(self.switch)


    def handleCommand(self, alias, device, device_data, command, level, color):
        self.switch.handle_command(device_data, command, level, color)

-------------

This creates one selector switch which responds to all the correct buttons.
However ... it does not work with the action_group selection yet.

I could do an additional transform which registers the states for all 6 switches in the remote. This would give me 1 selector switch with a whole lot of states (5 states for 6 switches).

I would rather have 5 separate selector switches which are controlled by the individual action groups. Action group 6 would control all 5 or, alternatively, be a separate selector switch.

How do I create multiple selector switches from one adapter file??

cheers,
John

**Comment by jjnh** [comment]
Hi, me again :-)

Currently I have gone for the quick-and-dirty solution, but at least that enables me to read all functions of the remote in Domoticz.

This is the content of my ZYCT202.py file:
---
from adapters.adapter_with_battery import AdapterWithBattery
from devices.switch.selector_switch import SelectorSwitch


class ZYCT202(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.sw1 = SelectorSwitch(devices, 'switch', 'state')
        self.sw1.add_level('1Off', '145_off')
        self.sw1.add_level('1On', '145_on')
        self.sw1.add_level('1Up', '145_up-press')
        self.sw1.add_level('1Down', '145_down-press')
        self.sw1.add_level('1Stop', '145_stop')
        self.sw1.add_level('2Off', '146_off')
        self.sw1.add_level('2On', '146_on')
        self.sw1.add_level('2Up', '146_up-press')
        self.sw1.add_level('2Down', '146_down-press')
        self.sw1.add_level('2Stop', '146_stop')
        self.sw1.add_level('3Off', '147_off')
        self.sw1.add_level('3On', '147_on')
        self.sw1.add_level('3Up', '147_up-press')
        self.sw1.add_level('3Down', '147_down-press')
        self.sw1.add_level('3Stop', '147_stop')
        self.sw1.add_level('4Off', '148_off')
        self.sw1.add_level('4On', '148_on')
        self.sw1.add_level('4Up', '148_up-press')
        self.sw1.add_level('4Down', '148_down-press')
        self.sw1.add_level('4Stop', '148_stop')
        self.sw1.add_level('5Off', '149_off')
        self.sw1.add_level('5On', '149_on')
        self.sw1.add_level('5Up', '149_up-press')
        self.sw1.add_level('5Down', '149_down-press')
        self.sw1.add_level('5Stop', '149_stop')
        self.sw1.add_level('6Off', '150_off')
        self.sw1.add_level('6On', '150_on')
        self.sw1.add_level('6Up', '150_up-press')
        self.sw1.add_level('6Down', '150_down-press')
        self.sw1.add_level('6Stop', '150_stop')
        self.sw1.set_selector_style(SelectorSwitch.SELECTOR_TYPE_MENU)
        self.sw1.disable_value_check_on_update()

        self.devices.append(self.sw1)

    def convert_message(self, message):
        message = super().convert_message(message)

        message.raw['state'] = str(message.raw['action_group']) + '_' + message.raw['action']

        return message


    def handleCommand(self, alias, device, device_data, command, level, color):
        self.sw1.handle_command(device_data, command, level, color)

        self.update_battery_status(device_data, converted_message)
        self.update_link_quality(device_data, converted_message)

---

This file creates a selector switch with 30 states numbered 5 states for 6 switches. Number 6 is the group switch on the remote.

The pythin file and a picture of the remote are attached.

Before using the file needs to be integrated into the __init__.py files depending on where it is stored in the adapters folder.

I hope this helps more people out there!!

Cheers,
John

[599006267](https://user-images.githubusercontent.com/3064265/72219814-69f90180-354a-11ea-91e2-f369096c8c4d.jpg)

[ZYCT202.zip](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/4050692/ZYCT202.zip)

**Comment by stas-demydiuk** [comment]
@jjnh Add support to the plugin. Could you please update and check

**Comment by jjnh** [comment]
Yes, looks like it's working.
