### ISSUE TITLE
Question: rename friendly name device

### ISSUE THREAD

**Issue by glsf91** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#224]
I have added some devices. Now I want to rename these devices in Zigbee2mqtt software (not this plugin). But the devices are not seen anymore by these plugin because of the rename I think.

Is it possible to use afterwards a friendly name in the Zigbee2mqtt (not this plugin) software and this plugin still pickup the device?

Of course I can also rename the device in Domoticz but I like also a rename in Zigbee2mqtt .

**Comment by stas-demydiuk** [comment]
You can rename devices in zigbee2mqtt as you want, just restart plugin after so it could fetch new data from zigbee2mqtt
