### ISSUE TITLE
add support for TRADFRI bulb E27 WW 806lm

### ISSUE THREAD

**Issue by jerome70** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#225]
Hello,

I have an issue with this bulb.
All others ikea and philips work well.

device succefully addes to domoticz but link remain to 0 and nothing append when i push button in domoticz

Thank you for your work

**Comment by stas-demydiuk** [comment]
Do you see any log in Domoticz or zigbee2mqtt console?

**Comment by jerome70** [comment]
tkanks for reply.
Domoticz nothing special in log
Zigbee2mqtt :
debug 2020-01-14 13:30:41: Publishing 'set' 'state' to 'chaufferie_1'
debug 2020-01-14 13:30:46: Received Zigbee message from 'routeur_3', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from e$
info  2020-01-14 13:30:46: MQTT publish: topic 'zigbee2mqtt/routeur_3', payload '{"state":true,"linkquality":107,"led_state":true}'
error 2020-01-14 13:30:56: Publish 'set' 'state' to 'chaufferie_1' failed: 'Error: Timeout - 6501 - 1 - 192 - 6 - 11 after 15000ms'
debug 2020-01-14 13:30:56: Error: Timeout - 6501 - 1 - 192 - 6 - 11 after 15000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
info  2020-01-14 13:30:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' $
debug 2020-01-14 13:30:56: Saving state to file /opt/zigbee2mqtt/data/state.json

**Comment by jerome70** [comment]
sorry for bad paste :

error 2020-01-14 14:01:15: Publish 'set' 'state' to 'chaufferie_1' failed: 'Error: Timeout - 6501 - 1 - 193 - 6 - 11 after 15000ms'
debug 2020-01-14 14:01:15: Error: Timeout - 6501 - 1 - 193 - 6 - 11 after 15000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
info  2020-01-14 14:01:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'chaufferie_1' failed: 'Error: Timeout - 6501 - 1 - 193 - 6 - 11 after 15000ms'","meta":{"friendly_name":"chaufferie_1"}}'

**Comment by stas-demydiuk** [comment]
According to the log, the issue is not with the plugin or zigbee2mqtt but with your zigbee network, looks like device is too far from zigbee coordinator or router.
