### ISSUE TITLE
Konke ContactSensor Inverted

### ISSUE THREAD

**Issue by noppie** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#226]
Hi,  I managed to add the Konke Contact Sensor by editing the __init__.py  ('2AJZ4KPDR': ContactAdapter, )
When the contact is closed, the state is "true"  (zigbee2mqtt/0x086bd7fffee973dc', payload '{"contact":true,) .
Added in Domoticz a Door Contact, but the result of state true is that Domoticz says the door is open. Is this configurable?

**Comment by stas-demydiuk** [comment]
Try to set contact type as "Door Lock Inverted"

**Comment by noppie** [comment]
Thanks for the reply.  Set as Door Lock Inverted gives me the next result:

contact true:  door unlocked
contact false:  door locked.

So I set it to Door Lock (but it isn't a door lock)

contact true: Door Locked
contact false:  Door Unlocked.

I use this in combination with homebridge so I can see the status in Homekit.  With this configuration Homekit shows the Door Lock as a Lock wich I can open en case via Homekit (and that's not wat it is.
