### ISSUE TITLE
does not have registered zigbee2mqtt device

### ISSUE THREAD

**Issue by eleutscher** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#227]
**Issue description**
After reboot of my PI, I can no longer turn on lights which are configured thru zigbee2mqtt.
For example
_(Zigbee2MQTT) Device Buitenlamp Schuur does not have registered zigbee2mqtt device
Status: User: eleutscher initiated a switch command (3882/Buitenlamp Schuur/On)_

I saw a simulair issue on Github and the 'solution' was restart domoticz. But if I do this I get the folowing error.
_MQTT message: zigbee2mqtt/bridge/log {'message': "Publish 'set' 'state' to '0x14b457fffe71bfe2' failed: 'Error: Data request failed with error: 'MAC no ack' (233)'", 'type': 'zigbee_publish_error', 'meta': {'friendly_name': '0x14b457fffe71bfe2'}}_

All the lights who are communication thru zigbee2mqtt will give this error. I am not a skilled Linux guy, please advice what to do. Restart system en services in different order gives the same output.

zigbee2mqtt version 1.8.0 (commit #da4d26a)

Doorcontact (also Zigbee) still communicate with Domoticz and report the battery status and door open/close

**Comment by eleutscher** [comment]
And then suddenly everything is working again. Strange.
After I clicked on a device in Domoticz in Setup/Devices

**Comment by stas-demydiuk** [comment]
```
zigbee2mqtt/bridge/log {'message': "Publish 'set' 'state' to '0x14b457fffe71bfe2' failed: 'Error: Data request failed with error: 'MAC no ack' (233)'", 'type': 'zigbee_publish_error', 'meta': {'friendly_name': '0x14b457fffe71bfe2'}}
```
This error occurs when zigbee stick can't find device in the network. Usually you need to wait couple minutes until zigbee stick will rebuild routes in the network or repair the device.

**Comment by eleutscher** [comment]
And the mystery continues because the message 'Mac no ack' is backup again today. Nothing changed on my part.
