### ISSUE TITLE
Add Innr FL 130 C Flex support

### ISSUE THREAD

**Issue by derekoharrow** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#229]
**Device description**
Innr Flex LED Strip

**MQTT message with device information**
`zigbee2mqtt/bridge/config/devices`, as example
```
'[{"ieeeAddr":"0x00124b00014d2b83","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1579009189184},{"ieeeAddr":"0x00158d0003440f7c","type":"Router","networkAddress":40825,"model":"FL 130 C","friendly_name":"Cabin_LEDs","manufacturerID":4454,"manufacturerName":"innr","powerSource":"Mains (single phase)","modelID":"FL 130 C","hardwareVersion":2,"softwareBuildID":"0x20001470","dateCode":"20180130","lastSeen":1579008532032}]'
```

**MQTT messages from device**
Standard RGBW controller

**MQTT state change commands**
Standard RGBW controller

I've got this working myself by adding the following line to plugins/zigbee2mqtt/adapters/innr/__init__.py

    'FL 130 C': RGBWAdapter,

**Comment by stas-demydiuk** [comment]
Updated the plugin, thanks!
