### ISSUE TITLE
IKEA TRADFRI control outlet (E1603)

### ISSUE THREAD

**Issue by remb0** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#23]
**Device description**
Put general device information here

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
  "0xd0cf5efffe6d24eb" [label="{0xd0cf5efffe6d24eb|Router|IKEA TRADFRI control outlet (E1603)|online}"];
  "0xd0cf5efffe6d24eb" -> "0x00124b0018ed1bb0" [label="1"]

{"ieeeAddr":"0xd0cf5efffe6d24eb","type":"Router","model":"E1603","friendly_name":"0xd0cf5efffe6d24eb"}]}'
```

**Comment by stas-demydiuk** [comment]
@remb0 I wonder if you could you please provide data with device state and commands how to control it

**Comment by remb0** [comment]
I don't get the states because this must be controlled by the hub (I lend out to a friend)
and I don't have a remote right now.

the only thing I see:
{"ieeeAddr":"0xd0cf5efffe6d24eb","type":"Router","model":"E1603","friendly_name":"0xd0cf5efffe6d24eb"}]}

I will report back when having the remote.

**Comment by Gemies** [comment]
It would be great that this device wil be supported, what can I do to help. How do I retrieve the information you need? Is there a tool I can use for it? please let me know

**Comment by Gemies** [comment]
2018-11-2 22:22:15 - debug: Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":1}}' of device 'TRADFRI control outlet' (0xd0cf5efffeef33cb)
2018-11-2 22:22:15 - info: MQTT publish, topic: 'zigbee2mqtt/tradfriplug', payload: '{"state":"ON","linkquality":120}'

Will this do?

**Comment by stas-demydiuk** [comment]
yes, thanks

**Comment by stas-demydiuk** [comment]
@Gemies, @remb0 could you please check with plugin from latest master branch

**Comment by remb0** [comment]
Nice work!!  I go some sensors extra :)
and also the ikea switch.  when on/off from domoticz:
Status: User: Admin initiated a switch command (3134/Zigbee2MQTT - 0xd0cf5efffe6d24eb/On)

the switch don't do anything:
Nov 03 12:27:42 octopi npm[607]:   zigbee2mqtt:info 2018-11-3 12:27:42 Zigbee publish to '0xd0cf5efffe6d24eb', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
Nov 03 12:27:42 octopi npm[607]:   zigbee2mqtt:error 2018-11-3 12:27:42 Zigbee publish to '0xd0cf5efffe6d24eb', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.

**Comment by stas-demydiuk** [comment]
It is zigbee network error, hopefully device repairing should help
https://github.com/Koenkk/zigbee2mqtt/issues/362

**Comment by Gemies** [comment]
Thanks works perfectly. Switch switches on and off. Also have the sensors they show link quality. Thanks for your work

**Comment by stas-demydiuk** [comment]
Thanks for the feedback!
