### ISSUE TITLE
IKEA GUNNARP led panel

### ISSUE THREAD

**Issue by pokeron** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#230]
**Device description**
IKEA GUNNARP LED panel, dimmable, white spectrum (40x40 cm)

**MQTT message with device information**
{"ieeeAddr":"0x14b457fffe74e525","type":"Router","networkAddress":30961,"model":"T1829","friendly_name":"0x14b457fffe74e525","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"GUNNARP panel 40*40","hardwareVersion":1,"softwareBuildID":"2.1.022","dateCode":"20190114","lastSeen":null}
```

**MQTT messages from device**

info  2020-01-16 12:02:02: MQTT publish: topic 'zigbee2mqtt/0x14b457fffe74e525', payload '{"state":"ON","linkquality":23,"brightness":255,"color_temp":0}'

info  2020-01-16 12:02:07: MQTT publish: topic 'zigbee2mqtt/0x14b457fffe74e525', payload '{"state":"OFF","linkquality":23,"brightness":255,"color_temp":0}'


**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here


Remark , I added it to the adapters/ikea/__init__.py as
'T1829': DimmableCtBulbAdapter,     # IKEA GUNNARP LED light panel, dimmable, white spectrum (40x40 cm)

and it works nice

**Comment by stas-demydiuk** [comment]
Updated the plugin, thanks!
