### ISSUE TITLE
The integration of the Ikea Remote E1524/E1810 in Domoticz is apparantly wrong

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#231]
**Issue description**
I had a discussion in an issue with Koenkk about the IKEA Remote E1524/E1810.
https://github.com/Koenkk/zigbee2mqtt/issues/2718
In this issue I also showed him how the remote was integrated in Domoticz and what didn't work as aspected. He wrote that the Integration as I showed him was definitely wrong and that I should make an issue for this, In home assistant this is integrated as a sensor.
https://github.com/Koenkk/zigbee2mqtt/issues/2718#issuecomment-575201078

**Additional information**
Zigbee2MQTT version: 1.8.0
Python version: 3.5.3
Domoticz version: 4.11550
Plugin version: Last version

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
In Domoticz this device is integrated as sensor as well. That's why you see this behavior:
```
When I activate them like this example (this switch is the TOGGLE button of the remote):

and I try turn on/off the switch, there is no respond at all.
They only change state when I physically press the remote button
```

**Comment by Anjerlaan** [comment]
I am so confused now....working on it for weeks now
Maybe you have a solution for my problem:

Your plugin added 3 IKEA GU10 bulbs and the Remote buttons as devices in Domoticz.
I created a group/scene in Domoticz and added the remote under activation device...like this

![afbeelding](https://user-images.githubusercontent.com/18295963/72561899-7cf13600-38aa-11ea-8098-7fad362366e2.png)

When I press the toggle button of the remote, the group responds with on/off.
But when I turn on the group in domoticz, the remote gets lost because it can't receive a signal that the group is set to on/off.

As a workaround I created a group in Z2M and bind the remote to it. (this works)
I change the state of the Z2M group with a virtual Domoticz on/off switch in a node red flow. This works too.
But here the problem, that when I use the Remote to turn on/off the Z2M group, the virtual switch doesn't know that the remote turned on/off the Z2M group
So the only way is to create another node red flow which gets the state of the group (or one of its members) when the remote is used and set the virtual switch to on/off.
But this makes the remote devices in domoticz useless??

Do you have another solution to this problem?

**Comment by Anjerlaan** [comment]
The problem is that the state of the toggle button of the remote is not updated in the domoticz device when a zigbee2mqtt group state change (ON/OFF) is send directly to the mqtt server.
If this is done the domoticz button is out of sinc (displays on when lights are off, and the other way around)

Is it possible to update the state of the domoticz devices based on a group change (or one of the devices in it)?

![afbeelding](https://user-images.githubusercontent.com/18295963/72380374-8e550980-3715-11ea-85c3-4d41b710edaa.png)

**Comment by stas-demydiuk** [comment]
Consider your IKEA remote as just a trigger, it doesn't really save any internal state. I would suggest to use dzVents scripts to achieve what you want

**Comment by Anjerlaan** [comment]
I have a dzVents script that syncs the Virtual Switch when the Remote toggle button is used, but this is only when the physical remote is used.

But when the Virtual Switch is used 1xON or 1xOFF (e.g. with voice command), the domoticz remote device can't be updated because it is only a trigger (although it is intergrated as a switch, which reports on/off?)....so when I use the physical remote again then the group of lights go either On/On or Off/Off, after that remote and virtual switch they are in sync again.
```
-- dzVents Script to turn on/off Virtual Switch when Remote is set to ON/OFF
return 
{
    on = { devices = {'Remote_E1524-E1810'}},

    execute = function(dz)
        local RemoteOn 
        local Switch = dz.devices('Keuken Licht')           -- Virtual on/Off Switch

        if dz.devices('Remote_E1524-E1810').state == 'On' then RemoteOn = true end   
        if RemoteOn then 
            Switch.switchOn().checkFirst().silent()      
         else
            Switch.switchOff().checkFirst().silent()        -- If Remote state is Off 
        end
        dz.log('Device ' .. Switch.name .. ' state: ' .. Switch.state, dz.LOG_INFO)
    end
}
```
Am I missing something here?

**Comment by stas-demydiuk** [comment]
If I got you right, this script should be enough:

```
-- dzVents Script to turn on/off Virtual Switch when Remote is set to ON/OFF
return 
{
    on = { devices = {'Remote_E1524-E1810'}},
    execute = function(dz, device)
        local Switch = dz.devices('Keuken Licht')           -- Virtual on/Off Switch

        Switch.toggleSwitch()
        dz.log('Device ' .. Switch.name .. ' state: ' .. Switch.state, dz.LOG_INFO)
    end
}
```

additionally, if you would like to have remote state in sync with the switch, you could add one more script:
```
return 
{
    on = { devices = {'Keuken Licht'}},
    execute = function(dz, device)
        local remote = dz.devices('Remote_E1524-E1810')           -- Virtual on/Off Switch
        
        if (device.state == 'On') then
            remote.switchOn().checkFirst().silent()
        else
            remote.switchOff().checkFirst().silent()
        end
    end
}
```

**Comment by Anjerlaan** [comment]
First of all thanx for your effort!
However running both scripts do exactly the same as my script, and also with the same error I described in my previous post:
if the **"have remote state in sync with the switch"** script runs, you have to press the button twice (ON/ON) or (OFF/OFF) to get them in sync.

**Comment by Anjerlaan** [comment]
If I don't run script2, then it it works whithout errors, but the ON/OFF button of the Remote_E1524-E1810 device is not in sync (in Domoticz), until the Virtual Switch is turned on/off again with voice or Domoticz button. It is a visual thing in domoticz!

Isn't it possible to turn the Remote_E1524-E1810 device to ON or OFF regardless of the remote toggle state?

**Comment by stas-demydiuk** [comment]
Yes, it is possible, Remote doesn't have any real internal state, it is stored only in Domoticz (to be able to have toggle functionality), so you could change it as you wish.

**Comment by Anjerlaan** [comment]
Where can I change that?

**Comment by stas-demydiuk** [comment]
By dzVents script as an option

**Comment by Anjerlaan** [comment]
You mean add it to the "additional" dzVents script you suggested?

**Comment by stas-demydiuk** [comment]
Yes. And I don't completely understand why do you need virtual switch device for your case?

**Comment by Anjerlaan** [comment]
Well I have created in zigbee2mqtt a group of 3 GU10 bulbs, which run smoother (turning all lights on at the same time) than creating a Group/Scene in domoticz. The virtual switch I use to change the state of the zigbee2mqtt group. With a node red flow I make the connection from domoticz out to mqtt in

**Comment by Anjerlaan** [comment]
Having one switch to control a group is also easier when using voice commands (i use controliz).
No i can say "hey google" turn on/off "Keuken Licht", a group scene is not a switch in Google Home, but a scene which needs to be activated instead of on/off.
I only use on/off or dimmer switches in Google Home, because when switches and group/scenes are mixed in Google Home it is more difficult to remember which light(s) are a group/scene and which is a (dimmer) switch.

**Comment by Anjerlaan** [comment]
In Home Assitant a zigbee2mqtt Groups are also integrated as a single device
https://www.zigbee2mqtt.io/integration/home_assistant.html#groups
Is this not possible in Domoticz?

**Comment by stas-demydiuk** [comment]
It is possible and we even have ticket for that #111 but haven't found any volunteer yet

**Comment by Anjerlaan** [comment]
Ah okay, sadly my skills are not good enough (yet), first I have to dig into plug-in scripting and the connection between domoticz and mqtt.

In the meantime are you willing to post an example how to change the Remote_E1524-E1810 switch device (temporarily) so that the ON/OFF button can be set to ON or OFF?

**Comment by stas-demydiuk** [comment]
Using dzVents script or what?

**Comment by Anjerlaan** [comment]
Yes with dzVents please, is there another way then?

**Comment by stas-demydiuk** [comment]
I guess you could use script from my previous example

```
return 
{
    on = { devices = {'Keuken Licht'}},
    execute = function(dz, device)
        if (device.state == 'On') then
            dz.devices('Remote_E1524-E1810').switchOn()
        else
            dz.devices('Remote_E1524-E1810').switchOff()
        end
    end
}
```

and add `.silent()` if required

**Comment by Anjerlaan** [comment]
But this is indeed the same script as your previous example...Now i begin to understand why you may not get me:

After I installed your plugin, domoticz started to add the devices grom Z2M.
The toggle button of the remote E1524-E1810 is discovered as "Zigbee Remote_E1524-E1810" On/Off Switch, which manually cannot be set to ON or OFF. It only can be set to ON or OFF when the remotes toggle button is used.

![afbeelding](https://user-images.githubusercontent.com/18295963/72936625-dc968800-3d67-11ea-97cc-e4e908725a1f.png)

If I click with my mouse on the Wall Outlet button, nothing happens, the switch stays ON or OFF, depending on which state it is set by the physical remote.
So these commands actually don't work :
```
dz.devices('Remote_E1524-E1810').switchOn()
dz.devices('Remote_E1524-E1810').switchOff()
```
I tested your last script (only this one is running) 
Look at my domoticz LOG after turning ON and OFF The Virtual Switch "Keuken Licht":
Keuken Licht, values ON and OFF but Device Remote_E1524-E1810 state: On and On????

2020-01-22 22:48:40.556 (Yeelight Dummy) Lighting 1 (Keuken Licht)
2020-01-22 22:48:40.545 Status: User: gsc initiated a switch command (183/Keuken Licht/On)
2020-01-22 22:48:40.684 Status: dzVents: Info: Handling events for: **"Keuken Licht", value: "On"**
2020-01-22 22:48:40.685 Status: dzVents: Info: ------ Start internal script: Keuken_Licht_Remote_Sync: Device: "Keuken Licht (Yeelight Dummy)", Index: 183
2020-01-22 22:48:40.686 Status: dzVents: Info: **Device Remote_E1524-E1810 state: On**
2020-01-22 22:48:40.686 Status: dzVents: Info: ------ Finished Keuken_Licht_Remote_Sync
2020-01-22 22:48:46.701 (Yeelight Dummy) Lighting 1 (Keuken Licht)
2020-01-22 22:48:46.686 Status: User: gsc initiated a switch command (183/Keuken Licht/Off)
2020-01-22 22:48:46.853 Status: dzVents: Info: Handling events for: **"Keuken Licht", value: "Off"**
2020-01-22 22:48:46.853 Status: dzVents: Info: ------ Start internal script: Keuken_Licht_Remote_Sync: Device: "Keuken Licht (Yeelight Dummy)", Index: 183
2020-01-22 22:48:46.855 Status: dzVents: Info: **Device Remote_E1524-E1810 state: On**
2020-01-22 22:48:46.855 Status: dzVents: Info: ------ Finished Keuken_Licht_Remote_Sync
2020-01-22 22:48:46.855 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua 

Somehow the Remote-E1524-E1810 ON/OFF switch is locked and only responds to the physical remote. This way it is not possible to sync "Remote_E1524-E1810" ON/OFF switch properly with any onther switch.

**Comment by stas-demydiuk** [comment]
Ahh, ok, got you, will take a look.

**Comment by stas-demydiuk** [comment]
@Anjerlaan could you please update plugin and take a look

**Comment by Anjerlaan** [comment]
Yep....working...thanx man!

Although I am not a programmer, I also was looking in your code yesterday and figured out that "toggle_switch.py" imports on_off_switch.py". So there should be a change somewhere!

Now I can use the "Remote-E1524-E1810 ON/OFF switch" instead of the virtual switch in the node-red flow to trigger the zigbee2mqtt group....and no sync scripts anymore (however they also do work now properly)

Keep up the good work!

**Comment by Anjerlaan** [comment]
Next step is to see if a (virtual) dimmer switch can be used to control the zigbee2mqtt group.

**Comment by stas-demydiuk** [comment]
The main issue to implement group support in the plugin is that it is impossible to identify what type of switch it should be. The easiest way is to use just On/Off switch and implement only basic actions but in this case you couldn't for example control brightness of lamps in group or their color.

**Comment by Anjerlaan** [comment]
Something like this?:

First find out which types of groups are possible (e.g. dimmable lights, non-dimmable lights, doorlocks, shutters, etc.) maybe a generic group for mixed devices.

Identify the devices that belong to the existing zigbee2mqtt groups and store the appropriate info in Lists.
These topics will get the info:
1. zigbee2mqtt/bridge/config/groups
2. zigbee2mqtt/bridge/config/devices
3. zigbee2mqtt/bridge/device/[friendly_name]/get_group_membership

List all your supported devices and add columns what properties they have (e.g. dimmable, color, brightwhite, sensor, toggle, on/off, etc.)....because this info will not be found in the devices list.

Then compare the lists to figure out what type of switch is applicable to the group.

And the possibility to change a type of Switch (Group) after discovery in Domoticz
