### ISSUE TITLE
Aqara curtain motor ZNCLDJ11LM support.

### ISSUE THREAD

**Issue by Art531** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#233]
**Device description**
Aqara curtain motor ZNCLDJ11LM, Zigbee2Mqtt support&info here: [https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html](https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html)

**MQTT message with device information**
{"ieeeAddr":"0x00158d0002b104ea","type":"EndDevice","networkAddress":58845,"model":"ZNCLDJ11LM","friendly_name":"curtain","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.curtain","dateCode":"08-13-2018","lastSeen":1579632648109}

**MQTT messages from device**
{"position":100,"running":false,"linkquality":5}
"Position" can be 0...100 (curtain percentage), "Running" can be true/false

**MQTT state change commands**
Topic: zigbee2mqtt/curtain/set/position
Raw value: from 0 to 100

Additional device attributes (via "zigbee2mqtt/curtain/set" topic):
{
    "options":{
        "reverse_direction": xxx,
        "hand_open": xxx,
        "reset_move": xxx
    }
}

reverse_direction: (true/false, default: false). Device can be configured to act in an opposite direction.
hand_open: (true/false, default: true). By default motor starts rotating when you pull the curtain by hand. You can disable this behaviour.
reset_move: (true/false, default: false). Reset the motor. When a path was cleared from obstacles.

**Comment by Art531** [comment]
Dear Stas, is it possible to implement native support of this curtain motor?

**Comment by stas-demydiuk** [comment]
@Art531 Could you please update plugin and check?

**Comment by Art531** [comment]
@stas-demydiuk Tested and working perfectly! Thank you so much!
