### ISSUE TITLE
Domoticz plugin have a problem after update cc2531

### ISSUE THREAD

**Issue by kevin11121147** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#237]
Hello, when updating cc2531 to the latest version (1.9.0), the plugin for domoticz does not work properly (device does not have registered zigbee2mqtt device), the problem is solved by updating zigbee2mqtt in the equipment tab. but you have to repeat the operation every time you restart. Please help

**Comment by stas-demydiuk** [comment]
Just updated zigbee2mqtt to 1.9.0 and doesn't see any issues, everything works as expected.

**Comment by kevin11121147** [comment]
I do this and this error comming back so i back up my copy with older version zigbee2mqtt..
