### ISSUE TITLE
Adding ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)

### ISSUE THREAD

**Issue by Androi1d** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#238]
Hi I was wondering if this product of Xiaomi could be added 

4: 0x04cf8cdf3c75a05d (0x04cf8cdf3c75a05d): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)

payload '{"state":"ON","linkquality":70,"power":2.79}'

I dont know if I provided enough information I am not very good with this and don't know all the ssh commands to receive the correct data you need. 

Any questions please let me know

Greetz,
Android

**Comment by Androi1d** [comment]
https://www.zigbee2mqtt.io/devices/ZNCZ04LM.html 
this is the model I habe

**Comment by stas-demydiuk** [comment]
Done! Could you please update plugin and check

**Comment by Androi1d** [comment]
Hey Stas-Demydiuk,

Thank you for adding but I do have a few questions 

I'll put my log underneath here 

Feb 02 16:48:58 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:48:58: Successfully interviewed '0x04cf8cdf3c75a05d', device has successfully been paired
Feb 02 16:48:58 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:48:58: Device '0x04cf8cdf3c75a05d' is supported, identified as: Xiaomi Mi power plug ZigBee EU (ZNCZ04LM)
Feb 02 16:48:58 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:48:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x04cf8cdf3c75a05d","model":"ZNCZ04LM","vendor":"Xiaomi","description":"Mi power plug ZigBee EU","supported":true}}'
Feb 02 16:49:02 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:49:02: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"OFF","linkquality":78,"power":0}'
Feb 02 16:50:13 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:50:13: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"ON","linkquality":78,"power":0}'
Feb 02 16:50:30 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:50:30: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"ON","linkquality":78,"power":3.94}'

**Comment by Androi1d** [comment]
"Power" should be an actual usage at that very moment  in Watts

It now only shows the total usage as long you have your device.

Maybe it could be an extra option I'll put a screenshot underneath of a neo coolcam z wave power plug for reference.

Any questions please let me know

**Comment by Androi1d** [comment]
![15806591619354140298204163390140](https://user-images.githubusercontent.com/60486081/73610985-80402d80-45dd-11ea-9c31-1489d4461a14.jpg)

**Comment by Androi1d** [comment]
And it doesn't send updates every couple of minutes. 

This device: 
zigbee2mqtt/0x00158d000444d792
Comes alive every 4 a 5 minutes

8: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x04cf8cdf3c75a05d","model":"ZNCZ04LM","vendor":"Xiaomi","description":"Mi power plug ZigBee EU","supported":true}}'
Feb 02 16:49:02 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:49:02: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"OFF","linkquality":78,"power":0}'
Feb 02 16:50:13 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:50:13: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"ON","linkquality":78,"power":0}'
Feb 02 16:50:30 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:50:30: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75a05d', payload '{"state":"ON","linkquality":78,"power":3.94}'
Feb 02 16:51:41 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:51:41: MQTT publish: topic 'zigbee2mqtt/0x00158d000444d792', payload '{"power":0.02,"consumption":0.32,"temperature":36,"linkquality":63,"state_l1":"OFF","state_l2":"OFF"}'
Feb 02 16:57:44 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 16:57:44: MQTT publish: topic 'zigbee2mqtt/0x00158d000444d792', payload '{"power":0.01,"consumption":0.32,"temperature":36,"linkquality":57,"state_l1":"OFF","state_l2":"OFF"}'
Feb 02 17:02:51 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 17:02:51: MQTT publish: topic 'zigbee2mqtt/0x00158d000444d792', payload '{"power":0.02,"consumption":0.32,"temperature":36,"linkquality":57,"state_l1":"OFF","state_l2":"OFF"}'
Feb 02 17:08:57 raspberrypi npm[1626]: zigbee2mqtt:info  2020-02-02 17:08:57: MQTT publish: topic 'zigbee2mqtt/0x00158d000444d792', payload '{"power":0,"consumption":0.32,"temperature":36,"linkquality":73,"state_l1":"OFF","state_l2":"OFF"}'

**Comment by Androi1d** [comment]
Ok I edited some things I hope you understand what I try to explain.

Thank you for all your efforts

**Comment by stas-demydiuk** [comment]
If you open Utility page, you should see both values, smth like this
![image](https://user-images.githubusercontent.com/2734836/73635008-32720680-466b-11ea-8765-a1b9ea1bd39f.png)

**Comment by Androi1d** [comment]
Your absolutely right Stas! Thanks it works as a charm.
