### ISSUE TITLE
Robb Dimmers/Switches (already supported by Zigbee2MQTT dev-branche)

### ISSUE THREAD

**Issue by JHurk** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#239]
**Device description (3 devices)**
Zigbee Rotary dimmer by [Robbshop](https://www.robbshop.nl/zigbee-draaidimmer-robb-smarrt)
Dimmer switch (on/off/brightness)

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
zigbee2mqtt/**<friendly name>**', payload '{"brightness":1,"linkquality":21,"state":"OFF","device":{"friendlyName":"**<friendly name>**","model":"ROB_200-014-0","ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":30828,"type":"Router","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r47"}}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
Device Off - brightness 1 (Turning off when fully dimmed)
zigbee2mqtt/**<friendly name>**', payload '{"brightness":1,"linkquality":21,"state":"OFF","device":{"friendlyName":"**<friendly name>**","model":"ROB_200-014-0","ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":30828,"type":"Router","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r47"}}

Device On - brightness 189 (device is set very bright when on)
MQTT publish: topic 'zigbee2mqtt/**<friendly name>**', payload '{"brightness":189,"linkquality":7,"state":"ON","device":{"friendlyName":"**<friendly name>**","model":"ROB_200-014-0","ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":30828,"type":"Router","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r47"}}'
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

Device Off
zigbee2mqtt/**<friendly name>**', payload '{"brightness":1,"linkquality":21,"state":"OFF","device":{"friendlyName":"**<friendly name>**","model":"ROB_200-014-0","ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":30828,"type":"Router","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r47"}}

Device On
MQTT publish: topic 'zigbee2mqtt/**<friendly name>**', payload '{"brightness":189,"linkquality":7,"state":"ON","device":{"friendlyName":"**<friendly name>**","model":"ROB_200-014-0","ieeeAddr":"0xec1bbdfffe7f3e4f","networkAddress":30828,"type":"Router","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r47"}}'

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by JHurk** [comment]
Yes! Updated and the devices showed in Domoticz. They work as expected, so thanks!!
