### ISSUE TITLE
Xiaomi Mija Temp and Hum issue

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#24]
The plugin shows separately temperature and humidity sensors, not giving them together. Moreover, no info about battery level. 
![zigbeeissue](https://user-images.githubusercontent.com/37578325/47665477-1abeef00-db99-11e8-9e3f-5b7291305e0c.PNG)

**Comment by stas-demydiuk** [comment]
Battery level will appear once device report it (usually device sends heartbeat message every hour).

Separate temperature and humidity sensor was implemented on purpose. Are there specific use case you need them in one domoticz device?

**Comment by loglux** [comment]
I need a consolidated Temperature and Humidity sensor as well as a consolidated sensor for Aqara's Humidity, Temperature and Pressure. By the way, when you use separate sensors for Humidity in the Floorplan, Domoticz doesn't recognize them properly. It uses Temperature sensor's icon and text:
![2018-10-31](https://user-images.githubusercontent.com/37578325/47774328-a002ea80-dce4-11e8-947c-0e2f73236d76.png)

**Comment by MiloshCZ** [comment]
@stas-demydiuk No, this sensor doesn't report battery status :-(
And I agree with using consolidated sensor (Temp+Hum+baro).

**Comment by loglux** [comment]
So, it would be useful to make things in the same way that is already used when we obtain sensors data from Xiaomi Getaway:  
For Mijia Sensors: 
Temperature
Humidity
Temperature and Humidity

For Aqara Sensors: 
Temperature
Humidity
Pressure
Temperature and Humidity

**Comment by MiloshCZ** [comment]
I think, that temp+hum+baro sensor will be ideal
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Temperature.2Fhumidity.2Fbarometer

**Comment by loglux** [comment]
But the choice must be to use Temperature + Humidity only from Aqara Sensor. I'm not interested check air pressure in each room in contrast to T&H.

**Comment by loglux** [comment]
That looks normal. At least it is a Domoticz's issue. This sensor is presented in the same way when it comes from Xiaomi Gateway
![pressurevsbar](https://user-images.githubusercontent.com/37578325/47843287-0a845b00-ddb7-11e8-8620-1275435455d2.PNG)

**Comment by MiloshCZ** [comment]
But, with "Barometer" sensor, you can calibrate it to the right value.
![image](https://user-images.githubusercontent.com/13035760/47844771-88e6fa00-ddc3-11e8-8285-a376de769cbf.png)

**Comment by loglux** [comment]
Go to Domoticz forum, there are some topics about it.

**Comment by loglux** [comment]
The combined Temp+Hum sensor would be a great step forward!

**Comment by stas-demydiuk** [comment]
@loglux  and @MiloshCZ could you please check with plugin from latest master

**Comment by loglux** [comment]
It looks like something went wrong:
![image](https://user-images.githubusercontent.com/37578325/48314045-ddf0f000-e5bb-11e8-9dac-64ff49389287.png)

**Comment by stas-demydiuk** [comment]
@loglux Could you please attach MQTT message from this device

**Comment by loglux** [comment]
Sorry, that's OK
I've pressed the button on the sensor and now it's working
![image](https://user-images.githubusercontent.com/37578325/48314073-32946b00-e5bc-11e8-9b3d-2c707c29d616.png)

**Comment by loglux** [comment]
Let's see what happens next

**Comment by loglux** [comment]
However

There is one issue that I guess could be fixed quickly now

![2018-11-11](https://user-images.githubusercontent.com/37578325/48315147-80b06b00-e5ca-11e8-802e-24898932a9f4.png)

Unfortunately, I missed the moment to make a screenshot

There is should be one digit after comma everywhere to avoid any confusion.

We see 20.34 and 20.3 but the problem is deeper than just 2 or 1 digit after the comma.
The 20.89 is 20.9 in Domoticz. I missed the moment but it was exactly what I saw. 
 I'd like to see the old system everywhere to avoid a mess in scripts.

**Comment by stas-demydiuk** [comment]
@loglux Could you please try now

**Comment by loglux** [comment]
The same
![image](https://user-images.githubusercontent.com/37578325/48316220-b0ff0600-e5d8-11e8-8f9b-1c43eff8f8c7.png)
![image](https://user-images.githubusercontent.com/37578325/48316227-be1bf500-e5d8-11e8-8bf2-e9d69a3195c2.png)

**Comment by stas-demydiuk** [comment]
Did you update the plugin and did you force device to send new state?

**Comment by loglux** [comment]
Sorry, I missed the point. Just one moment

**Comment by loglux** [comment]
it doesn't affect existed devices. To see changes I deleted a device then deactivate the plugin, updated it and activated it again. Then a new device was created.

**Comment by loglux** [comment]
Another sensor, which I didn't touch, still shows 2 digits.

**Comment by stas-demydiuk** [comment]
Value will be updated once device send current state

**Comment by loglux** [comment]
Yes, you're right. I pushed a button on the sensor and it shows rounded data now.

**Comment by loglux** [comment]
Thanks a Lot!

**Comment by loglux** [comment]
what about Aqara H+T+B? I'd like to wait a little seeing how others tackle with that. Does it give me a possibility for combined H+T without baro?

**Comment by stas-demydiuk** [comment]
It will create H+T+B sensor in addition to individual ones, what is the purpose you need just H+T without Baro?

**Comment by loglux** [comment]
What is the purpose to see the baro in each room? That's mental.

**Comment by stas-demydiuk** [comment]
@loglux should be available with latest master branch

**Comment by loglux** [comment]
Thanks a lot!

**Comment by Floris74** [comment]
Hi, 

I run into the same problem since i use zigbee2mqtt and your python script. I cant fix it. my tem/hum sensors are shown as 2 devices... how can i fix this?
(btw, thanks a lot for your plugin!!)
