### ISSUE TITLE
DIYRuZ DIYRuZ_magnet

### ISSUE THREAD

**Issue by imdos** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#243]
**Device description**
Description : DIYRuZ contact sensor
https://www.zigbee2mqtt.io/devices/DIYRuZ_magnet.html
https://modkam.ru/?p=1220

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
,"model":"DIYRuZ_magnet","friendly_name":"DIYRuZ_magnet-5","manufacturerID":0,"manufacturerName":"VLK_SW","powerSource":"Mains (single phase)","modelID":"DIYRuZ_magnet  ","hardwareVersion":1,"dateCode":"20190909        ","lastSeen":1580381987679}]}'
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
The sensor transmits the state of the reed switch, battery status and communication level.
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

The sensor transmits the state of the reed switch, battery status and communication level.

I've added the following to imitate a Xiaomi doorsensor.

adapters/__init__.py
from adapters.diyruz.diyruz_magnet import DiyRuzSensorMagnet
	# Custom devices (DiYRuz)
	'DIYRuZ_magnet': DiyRuzSensorMagnet # Custom devices (DiYRuz) magnet

**cat adapters/diyruz/diyruz_magnet.py**
# Adapter for Door/contact sensor found on https://modkam.ru/?p=1220
from adapters.adapter_with_battery import AdapterWithBattery
from devices.sensor.door_contact import DoorContactSensor
class DiyRuzSensorMagnet(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(DoorContactSensor(devices, 'sensor', 'contact'))

**Comment by stas-demydiuk** [comment]
Done. Could you please update plugin and check?

**Comment by imdos** [comment]
Okay, works as well.

**Comment by petrjandatu** [comment]
Please, is it possible to buy it elsewhere? Thank you.
