### ISSUE TITLE
TRADFRI LED bulb E26/E27 806 lumen, dimmable, warm white  ("LED1836G9")

### ISSUE THREAD

**Issue by Webworkx** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#244]
**Device description**
TRADFRI LED bulb E26/E27 806 lumen, dimmable, warm white  ("LED1836G9")

**MQTT message with device information**
"ieeeAddr":"0xec1bbdfffed0a424","networkAddress":19279,"friendly_name":"0xec1bbdfffed0a424","lastSeen":1580745904893

Hope you could add this device. Thanks!

**Comment by stas-demydiuk** [comment]
Done. Could you please update plugin and check

**Comment by Webworkx** [comment]
Fantastic! that was quick... It works!
