### ISSUE TITLE
CR Smart Home TS0001 Valve control

### ISSUE THREAD

**Issue by buteo72** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#245]
**Device description**
TS0001 CR Smart Home Valve control (control)

https://www.zigbee2mqtt.io/devices/TS0001.html

**MQTT message with device information**
```
{"ieeeAddr":"0x086bd7fffefb686f","type":"Router","networkAddress":11766,"model":"TS0001","friendly_name":"Regenklep         *","manufacturerID":0,"manufacturerName":"TUYATEC-pf3wdnnk","powerSource":"Mains (single phase)","modelID":"TS0001","dateCode":"20181219","lastSeen":1580766802719}]}'
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
zigbee2mqtt/Regenklep         *', payload '{"state":"ON","linkquality":120}
zigbee2mqtt/Regenklep         *', payload '{"state":"OFF","linkquality":120}
```

**I succesfully added the device in the \adapaters\__init__.py with the following information:**

    #CR Smart Home
    'TS0001':OnOffSwitchAdapter,        # WaterValve TS0001

And I can control the device from Domoticz

Regards,
Christian

**Comment by stas-demydiuk** [comment]
Thanks! Added to the plugin
