### ISSUE TITLE
Separate devices for  "battery" and "voltage"

### ISSUE THREAD

**Issue by Westcott1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#247]
Some of my sensors have "battery" and "voltage" e.g.
 "battery":100,"voltage":3045
I guess that "battery" is a percentage.

**Comment by stas-demydiuk** [comment]
Yes, battery is percentage and it is displayed in battery column on Devices page (see screenshot)

![image](https://user-images.githubusercontent.com/2734836/74603371-83e2b280-50bb-11ea-8af8-81c0d778de6d.png)

Additionally plugin creates own device for voltage data to be able to have log.

**Comment by Westcott1** [comment]
Thanks for the info!
Is this new behaviour?
My version of the plugin doesn't do it.

**Comment by stas-demydiuk** [comment]
I'd say this functionality is available for pretty long period of time.
