### ISSUE TITLE
Please add support for Weiser Lock  9GED18000-009

### ISSUE THREAD

**Issue by martardif** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#248]
Could you add the Weiser 9GED18000-009 lock to the list of devices please?

Reference: https://www.zigbee2mqtt.io/devices/9GED18000-009.html

Thanks !

**Comment by stas-demydiuk** [comment]
@martardif Could you please update plugin and check

**Comment by martardif** [comment]
It works very well! Wow! I can lock or unlock the lock from Domoticz... Thank you very, very much, I'm extremely grateful !
Is it complicated to add the state of the battery ? ({"state":"UNLOCK","linkquality":26,"**battery":100**,"user":65535,"source":1})

Greetings from Canada!

**Comment by stas-demydiuk** [comment]
It probably should show battery status on Devices page (battery column), like on the screenshot:

![image](https://user-images.githubusercontent.com/2734836/74603326-f1421380-50ba-11ea-858b-c78b824b3c24.png)

Doesn't it?

**Comment by martardif** [comment]
Yes it does, I just saw it ... Sorry ...

Thank you for your help and for adding the device!

Regards

Marco
