### ISSUE TITLE
Please put in support for a new IKEA bulb LED1903C5

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#249]
{"ieeeAddr":"0x680ae2fffe875d1a","type":"Router","networkAddress":6526,"model":"LED1903C5","friendly_name":"LampEddy","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI bulb E14 WS 470lm","hardwareVersion":1,"softwareBuildID":"2.1.022","dateCode":"20190312","lastSeen":1581419866107

https://www.ikea.com/nl/nl/p/ledare-led-lamp-e14-470-lumen-warm-dimmen-kaarslamp-opaalwit-60438588/
dimmable, color temperature and on/off

**Comment by stas-demydiuk** [comment]
Done

**Comment by SargonofAssyria** [comment]
Tnx

**Comment by SargonofAssyria** [comment]
Sorry have to reopen it.
I update my beta, I see the device in __init__.py
I restarted domoticz. I enabled Accept new hardware/sensors, but no new device in Domoticz???
I see this in the zigbee2mqtt log
`debug 2020-02-12 17:36:28: Device 'LampEddy' announced itself
debug 2020-02-12 17:36:34: Received Zigbee message from 'LampEddy', type 'readResponse', cluster 'genBasic', data '{"modelId":"TRADFRI bulb E14 WS 470lm","manufacturerName":"IKEA of Sweden"}' from endpoint 1 with groupID 0
debug 2020-02-12 17:36:35: Received Zigbee message from 'LampEddy', type 'readResponse', cluster 'genBasic', data '{"powerSource":1,"zclVersion":3}' from endpoint 1 with groupID 0
debug 2020-02-12 17:36:35: Received Zigbee message from 'LampEddy', type 'readResponse', cluster 'genBasic', data '{"appVersion":33,"stackVersion":98}' from endpoint 1 with groupID 0
debug 2020-02-12 17:36:35: Received Zigbee message from 'LampEddy', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1,"dateCode":"20190312"}' from endpoint 1 with groupID 0
debug 2020-02-12 17:36:35: Received Zigbee message from 'LampEddy', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"2.1.022"}' from endpoint 1 with groupID 0
info  2020-02-12 17:36:35: Successfully interviewed 'LampEddy', device has successfully been paired
info  2020-02-12 17:36:35: Device 'LampEddy' is supported, identified as: IKEA TRADFRI LED bulb E14 470 lumen, dimmable, white spectrum, opal white (LED1903C5)
info  2020-02-12 17:36:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"LampEddy","model":"LED1903C5","vendor":"IKEA","description":"TRADFRI LED bulb E14 470 lumen, dimmable, white spectrum, opal white","supported":true}}'
`

**Comment by SargonofAssyria** [comment]
I am on version 0.2.0 Suddenly I got this message:
`This plugin does not support zigbee device with model "LED1903C5/LED1835C6" yet`
And those bulbs don't work any more.

**Comment by stas-demydiuk** [comment]
Could you please check now

**Comment by SargonofAssyria** [comment]
Tnx, for the speedy work it works again. I already had put back an older version of zigbee2mqtt.
But this is better. I suppose you are not informed when @Koenk is changing something.
