### ISSUE TITLE
Doesn't have "model" attribute

### ISSUE THREAD

**Issue by blooesky** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#255]
When i trying to pair any device(xiaomi door sensor, xioami motion sensor, Ikea plug etc). The device is paired with succes and works but in domoticz logs show only this message.

(Zigbee2mqtt) Device 0x00158d0001daf6e5 (0x00158d0001daf6e5) doesn't have "model" attribute, skipped
(Zigbee2mqtt) Device 0x00158d0001daf6e5 (0x00158d0001daf6e5) doesn't have "model" attribute, skipped

I using CC2531 firmware CC2531_DEFAULT_20190608 ,domoticz 4.11674, the latest zigbee2mqtt plugin for domoticz

**Comment by stas-demydiuk** [comment]
It happens if zigbee2mqtt didn't receive device model from device yet. Usually it requires some time and issue will disappear by its own. Or another solution could be to repair device one (or couple) more time(s)
