### ISSUE TITLE
Please add support for Müller Licht Tint smart switch (404021)

### ISSUE THREAD

**Issue by MarcusKlerks** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#258]
Could you please add support for Müller Licht Tint smart switch (404021)?

Reference: https://www.zigbee2mqtt.io/devices/404021.html

I have added the '404021' switch to ../zigbee2mqtt/adapters/__init__.py (see below) and with that the switch works. Only thing is that it doesn't send the link quality.

# Müller Licht
'404000/404005/404012': RGBWAdapter,            # Müller Licht Tint LED bulb GU10/E14/E27 350/470/806 lumen, dimmable, color, opal white
'404006/404008/404004': DimmableCtBulbAdapter,  # Müller Licht Tint LED bulb GU10/E14/E27 350/470/806 lumen, dimmable, opal white
'404021': OnOffSwitchAdapter,										# Müller Licht Tint smart switch

Thanks in advance,
Mark

**Comment by stas-demydiuk** [comment]
Done!
