### ISSUE TITLE
support for IKEA Tradfri LED1623G12

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#26]
Hi Stas, can you please take the support for IKEA Tradfri LED1623G12?
If you tell me how I can read the data from the, I'm happy to help!
Thank you

**Comment by fkooten** [comment]
I tried to add 2 Trädfri lamps LED1623G12 and both failed to connect. Also the suggested reset did not work. What can be the reason?

**Comment by salopette** [comment]
{"ieeeAddr":"0x000b57fffe302fd0","type":"Router","mode     l":"LED1623G12","friendly_name":"0x000b57fffe302fd0"}]}

**Comment by salopette** [comment]
`{"id":10,"type":"EndDevice","ieeeAddr":"0x000b57fffe2ba3da","nwkAddr":53963,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI wireless dimmer","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":2064,"inClusterList":[0,1,3,9,2821,4096],"outClusterList":[3,4,6,8,25,4096],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{"65533":1,"batteryVoltage":0,"batteryPercentageRemaining":47,"batterySize":5,"batteryQuantity":2,"batteryAlarmMask":3,"batteryVoltMinThres":24,"batteryPercentMinThres":0,"batteryPercentThres1":20}},"genIdentify":{"dir":{"value":3},"attrs":{}},"genGroups":{"dir":{"value":2},"attrs":{}},"genOnOff":{"dir":{"value":2},"attrs":{}},"genLevelCtrl":{"dir":{"value":2},"attrs":{}},"genAlarms":{"dir":{"value":1},"attrs":{"65533":1}},"genOta":{"dir":{"value":2},"attrs":{}},"haDiagnostic":{"dir":{"value":1},"attrs":{"65533":1}},"lightLink":{"dir":{"value":3},"attrs":{"65533":1}}}}},"_id":"ONKQWxBtCaCItJkR"}
`

`{"id":10,"type":"EndDevice","ieeeAddr":"0x000b57fffe2ba3da","nwkAddr":53963,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI wireless dimmer","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":2064,"inClusterList":[0,1,3,9,2821,4096],"outClusterList":[3,4,6,8,25,4096],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{"65533":1,"batteryVoltage":0,"batteryPercentageRemaining":47,"batterySize":5,"batteryQuantity":2,"batteryAlarmMask":3,"batteryVoltMinThres":24,"batteryPercentMinThres":0,"batteryPercentThres1":20}},"genIdentify":{"dir":{"value":3},"attrs":{}},"genGroups":{"dir":{"value":2},"attrs":{}},"genOnOff":{"dir":{"value":2},"attrs":{}},"genLevelCtrl":{"dir":{"value":2},"attrs":{}},"genAlarms":{"dir":{"value":1},"attrs":{"65533":1}},"genOta":{"dir":{"value":2},"attrs":{}},"haDiagnostic":{"dir":{"value":1},"attrs":{"65533":1}},"lightLink":{"dir":{"value":3},"attrs":{"65533":1}}}}},"_id":"ONKQWxBtCaCItJkR"}
`

**Comment by salopette** [comment]
`{"id":2,"type":"Router","ieeeAddr":"0x000b57fffe302fd0","nwkAddr":51639,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E27 opal 1000lm","epList":[1],"status":"online","joinTime":1541007737,"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"10":{},"65533":1,"zclVersion":1,"appVersion":17,"stackVersion":87,"hwVersion":1,"manufacturerName":"IKEA of Sweden","modelId":"TRADFRI bulb E27 opal 1000lm","dateCode":"20160919","powerSource":1}},"genIdentify":{"dir":{"value":1},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genScenes":{"dir":{"value":3},"attrs":{"65533":1,"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"65533":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"15":0,"16384":254,"65533":1,"currentLevel":1,"remainingTime":0,"onOffTransitionTime":5,"onLevel":255}},"genOta":{"dir":{"value":2},"attrs":{}},"genPollCtrl":{"dir":{"value":2},"attrs":{}},"haDiagnostic":{"dir":{"value":1},"attrs":{"65533":1,"numberOfResets":0,"macRxBcast":0,"macTxBcast":0,"aPSRxBcast":0,"aPSTxBcast":0,"nwkFcFailure":0,"packetBufferAllocateFailures":0,"averageMacRetryPerApsMessageSent":1,"lastMessageLqi":64,"lastMessageRssi":-84}},"lightLink":{"dir":{"value":3},"attrs":{"65533":1}}}}},"_id":"lg3iLHYIg6jzO0dI"}
`

**Comment by stas-demydiuk** [comment]
@salopette could you please check with latest plugin

**Comment by salopette** [comment]
Device LED1623G12 

Hi Stas, Device LED1623G12 is not working properly anymore.
I can not dim it and turn it off.
