### ISSUE TITLE
Ikea repeater causes plugin to fail

### ISSUE THREAD

**Issue by derekoharrow** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#260]
**Issue description**
I'm using the Ikea E1746 repeater with the latest version of the Domoticz Zigbee2mqtt plugin. This causes the plugin to fail to work with the error in logs below.

The repeater is supported by zigbee2mqtt as described here - https://www.zigbee2mqtt.io/devices/E1746.html

The repeater is the next device in the list according to the Zigbee2mqtt output. 

Deleting the repeater from my Zigbee network makes everything work again, but of course I'd rather have the repeater present.

This used to work ok in the prior version.

**Additional information**
Zigbee2MQTT version: 1.10.0-dev
Python version: 3.7.3
Domoticz version: v4.11724
Plugin version: 0.1.0

**Logs**
`Feb 23 17:55:16 domoticz domoticz: (Zigbee) Received available devices list from bridge
Feb 23 17:55:16 domoticz domoticz: (Zigbee) Device BASICZBR3 0x00124b001e721f58 (Ryans_Blanket)
Feb 23 17:55:16 domoticz domoticz: (Zigbee) Device BASICZBR3 0x00124b001e7286ac (Laurens_Blanket)
Feb 23 17:55:16 domoticz domoticz: (Zigbee) Device BASICZBR3 0x00124b001e73367e (Dereks_Blanket)
Feb 23 17:55:16 domoticz domoticz: (Zigbee) Device BASICZBR3 0x00124b001e728d41 (Lindseys_Blanket)
Feb 23 17:55:16 domoticz domoticz: (Zigbee) 'onMessage' failed 'KeyError'.
Feb 23 17:55:16 domoticz domoticz: (Zigbee) ----> Line 186 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
Feb 23 17:55:16 domoticz domoticz: (Zigbee) ----> Line 100 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
Feb 23 17:55:16 domoticz domoticz: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
Feb 23 17:55:16 domoticz domoticz: (Zigbee) ----> Line 141 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
Feb 23 17:55:16 domoticz domoticz: (Zigbee) ----> Line 32 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function update
F`

**Comment by stas-demydiuk** [comment]
Could you please provide full error message and ideally MQTT message which causes plugin to fail

**Comment by derekoharrow** [comment]
The full error message from the Domoticz log file is as above.

The Zigbee2MQTT message is:

`info  2020-02-23 17:55:16: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b00014d2b83","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1582480516619},{"ieeeAddr":"0x00124b001e721f58","type":"Router","networkAddress":23937,"model":"BASICZBR3","friendly_name":"Ryans_Blanket","manufacturerID":0,"manufacturerName":"SONOFF","powerSource":"Mains (single phase)","modelID":"BASICZBR3","hardwareVersion":1,"dateCode":"20190907-V102","lastSeen":1582480422923},{"ieeeAddr":"0x00124b001e7286ac","type":"Router","networkAddress":35024,"model":"BASICZBR3","friendly_name":"Laurens_Blanket","manufacturerID":0,"manufacturerName":"SONOFF","powerSource":"Mains (single phase)","modelID":"BASICZBR3","hardwareVersion":1,"dateCode":"20190907-V102","lastSeen":1582480425168},{"ieeeAddr":"0x00124b001e73367e","type":"Router","networkAddress":40790,"model":"BASICZBR3","friendly_name":"Dereks_Blanket","manufacturerID":0,"manufacturerName":"SONOFF","powerSource":"Mains (single phase)","modelID":"BASICZBR3","hardwareVersion":1,"dateCode":"20190907-V102","lastSeen":1582480461851},{"ieeeAddr":"0x00124b001e728d41","type":"Router","networkAddress":35338,"model":"BASICZBR3","friendly_name":"Lindseys_Blanket","manufacturerID":0,"manufacturerName":"SONOFF","powerSource":"Mains (single phase)","modelID":"BASICZBR3","hardwareVersion":1,"dateCode":"20190907-V102","lastSeen":1582480506375},{"ieeeAddr":"0x000d6ffffe2ee6a9","networkAddress":23880,"model":"E1746","friendly_name":"IkeaRepeater01","manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI signal repeater","hardwareVersion":1,"softwareBuildID":"2.0.019","dateCode":"20180828","lastSeen":1582480323832}]}'
`

Of which, the JSON content is:

`{
  "ieeeAddr": "0x00124b00014d2b83",
  "type": "Coordinator",
  "networkAddress": 0,
  "friendly_name": "Coordinator",
  "softwareBuildID": "zStack12",
  "dateCode": "20190608",
  "lastSeen": 1582480516619
},
{
  "ieeeAddr": "0x00124b001e721f58",
  "type": "Router",
  "networkAddress": 23937,
  "model": "BASICZBR3",
  "friendly_name": "Ryans_Blanket",
  "manufacturerID": 0,
  "manufacturerName": "SONOFF",
  "powerSource": "Mains (single phase)",
  "modelID": "BASICZBR3",
  "hardwareVersion": 1,
  "dateCode": "20190907-V102",
  "lastSeen": 1582480422923
},
{
  "ieeeAddr": "0x00124b001e7286ac",
  "type": "Router",
  "networkAddress": 35024,
  "model": "BASICZBR3",
  "friendly_name": "Laurens_Blanket",
  "manufacturerID": 0,
  "manufacturerName": "SONOFF",
  "powerSource": "Mains (single phase)",
  "modelID": "BASICZBR3",
  "hardwareVersion": 1,
  "dateCode": "20190907-V102",
  "lastSeen": 1582480425168
},
{
  "ieeeAddr": "0x00124b001e73367e",
  "type": "Router",
  "networkAddress": 40790,
  "model": "BASICZBR3",
  "friendly_name": "Dereks_Blanket",
  "manufacturerID": 0,
  "manufacturerName": "SONOFF",
  "powerSource": "Mains (single phase)",
  "modelID": "BASICZBR3",
  "hardwareVersion": 1,
  "dateCode": "20190907-V102",
  "lastSeen": 1582480461851
},
{
  "ieeeAddr": "0x00124b001e728d41",
  "type": "Router",
  "networkAddress": 35338,
  "model": "BASICZBR3",
  "friendly_name": "Lindseys_Blanket",
  "manufacturerID": 0,
  "manufacturerName": "SONOFF",
  "powerSource": "Mains (single phase)",
  "modelID": "BASICZBR3",
  "hardwareVersion": 1,
  "dateCode": "20190907-V102",
  "lastSeen": 1582480506375
},
{
  "ieeeAddr": "0x000d6ffffe2ee6a9",
  "networkAddress": 23880,
  "model": "E1746",
  "friendly_name": "IkeaRepeater01",
  "manufacturerName": "IKEA of Sweden",
  "powerSource": "Mains (single phase)",
  "modelID": "TRADFRI signal repeater",
  "hardwareVersion": 1,
  "softwareBuildID": "2.0.019",
  "dateCode": "20180828",
  "lastSeen": 1582480323832
}
`

**Comment by stas-demydiuk** [comment]
Added support for this repeater to the plugin. But it shouldn't be the reason why plugin failed.

**Comment by derekoharrow** [comment]
That's fixed it - now the log says the following:

`2020-02-25 20:44:51.559 (Zigbee) Device 0x000d6ffffe2ee6a9 (IkeaRepeater01) doesn't have "model" attribute, skipped`

**Comment by stas-demydiuk** [comment]
@derekoharrow should the issue be closed?

**Comment by derekoharrow** [comment]
Yes. Thank you.
