### ISSUE TITLE
Heiman M420 Siren

### ISSUE THREAD

**Issue by geeano** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#261]
**Device description**
Request for support new device:
HEIMAN Smart siren (warning)
-model M420

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0xccccccfffed86303","type":"Router","networkAddress":16339,"model":"HS2WD-E","friendly_name":"0xccccccfffed86303","manufacturerID":4619,"manufacturerName":"HEIMAN","modelID":"WarningDevice-EF-3.0","hardwareVersion":16,"dateCode":"2019.5.23","lastSeen":1582707719259}


**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
MQTT publish: topic 'zigbee2mqtt/0xccccccfffed86303', payload '{"battery":100,"linkquality":15}'

**MQTT state change commands**

Received MQTT message on 'zigbee2mqtt/0xccccccfffed86303/set' with data '{"warning": {"mode": "emergency", "duration": "1", "strobe": "true"}}'

If device supports state change put MQTT topics + payload examples to change device state here

Received Zigbee message from '0xccccccfffed86303', type 'attributeReport', cluster 'ssIasWd', data '{"61440":3}' from endpoint 1 with groupID 0

**Comment by geeano** [comment]
Hello Stanislav, do you have any idea when you could look to my request. 
Due to different features compared to other devices Iḿ not able to do it my self, my python skills are too limited :-(
Thanks in advance

**Comment by geeano** [comment]
Hello Stanislav, that’s why asked your export view :-). 
There are three parameters, it would be preferable to have them all in the payload. 
Most important is mode: stop/emergency and duration in sec. So as domoticz device it should have a setting for a on/off switch feature that is converted by the plug-in in to the according payload message {“warming”: {“mode:” “emergency”, “duration:” 10}} . The value of mode could be “stop” or “emergency” and the value of duration: <1800 any value  > 0.

**Comment by stas-demydiuk** [comment]
I've added on/off switch which should activate siren, could you please checkout #261 branch and check. Also I wonder if device sends back its status? I see only battery and link quality in your example:
```
zigbee2mqtt/0xccccccfffed86303', payload '{"battery":100,"linkquality":15}
```

**Comment by geeano** [comment]
thank you, I will let you known soon

**Comment by geeano** [comment]
So far so good of first implementation (on/off with predefined duration)
There a 5 device created:
_cell:      general            Voltage           0V
_kWh:    general             kWh                0,000kWh
_signal:  general            customsensor 47               2
_switch: light/switch       switch              off
_volt:      general            voltage             0V

I don know the meaning of the powerconsumption. Only Link-quality and battery is available in the payload (in accordance of https://www.zigbee2mqtt.io/devices/HS2WD-E.html). The siren device is 240V AC powered and includes a backup battery in case of a power loss / failure.
From implementation point of view I understand your choise for using AdapterWithBattery. 
I don't understand the additional devices _volt and _kWh. Please let me known

Your question about status.
Once I activate the siren (switch on) the following messages are logged by Zigbee2MQTT: 
Mar 22 23:28:45 raspberrypi npm[547]: #033[34mzigbee2mqtt:debug#033[39m 2020-03-22 23:28:45: Received MQTT message on 'zigbee2mqtt/Heiman sirene_1st/set' with data '{"warning": {"mode": "emergency", "duration": 10}}'
Mar 22 23:28:45 raspberrypi npm[547]: #033[34mzigbee2mqtt:debug#033[39m 2020-03-22 23:28:45: Publishing 'set' 'warning' to 'Heiman sirene_1st'
Mar 22 23:28:45 raspberrypi npm[547]: #033[34mzigbee2mqtt:debug#033[39m 2020-03-22 23:28:45: Received Zigbee message from 'Heiman sirene_1st', type 'attributeReport', cluster 'ssIasWd', data '{"61440":3}' from endpoint 1 with groupID 0
Mar 22 23:28:55 raspberrypi npm[547]: #033[34mzigbee2mqtt:debug#033[39m 2020-03-22 23:28:55: Received Zigbee message from 'Heiman sirene_1st', type 'attributeReport', cluster 'ssIasWd', data '{"61440":0}' from endpoint 1 with groupID 0

I hope this answers your question. Thanks for this first step of implementation.
 




 2020-03-22 22:48:42.587 (zigbee) Command "On" from device "zigbee - Heiman sirene_2nd"
2020-03-22 22:48:42.593 (zigbee) MqttClient::publish zigbee2mqtt/Heiman sirene_2nd/set ({"warning": {"mode": "emergency", "duration": 10}})

**Comment by geeano** [comment]
Currently facing a problem after upgrading to new version (2020) of Domoticz :(

**Comment by geeano** [comment]
System recovered finally after several hours of resolving issues.
A cleaned my own files and I got rid of the additional unwanted devices. Now the expected devices are created only.
There is only one remiaing issue, which I have not investigated myself: the values of signal/link-quality and battery are not presented, although they are passed to mqtt:
2020-03-25 14:35:57.628 (zigbee) MQTT message: zigbee2mqtt/sirene-2 {'battery': 88, 'linkquality': 76}

**Comment by geeano** [comment]
Link quality appeared afterwards. For battery I created a new device request.

**Comment by geeano** [comment]
Thanks for the support. Really appreciated !

**Comment by geeano** [comment]
I added some code to send proper value to the additional features

        mode = 'emergency' if command.upper() == 'ON' else 'stop'
        strobe = 'true' if command.upper() == 'ON' else 'false'

        return {
            'topic': device_data['friendly_name'] + '/set',
            'payload': json.dumps({
                'warning': {
                        'mode': mode,
                        'strobe': strobe,
                        'duration': 1000
                        }
                })
        }

**Comment by Enjoy-Combi** [comment]
Hi,

I can see that the duration is 1000. Mine appears to last for 10 seconds not more. When I send a mosquitto_pub with duration to something else than 10 s it is OK.
Is there a location where I can define this parameter ?

**Comment by Enjoy-Combi** [comment]
Hi,

Found, duration located into siren.py under gerneric.
