### ISSUE TITLE
Ikea Tradfri on/off/up/down switch E1743 clicks

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#262]
**Issue description**
Zigbee2mqtt is sending "on" directly followed with a "" message.
It is translated in a "On" followed by a "Off" by the plugin to Domoticz.
It should only an "On" the "" should be discarded.

**Additional information**
Zigbee2MQTT version: 1.11.0-dev
Python version: 7.5.3
Domoticz version: 4.10717
Plugin version: 0.1.0

**Comment by pcurt** [comment]
Hi,
Can you please paste you log ?
For me, I have only one message sent by Zigbee2mqtt (I am using version 1.11.0 form master branch) 

```
2020-03-01 13:15:25.104 (Zigbee) MqttClient::ping
2020-03-01 13:15:32.819 (Zigbee) MQTT message: zigbee2mqtt/0x000d6ffffef35739 {'update_available': True, 'linkquality': 113, 'battery': 87, 'click': 'close'}
2020-03-01 13:15:35.087 (Zigbee) MqttClient::ping
2020-03-01 13:15:37.141 (Zigbee) MQTT message: zigbee2mqtt/0x000d6ffffef35739 {'update_available': True, 'linkquality': 113, 'battery': 87, 'click': 'open'}
```

**Comment by SargonofAssyria** [comment]
`info  2020-03-01 15:04:53: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":15,"last_seen":"2020-03-01T15:04:53+01:00","battery":74,"update_available":true,"device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 15:04:53: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":15,"last_seen":"2020-03-01T15:04:53+01:00","battery":74,"update_available":true,"click":"off","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 15:04:53: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":15,"last_seen":"2020-03-01T15:04:53+01:00","battery":74,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
`

**Comment by pcurt** [comment]
Have you try with Zigbee2MQTT branch master ?

**Comment by SargonofAssyria** [comment]
I did not, but now I have and it still the same.
1 message with on followed by an empty message in the same second.
So my domoticz device log shows an 'On' directly followed by an 'Off'

**Comment by SargonofAssyria** [comment]
With debug on this is what I get from zigbee2mqtt.
First 1 short click "I" then long click "I", then short click "O" and then long click "O"
`debug 2020-03-01 17:07:30: Received Zigbee message from 'SchakelaarEddy', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:30: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'on'
info  2020-03-01 17:07:30: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":39,"last_seen":"2020-03-01T17:07:30+01:00","battery":87,"update_available":true,"click":"on","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:30: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":39,"last_seen":"2020-03-01T17:07:30+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
debug 2020-03-01 17:07:32: Received Zigbee message from 'SchakelaarEddy', type 'commandMoveWithOnOff', cluster 'genLevelCtrl', data '{"movemode":0,"rate":83}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:32: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'brightness_up'
info  2020-03-01 17:07:32: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":42,"last_seen":"2020-03-01T17:07:32+01:00","battery":87,"update_available":true,"click":"brightness_up","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:32: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":42,"last_seen":"2020-03-01T17:07:32+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
debug 2020-03-01 17:07:33: Received Zigbee message from 'SchakelaarEddy', type 'commandStopWithOnOff', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:33: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'brightness_stop'
info  2020-03-01 17:07:33: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":39,"last_seen":"2020-03-01T17:07:33+01:00","battery":87,"update_available":true,"click":"brightness_stop","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:33: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":39,"last_seen":"2020-03-01T17:07:33+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
debug 2020-03-01 17:07:34: Received Zigbee message from 'SchakelaarEddy', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:34: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'off'
info  2020-03-01 17:07:34: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:34+01:00","battery":87,"update_available":true,"click":"off","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:34: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:34+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
debug 2020-03-01 17:07:36: Received Zigbee message from 'SchakelaarEddy', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":83}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:36: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'brightness_down'
info  2020-03-01 17:07:36: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:36+01:00","battery":87,"update_available":true,"click":"brightness_down","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:36: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:36+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
debug 2020-03-01 17:07:37: Received Zigbee message from 'SchakelaarEddy', type 'commandStopWithOnOff', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 901
info  2020-03-01 17:07:37: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy/click', payload 'brightness_stop'
info  2020-03-01 17:07:37: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:37+01:00","battery":87,"update_available":true,"click":"brightness_stop","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
info  2020-03-01 17:07:37: MQTT publish: topic 'zigbee2mqtt/SchakelaarEddy', payload '{"linkquality":55,"last_seen":"2020-03-01T17:07:37+01:00","battery":87,"update_available":true,"click":"","device":{"friendlyName":"SchakelaarEddy","model":"E1743","ieeeAddr":"0xec1bbdfffe910c8a","networkAddress":34544,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":34,"stackVersion":98,"zclVersion":3,"hardwareVersion":1,"dateCode":"20190410","softwareBuildID":"2.2.008"}}'
`

**Comment by pcurt** [comment]
Can you test with my forked repo please ?

**Comment by SargonofAssyria** [comment]
I would if I know how, and how to get back fast, because I am on a production system.
I tried to only change the 2 ikea files from your repo but that did not work out well.

**Comment by pcurt** [comment]
There was an error in file tradfri_remote_close_open.py. Only change file tradfri_switch_on_off.py with my update, then restart domoticz. 
And can you paste domoticz log please ?

**Comment by SargonofAssyria** [comment]
Not successfull.
`2020-03-01 20:22:28.577 Error: (Zigbee) 'onMessage' failed 'NameError':'name 'Domoticz' is not defined'.
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 186 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 100 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 159 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 61 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_mqtt_message
2020-03-01 20:22:28.577 Error: (Zigbee) ----> Line 28 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/ikea/tradfri_switch_on_off.py', function handleMqttMessage`

**Comment by pcurt** [comment]
Thanks for the log, I fixed it. Hope it is good now

**Comment by SargonofAssyria** [comment]
It "almost" seems to do the trick. The empty command translated to 'off' is gone, so On and Off work now. Tnx.
The device sends after the long click is released (up or down) the stop command. That seems OK.
But now there is a challenge to get the right triggers in Domoticz.

**Comment by pcurt** [comment]
We can add a release command in Domoticz selector switch, I think it would be better

This error log is at Domoticz startup or when you send a command ?
What do you mean by "get the right triggers in Domoticz." ?

**Comment by SargonofAssyria** [comment]
The error log is from every command send,
I have to make a dzVents script to change the brightness of a Bulb depending on how long the click is held. I am almost there. So the current 'Stop' command is fine for me.

**Comment by pcurt** [comment]
Great,
The error is due to a log that I haded, but it shouldn't. 
I remove the log, can you check that there is no error anymore ?

**Comment by SargonofAssyria** [comment]
Error is gone.

**Comment by pcurt** [comment]
Tanks for the help. I create the pull request to share the fix.
