### ISSUE TITLE
E1524/E1810 remote Switch (ON/OFF) weird behaviour after update v.0.1.0 

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#265]
**Issue description**
E1524/E1810 remote (ON/OFF switch), which was recently updated in your plugin, because the ON/OFF part of the switch did not work properly, sometimes switches back to old behaviour of not responding while pressing the on/off button.
When this happens, the only option is to remove the device, restart domoticz and add the switch again.

It is hard to track why and when this happens, any idea how to figure out what goes wrong here?

**Additional information**
Zigbee2MQTT version: 1.10.0
Python version:
Domoticz version: 4.11674
Plugin version: v.0.1.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
Do you see any errors in DOmoticz log or could you please provide MQTT messages from/to device when you see odd behavior?

**Comment by Anjerlaan** [comment]
Nope, but I will the next time, although i haven't seen it since I mentioned it in the thread...but it happened twice

**Comment by Anjerlaan** [comment]
Hi, I know what causes the problem now.

When I shutdown/start or restart the Raspberry Pi, the "E1524/E1810" remote (ON/OFF switch) does not respond anymore when I hit the button of the physical remote. But when I restart Zigbee2mqtt and Domoticz from the console the Switch is working as expected.

![afbeelding](https://user-images.githubusercontent.com/18295963/92511304-67e85f00-f20d-11ea-8615-2d0ff73192a5.png)

So I guess this has something to do with the order Zigbee2mqtt and Domoticz are started during boot?

**Comment by Anjerlaan** [comment]
It must be something with the order of loading the mosquitto and domoticz services because when I add:
`"DAEMON_ARGS="$DAEMON_ARGS -startupdelay 20"`
to "sudo nano /etc/init.d/domoticz.sh", the behaviour is as expected. (10 is too short)
