### ISSUE TITLE
RGBWW for groups

### ISSUE THREAD

**Issue by Gerard-Oedzes** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#270]
is rgbww suported for groups?

**Comment by stas-demydiuk** [comment]
Not yet, do you need such support?

**Comment by Gerard-Oedzes** [comment]
Would be nice !!

**Comment by Gerard-Oedzes** [comment]
Hallo, 

anny progress on this? 
It also would be nice if there is an option to not show the link quality (becouse in my case it is always zero) 

thnx!

**Comment by Gerard-Oedzes** [comment]
>  I wonder if you could update plugin and check

Thnx! working perfect! 

config.yaml:

`'3':
    friendly_name: woonkamer plafond spots_rgbw
    retain: false
    transition: 2
    optimistic: true
    devices:
      - '0x00178801045400e3'
      - '0x0017880104540a7e'
      - '0x0017880104540931'
`
![RGBW](https://user-images.githubusercontent.com/46130680/78421602-492bde00-7659-11ea-979f-eda61225feee.PNG)

Light are running verry smooth... 

One question left... my Hue Link Quality is allways zero.. is this becouse im using old HUE bulbs?

**Comment by stas-demydiuk** [comment]
Hard to say, if you could provide your MQTT message with light status it would be easier to say.
