### ISSUE TITLE
ICZB-IW11SW unreliable

### ISSUE THREAD

**Issue by janjansen1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#272]
I have been using this switch for a while now in combination with Domoticz and your plugin. Switching on has not caused any problems so far, but switching off very often often does not go well. When it goes wrong, the Domoticz log shows:

![image](https://user-images.githubusercontent.com/25150865/77248650-5d281680-6c3b-11ea-8da3-e1f8bd9817f5.png)

What is going wrong? 

Thank you in advance for your answer!

**Comment by geeano** [comment]
Is it not caused in the zigbee2mqtt domain ? Zigbee2mqtt logs could give further Info. KoenK could help you if you adress in the according github.

**Comment by stas-demydiuk** [comment]
Closing the issue as it is not related to plugin but to zigbee in general
