### ISSUE TITLE
Battery based devices without 'voltage' status.

### ISSUE THREAD

**Issue by geeano** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#273]
**Device description**
number of devices

**MQTT messages from device**

IKEA E1525/E1745
MQTT message: zigbee2mqtt/garage-motion {'occupancy': False, 'linkquality': 52, 'battery': 60, 'requested_brightness_level': 254, 'requested_brightness_percent': 100, 'update_available': False}
Heiman M420 Siren
(zigbee) MQTT message: zigbee2mqtt/sirene-2 {'battery': 88.5, 'linkquality': 15}

**Issue**
The battery status is only given by a pecentage and this percentage value is not presented in a device. Only an icon is given in the Device list. These devices do not provide a ‘voltage’ value.

**Request**
Would it be possible to create a new device to present the percentage of the battery charge. With this additional device it is possibe to set an alarm once the value becomes to low.

**Comment by stas-demydiuk** [comment]
@geeano could you please update plugin and check. New device should be available for all battery-powered devices

**Comment by geeano** [comment]
Thanks for your effort. Unfortunately I'm not at home. I wil let you know on Tuesday.
I appreciate your support.

**Comment by geeano** [comment]
![afbeelding](https://user-images.githubusercontent.com/45628879/80605518-7fc7ff00-8a33-11ea-85f3-f4c301fa8017.png)

The battery percentage value is available but not presented in the battery-percentage device.

Apr 29 15:39:17 raspberrypi npm[7098]: #033[32mzigbee2mqtt:info #033[39m 2020-04-29 15:39:17: MQTT publish: topic 'zigbee2mqtt/sirene-1', payload '{"battery":100,"linkquality":2}'

**Comment by geeano** [comment]
Battery percentage values are meanwhile updated. Unclear 
Request can be closed.
