### ISSUE TITLE
Support new device Ferguson Gas Sensor

### ISSUE THREAD

**Issue by fescik** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#274]
**Device description**

Vendor: Ferguson
Model: FS1RG
Zigbee model: GAS_V14

MQTT message: zigbee2mqtt/bridge/log {'type': 'devices', 'message': [{'ieeeAddr': '0x00124b00014ef40e', 'type': 'Coordinator', 'networkAddress': 0, 'friendly_name': 'Coordinator', 'softwareBuildID': 'zStack12', 'dateCode': '20190608', 'lastSeen': 1585253081828}, {'ieeeAddr': '0x005043c91737a595', 'type': 'Router', 'networkAddress': 46723, 'model': 'FS1RG', 'vendor': 'Ferguson', 'description': 'Combustible gas sensor', 'friendly_name': '0x005043c91737a595', 'manufacturerID': 48042, 'manufacturerName': 'Heiman', 'powerSource': 'Mains (single phase)', 'modelID': 'GAS_V14', 'hardwareVersion': 1, 'dateCode': '20150330', 'lastSeen': 1585252147230}]}

**Comment by stas-demydiuk** [comment]
Could you please attach message with device status as well?

**Comment by fescik** [comment]
MQTT message: zigbee2mqtt/0x005043c91737a595 {'gas': False, 'tamper': False, 'battery_low': False, 'linkquality': 13}
2020-03-28 08:49:09.628 (Zigbee2MQTT) Unhandled message from zigbee2mqtt: zigbee2mqtt/0x005043c91737a595 {'gas': False, 'tamper': False, 'battery_low': False, 'linkquality': 13} 
This is it?

**Comment by stas-demydiuk** [comment]
Yes it is. Why I don't see this device here https://www.zigbee2mqtt.io/information/supported_devices.html?

**Comment by fescik** [comment]
The device was added manually by manul here https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
I think this is a very similar device to this: https://www.zigbee2mqtt.io/devices/HS1CG-M.html
It even looks the same.

**Comment by stas-demydiuk** [comment]
Ok, could you please update plugin and check

**Comment by fescik** [comment]
Thank you very much. Everything works. The devices have been created.
