### ISSUE TITLE
HEIMAN SMHM-I1 - Can you please update the plugin to support it

### ISSUE THREAD

**Issue by whyzermans** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#275]
**Device description**
It is a Heiman Motion sensor - recognized as SMHM-I1. Normally listed in devices js. Messages from device appear normal. I saw there are other HEIMAN devices marked as supported for this version of the plugin but not this one. I would be glad if you could prepare that.Thanks in advance.

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
zigbee2mqtt:info  2020-03-28 10:52:56: HEIMAN Smart Motion Sensor (0x005043c917387fa0): SMHM-I1 - HEIMAN Smart motion sensor (EndDevice)

```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
zigbee2mqtt:info  2020-03-28 11:13:22: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":false,"tamper":false,"battery_low":false,"linkquality":110}'
zigbee2mqtt:info  2020-03-28 11:16:00: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":true,"tamper":false,"battery_low":false,"linkquality":115}'
zigbee2mqtt:info  2020-03-28 11:17:01: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":false,"tamper":false,"battery_low":false,"linkquality":115}'
zigbee2mqtt:info  2020-03-28 11:17:03: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":true,"tamper":false,"battery_low":false,"linkquality":110}'
zigbee2mqtt:info  2020-03-28 11:18:04: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":false,"tamper":false,"battery_low":false,"linkquality":115}'
zigbee2mqtt:info  2020-03-28 11:19:31: MQTT publish: topic 'zigbee2mqtt/HEIMAN Smart Motion Sensor', payload '{"occupancy":true,"tamper":false,"battery_low":false,"linkquality":113}'

```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by whyzermans** [comment]
Hi Stas. Thanks for the speedy action - of course it works. Closing the issue.
