### ISSUE TITLE
How to update Ikea devices ? 

### ISSUE THREAD

**Issue by varazir** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#276]
Hello, 

How do I update IKEA devices with this plugin ? 
The log from zigbee2mqtt say that my remote control has a update. 

Version: 2020.1 (build 11836)
Build Hash: 7e0c5045a
Compile Date: 2020-03-25 17:53:32
dzVents Version: 3.0.1
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
(zigbee2mqtt) Initialized version 0.1.0

With latest update from github ( 20200331)  of this plugin and zigbee2mqtt

**Comment by big-ted** [comment]
Click on the device to open the details page, click on the Update Firmware button in the OTA update panel, only do one device at a time

**Comment by varazir** [comment]
> Click on the device to open the details page, click on the Update Firmware button in the OTA update panel, only do one device at a time
How do you mean ? I clicked the edit button on the device and it show me https://i.imgur.com/5TmlypO.png

**Comment by big-ted** [comment]
Sorry my mistake, you need to use something like Zigbee2MqttAssitant or use a MQTT client with the topic zigbee2mqtt/bridge/ota_update/update and a payload of the device as named in Zigbee2mqtt

**Comment by pcurt** [comment]
Install on your system the following package:
`sudo apt-get install mosquitto-clients`
Then execute from your system the following command:
`mosquitto_pub -h localhost -t "zigbee2mqtt/bridge/ota_update/update" -m '0x000d6ffffef35739'`
(Replace the device Id with your own device)

**Comment by varazir** [comment]
> Install on your system the following package:
> `sudo apt-get install mosquitto-clients`
> Then execute from your system the following command:
> `mosquitto_pub -h localhost -t "zigbee2mqtt/bridge/ota_update/update" -m '0x000d6ffffef35739'`
> (Replace the device Id with your own device)

Thanks I'll check that out.

**Comment by varazir** [comment]
> Install on your system the following package:
> `sudo apt-get install mosquitto-clients`
> Then execute from your system the following command:
> `mosquitto_pub -h localhost -t "zigbee2mqtt/bridge/ota_update/update" -m '0x000d6ffffef35739'`
> (Replace the device Id with your own device)

It worked and not, but it's not a plugin issue. Would been nice to have this in the plugin it self but you can't get everything. 

 I'll check in the github for zigbee2mqtt for more TS. 

Thanks again.  Maybe add this to the wiki.
