### ISSUE TITLE
Bitron door sensor

### ISSUE THREAD

**Issue by Sh800904** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#277]
**Device description**
Bitron AV2010/21A Door sensor 

2020-04-01 19:34:11.987 (Zigbee2MQTT) This plugin does not support zigbee device with model "AV2010/21A" yet

*MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x00158d0001bd0e35","type":"EndDevice","model":"WXKG01LM","friendly_name":"0x00158d0001bd0e35"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
T publish: topic 'zigbee2mqtt/0x00124b0008a687d7', payload '{"contact":true,"tamper":true,"battery_low":false,"linkquality":26}'

**Comment by geeano** [comment]
The model in the MQTT seems not to be a Bitron door sensor:

https://www.zigbee2mqtt.io/devices/WXKG01LM.html

**Comment by Sh800904** [comment]
Thanks for your help! This fast! Wow!
