### ISSUE TITLE
Devices lastUpdate correct in GUI, incorrect in dzVents

### ISSUE THREAD

**Issue by raqua** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#278]
**Issue description**
I have a new script that notifies me, if any device has not been seen for some time. This script uses dzVents and sends me an email if last seen time of device is over my predefined threshold. 
I have mostly Xiaomi devices and those send a heartbeat. This is correctly reflected in Domoticz GUI, I see the last seen date time when a heartbeat message was sent. However, when querying this in dzVents, I only get the time of last state change, not the heartbeat. 
This is happening for Xiaomi's Motion Sensor, Button, Water Leak Sensor, Door Contact sensor. 

**Additional information**
Zigbee2MQTT version: 1.12.0
Python version: 3.8.1
Domoticz version: V4.11672
Plugin version: version 0.0.20

**Comment by raqua** [comment]
I have this script to show the behavior:
```
return
{
    on =
    {
        timer = { 'every minute' },
    },


    execute = function(dz, item)

        local dev = dz.devices().find(
            function(device)
                return device.name == 'Obyvacka/Vypinac/Svetlo'
            end)

        dz.log('UPDATE minutesAgo: ' .. dev.lastUpdate.minutesAgo)
        dz.log('UPDATE secondsAgo: ' .. dev.lastUpdate.secondsAgo)
        dz.log('UPDATE minutes: ' .. dev.lastUpdate.minutes)
        dz.log('UPDATE raaw: ' .. dev.lastUpdate.raw)
        
    end
}

```

**Comment by raqua** [comment]
![Screenshot from 2020-04-03 12-16-00](https://user-images.githubusercontent.com/1541886/78353352-2f7f8d80-75aa-11ea-9e8a-f81263a08c18.jpg)
![Screenshot from 2020-04-03 12-16-14](https://user-images.githubusercontent.com/1541886/78353354-30182400-75aa-11ea-906e-b84d256c052c.jpg)
![Screenshot from 2020-04-03 12-38-56](https://user-images.githubusercontent.com/1541886/78353355-30182400-75aa-11ea-9ee5-f189bb4a67ab.jpg)

**Comment by raqua** [comment]
As you can see on the 3 screenshots above:
12:02:27 heartbeat the device in Zigbee2Mqtt logs
On the second screen you see the device last seen date correctly set in GUI
On the third screenshot you can see that 12:36 my TEST script that I posted above run and showed that the device was last updated 9:32, which is when it was probably have been pushed. It does not reflect the hearbeat from 12:02. I have then pushed the button twice and the subsequent TEST script run shows that it is now updated.

**Comment by stas-demydiuk** [comment]
This issue should be addressed on Domoticz itself. Domoticz basically has 2 values: LastSeen and LastUpdate which behave differently depending on area (like UI and dzVents scripts)
