### ISSUE TITLE
Samsung SmartThings Smart Plug

### ISSUE THREAD

**Issue by derekoharrow** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#279]
Please can you add support for the Samsung SmartThings Smart Plug, which is already supported by zigbee2mqtt - https://www.zigbee2mqtt.io/devices/GP-WOU019BBDWG.html (support has been added for the F-APP-UK-V2, but not for this one).

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0xccccccfffe3cc886","type":"Router","networkAddress":6053,"model":"GP-WOU019BBDWG","friendly_name":"Cabin_Heater","manufacturerID":4456,"manufacturerName":"LDS","powerSource":"Mains (single phase)","modelID":"ZB-ONOFFPlug-D0005","hardwareVersion":1,"softwareBuildID":"2.3","dateCode":"20190716-165","lastSeen":1585916990652}]
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
info  2020-04-03 13:34:52: MQTT publish: topic 'zigbee2mqtt/Cabin_Heater', payload '{"power":0,"current":0,"voltage":0,"linkquality":13,"state":"OFF"}'
```

**MQTT state change commands**
See here - https://www.zigbee2mqtt.io/devices/GP-WOU019BBDWG.html

**Comment by geeano** [comment]
If you add a row in file /adapters/samsung/__init__.py at the end of the list,than it supports your power socket:

samsung_adapters = {
.
.
'F-APP-UK-V2': OnOffSwitchAdapter,  # SmartThings Outlet
'GP-WOU019BBDWG': OnOffSwitchAdapter, # SmartThings Outlet (new)
}

new = your device entry

**Comment by geeano** [comment]
"__init__.py"

**Comment by geeano** [comment]
> __init__.pi

>

**Comment by derekoharrow** [comment]
I've done that, and it works fine for on/off, but this switch has power monitoring, so that doesn't capture the power or usage info.

**Comment by geeano** [comment]
I see did not considered the additional features. In that case you have to created a new class.

Change the \__init\__.pi file

from adapters.samsung.GPWOU019BBDWG import GPWOU019BBDWG

'GP-WOU019BBDWG': GPWOU019BBDWG, # SmartThings Outlet (new)


==create new file GPWOU019BBDWG.py============

from adapters.on_off_switch_adapter import OnOffSwitchAdapter
from devices.sensor.current import CurrentSensor
from devices.sensor.voltage import VoltageSensor
from devices.sensor.kwh import KwhSensor


class GP-WOU019BBDWG(OnOffSwitchAdapter):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(VoltageSensor(devices, 'volt', 'voltage', ' (Voltage)'))
        self.devices.append(CurrentSensor(devices, 'ampere', 'current', ' (Current)'))
        self.devices.append(KwhSensor(devices, 'power', ['power'], ' (Power)'))

==
you can take the inri/SP120 as example code, you need to modify the class name en file

Be aware changes for your own risk. I'm not an expert ..

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by geeano** [comment]
Hi Stanislav, I saw in the payload three attributes:
payload '{"power":0,"current":0,"voltage"

Therefore I suggested to create a new class. I was not aware about the limit generic kWh class that you presented

**Comment by derekoharrow** [comment]
Brilliant - thank you!
