### ISSUE TITLE
Cannot connect Trädfri lamps LED1623G12

### ISSUE THREAD

**Issue by fkooten** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#28]
I tried to add 2 Trädfri lamps LED1623G12 and both failed to connect. Also the suggested reset did not work. What can be the reason as it happens to both? I have installed Trädfri lamps before without any issue. #27

**Comment by stas-demydiuk** [comment]
@fkooten Do they fail to connect to plugin or to zegbee gateway?

**Comment by fkooten** [comment]
after I added the type of lamp from the Trädfri selections I follow the instruction. To connect I should power off and on the lamp to start the initiation of the connection. When fail I should switch the lamp quickly on and off 6 times to reset, confirmed by the lamp twice lightning. Both these instructions do fail on both lamps

**Comment by stas-demydiuk** [comment]
I would suggest to ask directly on [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/issues) tracker, more chances to get help as this plugin is only about connecting devices from zigbee2mqtt to domoticz
