### ISSUE TITLE
Add support for SALUS SP600 socket

### ISSUE THREAD

**Issue by derekoharrow** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#280]
**Device description**
Salus SP600 as described here - https://www.zigbee2mqtt.io/devices/SP600.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x001e5e0902145f59","type":"Router","networkAddress":59137,"model":"SP600","friendly_name":"Tumble_Dryer","manufacturerID":4216,"manufacturerName":"Computime","powerSource":"Mains (single phase)","modelID":"SP600","hardwareVersion":2,"dateCode":"20160217","lastSeen":1585920798280}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
info  2020-04-03 14:47:32: MQTT publish: topic 'zigbee2mqtt/Tumble_Dryer', payload '{"energy":0.13,"linkquality":23,"state":"ON","power":285.5}'
```

**MQTT state change commands**
See here - https://www.zigbee2mqtt.io/devices/SP600.html

**Comment by derekoharrow** [comment]
I've got this working for now by adding the following to the top-level __init__.py:

` 'SP600': OnOffKwhAdapter,`

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by geeano** [comment]
productive day :-)

**Comment by derekoharrow** [comment]
Perfect - thank you!
