### ISSUE TITLE
Enhancement: OTA

### ISSUE THREAD

**Issue by JanJaapKo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#282]
Hi @stas-demydiuk ,

The Zigbee2MQTT allows OverTheAir (OTA) updates for certain devices to update their firmware. It would be interesting to expose this functionality from Domoticz.

Proposal:
- record in the device structure the need to update the firmware
- add switch on the plugin front end to enable the updates (remove MQTT Client ID parameter)
- loop over all devices that need an update and trigger this update when needed

The Zigbee2MQTT project indicates that the updates consume quite some bandwidth so should really be a user triggered action.

If you agree I can try some prototyping.

**Comment by kovainfo** [comment]
I will support!
And also add to the plugin the construction of a zigbee network.
The prototype is ready:
https://github.com/kovainfo/Domoticz-zigbee2mqtt-network-map

Moreover, you can develop a whole page on managing Zigbee devices through a separate tab (for example, through a custom template)

**Comment by JanJaapKo** [comment]
@kovainfo that looks like a nice addition as well. Please make a separate issue or PR for it so Stas can check it and merge if accepted.

**Comment by Luigi8723** [comment]
@kovainfo wow, nice Like Hass will Zigbee2mqtt directly support in Domoticz :)

**Comment by cocooma** [comment]
@kovainfo Awesome I was looking for this for a while. About to get it installed just pulling the latest Domoticz dev branch down

**Comment by kovainfo** [comment]
may be @stas-demydiuk 

> @kovainfo Awesome I was looking for this for a while. About to get it installed just pulling the latest Domoticz dev branch down

I hope that @stas-demydiuk  will pick up this project)) and we will get not only a beautiful network map, but also a full interface for zigbee2mqtt
I just don’t know JS very well, and this solution also uses external utilities. Instead of these utilities, everything could be done on the python plugin. For example, creating a service device "coordinator" that would work out various commands such as building a network, device joining, decoupling, updating OTA firmware, etc. And for the user - a separate page for configuring and displaying the entire zigbee2mqtt infrastructure.

**Comment by stas-demydiuk** [comment]
I would love to add such custom page to control zigbee2mqtt, but unfortunately currently I don't know any way how to setup communication channel between such page and python plugin.

**Comment by kovainfo** [comment]
> I would love to add such custom page to control zigbee2mqtt, but unfortunately currently I don't know any way how to setup communication channel between such page and python plugin.

I propose the following communication scheme:

The plugin creates an additional service device of type Text, where the sValue field will be a command field.
Operations to interact with the plugin and MQTT broker can be performed through the domoticz API / JSON url's:
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s

eg:
https: // <My IP> /json.htm?type=command&param=udevice&idx=437&svalue=Delete%200x12312312312321

The plugin receives the change in the sValue field and processes it in accordance with the internal logic.

**Comment by kovainfo** [comment]
for example:
<img width="1436" alt="Снимок экрана 2020-04-11 в 12 12 38" src="https://user-images.githubusercontent.com/36986231/79039989-ce7d3880-7bed-11ea-93e0-89a172edb30a.png">

**Comment by stas-demydiuk** [comment]
Implemented in scope of #291
