### ISSUE TITLE
Missing support for AC10786-DIM

### ISSUE THREAD

**Issue by Luigi8723** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#283]
I have added the Osram Smart+ Classic E27 Dimmable "AC10786-DIM"
Which is support byZigbee2mqtt ( https://www.zigbee2mqtt.io/devices/AC10786-DIM.html) , but there is no new device created in Domoticz, so I assume this one is not supported by the plugin.

Is this possible to add to the plugin?
I am not sure how to do this manualy 

Edit:

The link in the text below all supported devices is dead  https://koenkk.github.io/zigbee2mqtt/information/supported_devices.html ) 

In the text:
If your device is not listed here but zigbee2mqtt supports it, support can be added (fairly) easy by creating device adapter.

**Comment by stas-demydiuk** [comment]
Done, added to plugin

**Comment by Luigi8723** [comment]
Wow thats fast:) so i need to update the plugin en it will added to domoticz?

**Comment by stas-demydiuk** [comment]
Yes, you need to update plugin and restart Domoticz

**Comment by Luigi8723** [comment]
Will do (tomorrow) thanks

**Comment by Luigi8723** [comment]
Working nicely :) thanks
