### ISSUE TITLE
Tradfri E1524 does not work

### ISSUE THREAD

**Issue by albertomarrod** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#285]
Hi everyone! I am a new guy into this and I am not able to make the Tradfri E1524 works...

I was able to connect the Tradfri to the raspberry and this also with Domoticz as you can see on the pictures. The thing is, once I pair the Tradfri E1524 to the raspberry, the device does not work anymore. I mean, when I push any button on the device the lights does not do anything at all neither by pressing the buttons on domoticz.

![ZTM](https://user-images.githubusercontent.com/28586855/78793646-fc2a6d80-79b2-11ea-945b-f9adfd1f7e12.PNG)

I do not know if I am doing something wrong or I am not paring well the device. To pair it I have pressed 4 times the button as the manual says next to the CC2531 USB stick.

Could somebody help me with this?

Thank you so much in advance

**Comment by albertomarrod** [comment]
Hi! Just to add more information...

Appart from the E1524 I've got the IKEA TRADFRI driver for wireless control (30 watt) which is connected to the remote...

I had also tried to connect this driver to domoticz but once is connected nothing happens either... I am trying to trigger the lights from domoticz and nothing happens... Neither from the devices nor domoticz...


Please, any help? I am doing something wrong?

**Comment by stas-demydiuk** [comment]
I guess you need to pair your bulbs to the same zigbee stick as you did for E1524. After that you can create zigbee group with E1524 and all bulbs or configure it via dzVents as example

**Comment by albertomarrod** [comment]
> I guess you need to pair your bulbs to the same zigbee stick as you did for E1524. After that you can create zigbee group with E1524 and all bulbs or configure it via dzVents as example

Thank you for your reply!

Maybe I am not explaining well myself... What I've got it's the next...

I've got an tradfri E1524 who is connected to the IKEA TRADFRI driver for wireless control (30 watt). This last device is connected by cable to a few OMLOPP lights.

I have connected both of them to domoticz but nothing happens... I assume that to control the OMLOPP lights I have to doing through the TRADFRI driver as they are connected through cable...

Should I do something else? Do you need any kind of log to be able to help me more?

Thanks and sorry... I'm bit desperate with this as I had to take apart the kitchen cabinets to reach the TRADFRI control

**Comment by geeano** [comment]
What was the original setup ? Where you able to control the Tradfri driver directly with the E1524 controller or where using the Tradfri hub?

**Comment by albertomarrod** [comment]
> What was the original setup ? Where you able to control the Tradfri driver directly with the E1524 controller or where using the Tradfri hub?

Hi geeano!

Yes, I was able to control the TRADFRI driver directly with the E1524 controller.

The original setup is as I wrote on the comment above:

"A tradfri E1524 who is connected to the IKEA TRADFRI driver for wireless control (30 watt). This last device (the TRADFRI driver for wireless control) is connected by cable to a few OMLOPP lights."

Any idea?

Thanks

**Comment by geeano** [comment]
You have to connect / pair the Tradfri driver to the CC2531 Zigbee stick. Once it is succesfully paired it will appear as a new device in the device list of domoticz

**Comment by albertomarrod** [comment]
That is what I did it. It appears on domoticz but when I tried to change the status on domoticz, nothing happens... I don't understand why

**Comment by geeano** [comment]
In your screendump I don't see the Traffic driver. Did it appear on the device list too? If it is listed two you have too create an event or script that trigger the Traffic driver once you press a key on your E1524 switch. You can first check if the status of the switch is changing once you press a button.

**Comment by stas-demydiuk** [comment]
@albertomarrod was you able to setup your bulbs and E1524?

**Comment by albertomarrod** [comment]
> @albertomarrod was you able to setup your bulbs and E1524?

Hi @stas-demydiuk! No, I wasn't able to pair them... I don't know what's happening as the TRADFRI driver is doing nothing when I trigger the button either in domoticz or the E1524

**Comment by stas-demydiuk** [comment]
Have you paired bulbs to zigbee2mqt as well?

**Comment by albertomarrod** [comment]
They are LEDs and connected to the driver through a wire it's the driver which trigger these leds

**Comment by geeano** [comment]
Alberto, where you able to pair the driver and is it visible in device list of domoticz?
