### ISSUE TITLE
HLC610-Z - Shenzhen Homa Wireless dimmable controller can't be added

### ISSUE THREAD

**Issue by jvrrr** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#286]
Hi ,

In Zigbee2mqtt, the device is found and added.
But the Domoticz plug does not find it.

I'm a newbie...so I have tried to do my best to delicer all the information I can found.
I did'nt find any payload...maybe it is normal for this kind of device.

Shenzhen Homa Wireless dimmable controller (Router)
ZigBee ZLL 0-10V LED Light dimmer
https://a.aliexpress.com/_dUMPWes

0x00124b001eb0ac0b (0x00124b001eb0ac0b): HLC610-Z - Shenzhen Homa Wireless dimmable controller (Router)

{"ieeeAddr":"0x00124b001eb0ac0b","type":"Router","networkAddress":20682,"model":"HLC610-Z","friendly_name":"0x00124b001eb0ac0b","manufacturerID":0,"manufacturerName":"ShenZhen_Homa","powerSource":"Mains (single phase)","modelID":"HOMA1002","hardwareVersion":1,"softwareBuildID":"1.0.3","dateCode":"20170724","lastSeen":1586288489268}]}'

**Comment by stas-demydiuk** [comment]
@jvrrr your device wasn't supported by the plugin, I added such support, you need to update plugin and restart Domoticz

**Comment by jvrrr** [comment]
Yessss, it works great!  Thanks a lot!
