### ISSUE TITLE
Signal devices' description can not be edited

### ISSUE THREAD

**Issue by raqua** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#289]
**Issue description**
I am trying to edit description of device of type "signal". I can edit description of the same device's other values items (Xiaomi devices, temperature/humidity, motion etc.., but also my CC2530 router), but not signal.
When I click under Utility on EDIT of some device, I can chenge the value, but then, when I click UPDATE, nothing happens. The modal form stays there and no error is logged. 

**Additional information**
Zigbee2MQTT version: 1.12.1
Python version: 3.8.2
Domoticz version: 2020.1
Plugin version: 0.1.0

**Logs**
Nothing is logged.

**Comment by stas-demydiuk** [comment]
This isn't a plugin issue but Domoticz issue itself of updating such type of devices (Custom sensors). I would suggest to report it directly on Domoticz repository
