### ISSUE TITLE
Plugin user interface

### ISSUE THREAD

**Issue by stas-demydiuk** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#290]
Follow up ticket of #282 

Proposal:
- Add custom page to Domoticz which allow to see zigbee network map

Scope
- [x] Devices management
- [x] Groups management
- [x] Zigbee network map

**Comment by stas-demydiuk** [comment]
@kovainfo @cocooma @JanJaapKo @Luigi8723
guys, I've managed how plugin can add custom page to Domoticz, which will allow us to display network map (and basically implement any other UI which will be required for plugin)

I wonder if you could test it (available in network-map git branch) and provide the feedback.

@kovainfo, special thanks for suggesting the idea how to implement communication between plugin and custom UI, it works like a charm

**Comment by kovainfo** [comment]
It's worked fine for me! )))

there is one remark:
when you open the page, the "old" network map should open.
the network map should still be updated on demand (by pressing the button).
it’s just a map building procedure that consumes a lot of resources from zigbee2mqtt.

**Comment by kovainfo** [comment]
when I rename the zigbee friendlyname of a device that has already been added to domoticz - the ID of this device in domoticz remains the same. at first glance, this does not lead to problems and everything continues to work, but I did not understand much deeper))

**Comment by kovainfo** [comment]
It remains to make the "add" button for the "pair" function! )

**Comment by stas-demydiuk** [comment]
> when I rename the zigbee friendlyname of a device that has already been added to domoticz - the ID of this device in domoticz remains the same
That's all right, plugin relies on ieee address of device rather than on friendly name

**Comment by schurgan** [comment]
Hi Stas, since I have more sensors than the plugin can work, I had to duplicate zigbee2mqtt at all levels except the plugin itself.  That, in my opinion, because of this, in the custom tab is Loading and nothing happens.  How can I solve this problem and use these new features?  thanks

**Comment by dobber81** [comment]
I've got 3 different pi's, each with it's own zigbee2mqtt stick. 1 with stretch and one with buster. All on latest domoticz beta. All I get is "Loading..." under the new network map. Do I need to install or edit something to get the map?

**Comment by stas-demydiuk** [comment]
@schurgan could you please re-check with latest update?

**Comment by schurgan** [comment]
No changes unfortunately.  I have 2 services, zigbee2mqtt and zigbee2mqtt2 and also 2 plugins and two sticks.  Maybe I didn’t explain something right?

**Comment by schurgan** [comment]
Maybe you need to install any additional packages?

**Comment by stas-demydiuk** [comment]
what version of zigbee2mqtt are you using as well as domoticz version?
are there any errors in browser console?

**Comment by schurgan** [comment]
Domoticz latest release and zigbee2mqtt 1.12.1 -It seems to not give an error

**Comment by schurgan** [comment]
Now it's working. I updated services and now it works. Thanks Stas, great
