### ISSUE TITLE
How to create adapter to support new device

### ISSUE THREAD

**Issue by macdelft** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#292]
**Device description**
Hi, i would like to add an adapter for an unsupported device. The documentation states that this is possible, however, it's not described how to do this exactly. Can you explain this? Thanks in advance!

**MQTT message with device information**

To open sunscreen:
`mosquitto_pub -t zigbee2mqtt/0xccccccfffe269b0e/set -m '{"position":100}'`

Feedback from sunscreen:
`zigbee2mqtt:debug 2020-04-15 13:46:36: Received Zigbee message from '0xccccccfffe269b0e', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":254}' from endpoint 1 with groupID 0
`
`MQTT publish: topic 'zigbee2mqtt/0xccccccfffe269b0e', payload '{"state":"OPEN","position":"100","linkquality":86}'`

**Comment by stas-demydiuk** [comment]
Hi @macdelft. It is in my todo list to create such documentation but unfortunately haven't yet.

I would recommend to start from this [file](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/master/adapters/__init__.py) which contains mapping for all supported devices. Key in this mapping is device model and value is class of corresponding adapter. To add support for new device you'll need to add additional mapping item.

There are many typical adapters for different devices in `/adapters` and `adapters/generic` folders which can be easily reused for many common devices like bulbs and different sensors

In case you will need to create custom adapter, create a new file with class extended from `Adapter` or `AdapterWithBattery` and override `__init__` method. In this method fill in `self.devices` array with required Domoticz devices for your zigbee device. Also you'll need to define `handleCommand` method in case your zigbee device can be controlled (see [on/off switch](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/master/adapters/on_off_switch_adapter.py) adapter as example.

**Comment by Krolik1988** [comment]
Hi, take a look [here](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/365). May be will help to you.

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
