### ISSUE TITLE
Battery Status isssue E1524/E1810 

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#294]
**Issue description**
Hi,

The Domoticz-zigbee2mqtt Plugin creates 7 devices for the IKEA Remote E1524/E1810:
- 5 buttons
- 1 Link Quality
- 1 Battery Voltage

When I look into the Domoticz devices list, all devices have a battery status, execpt for the Voltage device, which would be expected. Also not all battery levels are equal, which is strange because there is only one battery cell inside the remote.

![Remote E1524-E1810](https://user-images.githubusercontent.com/18295963/80021354-ac7f9200-84da-11ea-9635-1acd379d4add.JPG)

The reason I ask this for is that I have a dzVents script which notifies me in Telegram if any of all my devices with a batteryLevel function is below 20%.
And it would be quite annoying if all the E1524/E1810 remote devices would notify, while only the Battery Voltlage should notify a low battery status.

Why does all devices have a battery level function, but not the one meant for it?

**Additional information**
Zigbee2MQTT version: 1.12.2
Python version: 3.7.3
Domoticz version: 2020.1
Plugin version: 0.1.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
Plugin updates battery status of each device when particular Domoticz device receive an update from zigbee2mqtt (when you press particular button in your case), that 's why you see different values. I'd say the most actual one is signal level as plugin updates it every time on message from zigbee2mqtt.

Regarding why all devices have battery status, there is no any specific reason for that and I guess it is just the way how the plugin is initially implemented. Honestly I don't see much valuable reasons to change behavior now and as result to create breaking changes for everyone who already use the plugin.

**Comment by geeano** [comment]
Ï faced they same problem. The device does not generate a battery voltage value. Only a percentage,  but that is not converted. Therefore a requested a new device that shows a battery percentage additional to the indicator in the device list as showed above.

**Comment by Anjerlaan** [comment]
> I'm facing the same problem. The device does not generate a battery voltage value. Only a percentage, but that is not converted. Therefore a requested a new device that shows a battery percentage additional to the indicator in the device list as showed above. #273

Apparently there is no reason to change this behaviour

**Comment by geeano** [comment]
Stanlislav created an enhancement. You could try it also. See #273

**Comment by Anjerlaan** [comment]
Updated the plug-in.
2 E1524/E1810 devices are added...showing 0%

**Comment by stas-demydiuk** [comment]
Please attach your MQTT log

**Comment by Anjerlaan** [comment]
After some restarts of zigbee2mqtt and Domoticz, the battery is showing the correct percentage! But anyway here my log after last restart zigbee2mqtt and domoticz:
[log.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/4536276/log.txt)

You will notice that one of the 2 IKEA remotes with the friendly name "Remote_E1524-E1810", is not showing a battery status...this is at the moment an issue for which KoenK offered a solution, but I still have to test this: https://github.com/Koenkk/zigbee2mqtt/issues/3401

Is it normal behaviour that the full Text of the network scan is shown at the data field of the "api_transport" device in the domoticz devices tab?

**Comment by stas-demydiuk** [comment]
> Is it normal behaviour that the full Text of the network scan is shown at the data field of the "api_transport" device in the domoticz devices tab?

Yes, this device is used for communication between plugin and custom UI page
