### ISSUE TITLE
Zigbee2mqtt ui page keeps loading

### ISSUE THREAD

**Issue by Webworkx** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#295]
**Issue description**
Opening the new Zigbee2mqtt UI page, all tabs say "Loading"

When clicking Network map or Devices I see activity in the zigbee2mqtt log on my rapsberry pi.
So it is fetching info, but does not display anything.

**Additional information**
Zigbee2MQTT version: 1.12
Python version: 3.6.9
Domoticz version: 4.11214
Plugin version: Latest master

Are there more dependencies to get the ui to work.
With the latest plugin i'm not able to set permit_join to true, so i hope there is a fix?

**Comment by kovainfo** [comment]
> **Issue description**
> Opening the new Zigbee2mqtt UI page, all tabs say "Loading"
> 
> When clicking Network map or Devices I see activity in the zigbee2mqtt log on my rapsberry pi.
> So it is fetching info, but does not display anything.
> 
> **Additional information**
> Zigbee2MQTT version: 1.12
> Python version: 3.6.9
> Domoticz version: 4.11214
> Plugin version: Latest master
> 
> Are there more dependencies to get the ui to work.

It looks like zigbee2mqtt is not responding to the plugin.
zigbee2mqtt 1.12.2 and Domoticz 2020.1 11960 works fine for me.

> With the latest plugin i'm not able to set permit_join to true, so i hope there is a fix?
permit_join - in top right corner of plugin page

**Comment by Webworkx** [comment]
zigbee2mqtt is responding, because it its log i see "Starting network scan (includeRoutes 'false')" when clicking network map

On the top right corner this option is failing on the UI page. I saw the screenshot on the plugin page so new that it moved there.

Will try an update to zigbee2mqtt 1.12.2 but domoticz i can not because running old raspberry pi.

**Comment by stas-demydiuk** [comment]
Hi @Webworkx I wonder if you could share if there are any errors in browser console, but most likely your version of Domoticz just isn't supported :( as plugin heavily relies on its UI

**Comment by Webworkx** [comment]
Hello stas-demydiuk, That ofcourse could be the case, are there more people running Domoticz version: 4.11214 that could confirm that?

There are no console errors, and as stated before, clicking on network map is triggering zigbee2mqtt.

I hope you could make me a fix so i could at least set permit_join again in the hardware settings instead of only in the UI.

Will have to build a new pi image, using debian 8 jessie still, upgrading failed.

**Comment by stas-demydiuk** [comment]
I guess the most easiest for you would be to just rollback the plugin to 0.1.0 as new version brings just new UI. 

Additionally as an option could be to run Domoticz in docker container so you can update to latest version (you could use my image for that https://hub.docker.com/repository/docker/demydiuk/domoticz)

**Comment by Webworkx** [comment]
How do i rollback to 0.1.0?

i'm not very familiar with docker, i need to install docker first on the pi? And can it communicate with zigbee2mqtt on the same pi?

**Comment by stas-demydiuk** [comment]
https://git-scm.com/docs/git-checkout
You need to checkout this commit https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/commit/7f1c1801e912ef98a92818e6a3b9591df4a21802

**Comment by Webworkx** [comment]
In the meantime i'm fully uptodate
Running Debian buster on my raspberry pi
Zigbee2MQTT version: 1.13
Python version: 3.7.3
Domoticz version: 2020.2
Plugin version: Latest master

All working fine in domoticz, but still the zigbee2mqtt page is only saying loading.
No errors in console in browser.

When looking in zigbee2mqtt log i see following when clicking network map tab:
zigbee2mqtt:info  2020-05-05 14:14:54: Starting network scan (includeRoutes 'false')

Non of the tabs give data. it only says loading....

**Comment by kovainfo** [comment]
It looks like the zigbee2mqtt service is not responding

**Comment by Webworkx** [comment]
Thanks for the reply. It is working as i can see in the logs, all my zigbee devices respond and function in domoticz. 

After some testing it seems that i have a problem in Chrome. Tried it in Firefox and all seems to be working. Tried it in Edge too, but the browser keeps reloading the page, so is also not working.
Will try to find out what the problem in Chrome is.

Problem partly solved!
