### ISSUE TITLE
Device entries in Zigbee page are  filtered when Domoticz device page is filtered

### ISSUE THREAD

**Issue by MarcusKlerks** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#299]
When the Domoticz device page is filtered by using 'Search', the device entries on the Zigbee custom page are filtered accordingly.
I think this is confusing when the filter appliance is 'forgotten' by the user.

**Comment by stas-demydiuk** [comment]
Plugin just reuses existing Domoticz table so at the moment it can't be configured the way you've requested.
