### ISSUE TITLE
Aqara Square Switch version misinterpretation

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#30]
I have an Aqara Square Switch, which supports click, double_click, long_click_press and long_click_release

From Zigbee2MQTT:

Nov 01 14:33:37 housespirit npm[1946]:   zigbee2mqtt:info 2018-11-1 14:33:37 MQTT publish, topic: 'zigbee2mqtt/0x00158d0001e89451', payload: '{"battery":"100.00","voltage":3035,"linkquality":78,"click":"single"}'
Nov 01 14:33:46 housespirit npm[1946]:   zigbee2mqtt:info 2018-11-1 14:33:46 MQTT publish, topic: 'zigbee2mqtt/0x00158d0001e89451', payload: '{"battery":"100.00","voltage":3035,"linkquality":73,"click":"double"}'
Nov 01 14:33:50 housespirit npm[1946]:   zigbee2mqtt:info 2018-11-1 14:33:50 MQTT publish, topic: 'zigbee2mqtt/0x00158d0001e89451', payload: '{"battery":"100.00","voltage":3035,"linkquality":65,"action":"hold"}'
Nov 01 14:33:54 housespirit npm[1946]:   zigbee2mqtt:info 2018-11-1 14:33:54 MQTT publish, topic: 'zigbee2mqtt/0x00158d0001e89451', payload: '{"battery":"100.00","voltage":3035,"linkquality":34,"action":"release"}'

From Domoticz through the Xiaomi Gateway:
{"cmd":"read_ack","model":"remote.b1acn01","sid":"158d0001e89451","short_id":59627,"data":"{\"voltage\":3115}"}
{"cmd":"report","model":"remote.b1acn01","sid":"158d0001e89451","short_id":59627,"data":"{\"status\":\"double_click\"}"}
{"cmd":"report","model":"remote.b1acn01","sid":"158d0001e89451","short_id":59627,"data":"{\"status\":\"long_click_press\"}"}
{"cmd":"report","model":"remote.b1acn01","sid":"158d0001e89451","short_id":59627,"data":"{\"status\":\"long_click_release\"}"}
{"cmd":"report","model":"remote.b1acn01","sid":"158d0001e89451","short_id":59627,"data":"{\"status\":\"click\"}"}

And it has been recognized incorrectly through the Zigbee2MQTT Plugin, giving me Off, Click, Double Click, Triple Click and Quadruple Click options.

Please, give an attention to the fact that there are a variety of versions of Aqara Square Switch. One of them has a gyro sensor, by the way

It must be presented like that:
![aqarasquare02](https://user-images.githubusercontent.com/37578325/47858757-a5dff500-dde4-11e8-9cf7-1ace1dc0dc8f.PNG)
![aqarasquare01](https://user-images.githubusercontent.com/37578325/47858752-a11b4100-dde4-11e8-95df-d238d9eeeb6d.PNG)

But I've got this crap instead:
![aqarasquare04](https://user-images.githubusercontent.com/37578325/47858784-b4c6a780-dde4-11e8-95a6-35c5ab433beb.PNG)
![aqarasquare03](https://user-images.githubusercontent.com/37578325/47858794-b98b5b80-dde4-11e8-8850-1023f77e0100.PNG)

**Comment by stas-demydiuk** [comment]
Have you updated plugin to the latest version and if yes what level you currently have in selector switch?

**Comment by loglux** [comment]
opps...

**Comment by loglux** [comment]
it still a mess
![aqaramess](https://user-images.githubusercontent.com/37578325/47877095-f8d0a100-de12-11e8-8294-29ccc8533157.PNG)

**Comment by stas-demydiuk** [comment]
Yes, it is expected as currently it is not possible to recognize what exactly version of Switch you have (with or without gyro), that's why plugin creates all possible states for both versions

**Comment by loglux** [comment]
remote.b1acn01 without a gyro.

**Comment by stas-demydiuk** [comment]
I mean both of them have model WXKG11LM

**Comment by loglux** [comment]
it does not excuse this mess that makes the plugin useless.

**Comment by loglux** [comment]
it should be a way how to fix this issue

**Comment by stas-demydiuk** [comment]
Any ideas are welcome

**Comment by loglux** [comment]
I've just eliminated two useless strings for my switch. How to make it automatically to the button set instead of the selector?

**Comment by loglux** [comment]
I've checked /zigbee2mqtt/data/database.db file and see that the mark is present here, so it is possible to distinguish between different variations of Aqara Square mini switch.

**Comment by loglux** [comment]
To get a correct device in Domoticz, I've commented those strings:
        self.switch = SelectorSwitch(devices, 'switch', 'state')
        self.switch.add_level('Off', None)
        self.switch.add_level('Click', 'single')
        self.switch.add_level('Double Click', 'double')
 **#       self.switch.add_level('Triple Click', 'triple')**
 **#       self.switch.add_level('Quadruple Click', 'quadruple')**
        self.switch.add_level('Long Click', 'hold')
        self.switch.add_level('Long Click Release', 'release')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_MENU)

**Comment by stas-demydiuk** [comment]
It will work for your version of device and owners of another version could comment
```
# self.switch.add_level('Long Click', 'hold')
# self.switch.add_level('Long Click Release', 'release')
```

**Comment by stas-demydiuk** [comment]
They both have the same modelId in MQTT message from zigbee2mqtt, so currently I see no way

**Comment by loglux** [comment]
quite opposite, they have different modelid and Domoticz can distinct one of another in last beta only (or in one of the forks, which I use). The current Domoticz release cannot recognise the **remote.b1acn01** version because of the different modelid here.

**Comment by stas-demydiuk** [comment]
Looks like you are mixing up native Xiaomi gateway support and support with zigbee2mqtt, they are not connected to each other.

If you see how to proper recognize devices from these 2 MQTT messages
```
{"ieeeAddr":"0x00158d0001b1a9df","type":"EndDevice","model":"WXKG01LM","friendly_name":"Switch"}
```
and
```
{"ieeeAddr":"0x00158d0001e89451","type":"EndDevice","model":"WXKG01LM","friendly_name":"0x00158d0001e89451"}
``
I would appreciate your help

**Comment by loglux** [comment]
zigbee2mqtt/data/database.db
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d0001e89451","nwkAddr":57,"manufId":4151,"epList":[1],"status":"online","joinTime":1541104864,"endpoints":{"1":{"profId":260,"epId":1,"devId":259,"inClusterList":[0,3,18],"outClusterList":[0$
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d0001e89451","nwkAddr":57,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.remote.b1acn01\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"status":"online","joinTi$
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d0001e89451","nwkAddr":57,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.remote.b1acn01\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"status":"online","joinTi$

**Comment by loglux** [comment]
so the modelld is correctly accepted by zigbee2mqtt as  **"modelId":"lumi.remote.b1acn01**
but in your example we see **"model":"WXKG01LM"**, which is not modelld

**Comment by stas-demydiuk** [comment]
Publish such MQTT message to your zigbee2mqtt instance
```
zigbe2mqtt/bridge/config/devices
```

**Comment by loglux** [comment]
That is completely wrong because modelld is missing

Nov 03 15:13:39 housespirit npm[6736]:   zigbee2mqtt:info 2018-11-3 15:13:39 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"devices","message":[{"ieeeAddr":"0x00158d0001824ddf","type":"EndDevice","model":"WSDCGQ01LM","friendly_name":"0x00158d0001824ddf"},{"ieeeAddr":"0x00158d000239425d","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d000239425d"},{"ieeeAddr":"0x00158d00024e6d01","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"0x00158d00024e6d01"},{"ieeeAddr":"0x00158d00024e6792","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"0x00158d00024e6792"},{"ieeeAddr":"0x00158d0001e89451","type":"EndDevice","model":"WXKG11LM","friendly_name":"0x00158d0001e89451"}]}'

**Comment by stas-demydiuk** [comment]
If you think so better to ask zigbee2mqtt contributors about such feature as I'm not the one

**Comment by loglux** [comment]
I looked at Zigbee2MQTT logs archive today and see that zigbee2mqtt acuatlly see modelId however the parameter is seen in debug messages. 

2018-11-3 19:33:13 - debug: Saving state to file /home/domoticz/zigbee2mqtt/data/state.json
2018-11-3 19:34:05 - debug: Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"65281":{"1":3025,"3":25,"4":5032,"5":36,"6":[0,1],"10":0}}}' of device 'lumi.remote.b1acn01      ' (0x00158d0001e89451)
2018-11-3 19:34:05 - info: MQTT publish, topic: 'zigbee2mqtt/0x00158d0001e89451', payload: '{"battery":"99.00","voltage":3025,"linkquality":73}'
2018-11-3 19:34:05 - debug: Received zigbee message of type 'devChange' with data '{"cid":"genBasic","data":{"65281":[null,3025,null,25,5032,36,[0,1],null,null,null,0]}}' of device 'lumi.remote.b1acn01      ' (0x00158d0001e89451)
2018-11-3 19:38:13 - debug: Saving state to file /home/domoticz/zigbee2mqtt/data/state.json

**Comment by jjnh** [comment]
The newly arrived Aqara WXKG03LM was not working with my Domoticz/Zigbee2MQTT installation. Messages were coming in correctly, but the switch in Domoticz was not created or responding at all. I started working on the issue and in the end I changed the WXKG03LM.py file into the following:

`from adapters.adapter_with_battery import AdapterWithBattery
from devices.switch.selector_switch import SelectorSwitch


class WXKG03LM(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.switch = SelectorSwitch(devices, 'switch', 'state')
        self.switch.add_level('Off', None)
        self.switch.add_level('Single', 'single')
        self.switch.add_level('Double', 'double')
        self.switch.add_level('Hold', 'hold')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_MENU)

        self.devices.append(self.switch)

    def convert_message(self, message):
        message = super().convert_message(message)

        if 'click' in message.raw:
            message.raw['state'] = message.raw['click']
        elif 'action' in message.raw:
            message.raw['state'] = message.raw['action']

        return message
				
    def handleCommand(self, alias, device, device_data, command, level, color):
        self.switch.handle_command(device_data, command, level, color)`

Now the switch is created correctly when added to Zigbee and states are correctly interpreted. I hope this helps!

**Comment by stas-demydiuk** [comment]
@jjnh Thanks! Updated the plugin

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
