### ISSUE TITLE
Paring and allow UI options

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#303]
New UI
 GREAT work thanks!!!!

Only why i can pair and allow?

In the ui i see only a text on the allow.
I cannot see the status.. Perhaps a button green and red or something?

**Comment by stas-demydiuk** [comment]
I'm not sure I got your point. Could you please explain?

**Comment by Dylantje** [comment]
I mean this:
[url=https://ibb.co/cTjRRdt][img]https://i.ibb.co/cTjRRdt/Screen-Shot095.png[/img][/url]
why not:
[url=https://ibb.co/d4GRNRW][img]https://i.ibb.co/d4GRNRW/Screen-Shot097.png[/img][/url]
and
[url=https://ibb.co/8r1TWX5][img]https://i.ibb.co/8r1TWX5/Screen-Shot098.png[/img][/url]

And the differences between allow and pairing?
[url=https://ibb.co/vJ1vQs7][img]https://i.ibb.co/vJ1vQs7/Screen-Shot096.png[/img][/url]
They do the same i think?

**Comment by stas-demydiuk** [comment]
`Allow pairing` is showing current pairing state of zigbee stick and allows to change it.
`Pair Device` button will trigger pairing process: enable pairing on stick, show modal with log and disable pairing mode on stick once modal is closed.
