### ISSUE TITLE
Xiaomi vibration sensor, please can you add a fourth device with 'strenght value'?

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#306]
**Issue description**
Hello dear @stas-demydiuk. I hope you are okay 

The xiaomi vibration sensor adds to domoticz 3 devices:

```
4xx	zigbe2mqtt	0x00158d000xxxxx_signal	54	zigbe2mqtt - 0x00158d000xxxxx (Link Quality)	General	Custom Sensor	115

4xx	zigbe2mqtt	0x00158d000xxxxx_cell	60	zigbe2mqtt - 0x00158d000xxxxx (Battery Voltage)	General	Voltage	3.025 V

4xx	zigbe2mqtt	0x00158d000xxxxx_action	64	sensor vibra	Light/Switch	Selector Switch	Off

```
I would need a fourth device to be added in order to use the 'strength' value provided by this sensor, I have spoken with @koeenk (zigbee2mqtt developer) to add the strenght value to the information that sends the sensor to domoticz (https://github.com/Koenkk/zigbee2mqtt/issues/2258) . 
this information is already added.

I speak also with @waaren from domoticz comments that it is necessary to implement a fourth device or other options when adding the sensor to domoticz (https://www.domoticz.com/forum/viewtopic.php?f=59&t=32517)

I think you could add this fourth device. I need to use the value strenght in domoticz to be able to close my awnings depending on the vibration force of the wind, I put some links so that you can find information about the value 'Strength' me and many people from the domoticz telegram group would be eternally grateful

**Additional information**
Zigbee2MQTT version: 1.13.0-dev
Python version: Python 2.7.16 / Python 3.7.3
Domoticz version: Version: 2020.2 (build 12012)
Plugin version: 0.2.0

**Logs**
zigbee2mqtt.log
`may 04 16:18:30 raspberrypi npm[24127]: zigbee2mqtt:info  2020-05-04 16:18:30: MQTT publish: topic 'zigbee2mqtt/0x00158d0002a51c0a', payload '{"battery":100,"voltage":3025,"linkquality":113,"angle":5,"angle_x":9,"angle_y":-68,"angle_z":20,"angle_x_absolute":81,"angle_y_absolute":158,"strength":17}'`

domoticz.log
`2020-05-04 16:21:19.993 (zigbe2mqtt) MQTT message: zigbee2mqtt/0x00158d0002a51c0a {'battery': 100, 'voltage': 3025, 'linkquality': 113, 'angle': 5, 'angle_x': 9, 'angle_y': -68, 'angle_z': 20, 'angle_x_absolute': 81, 'angle_y_absolute': 158, 'strength': 17, 'action': 'vibration'}
`

**Comment by SargonofAssyria** [comment]
The same as this one: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/305
B.t.w it is a fifth device.

**Comment by kitopopo** [comment]
Dear @stas-demydiuk,

you are right, they are 4. I apologize, someone came forward to do the issue, probably someone who read my conversations today in the forum, I close the issue to leave only one issue open. Many thanks for your job and dedication. you are very kind. best regards

**Comment by kitopopo** [comment]
dear friend @stas-demydiuk,

First of all thank you very much for adding the strenght value to domoticz. I hope you are okay.
I have thought that to have better control over the awnings with the vibration sensor, it could be interesting to add the information of the angles (if possible) since they show updated update in each vibration, instead the strenght value is updated every 5 minutes. I apologize for not thinking about this when we include only the strenght value. I would be grateful. Thank you very much for your work. a cordial greeting


`"angle":5,"angle_x":25,"angle_y":-44,"angle_z":35,"angle_x_absolute":65,"angle_y_absolute":134,"strength":55}`

**Comment by kitopopo** [comment]
In case someone wants to follow this thread, a new thread was opened in the following link.

`https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/305`

Thanks again @stas-demydiuk , good job
