### ISSUE TITLE
DIYRuZ_R4_5

### ISSUE THREAD

**Issue by adventis312** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#308]
**Device description**
Put general device information here

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x00158d0001bd0e35","type":"EndDevice","model":"WXKG01LM","friendly_name":"0x00158d0001bd0e35"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
zigbee2mqtt:info 2018-10-28 13:34:09 MQTT publish, topic: 'zigbee2mqtt/WeatherGuestRoom', payload: '{"temperature":24.59,"linkquality":39,"humidity":36.56,"pressure":990,"battery":"37.00","voltage":2975}'

zigbee2mqtt:info 2018-10-28 13:34:09 MQTT publish, topic: 'zigbee2mqtt/WeatherGuestRoom', payload: '{"temperature":24.59,"linkquality":39,"humidity":37.55,"pressure":990,"battery":"37.00","voltage":2975}'

zigbee2mqtt:info 2018-10-28 13:34:09 MQTT publish, topic: 'zigbee2mqtt/WeatherGuestRoom', payload: '{"temperature":24.59,"linkquality":39,"humidity":37.55,"pressure":989,"battery":"37.00","voltage":2975}'
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload 
{"state_bottom_left":"OFF","linkquality":65,"state_bottom_right":"ON","state_top_left":"ON","state_top_right":"ON","state_center":"OFF"}

**Comment by stas-demydiuk** [comment]
Probably you've attached `MQTT message with device information` and `MQTT messages from device` with wrong device
