### ISSUE TITLE
api_transport device gets recreated every time.

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#309]
**Issue description**
There is a device 'api_transport' created over and over again.
I delete it because I do not know where it is used for.
It is a General/Text device and sometimes the content is blank and sometimes the content is the json from the 'Coordinator firmware version'
Has it any use or is it a bug?

**Additional information**
Zigbee2MQTT version:  1.13.0-dev (commit #e792f8b)
Python version: 3.7.3
Domoticz version: 4.10717
Plugin version: latest

**Comment by kovainfo** [comment]
It's not a bug, it'a a feature. This is a part of API for communicate with zigbee2mqtt service. Do not delete this sensor. This sensor will be recreated again and again as soon as a direct connection to the zigbee2mqtt service is required.

**Comment by SargonofAssyria** [comment]
I do not that is correct. It is filling my database in an uncontrolled way.
Sometimes the text in that text field is the max. of 200, so it looks that is truncated anyway.
What is the use of such a feature?

**Comment by SargonofAssyria** [comment]
Oke, now I see where it is used for.
I will use zigbee2mqqtassistant in the future and disable the 'Eigen' tab.

**Comment by kovainfo** [comment]
> I do not think that is correct. It is filling my database in an uncontrolled way.
> Sometimes the text in that text field is the max. of 200, so it looks that is truncated anyway.
> What is the use of such a feature?

Information is stored for no more than 7 days (by default). Information gets there only when working with the plug-in UI.
