### ISSUE TITLE
Feature request - Battery voltage and Signal level as new device

### ISSUE THREAD

**Issue by MiloshCZ** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#31]
Hi,
is it possible to create new devices for Signal level and battery voltage? Only for devices, that reports it, of course. It could be nice to see this things.

Thanks

**Comment by stas-demydiuk** [comment]
Also was thinking about that, probably worth to add

**Comment by stas-demydiuk** [comment]
Feature is implemented in latest master branch
