### ISSUE TITLE
Xiaomi JTYJ-GD-01LM/BW - extra features (smoke_density, self-test, sensitivity)

### ISSUE THREAD

**Issue by lesleypersyn** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#311]
There are more features for the smoke sensor available and not visible with this plugin:

**- smoke_density**
The _result received_ is:
{"battery":100,"voltage":3115,"smoke_density":2,"linkquality":94,"smoke":false}
This is a value 

**- self-test**
A self-test can be triggered with _publishing_ zigbee2mqtt/[devicename]/set {"selftest": ""}
This gives a beep in the smoke sensor

**- sensitivity**
Same as self-test can be triggered with _publishing_ zigbee2mqtt/[devicename]/set {"sensitivity": "value'}
where "value" is low, medium or high

extra info: https://www.zigbee2mqtt.io/devices/JTYJ-GD-01LM_BW.html

If you need more info, please ask.
Thanks.

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by SargonofAssyria** [comment]
I checked, it works.
