### ISSUE TITLE
ICZB-KPD14S

### ISSUE THREAD

**Issue by m-j-1984** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#312]
**Device description**
icasa CZB-KPD14S Pulse 4S Keypad

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
can't reconfigure device:  warn  2020-05-13 14:40:42: Skipping configure of '0xccccccfffe26a1cb', device does not require this.

hope this helps:
Zigbee Id is 0xccccccfffe26a1cb.
Address on Zigbee Network is 0x7C18.
Link quality is 47/255.
Battery level is 37.5%.
Model is ICZB-KPD14S by icasa.
Hardware version is 0.
Firmware version is 2.5.3_r20.
This device type is EndDevice
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example

click off

info  2020-05-13 14:21:30: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/click', payload 'off'
info  2020-05-13 14:21:30: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":57,"rate":50,"brightness":203,"click":"off","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:21:30: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":57,"rate":50,"brightness":203,"click":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

click on

info  2020-05-13 14:21:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/click', payload 'on'
info  2020-05-13 14:21:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":34,"rate":50,"brightness":203,"click":"on","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:21:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":34,"rate":50,"brightness":203,"click":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

click s1

info  2020-05-13 14:21:37: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/click', payload '1'
info  2020-05-13 14:21:37: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":34,"rate":50,"brightness":203,"click":1,"device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:21:37: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":34,"rate":50,"brightness":203,"click":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

click s2

info  2020-05-13 14:21:40: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/click', payload '2'
info  2020-05-13 14:21:40: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":21,"rate":50,"brightness":203,"click":2,"device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:21:40: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":21,"rate":50,"brightness":203,"click":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

hold off button (top left button)

info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_left'
info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":47,"rate":50,"brightness":203,"action":"rotate_left","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":47,"rate":50,"brightness":203,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_left'
info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":183,"action":"rotate_left","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:11: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":183,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_left'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":163,"action":"rotate_left","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":163,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_left'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":143,"action":"rotate_left","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":143,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_left'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":123,"action":"rotate_left","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":123,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_stop'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":49,"rate":50,"brightness":112,"action":"rotate_stop","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:12: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":49,"rate":50,"brightness":112,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

hold on button  (top right button)

info  2020-05-13 14:22:33: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_right'
info  2020-05-13 14:22:33: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":47,"rate":50,"brightness":112,"action":"rotate_right","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:33: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":47,"rate":50,"brightness":112,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_right'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":132,"action":"rotate_right","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":132,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_right'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":152,"action":"rotate_right","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":152,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_right'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":172,"action":"rotate_right","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":70,"rate":50,"brightness":172,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb/action', payload 'rotate_stop'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":42,"rate":50,"brightness":173,"action":"rotate_stop","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'
info  2020-05-13 14:22:34: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe26a1cb', payload '{"battery":37.5,"linkquality":42,"rate":50,"brightness":173,"action":"","device":{"friendlyName":"0xccccccfffe26a1cb","model":"ICZB-KPD14S","ieeeAddr":"0xccccccfffe26a1cb","networkAddress":31768,"type":"EndDevice","manufacturerID":4644,"manufacturerName":"icasa","powerSource":"Battery","applicationVersion":0,"stackVersion":0,"zclVersion":3,"hardwareVersion":0,"dateCode":"NULL","softwareBuildID":"2.5.3_r20"}}'

button s1 and s2 doesn't seem to support hold

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

unknown

**Comment by stas-demydiuk** [comment]
Support was added. Could you please update plugin and check
