### ISSUE TITLE
Gledopto GL-C-008-2ID

### ISSUE THREAD

**Issue by mozzarelka** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#313]
Device description
Zigbee LED controller RGB + CCT (2 ID),

MQTT message with device information:
ieeeAddr: 0x00124b001f79eb50,
type: Router,
networkAddress: 32840,
model: GL-C-008-2ID,
vendor: Gledopto,
description: Zigbee LED controller RGB + CCT (2 ID),
friendly_name: LED_strip,
manufacturerID: 0,
manufacturerName: GLEDOPTO,
powerSource: Mains (single phase),
modelID: GL-C-007,
hardwareVersion: 1,
softwareBuildID: 2.0.2,

[Zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/issues/3525)

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by mozzarelka** [comment]
Hi, thanks for quick action. Device appears in Domoticz but only color LEDs are manageable. White one is still "on" and this is not possible to turn off or change from cold to warm one.

**Comment by stas-demydiuk** [comment]
I've added it as just standard RGBWW controller. Should it behave somehow different?

**Comment by mozzarelka** [comment]
I can tell how it works in MQTT, there are two different sub-devices.
To manage RGB we have to send  zigbee2mqtt/[friendly_name]/**11**/set with poper payload.
For Warm/Cold White there is another topic zigbee2mqtt/[friendly_name]/**15**/set
This is the same zigbee device (one frindly name) but different sub-names (ID, endpoint).
Now this is possible to change color or brightens of RGB led's but white are still  ON.

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check now
