### ISSUE TITLE
Please add ROB_200-003-0 to Domoticz plugin for Zigbee

### ISSUE THREAD

**Issue by ChrispiB** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#315]
**Device description**
ROB_200-003-0

**MQTT message with device information**
zigbee2mqtt:info 2020-05-21 21:14:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b0018e85a32","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1590088443423},{"ieeeAddr":"0xec1bbdfffe31f648","type":"Router","networkAddress":15425,"model":"ROB_200-003-0","vendor":"ROBB","description":"Zigbee AC in wall switch","friendly_name":"0xec1bbdfffe31f648","manufacturerID":4644,"manufacturerName":"ROBB smarrt","powerSource":"Mains (single phase)","modelID":"ROB_200-003-0","hardwareVersion":0,"softwareBuildID":"2.5.3_r46","dateCode":"NULL","lastSeen":1590088375896}]}' 
zigbee2mqtt:info 2020-05-21 21:14:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"groups","message":[]}' 
zigbee2mqtt:info 2020-05-21 21:14:03: Zigbee: allowing new devices to join. 
zigbee2mqtt:info 2020-05-21 21:14:03: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.13.1","commit":"3046680","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'

**MQTT messages from device**

**MQTT state change commands**
zigbee2mqtt:info 2020-05-21 21:14:21: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe31f648', payload '{"state":"ON","linkquality":81}' 
zigbee2mqtt:info 2020-05-21 21:14:29: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe31f648', payload '{"state":"OFF","linkquality":84}'

**Comment by ChrispiB** [comment]
Thanks!! As I am really new, how do I get it to work on Domoticz?

**Comment by stas-demydiuk** [comment]
You need to update plugin and restart Domoticz
