### ISSUE TITLE
Support for innr sp120

### ISSUE THREAD

**Issue by Luigi8723** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#316]
Hi,

Could you please add the Innr sp120 to the plugin supported devices?
https://www.zigbee2mqtt.io/devices/SP_120.html
This one is already supported by zigbee2mqtt.

Thank you

**Comment by stas-demydiuk** [comment]
This one is already supported

**Comment by Luigi8723** [comment]
Ah, i cheched the supported list but didn't found it over there. Thanks
