### ISSUE TITLE
Please add iCasa ICZB-KPD18S

### ISSUE THREAD

**Issue by TheOlfer** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#318]
**Device description**
Model	ICZB-KPD18S
Vendor	iCasa
Description	Zigbee 3.0 Keypad Pulse 8S
Supports	click, action, brightness, scenes 

**MQTT message with device information**
{"ieeeAddr":"0xccccccfffe89fa99",
"type":"EndDevice",
"networkAddress":6014,
"model":"ICZB-KPD18S",
"vendor":"iCasa",
"description":"Zigbee 3.0 Keypad Pulse 8S",
"friendly_name":"Switch",
"manufacturerID":4644,
"manufacturerName":"icasa",
"powerSource":"Battery",
"modelID":"ICZB-KPD18S",
"hardwareVersion":0,
"softwareBuildID":"2.5.3_r20",
"dateCode":"NULL",
"lastSeen":1590433139448}

**MQTT messages from device**
Off:
{"linkquality":49,"battery":50,"rate":50,"brightness":245,"click":"off"} 

Longpress Off, brightness is counting down
OnPress
{"linkquality":76,"battery":50,"rate":50,"brightness":92,"action":"rotate_left"}

OnRelease
{"linkquality":76,"battery":50,"rate":50,"brightness":92,"action":"rotate_stop"}

On:
{"linkquality":60,"battery":50,"rate":50,"brightness":92,"click":"on"}

Longpress On:
On Press, brightness is counting up
{"linkquality":76,"battery":50,"rate":50,"brightness":92,"action":"rotate_right"}

OnRelease:
{"linkquality":60,"battery":50,"rate":50,"brightness":92,"action":"rotate_stop"}

S1
{"linkquality":60,"battery":50,"rate":50,"brightness":182,"click":1}

S2
{"linkquality":52,"battery":50,"rate":50,"brightness":182,"click":2} 

S3
{"linkquality":60,"battery":50,"rate":50,"brightness":182,"click":3}

S4
{"linkquality":60,"battery":50,"rate":50,"brightness":182,"click":4}

S5
{"linkquality":60,"battery":50,"rate":50,"brightness":182,"click":5}

S6
{"linkquality":57,"battery":50,"rate":50,"brightness":182,"click":6}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

Thanks in Advance!!

**Comment by maxwicky** [comment]
Yes, i also have an iCasa KPD18S.
It would be great to get it work.

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by maxwicky** [comment]
I did an update.
The log in domoticz says: this plugin does not support zigbee device with model "ICZB-KPD18S" yet

It is visible in zigbee2mqtt (under Custom tab) when i pair it in Domoticz.

**Comment by stas-demydiuk** [comment]
Probably the plugin wasn't updated for some reason, could you please check that you have the latest version from master branch

**Comment by TheOlfer** [comment]
Thanks a lot! I did an update an the device appeared in the Domoticz devices list.
One Selector Switch with 'on', 'off' and 'S1' to 'S6' levels.
One Dimmer Switch to control the Brightness.
Three General Devices for Battery and Link Quality Status and one for Voltage.
It seems that it works pretty well, but it throws a message in the logs, when I try to switch a level directly in domoticz. It Wer I'll also not switch the scene. Using the Hardware is working. This is the Mrssage:

 (Zigbee2Mqtt) Update command has not been implemented for device "iCasaSW (State)"

I assume, that is has something to do with MQTT state change commands, that I've not specified (because of lack of knowledge), possible?

**Comment by maxwicky** [comment]
> Probably the plugin wasn't updated for some reason, could you please check that you have the latest version from master branch

Yes, found it. 
New device with s1 to s6, on off etc.

Testing the next days.
Thanks a lot

**Comment by maxwicky** [comment]
The device is visible in domoticz and switches, but doesnt switch while pressing a button on the icasa device, or while select ON, S1, S2 etc on the switch in domoticz

**Comment by stas-demydiuk** [comment]
@TheOlfer could you please update once again and check.

@maxwicky what do you mean by `doesnt switch while pressing a button`, does it mean that status is not updated in Domoticz when you press button on device. @TheOlfer do you have the same issue?

**Comment by maxwicky** [comment]
Yes, when i set to ON, it doesnt switch to ON but stays OFF (see picture)
Also when pressing wallswitch ON button it stays OFF
![SmartSelect_20200603-192509_Samsung Internet](https://user-images.githubusercontent.com/66138303/83668485-51a88280-a5d0-11ea-86c6-82c5fe49868d.jpg)

**Comment by TheOlfer** [comment]
@stas-demydiuk I did and the controller itself is working flawlessly for me. I'm on latest beta at dodoticz, if this helps. 

Details:
Pressing On button - - > Dmtcz changes Selector Switch to  Level On and changes State to On
Pressing Off button - - > Dmtcz changes to Level Off and changes State to Off
Pressing Buttons S1 to S6 changesevel accordingly
Long press Off will decrease the dimmer switch value and it stops on release. 
Long press On will increase the dimmer switch value and it stops on release

Tests in Domoticz without HW
 Selector Switch state is Off, Level is Off:
Pressing Icon in UI to to turn Device On - - > nothing happens, no log entry, no UI popup
Changing Level to On - - > popup appears with info, that device will switch on. Device State will stay Off, log entry:
2020-06-03 21:22:40.647 (Zigbee2Mqtt) Update command has not been implemented for device "iCasa SW (State)"
2020-06-03 21:22:40.610 Status: User: Admin initiated a switch command (298/iCasa SW (State)/Set Level)

Almost the same if Device State is On:
Pressing Icon in UI to turn device Off--> popup appears to inform that device will switch off, device will stay On, level will not change, log entry:
2020-06-03 21:26:28.921 (Zigbee2Mqtt) Update command has not been implemented for device "iCasa SW (State)"
2020-06-03 21:26:28.902 Status: User: Admin initiated a switch command (298/iCasa SW (State)/Off)

Same for Device state is On
Changing level in UI - - > popup appears to inform that level will change. State will not change, entry in log:
2020-06-03 21:31:05.235 (Zigbee2Mqtt) Update command has not been implemented for device "iCasa SW (State)"
2020-06-03 21:31:05.219 Status: User: Admin initiated a switch command (298/iCasa SW (State)/Set Level)

**Comment by maxwicky** [comment]
It is working.
I had 2 zigbee2mqtt plugin-folders (dont know why), i updated both and now it is working.
