### ISSUE TITLE
Device support Xiaomi Mi window and door sensor 

### ISSUE THREAD

**Issue by EnterPrayz** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#319]
**Device description**
Xiaomi Mi window and door sensor

**MQTT message with device information**
```
{
    "ieeeAddr": "00158D00045F70FE",
    "flags": 0,
    "friendly_name": "Коридор",
    "type": "EndDevice",
    "PS": 0,
    "last_seen": 1590577709,
    "ManufName": "",
    "ModelId": "lumi.sensor_magnet",
    "supported": 1,
    "Interview": {
      "State": 0,
      "TS": 1590534464
    },
    "Rtg": [
      
    ],
    "st": {
      "battery": 100,
      "contact": false,
      "linkquality": 113,
      "trSeqNum": 114,
      "voltage": 3.03
    }
  }
```

**MQTT messages from device**
![image](https://user-images.githubusercontent.com/7173595/83018839-98c1d100-a02e-11ea-9951-947d5744aafe.png)

**MQTT state change commands**
![image](https://user-images.githubusercontent.com/7173595/83018905-bd1dad80-a02e-11ea-83ed-a6c6f15dc740.png)

**Comment by stas-demydiuk** [comment]
This one is already supported
