### ISSUE TITLE
Device support Xiaomi Mi Motion Sensor

### ISSUE THREAD

**Issue by EnterPrayz** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#320]
**Device description**
Xiaomi Mi Motion Sensor

**MQTT message with device information**
```
{
    "ieeeAddr": "00158D0003D14EE9",
    "flags": 0,
    "friendly_name": "Гараж",
    "type": "EndDevice",
    "PS": 0,
    "last_seen": 1590580258,
    "ManufName": "",
    "ModelId": "lumi.sensor_motion",
    "supported": 1,
    "Interview": {
      "State": 0,
      "TS": 1590508669
    },
    "Rtg": [
      
    ],
    "st": {
      "battery": 100,
      "linkquality": 81,
      "occupancy": true,
      "occupancy_timeout": 120,
      "trSeqNum": 140,
      "voltage": 3.03
    }
  }
```
**MQTT messages from device**
![image](https://user-images.githubusercontent.com/7173595/83019477-ae83c600-a02f-11ea-9b29-fb8d12b185c1.png)

**MQTT state change commands**
![image](https://user-images.githubusercontent.com/7173595/83019540-cd825800-a02f-11ea-8384-0141c780a895.png)

**Comment by stas-demydiuk** [comment]
This one is already supported
