### ISSUE TITLE
Please add support for iCasa bulb

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#324]
**Device description**
iCasa Bulb (see https://www.zigbee2mqtt.io/devices/ICZB-B1FC60_B3FC64_B2FC95_B2FC125.html)

{"id":15,"type":"Router","ieeeAddr":"0x00158d00013dcf2c","nwkAddr":10693,"manufId":4137,"manufName":"icasa","powerSource":"Mains (single phase)","modelId":"ICZB-FC","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,4,3,6,8,5,768,65535,65535,4096,4111],"outClusterList":[25,4111],"clusters":{"genBasic":{"attributes":{"modelId":"ICZB-FC","manufacturerName":"icasa","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":1,"hwVersion":21,"dateCode":"20190803","swBuildId":"2.4.2"}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":1,"hwVersion":21,"dateCode":"20190803","swBuildId":"2.4.2","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1590835092146}

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by ArJay60** [comment]
Working fine. Issue closed
