### ISSUE TITLE
Could you add support for Sunricher zg2833k8-eu05 please?

### ISSUE THREAD

**Issue by DatafoxChris** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#326]
**Device description**
Sunricher 8 button (sunricher-zg2833k8-eu05)

**MQTT message with device information**
{"ieeeAddr":"0xccccccfffe8a0e53","type":"EndDevice","networkAddress":16740,"model":"ROB_200-007-0","vendor":"ROBB","description":"Zigbee 8 button wall switch","friendly_name":"8Button - Anke","manufacturerID":4644,"manufacturerName":"Sunricher","powerSource":"Battery","modelID":"ZG2833K8_EU05","hardwareVersion":0,"softwareBuildID":"2.5.3_r20","dateCode":"NULL","lastSeen":1591376896725}]}

**MQTT messages from device**
{"linkquality":218,"action":"on_1","action_group":25601}
{"linkquality":218,"action":"on_2","action_group":25602}
{"linkquality":218,"action":"on_3","action_group":25603}
{"linkquality":218,"action":"on_4","action_group":25604}
{"linkquality":218,"action":"off_1","action_group":25601}
{"linkquality":218,"action":"off_2","action_group":25602}
{"linkquality":218,"action":"off_3","action_group":25603}
{"linkquality":218,"action":"off_4","action_group":25604}

{"linkquality":222,"action":"brightness_move_up_1","action_rate":50,"action_group":25601}
{"linkquality":222,"action":"brightness_stop_1","action_group":25601}
{"linkquality":222,"action":"brightness_move_down_1","action_rate":50,"action_group":25601}
{"linkquality":222,"action":"brightness_stop_1","action_group":25601}
{"linkquality":222,"action":"brightness_move_up_2","action_rate":50,"action_group":25602}
{"linkquality":222,"action":"brightness_stop_2","action_group":25602}
{"linkquality":222,"action":"brightness_move_down_2","action_rate":50,"action_group":25602}
{"linkquality":222,"action":"brightness_stop_2","action_group":25602}
{"linkquality":222,"action":"brightness_move_up_3","action_rate":50,"action_group":25603}
{"linkquality":222,"action":"brightness_stop_3","action_group":25603}
{"linkquality":222,"action":"brightness_move_down_3","action_rate":50,"action_group":25603}
{"linkquality":222,"action":"brightness_stop_3","action_group":25603}
{"linkquality":222,"action":"brightness_move_up_4","action_rate":50,"action_group":25604}
{"linkquality":222,"action":"brightness_stop_4","action_group":25604}
{"linkquality":222,"action":"brightness_move_down_4","action_rate":50,"action_group":25604}
{"linkquality":222,"action":"brightness_stop_4","action_group":25604}

**Comment by DatafoxChris** [comment]
I think this could be implemented as 4 switches and 4 selectors

**Comment by DatafoxChris** [comment]
Do you need anything else ?

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
