### ISSUE TITLE
Plugin is not working after some problems.

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#327]
Running on all the latstes versions Domoticz, plugin etc.
Running on a odroid N2 debian
`pi@192.168.5.70's password:
  ___      _           _     _   _   _ ____
 / _ \  __| |_ __ ___ (_) __| | | \ | |___ \
| | | |/ _` | '__/ _ \| |/ _` | |  \| | __) |
| |_| | (_| | | | (_) | | (_| | | |\  |/ __/
 \___/ \__,_|_|  \___/|_|\__,_| |_| \_|_____|

Welcome to Armbian buster with Linux 5.6.15-meson64

System load:   2.03 2.13 2.01   Up time:       35 min
Memory usage:  25 % of 3634MB   Zram usage:    1 % of 1023Mb    IP:            192.168.5.70
CPU temp:      46°C
Usage of /:    9% of 57G

Last login: Sat Jun  6 10:46:32 2020 from 192.168.5.2

pi@odroidn2:~$
`
.

.
`
pi@odroidn2:~$ cd domoticz/plugins/zigbee2mqtt
pi@odroidn2:~/domoticz/plugins/zigbee2mqtt$ git pull
Already up to date.
pi@odroidn2:~/domoticz/plugins/zigbee2mqtt$
`
.
After I suffered from a brute force, and during that immediately a domoticz update.
I have problems with the mqtt plugin.
Mqtt is running, and flows are working, only the idx that work with the plugin are not working. The web interface does not work either.
<a href="https://ibb.co/Yb4FrPs"><img src="https://i.ibb.co/Yb4FrPs/Screen-Shot300.png" alt="Screen-Shot300" border="0"></a>
Is there a way to keep my all my idx and still get the plugin working?
I don't have time to reset all idx.
Because when I do a new installation all get new idx.

Everthing i try does work?
The plugin works fine for months...

Also did install the new plugin
Some problem, and no new devices in to domoticz?

Did check the yaml file for zigbee to mqqt and that is valid.

Error in Domoticz:
`2020-06-06 12:50:25.758 Error: (DMP: Z2M2) Disconnected from MQTT Server: 127.0.0.1:1883
`

**Comment by stas-demydiuk** [comment]
Try to check that Domoticz's websocket connection works properly. I guess the issue is there.
