### ISSUE TITLE
New device support: Meazon 1Phase Electricity Meter

### ISSUE THREAD

**Issue by DatafoxChris** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#328]
**Device description**
Meazon 1Phase Electricity Meter

**MQTT message with device information**
{"ieeeAddr":"0x00124b0002cc3bab","type":"Router","networkAddress":9187,"model":"MEAZON_DINRAIL","vendor":"Meazon","description":"DinRail 1-phase meter","friendly_name":"Meazon Meter 1","manufacturerID":4406,"manufacturerName":"Meazon S.A","powerSource":"Mains (single phase)","modelID":"102.106.000540","hardwareVersion":2,"dateCode":"20141215GREECE  ","lastSeen":1591615537174}

**MQTT messages from device**
{"linefrequency":49.95,"power":0,"voltage":234.49,"current":0,"reactivepower":0.02,"measureserial":3,"linkquality":0,"state":"ON","energyconsumed":0,"energyproduced":0,"reactivesummation":0}

state --> Represents the state of an internal relay
power --> Watt
energyconsumed/energyproduced --> WattHour

State can be controlled by MQTT:
Topic: zigbee2mqtt/Meazon Meter 1/set/state
Payload: ON
Payload: OFF

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by DatafoxChris** [comment]
Running Domoticz on Windows i have downloaded your master branch and replaced the files in the plugin/zigbee2mqtt folder in domoticz installation location. 

Result:

2020-06-13 22:44:23.383 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Meazon Meter 1 {'state': 'OFF', 'linkquality': 222, 'energyconsumed': 110, 'energyproduced': 0, 'reactivesummation': 0, 'measureserial': 699, 'linefrequency': 50.04, 'power': 0.84, 'voltage': 231.29, 'current': 0, 'reactivepower': 0}
2020-06-13 22:44:23.383 (Zigbee2MQTT) This plugin does not support zigbee device with model "MEAZON_DINRAIL" yet
2020-06-13 22:44:23.383 (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by stas-demydiuk** [comment]
Probably you don't have the latest version from master branch. Please follow the steps how to update plugin

**Comment by DatafoxChris** [comment]
Removed the folder, and executed: 
git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt

Manually executed the copy-actions needed to install the plugin:

            copy2(source_path + '/zigbee2mqtt.html', templates_path)
            copy2(source_path + '/zigbee2mqtt.js', templates_path)
            copy2(source_path + '/zigbee_devices.js', dst_plugin_path)
            copy2(source_path + '/zigbee_groups.js', dst_plugin_path)
            copy2(source_path + '/libs/leaflet.js', dst_plugin_path)
            copy2(source_path + '/libs/leaflet.css', dst_plugin_path)
            copy2(source_path + '/libs/viz.js', dst_plugin_path)
            copy2(source_path + '/libs/viz.full.render.js', dst_plugin_path)

Installed windows updates, rebooted the Domoticz server.

Result:
2020-06-14 09:17:27.050 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Meazon Meter 1 {'state': 'OFF', 'linkquality': 234, 'energyconsumed': 118, 'energyproduced': 0, 'reactivesummation': 0, 'measureserial': 741, 'linefrequency': 50.04, 'power': 0.86, 'voltage': 228.54, 'current': 0, 'reactivepower': -0.02}
2020-06-14 09:17:27.050 (Zigbee2MQTT) This plugin does not support zigbee device with model "MEAZON_DINRAIL" yet
2020-06-14 09:17:27.050 (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by stas-demydiuk** [comment]
Could you please check that [this file](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/master/adapters/__init__.py) has the same content on your machine (`'MEAZON_DINRAIL': DinrailAdapter` line is present)

**Comment by DatafoxChris** [comment]
In the file '__init__.py' on my system:

Line 27:  from adapters.meazon.dinrail import DinrailAdapter

Lines 114, 115:
    # Meazon
    'MEAZON_DINRAIL': DinrailAdapter,   # Meazon DinRail 1-phase meter

**Comment by stas-demydiuk** [comment]
It is really strange to see the message that device is not supported in this case. Could you please restart Domoticz one more time

**Comment by DatafoxChris** [comment]
I have rebooted the whole server, but ok: ik will restart Domoticz again...

**Comment by DatafoxChris** [comment]
As expected the result is:

2020-06-14 19:55:24.247 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Meazon Meter 1 {'state': 'OFF', 'linkquality': 248, 'energyconsumed': 127, 'energyproduced': 0, 'reactivesummation': 0, 'measureserial': 784, 'linefrequency': 49.99, 'power': 0.84, 'voltage': 233.28, 'current': 0, 'reactivepower': 0.02}
2020-06-14 19:55:24.247 (Zigbee2MQTT) This plugin does not support zigbee device with model "MEAZON_DINRAIL" yet
2020-06-14 19:55:24.247 (Zigbee2MQTT) If you would like plugin to support this de

**Comment by DatafoxChris** [comment]
Let's try to debug: 
__init__.py is the only file that would need additional code for the Meazon support ?

Please talk me through the debugging

**Comment by DatafoxChris** [comment]
I have added a debug line to devices_manager.py but it has no effect.... does Domoticz have a cache for the python scripts ?

**Comment by DatafoxChris** [comment]
Ok, found it: I had 'Zigbee2MQTT - Copy' folder, and also 'Zigbee2MQTT' folder. Domoticz seems to have selected 'copy' folder to run the plugin from, while i didn't configure that. 

Removed 'Zigbee2MQTT' folder, updated the plugin in 'Zigbee2MQTT - Copy' folder, and now the Meazon Device is added into Domoticz!  :)

**Comment by DatafoxChris** [comment]
Nice work!  Could you also map the Line Frequency to a Domoticz device please?

**Comment by DatafoxChris** [comment]
Renamed the plugin-folder to the correct name, and restarted Domoticz. Everything is OK now. 

Any plans to add support for z2m device groups ?

**Comment by stas-demydiuk** [comment]
Plugin already supports zigbee groups. Or you mean something specific?

**Comment by DatafoxChris** [comment]
I mean that the groups are added to Domoticz for example like dimmers, but also that the plugin allows for binding of a switch to a group.

**Comment by stas-demydiuk** [comment]
Plugin can add device to zigbee group as well. It can be done via UI page, `Groups -> Members` tab

**Comment by DatafoxChris** [comment]
Yes, devices (for example lights) can be added to a group. 
But i mean: i would like to join a Switch to a group by using your plugin, i mean this:

https://www.zigbee2mqtt.io/information/binding.html
topic: zigbee2mqtt/bridge/bind/button-name
raw payload: group-name

**Comment by stas-demydiuk** [comment]
Got you, you mean device binding. You can create additional ticket for that and I'll try to add support  some point.

**Comment by DatafoxChris** [comment]
About the Meazon Meter: I connected my SolarEdge Inverter to this meter. Now i notice that the Consumed and Produced domoticz-devices show the same values:

![2020-06-16_13-16-51](https://user-images.githubusercontent.com/52993597/84768007-bf42ae80-afd3-11ea-9c54-5211ea7f200d.png)

But the z2m data shows different values:

{"state":"OFF","linkquality":46,"**energyconsumed**":14,"**energyproduced**":12,"reactivesummation":15,"measureserial":3,"linefrequency":49.99,"power":-54.15,"voltage":233.38,"current":0.8,"reactivepower":-175.07}

I think your adapter is OK:

kwh_consumed = KwhSensor(devices, 'cons', ['power', '**energyconsumed**'], ' (Consumed)')
kwh_produced = KwhSensor(devices, 'prod', ['power', '**energyproduced**'], ' (Produced)')

Do you know why the two domoticz-devices show the same values?

**Comment by DatafoxChris** [comment]
Why do i see negative values for the kWh meters? Could you please tell me how to change this to always be positive values

**Comment by stas-demydiuk** [comment]
Could you please play with Domoticz device settings (type and energy read) and check if it help

![image](https://user-images.githubusercontent.com/2734836/84792690-d8138a00-affc-11ea-8836-e0b5b2925f10.png)

**Comment by DatafoxChris** [comment]
Switched to 'From device' and also switched the type.
This seems to solve the problem :)  thanks !

**Comment by DatafoxChris** [comment]
This meter is correctly added to Domoticz now
