### ISSUE TITLE
Support for WV704R0A0902 (Schneider Electric Wiser radiator thermostat)

### ISSUE THREAD

**Issue by russdan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#329]
**Device description**
WV704R0A0902 (Schneider Electric Wiser radiator thermostat)

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`,

{'ieeeAddr': '0x14b457fffe76a91b', 'type': 'EndDevice', 'networkAddress': 3117, 'model': 'WV704R0A0902', 'vendor': 'Schneider Electric', 'description': 'Wiser radiator thermostat', 'friendly_name': 'Bedroom radiator', 'manufacturerID': 4190, 'manufacturerName': 'Schneider Electric', 'powerSource': 'Battery', 'modelID': 'iTRV', 'hardwareVersion': 0, 'softwareBuildID': 'ad3e958', 'lastSeen': 1591463622788}]}

**MQTT messages from device**
info  2020-06-06 18:11:42: MQTT publish: topic 'zigbee2mqtt/Bedroom radiator', payload '{"ADC":"1453,1454,1,197,-32768,2000,0,329,100,197,197,202","linkquality":63,"ALG":"8,1,200,197,3,5,329,3,329,51,100","local_temperature":19.9,"MOT":"Stall","boost":"None","occupied_heating_setpoint":20,"keypad_lockout":false,"battery":38,"voltage":2.5,"pi_heating_demand":49}'
info  2020-06-06 18:11:42: MQTT publish: topic 'zigbee2mqtt/Bedroom radiator', payload '{"ADC":"1453,1454,1,197,-32768,2000,0,329,100,197,197,202","linkquality":63,"ALG":"8,1,200,197,3,5,329,3,329,51,100","local_temperature":19.9,"MOT":"Stall","boost":"None","occupied_heating_setpoint":20,"keypad_lockout":false,"battery":38,"voltage":2.5,"pi_heating_demand":51}'

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here
All I see in the logs are "ADC" the messages posted above - it should support a number of commands, see here:
https://www.zigbee2mqtt.io/devices/WV704R0A0902.html#controlling

**Comment by russdan** [comment]
Hi Stanislav, I have managed to get this working locally and have created a local git branch with the changes  needed - it needed a new "adapter with battery" as the reported voltage is not /1000, and then a new adapter (I used the eurotronic thermostat as the template, although Wiser doesn't seem to support "mode") and then the changes to __init__.py.    As I can't push the changes back to git I've attached them here:
[schneider_electric_wiser.zip](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/4742457/schneider_electric_wiser.zip)

I notice in the zigbee2mqtt logs there are sometimes timeout errors such as "Publish 'set' 'occupied_heating_setpoint' to 'Bedroom radiator' failed: 'Error: Write 0x14b457fffe76a91b/1 hvacThermostat({"occupiedHeatingSetpoint":2200}, {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 9000ms)'"  but updating the setpoint does seem to work correctly.

**Comment by russdan** [comment]
Apologies, I left one line for the switch in the adapter file (trying to get the switch working I didn't then remove it) - revised version attached:
[schneider_electric_wiser.zip](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/4742618/schneider_electric_wiser.zip)

**Comment by stas-demydiuk** [comment]
Thanks! Added device to the plugin.
