### ISSUE TITLE
SZ-SRN12N Smart siren dont work

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#332]
**Device description**
Put general device information here

**MQTT message with device information**
{"ieeeAddr": "0xd0cf5efffe48f34d", "type": "Router", "networkAddress": 49074, "model": "SZ-SRN12N", "vendor": "SmartThings", "description": "Smart siren", "friendly_name": "0xd0cf5efffe48f34d", "manufacturerID": 4401, "modelID": "SZ-SRN12N", "lastSeen": 1591966971374}

{"id":2,"type":"Router","ieeeAddr":"0xd0cf5efffe48f34d","nwkAddr":49074,"manufId":4401,"modelId":"SZ-SRN12N","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClusterList":[0,3,1280,1282,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SZ-SRN12N"}}},"binds":[]}},"interviewCompleted":false,"meta":{},"lastSeen":1591966971374}

![sshot-1](https://user-images.githubusercontent.com/32480002/84509710-62d64b00-acc4-11ea-81ab-84457f18a2d3.jpg)

**Comment by stas-demydiuk** [comment]
Could you update plugin and check

**Comment by salopette** [comment]
Да, хочу полностью удалить из З2М

**Comment by salopette** [comment]
Works!
