### ISSUE TITLE
Remove device, but how?

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#333]
Hello Stas, how can I delete a device? I didn't find that anywhere in your plug-in.
Can you do such a function please?

Thank you!

**Comment by stas-demydiuk** [comment]
Do you want to remove device from Domoticz or from zigbee network?

**Comment by salopette** [comment]
Да, хочу полностью удалить из З2М.

Может можно сделать мусорное ведро рядом с карандашом, для удаления

**Comment by kovainfo** [comment]
> Да, хочу полностью удалить из З2М.
> 
> Может можно сделать мусорное ведро рядом с карандашом, для удаления
> 
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/293

**Comment by stas-demydiuk** [comment]
@salopette / @kovainfo could you please update plugin and check this new feature

**Comment by salopette** [comment]
Many thanks Stas! Works!!
