### ISSUE TITLE
Could you add support for Siterwell GS361A-H04 please?

### ISSUE THREAD

**Issue by norrem** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#334]
Device description
Radiator valve with thermostat Siterwell - GS361A-H04

MQTT message with device information
{"ieeeAddr":"0xec1bbdfffe8a6417","type":"EndDevice","networkAddress":50222,"model":"GS361A-H04","vendor":"Siterwell","description":"Radiator valve with thermostat","friendly_name":"0xec1bbdfffe8a6417","manufacturerID":0,"manufacturerName":"_TYST11_zivfvd7h","powerSource":"Battery","modelID":"ivfvd7h\u0000","hardwareVersion":1,"dateCode":"20180727","lastSeen":1592205074880}]'

MQTT messages from device
{"system_mode":"manual","linkquality":55,"current_heating_setpoint":"25.0","window_detection":"ON","valve_detection":"ON","child_lock":"UNLOCKED","local_temperature":"22.6","battery":91}
{"system_mode":"auto","linkquality":55,"current_heating_setpoint":"25.0","window_detection":"OFF","valve_detection":"OFF","child_lock":"LOCKED","local_temperature":"22.6","battery":91}
{"system_mode":"off","linkquality":55,"current_heating_setpoint":"25.0","window_detection":"OFF","valve_detection":"OFF","child_lock":"LOCKED","local_temperature":"22.6","battery":91}

The thermostat can be controlled. I did not make documentation available from the supplier. I am posting the configuration from the HA system from which it works.

lock:
  - platform: "mqtt"
    state_topic: true
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/set"
    command_topic_postfix: "child_lock"
    payload_lock: "LOCK"
    payload_unlock: "UNLOCK"
    state_locked: "LOCKED"
    state_unlocked: "UNLOCKED"
    value_template: "{{ value_json.child_lock }}"

switch:
  - platform: "mqtt"
    state_topic: true
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/set"
    command_topic_postfix: "window_detection"
    payload_off: "OFF"
    payload_on: "ON"
    state_off: "OFF"
    state_on: "ON"
    value_template: "{{ value_json.window_detection }}"
    icon: "mdi:window-open-variant"

switch:
  - platform: "mqtt"
    state_topic: true
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/set"
    command_topic_postfix: "valve_detection"
    payload_off: "OFF"
    payload_on: "ON"
    state_off: "OFF"
    state_on: "ON"
    value_template: "{{ value_json.valve_detection }}"

climate:
  - platform: "mqtt"
    availability_topic: "zigbee2mqtt/bridge/state"
    min_temp: "5"
    max_temp: "30"
    modes: 
      - "off"
      - "auto"
      - "heat"
    mode_state_topic: true
    mode_state_template: "{{ value_json.system_mode }}"
    mode_command_topic: true
    current_temperature_topic: true
    current_temperature_template: "{{ value_json.local_temperature }}"
    temperature_state_topic: true
    temperature_state_template: "{{ value_json.current_heating_setpoint }}"
    temperature_command_topic: "current_heating_setpoint"
    temp_step: 0.5
    action_topic: true
    action_template: "{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by norrem** [comment]
After the upgrade (also after removing and reinstalling the plugin)
![termostat](https://user-images.githubusercontent.com/26966792/84652869-a4f1cd80-af0c-11ea-9773-9fa61220ea27.png)

**Comment by stas-demydiuk** [comment]
Sorry was a small typo, could you please update once again

**Comment by norrem** [comment]
After update
![termostat_error](https://user-images.githubusercontent.com/26966792/84696268-890e1c00-af4c-11ea-977a-8a2b35ae6cd0.png)

**Comment by stas-demydiuk** [comment]
Ok, please try now

**Comment by norrem** [comment]
devices appeared on the list :). Child switch test showed the following logs.
![termostat_ok_dev_error_](https://user-images.githubusercontent.com/26966792/84698659-74338780-af50-11ea-9998-53203e492953.png)
 I will test all functionalities and send all logs. thank you very much
![termostat_ok](https://user-images.githubusercontent.com/26966792/84698368-fa030300-af4f-11ea-9e68-95a880671569.png)

**Comment by norrem** [comment]
Tests showed:
- the thermostatic head reacts to changes in domoticz
- the switch states do not change
![switch](https://user-images.githubusercontent.com/26966792/84737191-acb28000-afa7-11ea-8826-a867f79e9b6d.png)
- every change in the state of any switch is signaled by the same error. Log in previous post

**Comment by stas-demydiuk** [comment]
Could you please try now

**Comment by norrem** [comment]
It works!! Thank you for quick implementation.
