### ISSUE TITLE
Device binding

### ISSUE THREAD

**Issue by DatafoxChris** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#335]
Possibility to join a Switch to a Group by using Binding:

https://www.zigbee2mqtt.io/information/binding.html
topic: zigbee2mqtt/bridge/bind/button-name
raw payload: group-name

**Comment by martin-g-it** [comment]
Why not use the Zigbee2MQTT frontend for this? Works perfectly nowadays.

**Comment by stas-demydiuk** [comment]
Closing this one as this feature is already available in Zigbee2MQTT UI and there is no need for additional effort to implement the same on plugin side
