### ISSUE TITLE
TRADFRI bulb GU10 WS 400lm Not Supported

### ISSUE THREAD

**Issue by big-ted** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#336]
TRADFRI bulb GU10 WS 400lm

Looks like Zigbee2MQTT 1.14 has broken your plugin with this device

{"ieeeAddr":"0x000d6ffffe4c76a2","type":"Router","networkAddress":52214,"model":"LED1537R6/LED1739R5","vendor":"IKEA","description":"TRADFRI LED bulb GU10 400 lumen, dimmable, white spectrum","friendly_name":"IkeaKitchen4","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI bulb GU10 WS 400lm","hardwareVersion":1,"softwareBuildID":"2.0.023","dateCode":"20190407","lastSeen":1592333651020},

zigbee2mqtt/IkeaKitchen4/set

{
  "state": "ON",
  "brightness": 100,
  "color_temp": 325
}

{"state":"ON","linkquality":94,"brightness":100,"color_temp":325,"color":{"x":0.46,"y":0.411},"update_available":false}

Domoticz:

2020-06-16 19:50:33.429 (ZigBee2MQTT) This plugin does not support zigbee device with model "LED1537R6/LED1739R5" yet
2020-06-16 19:50:33.429 (ZigBee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by salopette** [comment]
same here

{"id":6,"type":"Router","ieeeAddr":"0x90fd9ffffedc81fb","nwkAddr":52017,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb GU10 WS 400lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64636],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI bulb GU10 WS 400lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20200311","swBuildId":"2.3.050"}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20200311","swBuildId":"2.3.050","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1592496562461}
{"id":7,"type":"Router","ieeeAddr":"0x000d6ffffe12d3d6","nwkAddr":36064,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb GU10 WS 400lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64636],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI bulb GU10 WS 400lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":2,"appVersion":32,"hwVersion":1,"dateCode":"20190407","swBuildId":"2.0.023"}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":32,"hwVersion":1,"dateCode":"20190407","swBuildId":"2.0.023","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1592497056883}

**Comment by stas-demydiuk** [comment]
Could you please update and check now

**Comment by salopette** [comment]
THX Stas! It Works!

**Comment by big-ted** [comment]
Perfect, that fixed the issue, the light I unpaired and repaired to see if that would help, showed up straight after Domoticz was restarted and all the others are working again
