### ISSUE TITLE
Please add support for SP 220 - Innr Smart plug (Router)

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#337]
**Device description**
SP 220 - Innr Smart plug (Router)

**MQTT message with device information**
MQTT publish: topic 'homeassistant/sensor/0x680ae2fffe724800/linkquality/config', payload '{"
icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/lampen","json_attributes_topic":"zigbee2mqtt/lampen","name":"lampen_linkquality","unique_id":"0x680ae2fffe724800_linkquality_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x680ae2fffe724800"],"name":"lampen","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart plug (S220)","manufacturer":"Innr"},"availability_topic":"zigbee2mqtt/bridge/state"}'

This device: https://www.zigbee2mqtt.io/devices/SP_220.html

If you need more info, just let me know.
I suppose it is close to or the same as SP 120

**Comment by stas-demydiuk** [comment]
Done. Could you please update plugin and check

**Comment by SargonofAssyria** [comment]
Yes, I did and it works :-) Tnx a lot.
