### ISSUE TITLE
Ikea LED1624G9 added as RGBW should be RGBWW

### ISSUE THREAD

**Issue by Tweak-NL** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#338]
Sorry i am new to this.. Today i tried to pair the TRADFRI LED bulb E14/E26/E27 600 lumen, dimmable, color, opal white

This worked, but it gets added in Domoticz as RGBW and it should be RGBWW now kelvin is not working so cant choose white/warm white.

I already updated the plugin to newest version and im using Version: 2020.1 (build 11930) (Domoticz)
![image](https://user-images.githubusercontent.com/67078330/84956529-b8ae5700-b0f9-11ea-905b-8ecb35479600.png)
![image](https://user-images.githubusercontent.com/67078330/84956591-d380cb80-b0f9-11ea-8f54-892425742a59.png)

**Comment by stas-demydiuk** [comment]
Could you please double check that this bulb supports color temperature change?

**Comment by Tweak-NL** [comment]
Oops.. my bad.. When u remove the power from the bulb and turn it back on the color is warm white.. But it seems u have to choose it from the color palette. Domoticz is now showing this after power cycle: 
![image](https://user-images.githubusercontent.com/67078330/85065658-d937e900-b1ad-11ea-8e0c-24335a9d0270.png)

**Comment by Tweak-NL** [comment]
Sorry but with the pallet im not able to get warm white..
