### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#339]
Stas, can you maybe see why battery jams are not shown?
This is the battery symbol, but zero is displayed in the Battery Voltage line.
This is the case for all devices with a battery.

![sshot-1](https://user-images.githubusercontent.com/32480002/85063853-0931bd00-b1ab-11ea-9082-55a73fd704d6.jpg)

**Comment by stas-demydiuk** [comment]
Maybe this device doesn't support battery voltage measurement and provides just percentage value
