### ISSUE TITLE
Ikea lamps are controlled, but there is no response in the group.

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#340]
Hi Stas, I have 8 Tradfri lamps in the kitchen, I have now made them into a group.
When I switch the group on or off, the 8 lamps are controlled, but there is only one message from lamp 1 Back message to domoticz.

And the group switch always stays off, whether on or off.

![sshot-1](https://user-images.githubusercontent.com/32480002/85204653-3a7acc00-b316-11ea-8622-a159104364a1.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/85204655-3b136280-b316-11ea-876b-02fa57ee6d34.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/85204656-3b136280-b316-11ea-9d12-23ff110e9539.jpg)

**Comment by stas-demydiuk** [comment]
Unfortunately, don't have any zigbee bulbs to test how groups actually work

**Comment by salopette** [comment]
how can I help? Do you need log or something else?

**Comment by salopette** [comment]
Stas Can you do something there?

# Optional: Default transition to be used when e.g. changing brightness (in seconds) (default: 0)
    transition: 2
 # Optional: Change group state when one of the devices in it changes state, see 'State changes' below (default: true)

State changes #
By default when one of the devices in a group changes its state, the group state will update to reflect the change. If any lights within the group have a state of on, the group state will stay on. Also when the state of a group is changed by a command (so not via a state change of a device in it; see previous line), all devices in the group will also change its state. This behaviour can be disabled by setting optimistic: false for the group.
