### ISSUE TITLE
Heiman gas detector

### ISSUE THREAD

**Issue by AkoTerpuh** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#343]
**Device description**
Put general device information here
HEIMAN Combustible gas sensor (gas)
**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
MQTT message: zigbee2mqtt/bridge/log {'type': 'devices', 'message': [{'ieeeAddr': '0x00124b001949bddb', 'type': 'Coordinator', 'networkAddress': 0, 'friendly_name': 'Coordinator', 'softwareBuildID': 'zStack12', 'dateCode': '20190608', 'lastSeen': 1593421609799}, {'ieeeAddr': '0x000d6f0014f7bf0f', 'type': 'Router', 'networkAddress': 18552, 'model': 'HS1CG-E', 'vendor': 'HEIMAN', 'description': 'Combustible gas sensor', 'friendly_name': '0x000d6f0014f7bf0f', 'manufacturerID': 4619, 'manufacturerName': 'HEIMAN', 'powerSource': 'Mains (single phase)', 'modelID': 'GASSensor-EM', 'hardwareVersion': 16, 'dateCode': '2018.3.26', 'lastSeen': 1593421040562}]}
```
**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
MQTT message: zigbee2mqtt/0x000d6f0014f7bf0f {'gas': True, 'tamper': False, 'battery_low': False, 'linkquality': 0}
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by AkoTerpuh** [comment]
Дуже дякую!

Thank you so much! Everything up and running flawlessly.
Good job!
:)
