### ISSUE TITLE
Door sensor konke

### ISSUE THREAD

**Issue by Hydci** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#346]
Hello,
To start thank you for your work I use the plugin from the start it's perfect :)

Here I have aqara and konke door sensor, the AQARA sensor creates a 'DOOR CONTACT' device the konke sensor creates a 'CONTACT' device I changed the sensor to 'DOOR CONTACT' but the open / close direction and reverse is it possible to correct for the konke sensors the creation of a device 'DOOR CONTACT' and have the right direction opening / closing?

Thank you

**Additional information**
Zigbee2MQTT version: last dev (git pull today 02/07/2020)
Python version: Python 3.7.3
Domoticz version: 2020.2
Plugin version: last (git pull today 02/07/2020)

**Comment by stas-demydiuk** [comment]
Aqara sensors were the first supported by the plugin and to me, quite logical was to use DoorSensor instead of Contact, but later I receive feedback that others prefer just regular contact as these sensors could be placed on windows for example. That's why all later door sensors use Contact.

You can basically achieve desired behavior by switching to `Door Lock Inverted` type

**Comment by Hydci** [comment]
Okay I can understand that some people wanted the contact mode no worries but the logic would like that when the window is closed and the sensor in contact with the magnet declares to close in domoticz outside the it declares open normally window to close in domoticz that should put close don't you think?

**Comment by stas-demydiuk** [comment]
I'm not sure I got your point, could you please attach some screens maybe

**Comment by Hydci** [comment]
Here is a picture the state in domoticz should be opened not close

[url=http://www.noelshack.com/2020-27-4-1593715631-capture.png][img]http://image.noelshack.com/minis/2020/27/4/1593715631-capture.png[/img][/url]
[url=http://www.noelshack.com/2020-27-4-1593715631-img-0180.jpg][img]http://image.noelshack.com/minis/2020/27/4/1593715631-img-0180.png[/img][/url]

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
