### ISSUE TITLE
Feature request: Dim groups 

### ISSUE THREAD

**Issue by varazir** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#348]
Groups are only on or off in the plugin is there a way to be able to dim devices in a group ?

**Comment by stas-demydiuk** [comment]
Yes, you need to create dimmer group, see https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin#zigbee-groups-support

**Comment by varazir** [comment]
You can't edit the name of the group in the gui ?

**Comment by stas-demydiuk** [comment]
No, it isn't possible to rename the group, you need to create new one

**Comment by varazir** [comment]
ok thanks
