### ISSUE TITLE
Error: (Zigbee2MQTT) failed to load 'plugin.py',

### ISSUE THREAD

**Issue by powergrim** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#35]
**Device description**
Raspberry Pi with Domoticz 4.10200

**MQTT message with device information**
Nov 14 21:00:47 DOMOTICZ npm[756]:   zigbee2mqtt:warn 11/14/2018, 9:00:47 PM `permit_join` set to  `true` in configuration.yaml.
Nov 14 21:00:47 DOMOTICZ npm[756]:   zigbee2mqtt:warn 11/14/2018, 9:00:47 PM Allowing new devices to join.
Nov 14 21:00:47 DOMOTICZ npm[756]:   zigbee2mqtt:warn 11/14/2018, 9:00:47 PM Set `permit_join` to `false` once you joined all devices.
Nov 14 21:00:47 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:47 PM Zigbee: allowing new devices to join.
Nov 14 21:00:47 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:47 PM Connecting to MQTT server at mqtt://localhost
Nov 14 21:00:48 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:48 PM zigbee-shepherd ready
Nov 14 21:00:48 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:48 PM Connected to MQTT server
Nov 14 21:00:48 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:48 PM MQTT publish, topic: 'zigbee2m

**MQTT messages from device**
Nov 14 21:00:48 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:00:48 PM MQTT publish, topic: 'zigbee2mqtt/PIR-01', payload: '{"illuminance":0,"linkquality":152,"occupancy":false,"battery":"100.00","voltage":3175}'
Nov 14 21:51:16 DOMOTICZ npm[756]:   zigbee2mqtt:info 11/14/2018, 9:51:16 PM MQTT publish, topic: 'zigbee2mqtt/PIR-01', payload: '{"illuminance":0,"linkquality":152,"occupancy":false,"battery":"100.00","voltage":3175}'

**Domoticz Errors**
2018-11-14 22:06:24.594 Error: (Zigbee2MQTT) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/zigbee2mqtt/:/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload'.
2018-11-14 22:06:24.594 Error: (Zigbee) Module Import failed, exception: 'SyntaxError'
2018-11-14 22:06:24.594 Error: (Zigbee) Import detail: File: /home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/color_temp_dimmer_switch.py, Line: 48, offset: 14
2018-11-14 22:06:24.594 Error: (Zigbee) Error Line ' **args,
2018-11-14 22:06:24.594 '
2018-11-14 22:07:32.293 Error: Zigbee hardware (16) thread seems to have ended unexpectedly

-----------------------------------------------
For some reason my Domoticz installation doens't want to run the plugin. I`ve installed a new Pythonlib 4.3 and everythings else seems to be working fine. I`ve deleted the plugin and reinstalled it to no avail.

**Comment by stas-demydiuk** [comment]
What Python version do you have on your Raspberry?

**Comment by powergrim** [comment]
Python2 2.7.9 and Python3 3.4.2 where as Python 2 is set as default.

**Comment by MarcE85** [comment]
> Python2 2.7.9 and Python3 3.4.2 where as Python 2 is set as default.

Hey, i've got the same error. This is a Problem with python version < 3.4.2. After an update to version 3.6.3 it works.

**Comment by stas-demydiuk** [comment]
Yes, looks like `**dict` syntax was added only in Python 3.5. Will take a look if we can avoid its usage to have wider python versions support

**Comment by powergrim** [comment]
I`ve brought my Python version back to 3.4.2 after some hassle and it's working fine now after a git pull in the plugin folder!

Thanks a lot for your effort and quick action!!
