### ISSUE TITLE
Add Philips Hue white ambiance suspension Amaze

### ISSUE THREAD

**Issue by Hydci** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#351]
Hello,
I open this ticket to request support for this device, I look at the list it is not yet in there thank you
https://www.zigbee2mqtt.io/devices/4023330P7.html

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by Hydci** [comment]
Hello @stas-demydiuk 
Thank you for the speed of the support I am traveling this weekend I confirm you the good work Monday of the device

**Comment by Hydci** [comment]
Hello @stas-demydiuk 
I just tried it everything works perfectly I close the ticket
