### ISSUE TITLE
(Q) what is the set-state button for?

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#353]
Hello Stas, what is the set-state button for?
What can you enter there? And if so how do you do that, do you have an example?

![sshot-2](https://user-images.githubusercontent.com/32480002/86509672-e8dc4200-bde9-11ea-84ff-fd916c085a91.jpg)

**Comment by stas-demydiuk** [comment]
It allows you to manually control your Zigbee devices via MQTT. For example, to switch device on you can send such payload:
```
{"state": "ON"}
```
Supported commands are depended on the device
See https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttfriendly_nameset for more info
