### ISSUE TITLE
Hue Motion Sensor illuminance_lux

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#358]
Hello Stas, the Hue Motion Sensor is missing a value (illuminance_lux) in domoticz, please add it.

![sshot-2](https://user-images.githubusercontent.com/32480002/87081852-4fb68c80-c22a-11ea-8231-a64dd098c604.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/87081859-51805000-c22a-11ea-92aa-90dd446db595.jpg)

{"id":4,"type":"EndDevice","ieeeAddr":"0x00178801086412ee","nwkAddr":40757,"manufId":4107,"manufName":"Philips","powerSource":"Battery","modelId":"SML001","epList":[1,2],"endpoints":{"1":{"profId":49246,"epId":1,"devId":2128,"inClusterList":[0],"outClusterList":[0,3,4,6,8,768,5],"clusters":{"genBasic":{"attributes":{"modelId":"SML001","manufacturerName":"Philips","powerSource":3,"zclVersion":1,"appVersion":2,"hwVersion":1,"dateCode":"20160630","swBuildId":"6.1.0.18912"}}},"binds":[]},"2":{"profId":260,"epId":2,"devId":263,"inClusterList":[0,1,3,1030,1024,1026],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"stackVersion":1}},"msOccupancySensing":{"attributes":{"occupancy":0}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"msTemperatureMeasurement":{"attributes":{"measuredValue":1982}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":0}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff040801","endpointID":1},{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00212effff040801","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00212effff040801","endpointID":1},{"cluster":1030,"type":"endpoint","deviceIeeeAddress":"0x00212effff040801","endpointID":1}]}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20160630","swBuildId":"6.1.0.18912","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1594297788254}

**Comment by salopette** [comment]
Стас, не мог бы пожалуйста поправить?

**Comment by stas-demydiuk** [comment]
Done
