### ISSUE TITLE
Add tuya thermostatic

### ISSUE THREAD

**Issue by Hydci** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#361]
Hello @stas-demydiuk 
To request support for this thermostatic head which has just been added to the dev branch not very long ago

Aliexpress:
https://fr.aliexpress.com/item/4001043738901.html?spm=a2g0s.9042311.0.0.f41b6c37Mr9B4F

koenk Koenkk
https://github.com/Koenkk/zigbee-herdsman-converters/commit/4f96c1e8792c0565105b2819d69f3ab3990efba1

Koenkk ticket
https://github.com/Koenkk/zigbee2mqtt/issues/3821

Thanks in advance for adding

**Comment by JediMax27** [comment]
+1

**Comment by stas-demydiuk** [comment]
Closing in favor of #383
