### ISSUE TITLE
SWO-MOS1PA Swann Motion and temperature sensor (occupancy)

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#366]
**Device description**
SWANN Motion Detector

```
zigbee2mqtt:debug 2020-07-20 19:29:54: Received Zigbee message from 'SwannONe Motion Sensor', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"zonestatus":49,"extendedstatus":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-07-20 19:29:54: MQTT publish: topic 'zigbee2mqtt/SwannONe Motion Sensor', payload '{"occupancy":true,"tamper":false,"battery_low":false,"linkquality":70}'

'0x00124b00063b5aa2':
    friendly_name: SwannONe Motion Sensor

```

**Comment by loglux** [comment]
Please add Support for this device.

**Comment by Krolik1988** [comment]
Hi, for temporary you can try [my](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/365) solution as example. Just find in sensors, sensor with options like your, make new folder, copy there sensors py and init, and add it to other init.. Just check my link. Hope will help.

**Comment by Krolik1988** [comment]
Just try to 
Stop domoticz,

ADD lines to 
>/adapters/__init__.py
```
#Swann 
'MOS1PA'  MotionAndTemperatureSensorAdapter,    # SWO-MOS1PA Swann Motion and temperature sensor
```
Then start dz, allow to join new devices, and triger this sensor. May be it will work, if not, then will go next. ))

**Comment by stas-demydiuk** [comment]
Support was added, could you please update plugin and check

**Comment by loglux** [comment]
Thank you very much. It's working good
It's the best zigbee motion sensor I've ever had
