### ISSUE TITLE
Aqara motion sensor is recognized as a On/Off device

### ISSUE THREAD

**Issue by bricololo44** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#370]
**Issue description**
My aqara motion-luminance device (RTCGQ11LM) is recognized as a On/Off and not as Motion sensor.
Is there a solution ?
Thanks

**Additional information**
Zigbee2MQTT version:
Python version: Python 3.7.3
Domoticz version: Domoticz V2020.2
Plugin version: v.1.14.0 (zStack12 20190608)

**Comment by stas-demydiuk** [comment]
Could you please check Domoticz devices once again, most likely you've mixed up it with some other device as the plugin uses MotionSensor for this device

**Comment by bricololo44** [comment]
I found, I have a lua script which writes the date of the last update in the observation box of the device, and at the same time it modified the type of the device.
Thank you
