### ISSUE TITLE
New Device Support for CR Smart Gas Sensor

### ISSUE THREAD

**Issue by lily148** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#371]
**Device description**
It is a GAS sensor where return true/false and also temper status 

**MQTT message with device information**
```
zigbee2mqtt/0xec1bbdfffec3e8a0 {'tamper': False, 'battery_low': False, 'linkquality': 105, 'gas': False}
```

It is not a battery power device. You can't control the status from app or Domoticz, just receive notification from device like most sensor do...

**Comment by jasonlim97** [comment]
Added the Gas sensor and created pull request.
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/pull/372

**Comment by stas-demydiuk** [comment]
Support was added in the master branch
