### ISSUE TITLE
Request for adding new device: Blitzwolf TuYa 10A UK smart plug (TS0121)

### ISSUE THREAD

**Issue by salmr** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#374]
**Device description**
Blitzwolf TuYa 10A UK smart plug (TS0121)

**MQTT message with device information**
zigbee2mqtt:info  2020-07-27 22:14:28: Starting interview of '0x842e14fffef5a2f8'

zigbee2mqtt:info  2020-07-27 22:14:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x842e14fffef5a2f8"}}'

zigbee2mqtt:info  2020-07-27 22:14:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x842e14fffef5a2f8"}}'

zigbee2mqtt:info  2020-07-27 22:14:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x842e14fffef5a2f8"}}'

zigbee2mqtt:info  2020-07-27 22:14:30: Successfully interviewed '0x842e14fffef5a2f8', device has successfully been paired

zigbee2mqtt:info  2020-07-27 22:14:30: Device '0x842e14fffef5a2f8' is supported, identified as: TuYa 10A UK smart plug (TS0121)

zigbee2mqtt:info  2020-07-27 22:14:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x842e14fffef5a2f8","model":"TS0121","vendor":"TuYa","description":"10A UK smart plug","supported":true}}'

**MQTT messages from device**

zigbee2mqtt:info  2020-07-27 22:14:31: MQTT publish: topic 'zigbee2mqtt/0x842e14fffef5a2f8', payload '{"state":"OFF","linkquality":73}'

zigbee2mqtt:info  2020-07-27 22:14:35: MQTT publish: topic 'zigbee2mqtt/0x842e14fffef5a2f8', payload '{"state":"ON","linkquality":73}'

{"ieeeAddr":"0x842e14fffedb8974","type":"Router","networkAddress":52881,"model":"TS0121","vendor":"TuYa","description":"10A UK smart plug","friendly_name":"0x842e14fffedb8974","manufacturerID":4098,"manufacturerName":"_TZ3000_3ooaz3ng","powerSource":"Mains (single phase)","modelID":"TS0121","hardwareVersion":1,"dateCode":"","lastSeen":1595867684429}

**MQTT state change commands**
zigbee2mqtt:info  2020-07-27 22:18:15: MQTT publish: topic 'zigbee2mqtt/0x842e14fffef5a2f8', payload '{"state":"ON","linkquality":28}'

zigbee2mqtt:info  2020-07-27 22:18:17: MQTT publish: topic 'zigbee2mqtt/0x842e14fffef5a2f8', payload '{"state":"OFF","linkquality":26}'

**Comment by stas-demydiuk** [comment]
Device with modelID TS0121 already supported
