### ISSUE TITLE
Adding GLEDOpto GL-C-007 results in "doesn't have "model" attribute, skipped "

### ISSUE THREAD

**Issue by CyberClwn** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#375]
**Issue description**
When i add a GL-C-007 within zigbee2mqtt, the device shows up in the devicelist in Domoticz as a "GL-C-007-1ID". Which seems correct to me. But there are no switches created or shown if the device is selected in the mqtt device list. If i select another device i see the items list <id>_signal and <id>_light. But not with the GL-C-007.   all i get in the log is "Device < id >  ( < friendly name > ) doesn't have "model" attribute, skipped". Or am i doing something wrong ? 

Sorry if this was addressed before, but couldn't find anything about this.

**Additional information**
Zigbee2MQTT version: 1.14.2
Python version:
Domoticz version: 4.11807
Plugin version: 0.2.0

**Logs**
2020-07-28 21:09:57.010 (ZigBee) Received available devices list from bridge
2020-07-28 21:09:57.013 (ZigBee) Device < id > ( < friendly name > ) doesn't have "model" attribute, skipped

**Comment by stas-demydiuk** [comment]
@CyberClwn, do you still have the issue?

**Comment by CyberClwn** [comment]
@stas-demydiuk , yes i have.

tried many remove/rejoins .. but still not working like i expect.

**Comment by CyberClwn** [comment]
No one have an idea?  :(

**Comment by CyberClwn** [comment]
@stas-demydiuk 

After last update of zigbee2mqtt and the plugin, i now get this message :
"2020-08-18 16:24:25.424 (ZigBee) This plugin does not support zigbee device with model "GL-C-007-1ID" yet"

But it was in the supported devices-list.
Do you still prefer me to add a new issue with the template, that's also in the log now ?

**Comment by stas-demydiuk** [comment]
Added support of this new device to the plugin. Could you please update and check

**Comment by CyberClwn** [comment]
Hi, 

Yes, it is now working. Great, thanks.

Just 1 detail, i'm not sure if it is intended or not.
But the Device is marked as RGBWW, but it is RGBW.

The colors work correctly.
When warmwhite is selected, it uses the white led (with little % on RGB's)
But when coldwhite is selected it uses the RGB's to make white (with little % on the white led.)

Is that how it is intended ?
It is working for me, so no problem there. But was just wondering if it is by design :)

Thanks for the time/help/fix.

**Comment by stas-demydiuk** [comment]
I'm not sure is it inteded or not as zigbee2mqtt uses pretty standard way to communicate with device. Most likely this behavior is by design from the manufacturer.
