### ISSUE TITLE
Mqtt in domoticz/in change nvalue don't command zigbee2mqtt

### ISSUE THREAD

**Issue by fennec622** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#379]
**Issue description**
i have QBKG25LM with 3 switch ON/OFF
for one but it's the same for all
IDX 2345

I want to change to ON idx 2345 

So i publish not me but tasmota with idx 2345

domoticz/in
{"idx":2345,"nvalue":1,"svalue":"","Battery":100,"RSSI":10}

Status on domoticz change to ON but no command in zigbee2mqtt

If i click on switch idx  2345 on domoticz interface command zigbee2mqtt start and light ON

**Additional information**
Zigbee2MQTT version:
v.1.14.2 (zStack12 20190608)
Python version:
3.7.3
Domoticz version:
2020.2
Plugin version:
0.2.0
**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
I guess better to post the issue on Domoticz itself as plugin just utilizes their API
