### ISSUE TITLE
Looking for the proper way to ignore unnecessary PIR switches 

### ISSUE THREAD

**Issue by d-EScape** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#38]
I have several RTCGQ11LM "Xiaomi Human Body Sensor" PIR's. They frequently send updates on the occupancy state which result in unnecessary On/Off events in Domoticz. Looking at the source code of your plugin I could not find a proper way to ignore the on/off events if Domoticz already has the correct state.

Could this be accomplished on a per-devicetype basis with the adapter files? There are other devices that do benefit from resending the same state (like buttons / remote controls), so I didn't want to change this behavior globally (like in plugin.py itself).
Besides, I still would want the plugin to update the battery and link status, just filter out the occupancy state when it is repeated.

**Comment by stas-demydiuk** [comment]
I think currently we can safety ignore such updates since we have own domoticz devices to represent battery and signal level
