### ISSUE TITLE
Update doesnot work

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#380]
Hi...
i use the plugin for a long time without update.
I try to do this like the wiki says.
Only get still an error:
`fatal: not a git repository (or any of the parent directories): .git
` 
My pad i use:
/home/pi/domoticz/plugins/domoticz-zigbee2mqtt-plugin-master
I changed the update pad..
Only still get this error?

When is install the new plugin , do i get new devices?
Of is the idx still the same.?

**Comment by stas-demydiuk** [comment]
Yes, all idx will be the same after update. 
You error means that plugin wasn't installed using `git`, probably you just downloaded the sources. Try to remove it from disk and install again into the **same** folder
