### ISSUE TITLE
This plugin does not support zigbee device with model "RHK08" yet

### ISSUE THREAD

**Issue by jvrietveld** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#385]
I have a SONOFF SNZB-02 - ZigBee Temperature and Humidity Sensor that I purchased from ITEAD directly, but it show as model RHK08 manufactured by eWeLink under devices. 

**MQTT message with device information**
{"version":"1.12.2","commit":"911cd58","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20180507}},"log_level":"info","permit_join":false}

**MQTT messages from device**
{"temperature":34.79,"linkquality":123,"humidity":34.3,"battery":80,"voltage":2900}

Domoticz log:
![rhk08](https://user-images.githubusercontent.com/10206644/90276511-52795280-de64-11ea-860b-031849314cd4.png)

2020-08-14 19:25:34.553 (Zigbee2MQTT) This plugin does not support zigbee device with model "RHK08" yet
2020-08-14 19:25:34.553 (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: 
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

Is this a know issue ?

**Comment by stas-demydiuk** [comment]
Device was added, could you please update plugin and check

**Comment by jvrietveld** [comment]
Thanks for the quick update although I was expecting to see the Sonoff SNZB-02 and not an ewelink device.
Is this an ewelink in a Sonoff case?

pi@domoticz:~/domoticz/plugins/zigbee2mqtt $ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
   b8edcb0..c9f3c06  master     -> origin/master
Updating b8edcb0..c9f3c06
Fast-forward
 CHANGELOG.md                 |  3 +++
 SUPPORTED_DEVICES.md         |  6 ++++++
 adapters/__init__.py         |  4 ++--
 adapters/ewelink/__init__.py | 11 +++++++++++
 4 files changed, 22 insertions(+), 2 deletions(-)
 create mode 100644 adapters/ewelink/__init__.py
![WIN_20200814_20_53_35_Pro](https://user-images.githubusercontent.com/10206644/90283375-69be3d00-de70-11ea-8cdc-884fe3486aa8.jpg)

**Comment by stas-demydiuk** [comment]
I guess they are the same
https://www.zigbee2mqtt.io/information/supported_devices.html#ewelink

**Comment by jvrietveld** [comment]
Hi,

Can you do something about the warning message in the logfile? The  Zigbee2MQTT plugin reports this still as not supported.
2020-08-15 16:22:14.290 (Zigbee2MQTT) This plugin does not support zigbee device with model "RHK08" yet
2020-08-15 16:22:14.290 (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by stas-demydiuk** [comment]
You need to update the plugin to get rid of the warning

**Comment by jvrietveld** [comment]
Thanks again for the quick support but I get keeping 'Already up to date.' after the git pull command.

**Comment by stas-demydiuk** [comment]
Hmm, very strange. Have you restarted Domoticz after the update

**Comment by jvrietveld** [comment]
Yes! The restart was the fix and not only that. I have a list of devices now as well. Great job.
![zigbee2](https://user-images.githubusercontent.com/10206644/90330218-6380ab80-dfab-11ea-8792-0aae26cdd166.png)
