### ISSUE TITLE
Add support for Neo NAS-AB02B0

### ISSUE THREAD

**Issue by jvrrr** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#389]
Can someone add support for  the Neo NAS-AB02B0

It is already supported in zigbee2mqtt:
https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html

Great thanks!!!

**Comment by jvrrr** [comment]
aug 18 11:32:15 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:15: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":111,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:38 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"Alarm"}}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":81,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":81,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.2","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high","duration":10}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":81,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":81,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":54,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":70,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'
aug 18 11:32:41 zigbee npm[1553]: Zigbee2MQTT:info  2020-08-18 11:32:41: MQTT publish: topic 'zigbee2mqtt/Alarm', payload '{"alarm":false,"linkquality":84,"humidity_alarm":true,"melody":5,"temperature_min":18,"humidity_max":80,"temperature":"25.7","humidity":70,"temperature_max":27,"temperature_alarm":true,"humidity_min":45,"volume":"high"}'

**Comment by stas-demydiuk** [comment]
What functionality do you expect from this device?

**Comment by jvrrr** [comment]
I hope it would do my dishes, was my car...but if it is not possible ;-) ....

I like to use it as a door bell and fire alarm.
So it would be nice ..
- if my smoke detector  detects smoke I can set a "Melody" and "Volume".
- If someone is pushing the door bell knob, it  set a "Melody" and  "Volume".

It also would be great if humidity and temp ready work.

for me personally I would not use the humidity_alarm, temperature_alarm...If I need it, I can creat this function in domoticz.

Thanks!!!!!

**Comment by jvrrr** [comment]
Do expect something ...do I have to deliver some information?

Thanks again!

**Comment by stas-demydiuk** [comment]
Added support for temperature and humidity sensors and alarm and volume control. Could you please check.
What are the valid values for melody param?

**Comment by jvrrr** [comment]
Wow great!!!
I will test it this week

**Comment by jvrrr** [comment]
I found here that the melody can be set from 1-18 : 
https://github.com/Koenkk/zigbee2mqtt/issues/3749
(last post)

**Comment by jvrrr** [comment]
I tried it out, it is allmost perfect!

There are 2 issues.
1. When I push the on or off button it takes 4-5 sec till it activate/disable the device. (It   takes 4-5 sec. before I also see the message in zigbee2mqtt)
2. Missing the melody select box ;-) 

Thanks, what a great job!!!

**Comment by jvrrr** [comment]
> Added support for temperature and humidity sensors and alarm and volume control. Could you please check.
> What are the valid values for melody param?

Hi  stas-demydiuk,
Do you need some more info from me?

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check for melody support

**Comment by jvrrr** [comment]
> Could you please update plugin and check for melody support

I have tried it out, it works great!
The only thing is that every command I send from Domoticz it takes 2 seconds.
So if I activate this alarm in Domoticz, it take 2 seconds for it is recieved in Zigbee2mqtt. Is there a fix for?

Thanks for the great work!

**Comment by jvrrr** [comment]
Just do some Blockly testingen ...there are some issues.

- To select melody, I need to use %level. =0 melody 1, 10=melody 2, 20= etc..
I'm to able to select higer then level=100%...so I cant select melody 12 and higher.

- Mostly it thakes more then 2 seconds till the alarm and/or Melody sets in.
And many times is doesn't sound add all.

![image](https://user-images.githubusercontent.com/63355527/94614512-91ddf000-02a6-11eb-8431-35c5947056b6.png)


sorry !!!

Thnaks a lot!

**Comment by stas-demydiuk** [comment]
Unfortunately, it isn't connected to the plugin, it probably relates to the device or to Zigbee network connectivity

**Comment by jvrrr** [comment]
"To select melody, I need to use %level. =0 melody 1, 10=melody 2, 20= etc..
I'm to able to select higer then level=100%...so I cant select melody 12 and higher."

Can you make the staps  1-18 and no 0-10-20-30?
That will fix the first issue.
![image](https://user-images.githubusercontent.com/63355527/94856258-01331b80-0430-11eb-9331-0cc6c078c642.png)


The second issue I will post on zigbee2mqtt.

Thanks again!!

**Comment by dobber81** [comment]
I'm missing a "duration" setting. When siren is triggered it seems to default to about 10-12 seconds and then turn it self off. I would like a way to set it to more.

**Comment by SargonofAssyria** [comment]
I am using:
zigbee2mqtt version 1.16.2-dev commit: fb4b014
coordinator type zStack3x0
coordinator revision 20201113
frontend version 0.2.108
And the latest version of the plugin, but the 'Alarm' device does not function, it is created as an On/Of switch but Zigbee expects boolean.
![2020-12-21_14-17-13](https://user-images.githubusercontent.com/24824113/102781022-431c8f80-4397-11eb-8dd8-0dae830d06ab.png)

**Comment by stas-demydiuk** [comment]
Do you see any errors in Domoticz Log?

**Comment by SargonofAssyria** [comment]
No, not on this devices. My only errors are:
`2020-12-30 18:42:05.416 Error: (Zigbee) UPS: can not process numeric item "energy"
2020-12-30 18:42:05.416 Error: (Zigbee) UPS: can not process binary item "power_outage_memory"
2020-12-30 18:42:05.419 Error: (Zigbee) Hobbykamer: can not process binary item "battery_low"`
The 'UPS' device is a ZNCZ02LM and the Hobbykamer is a SEA801-Zigbee/SEA802-Zigbee

**Comment by stas-demydiuk** [comment]
`battery_low` support will be added in the scope of another issue, closing this one
