### ISSUE TITLE
Plug mapping shows errors

### ISSUE THREAD

**Issue by bricololo44** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#390]
![Erreur plug](https://user-images.githubusercontent.com/67336278/90505492-01fb4100-e153-11ea-9139-34c3f18863f1.jpg)
Issue description
I start the installation of plug to extend my network.
I have a plug that works fine but the mapping shows errors 
     failed lqi,routingTable
There is a green arrow whose meaning I do not know.
There are also no arrows of the 2 devices which should be associated.

Additional information
Zigbee2MQTT version:
Python version: Python 3.7.3
Domoticz version: Domoticz V2020.2
Plugin version: v.1.14.0 (zStack12 20190608)

**Comment by stas-demydiuk** [comment]
Please raise this issue on zigbee2mqtt, as it doesn't relate to the Domoticz plugin
