### ISSUE TITLE
Ikea light bulb in combination with remote control

### ISSUE THREAD

**Issue by Peertje87** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#393]
**Issue description**

When I add a Ikea lightbulb to domoticz, it works fine. When I add a remote to the lightbulb, the connection with domoticz is lost and Domoticz logs an error: 

Error: (zigbee2mqtt) A Zigbee publish error occured for device '0x690ae2fffeaeafde' with error message: Publish 'set' 'state' to '0x690ae2fffeaeafde' failed: 'Error: Command 0x690ae2fffeaeafde/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Data request failed with error: 'MAC no ack' (233))

**Steps to reproduce:** 

Turn on IKEA Light bulb
Turn on switch "Allow new zigbee devices to join"
Turn on switch "Accept new hardware/sensors for 5 minutes"
Turn IKEA light bulb 6 times on and off and wait for a couple of minutes
Add the founded IKEA switch
Turn switch on in domoticz (result: it works). 
Hold IKEA remote within 5cm of IKEA light bulb. 
Push and hold pairing button for 10 seconds

**Result:**

Light bulb can only be managed via remote control

**Expected result:**

Remote control and Domoticz switch should work both. 

**Additional information**
Zigbee2MQTT version: 
Python version:
Domoticz version: 2020.2
Plugin version: v.1.14.1 (zStack12 20190608)

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

Error: (zigbee2mqtt) A Zigbee publish error occured for device '0x690ae2fffeaeafde' with error message: Publish 'set' 'state' to '0x690ae2fffeaeafde' failed: 'Error: Command 0x690ae2fffeaeafde/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Data request failed with error: 'MAC no ack' (233))

**Comment by jpveen** [comment]
Sounds like normal behaviour to me, the Ikea cannot be paired to the ikea-remote and the zigbee2mqtt controller at the same time. Maybe Ikea can solve this ;-)

**Comment by Peertje87** [comment]
@ikea
That would be nice :)

@jpveen
Thank you for your quick reply.
