### ISSUE TITLE
Feibit SCA01ZB Support

### ISSUE THREAD

**Issue by rolfie23** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#395]
Bought the Feibit SCA01ZB because it was listed at the Zigbee2MQTT page, forgot about the plugin for Domoticz but it isn't working for the plugin.

HEIMAN Carbon monoxide sensor is exactly the same, and already supported. Is it possible to add in the Domoticz Plugin?

Dont know how to get the Zigbee messages, your readme in that is very poor. The only thing i can find is the following:
`{"ieeeAddr":"0x00158d0001ff5a7b","type":"EndDevice","networkAddress":58943,"model":"SCA01ZB","vendor":"Feibit","description":"Smart carbon monoxide sensor","friendly_name":"CO melder zolder","manufacturerID":4478,"manufacturerName":"feibit","powerSource":"Battery","modelID":"FNB56-COS06FB1.7","hardwareVersion":1,"softwareBuildID":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","dateCode":"20171215","lastSeen":1598566515462}]}`

And maybe this is helping:
`MQTT publish: topic 'zigbee2mqtt/CO melder zolder', payload '{"carbon_monoxide":false,"tamper":false,"battery_low":false,"linkquality":44}'`

**Comment by croc1234** [comment]
I bought this device as well. Tried to copy domoticz/plugins/zigbee2mqtt/adapters/heiman/HS1CAE.py  to feibit/SCA01ZB.py
But so far no luck in getting the device to work in Domoticz. It does not show up in devices and i get an error: 

Aug 27 12:21:03 pi npm[2237]: #033[32mzigbee2mqtt:info #033[39m 2020-08-27 12:21:03: MQTT publish: topic 'zigbee2mqtt/0x00158d000205c489', payload '{"carbon_monoxide":false,"tamper":false,"battery_low":false,"linkquality":86,"battery":100,"voltage":3000}'
Aug 27 12:21:03 pi npm[2237]: #033[32mzigbee2mqtt:info #033[39m 2020-08-27 12:21:03: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.13.1","commit":"2cb234c","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
Aug 27 12:21:12 pi npm[2237]: #033[31mzigbee2mqtt:error#033[39m 2020-08-27 12:21:12: Failed to configure '0x00158d000205c489', attempt 1 (Error: Bind 0x00158d000205c489/1 genPowerCfg from '0x00124b0018df3ee4/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
Aug 27 12:21:12 pi npm[2237]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:244:23)
Aug 27 12:21:12 pi npm[2237]:     at Generator.throw (<anonymous>)
Aug 27 12:21:12 pi npm[2237]:     at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))

**Comment by croc1234** [comment]
and this is the log from journalctl -u zigbee2mqtt.service -f


Aug 27 13:01:05 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:05: Configuring '0x00158d000205c489'
Aug 27 13:01:05 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00158d000205c489"}}'
Aug 27 13:01:05 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:05: MQTT publish: topic 'zigbee2mqtt/0x00158d000205c489', payload '{"carbon_monoxide":false,"tamper":false,"battery_low":false,"linkquality":63,"battery":100,"voltage":3000}'
Aug 27 13:01:05 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:05: MQTT publish: topic 'zigbee2mqtt/0x00158d000205c489', payload '{"carbon_monoxide":false,"tamper":false,"battery_low":false,"linkquality":63,"battery":100,"voltage":3000}'
Aug 27 13:01:06 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:06: MQTT publish: topic 'zigbee2mqtt/0x00158d000205c489', payload '{"carbon_monoxide":false,"tamper":false,"battery_low":false,"linkquality":63,"battery":100,"voltage":3000}'
Aug 27 13:01:06 pi npm[10845]: Zigbee2MQTT:error 2020-08-27 13:01:06: Failed to configure '0x00158d000205c489', attempt 2 (Error: ConfigureReporting 0x00158d000205c489/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'SOFTWARE_FAILURE')
Aug 27 13:01:06 pi npm[10845]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
Aug 27 13:01:06 pi npm[10845]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
Aug 27 13:01:06 pi npm[10845]:     at Generator.next (<anonymous>)
Aug 27 13:01:06 pi npm[10845]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
Aug 27 13:01:07 pi npm[10845]: Zigbee2MQTT:info  2020-08-27 13:01:07: Configuring '0x00158d000205c489'
Aug 27 13:01:08 pi npm[10845]: Zigbee2MQTT:error 2020-08-27 13:01:08: Failed to configure '0x00158d000205c489', attempt 3 (Error: ConfigureReporting 0x00158d000205c489/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'SOFTWARE_FAILURE')
Aug 27 13:01:08 pi npm[10845]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
Aug 27 13:01:08 pi npm[10845]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
Aug 27 13:01:08 pi npm[10845]:     at Generator.next (<anonymous>)
Aug 27 13:01:08 pi npm[10845]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))

**Comment by rolfie23** [comment]
Croc1234, where is your reply?

**Comment by rolfie23** [comment]
@Crock1234

**Comment by croc1234** [comment]
I have a similar device which is recognised as Feibit SCA01ZB or FNB56-COS06FB1.7 in zigbee2mqtt. This device is available in the development source and i have added the following code in /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices.js

  {
        zigbeeModel: ['FNB56-COS06FB1.7'],
        model: 'SCA01ZB',
        vendor: 'Feibit',
        description: 'Smart carbon monoxide sensor',
        supports: 'carbon monoxide',
        fromZigbee: [fz.ias_carbon_monoxide_alarm_1, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
            await configureReporting.batteryAlarmState(endpoint);
        },
    },


but still i get the following message when i try to pair the device:

Failed to configure '0x00158d000205c489', attempt 2 (Error: ConfigureReporting 0x00158d000205c489/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'SOFTWARE_FAILURE')

Am i missing a step?

**Comment by rolfie23** [comment]
In Zigbee2MQTT it was recornized instandly by the program, maybe update zigbee2mqtt? 
On the domoticz plugin i finaly have an message of the device:
`{"carbon_monoxide":false,"tamper":false,"battery_low":true,"linkquality":42,"battery":90,"voltage":2900}`
@stas-demydiuk hope you can do something with all this info.

**Comment by ReneOverkleeft** [comment]
Hi,

Same here....
The device SCA01ZB is available in Zigbee2Mqtt and visible in the Zigbee2Mqtt page within Domiticz.
But failed to add to Domoticz devices.
So i supose the plugin needs an update with this device.

2020-08-29 17:42:58.210 (Zigbee2MQTT) This plugin does not support zigbee device with model "SCA01ZB" yet
2020-08-29 17:42:58.210 (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by bizziebis** [comment]
I would also like to see SCA01ZB to be supported. I can test if needed!

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by croc1234** [comment]
Works like a charm!  Switch device with on/off status added. Thank you very much.

**Comment by bizziebis** [comment]
It's working! Thanks

**Comment by rolfie23** [comment]
It's working! Great! Only it's an on/off switch, not possible to make it an dusk sensor like a smoke detector?
