### ISSUE TITLE
Innr additional filament bulbs

### ISSUE THREAD

**Issue by GurbEHV** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#396]
There are some additional Innr filament bulbs, that can be added to /adapters/innr/__init__.py by copying the one that's in there now. I've got a [RF 261](https://www.zigbee2mqtt.io/devices/RF_261.html) and made it work by copying the information for RF 263 like so:
`    'RF 261': DimmableBulbAdapter,      # Innr E27 filament bulb dimmable`
Most likely, [RF 264](https://www.zigbee2mqtt.io/devices/RF_264.html) would also work, bu I don;t have that.

Thanks for your work!

**MQTT message with device information**
`{"dateCode":"20191206-257","description":"E27 filament bulb dimmable","friendly_name":"Licht Zithoek","hardwareVersion":1,"ieeeAddr":"0x680ae2fffeea4d26","lastSeen":1598099198480,"manufacturerID":4454,"manufacturerName":"innr","model":"RF 261","modelID":"RF 261","networkAddress":46321,"powerSource":"Mains (single phase)","softwareBuildID":"2.2","type":"Router","vendor":"Innr"}`

**MQTT messages from device**
`{"brightness": 196,"last_seen": 1598100644308,"state": "ON"}`

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by GurbEHV** [comment]
Updated and checked for RF 261, works fine, thanks!
