### ISSUE TITLE
Xiaomi MiJia Honeywell smoke detector - functionality question

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#397]
Hi,

I have bought 3 Xiaomi MiJia Honeywell smoke detectors and added them to zigbee2mqtt with the 
domoticz-zigbee2mqtt-plugin.
Several devices (sensors, battery, etc.) are announced and one of them is the Smoke Detector switch.

![afbeelding](https://user-images.githubusercontent.com/18295963/90976753-de177100-e53f-11ea-8c3a-294f31d974d3.png)

By default the switch is OFF, but when I push the button "Turn on Alarm" nothing happens (the Test Switch button works though).
Is this normal behaviour? In other words: is this Switch only used to turn the alarm off?

**Comment by stas-demydiuk** [comment]
I don't understand the language on your screenshot but most likely this button is aimed to trigger selftest, see https://www.zigbee2mqtt.io/devices/JTYJ-GD-01LM_BW.html
