### ISSUE TITLE
Alecto Smart-door10

### ISSUE THREAD

**Issue by timbay1985** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#398]
**Device description**
ALecto Smart-door10

**MQTT message with device information**
PUT here the device data you receive when publish message with topic

20-08-26 15:47:23.728 (zigbee2mqtt) Received available devices list from bridge
2020-08-26 15:47:23.730 (zigbee2mqtt) Device 0x14b457fffe2d5e56 (0x14b457fffe2d5e56) doesn't have "model" attribute, skipped

**Comment by stas-demydiuk** [comment]
Provided info is invalid, please create issue according to template
