### ISSUE TITLE
LifeControl MCLH-08 Air sensor configuration

### ISSUE THREAD

**Issue by whitepail** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#400]
**Device description**
LifeControl MCLH-08 Air sensor
https://www.zigbee2mqtt.io/devices/MCLH-08.html

**MQTT message with device information**
{"ieeeAddr":"0x00158d0000da31c9","type":"EndDevice","networkAddress":43739,"model":"MCLH-08","vendor":"LifeControl","description":"Air sensor","friendly_name":"0x00158d0000da31c9","manufacturerID":4151,"manufacturerName":"Nexturn","powerSource":"Battery","modelID":"VOC_Sensor","hardwareVersion":1,"softwareBuildID":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","dateCode":"2016-06-01","lastSeen":1598529240745}]}'

**MQTT messages from device**
Zigbee2MQTT:info  2020-08-27 12:24:02: MQTT publish: topic 'zigbee2mqtt/0x00158d0000da31c9', payload '{"temperature":27.26,"humidity":45.48,"eco2":467,"voc":10,"linkquality":102}'

**MQTT state change commands**
State change not applicable (sensor only)

**Comment by stas-demydiuk** [comment]
Done, could you please update the plugin and check?

**Comment by whitepail** [comment]
Thanks a lot!

Sensors detected and working ok.
The couple of things I noticed that can be updated:
1) eco2 measures currently marked as "General/Custom Sensor" instead of
"Air Quality/Voltcraft CO-20".
2) device do not report battery level, so "battery" sensor make no sense
(always 0)


вс, 30 авг. 2020 г. в 13:29, Stanislav Demydiuk <notifications@github.com>:

**Comment by stas-demydiuk** [comment]
Do you know `type`, `Subtype`  and `Switchtype` for CO2 sensor in Domoticz?
see "Available Device Types" section here https://www.domoticz.com/wiki/Developing_a_Python_plugin

**Comment by whitepail** [comment]
Type: 249 (Air Quality)
Subtype: 1
SwitchType: 0

пн, 31 авг. 2020 г. в 21:54, Stanislav Demydiuk <notifications@github.com>:

**Comment by stas-demydiuk** [comment]
Could you please remove all related Domoticz devices, update plugin and check again
