### ISSUE TITLE
Immax 4-Touch single click buttons

### ISSUE THREAD

**Issue by NE8XT** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#401]
Stas, please add the Immax NEO SMART remote control to support,
It is already supported in zigbee2mqtt: https://www.zigbee2mqtt.io/devices/07046L.html

Zigbee2MQTT:info  2020-08-29 06:41:54: Successfully interviewed '0x000d6ffffe40a97a', device has successfully been paired
Zigbee2MQTT:info  2020-08-29 06:41:54: Device '0x000d6ffffe40a97a' is supported, identified as: Immax 4-Touch single click buttons (07046L)
Zigbee2MQTT:info  2020-08-29 06:41:54: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x000d6ffffe40a97a","model":"07046L","vendor":"Immax","description":"4-Touch single click buttons","supported":true}}'
Zigbee2MQTT:info  2020-08-29 06:42:04: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe40a97a', payload '{"action":"arm_away","linkquality":118}'
Zigbee2MQTT:info  2020-08-29 06:42:07: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe40a97a', payload '{"linkquality":115,"action":"arm_stay"}'
Zigbee2MQTT:info  2020-08-29 06:42:30: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe40a97a', payload '{"linkquality":120,"action":"disarm"}'

**"arm_away"
"arm_stay"'
"disarm"
"panic"**

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by NE8XT** [comment]
Everything is fine, thank you very much Stas !! 
![immax](https://user-images.githubusercontent.com/6293406/91660268-a4adab00-ead5-11ea-87f0-87d17fe6850b.jpg)
