### ISSUE TITLE
Zigbee2Tasmota support

### ISSUE THREAD

**Issue by enesbcs** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#403]
**Device description**
Are there any plan to support Zigbee2Tasmota mqtt message translation?

**Zigbee2mqtt page**
https://tasmota.github.io/docs/Zigbee/

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
topic: tele/tasmota_xxxxxx/SENSOR
(xxxxxx is device specific)

payload examples:
{"ZbReceived":{"0xAC31":{"Device":"0xAC31","0500<00":"010000000000","ZoneStatusChange":1,"Endpoint":1,"LinkQuality":81}}}
{"ZbReceived":{"0xAC31":{"Device":"0xAC31","0500<00":"000000000000","ZoneStatusChange":0,"Endpoint":1,"LinkQuality":84}}}
{"ZbReceived":{"0x0D5A":{"Device":"0x0D5A","ModelId":"lumi.sensor_ht","Endpoint":1,"LinkQuality":184}}}
{"ZbReceived":{"0x0D5A":{"Device":"0x0D5A","Temperature":30.2,"Humidity":58.85,"Endpoint":1,"LinkQuality":195}}}
{"ZbReceived":{"0x9F9F":{"Device":"0x9F9F","Power":1,"Endpoint":1,"LinkQuality":95}}}

```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here
topic: 'cmnd/tasmota_xxxxxx/ZbSend'  payload '{ "device":"0x9F9F", "send":{"Power":"Off"} }'
topic: 'cmnd/tasmota_xxxxxx/ZbSend'  payload '{ "device":"0x9F9F", "send":{"Power":"On"} }'

**MQTT get device information**

topic: 'cmnd/tasmota_xxxxxx/ZbStatus2'  payload: "0x9F9F"

reply topic:
stat/tasmota_xxxxxx/RESULT payload: {"ZbStatus2":[{"Device":"0x9F9F","IEEEAddr":"0x00124B001E728B58","ModelId":"BASICZBR3","Manufacturer":"SONOFF","Endpoints":["0x01"]}]}

**Comment by khongpt** [comment]
I was very glad to hear that zigbee2mqtt can converts zigbee2tasmota mqtt message. wish to have!

**Comment by stas-demydiuk** [comment]
I don't have any plans to add `zigbee2tasmota` support in the scope of this plugin. Maybe someone could create their own one.
