### ISSUE TITLE
Support new Philips Hue 1600 lumen bulbs

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#404]
Hi, you probably don't need all the stuff below, but I've added it anyway. 

I think we just need an extra line in ../adapters/philips/__init.py like this: -

'929002335001': DimmableBulbAdapter,    # Philips Hue white A21 bulb B22 with Bluetooth (1600 Lumen)

I know this works because I have some of these bulbs and have tested the change.

Note that there is also an Edison version of the same bulb which is also already supported in zigbee-herdsman-converters, so it might be a good idea to add it at the same time: -

'9290023349': DimmableBulbAdapter,    # Philips Hue white A67 bulb E26 with Bluetooth (1600 Lumen)

Note that I don't have one of the Edison ones so I can't test that change.

Hugh

**Device description**
Philips Hue white A21 bulb B22 with Bluetooth (1600 Lumen)

**Zigbee2mqtt page**
Not yet added to that page but has been added to zigbee-herdsman-converters/devices.js

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x0017880108d981b0","type":"Router","networkAddress":2110,"model":"929002335001","vendor":"Philips","description":"Hue white A21 bulb B22 with Bluetooth (1600 Lumen)","friendly_name":"LOUNGE.DINING.CEILING","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","modelID":"LWA010","hardwareVersion":1,"softwareBuildID":"1.55.7_r28193","dateCode":"20190322","lastSeen":1599138898877}

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
info  2020-09-03 13:40:05: MQTT publish: topic 'zigbee2mqtt/LOUNGE.DINING.CEILING', payload '{"brightness":254,"linkquality":117,"state":"OFF","update_available":false,"device":{"friendlyName":"LOUNGE.DINING.CEILING","model":"929002335001","ieeeAddr":"0x0017880108d981b0","networkAddress":2110,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":2,"hardwareVersion":1,"dateCode":"20190322","softwareBuildID":"1.55.7_r28193"}}'
```

**MQTT state change commands**
info  2020-09-03 14:20:19: MQTT publish: topic 'zigbee2mqtt/LOUNGE.DINING.CEILING', payload '{"brightness":117,"linkquality":117,"state":"ON","update_available":false,"device":{"friendlyName":"LOUNGE.DINING.CEILING","model":"929002335001","ieeeAddr":"0x0017880108d981b0","networkAddress":2110,"type":"Router","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","applicationVersion":2,"stackVersion":1,"zclVersion":2,"hardwareVersion":1,"dateCode":"20190322","softwareBuildID":"1.55.7_r28193"}}'

**Comment by stas-demydiuk** [comment]
Thanks! Updated the plugin
