### ISSUE TITLE
Support for Smart Light Switch Lonsonho X711A

### ISSUE THREAD

**Issue by CoolGool** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#405]
**Device description**
Lonsonho X711A (1 gang, without Neutral)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/X711A.html

**MQTT message with device information**
```
{"dateCode":"","description":"Smart light switch - 1 gang without neutral wire","friendly_name":"0xbc33acfffe18b4e3","hardwareVersion":1,"ieeeAddr":"0xbc33acfffe18b4e3","lastSeen":1599218158946,"manufacturerID":4098,"manufacturerName":"_TYZB01_xfpdrwvc","model":"TS0011","modelID":"TS0011","networkAddress":31437,"powerSource":"Battery","type":"EndDevice","vendor":"TuYa"}
```

**MQTT messages from device**
```
Zigbee2MQTT:info  2020-09-06 14:42:46: MQTT publish: topic 'zigbee2mqtt/0xbc33acfffe18b4e3', payload '{"linkquality":0,"state":"ON"}'
Zigbee2MQTT:info  2020-09-06 14:42:49: MQTT publish: topic 'zigbee2mqtt/0xbc33acfffe18b4e3', payload '{"linkquality":0,"state":"OFF"}'
```

**MQTT state change commands**
zigbee2mqtt/0xbc33acfffe18b4e3/set ON

**Error message in Domoticz log**
(Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md
(Zigbee2MQTT) This plugin does not support zigbee device with model "TS0011" yet

**NOTE**
This device used to work with an older version of Zigbee2MQTT and domoticz-zigbee2mqtt-plugin. After upgrading both software components to the latest version this week, it stopped working with the above error message in Domoticz log

**Comment by stas-demydiuk** [comment]
Done. Could you please update plugin and check.

**Comment by CoolGool** [comment]
Sorry, doesn't work yet. Did the update on the plugin with git pull and restarted Domoticz. Still same error message in Domoticz log.
FYI the output of the git pull, because I don't see anything related to TS0011:

remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 58 (delta 45), reused 50 (delta 45), pack-reused 8
Unpacking objects: 100% (58/58), done.
From https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
   01ea95b..077d9e5  master     -> origin/master
Updating 01ea95b..077d9e5
Fast-forward
 CHANGELOG.md                                |   6 ++++++
 SUPPORTED_DEVICES.md                        |   5 +++++
 adapters/__init__.py                        |   5 +++--
 adapters/{innr/SP120.py => generic/plug.py} |   5 +++--
 adapters/innr/__init__.py                   |   4 ++--
 adapters/lumi/WXKG01LM.py                   |  10 +++++++++-
 adapters/lumi/ZNCZ02LM.py                   |  10 ++++++++--
 adapters/lumi/ZNCZ04LM.py                   |  10 ++++++++++
 adapters/lumi/__init__.py                   |  10 +++++++---
 adapters/lumi/plug.py                       |   7 +++----
 adapters/netvox/Z809A.py                    |  12 ------------
 adapters/netvox/__init__.py                 |   0
 adapters/philips/__init__.py                |   2 ++
 adapters/tuya/TS0041.py                     |  18 ++++++++++++++++++
 adapters/tuya/TS0601.py                     | 105 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 adapters/tuya/__init__.py                   |   8 ++++++++
 devices/switch/level_switch.py              |  14 ++++++++++++++
 devices_manager.py                          |   2 +-
 18 files changed, 204 insertions(+), 29 deletions(-)
 rename adapters/{innr/SP120.py => generic/plug.py} (88%)
 create mode 100644 adapters/lumi/ZNCZ04LM.py
 delete mode 100644 adapters/netvox/Z809A.py
 delete mode 100644 adapters/netvox/__init__.py
 create mode 100644 adapters/tuya/TS0041.py
 create mode 100644 adapters/tuya/TS0601.py
 create mode 100644 devices/switch/level_switch.py

**Comment by stas-demydiuk** [comment]
Sorry, maybe I missed something but you've asked for support of https://www.zigbee2mqtt.io/devices/X711A.html, it's model is `X711A` not `TS0011`

**Comment by CoolGool** [comment]
I apologize, my bad. I ordered the `X711A` but apparently received the `TS0011`, which looks exactly the same. Anyway, it works now. Many thanks!
