### ISSUE TITLE
New Device Support(TS0601 Zemismart model: 'M515EGB' Curtain motor) 

### ISSUE THREAD

**Issue by Krolik1988** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#406]
**Device description**
Hello, got new roller curtains motor, and triying to add it to your plug-in. Please check if everything is correct(I think not) and please add support. It look likes motor it self are RF, but then it have USB stick Zigbee Router(I think)

**Zigbee2mqtt page**
[In progress](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1536). Probably it's almost works, waiting for check.

**MQTT message with device information**
{"id":6,"type":"Router","ieeeAddr":"0x842e14fffefec07d","nwkAddr":51870,"manufId":4098,"manufName":"_TZE200_xuzcvlku","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_xuzcvlku","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1599402930812}

"friendly_name":"0x842e14fffefec07d"
"type":"devices"
"modelId":"TS0601"
"manufacturerName":"_TZE200_xuzcvlku"
"powerSource":1
"zclVersion":3
"appVersion":68
"stackVersion":0
"hwVersion":1
"dateCode":""
data '{}'

"manufacturerID":4098
"manufacturerName":"_TZE200_xuzcvlku"
"model":"TS0601"
"modelID":"TS0601"
"powerSource":"Mains (single phase)"
"type":"Router"
"vendor":"-"
"type":"devices"

Cluster 'genTime', data '["localTime"]' 
 type 'raw'
cluster 'manuSpecificTuyaDimmer'
data '{"data":[25,4,36,0,6]
"type":"Buffer"}

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
0x842e14fffefec07d (0x842e14fffefec07d): TS0601_curtain - TuYa Curtain motor (Router)

MQTT publish: topic 'zigbee2mqtt/0x842e14fffefec07d', payload '{"linkquality":36,"running":true}'


Received Zigbee message from '0x842e14fffefec07d', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0,0,0,100],"type":"Buffer"},"dp":514,"fn":0,"status":0,"transid":213}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-06 17:17:08: MQTT publish: topic 'zigbee2mqtt/0x842e14fffefec07d', payload '{"linkquality":47,"running":true}'


```

I added next line to /adapters/zemismart/__init.py__:
```
    'TS0601_curtain': BlindAdapter,  # Zemismart Curtain/roller blind switch
```

But i'm not sure it works well. I got:

Zigbee2MQTT  (Link Quality) | General | Custom Sensor

Zigbee2MQTT  Light/Switch | Switch | Open
![20200904_165939](https://user-images.githubusercontent.com/52775223/92329296-e656cc80-f066-11ea-8a18-83cd576f2ac8.jpg)

Look likes it work, only I don't know if there must be battery indication.

**Comment by stas-demydiuk** [comment]
Added support to the plugin, thanks!

**Comment by TheOriginal92** [comment]
Hey i have the exact same 'M515EGB' Curtain motor, but it still shows up as unsupported.
I am using the latest -dev branch on docker.

- Zigbee2MQTT version: 1.17.1-dev 
- commit: 88a105e
- Coordinator type: zStack3x0
- Coordinator revision: 20210120
- Frontend version: 0.3.64

Already removed the device from my data/database.db file and repaired it but no avail.

Can someone help me here?

Thank you very much :)
