### ISSUE TITLE
DIYRuZ_RT alternative firmware

### ISSUE THREAD

**Issue by enesbcs** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#407]
**Device description**
Sonoff Basic ZBR3 with DS18b20 and Z-Stack 3.0 firmware
https://habr.com/ru/company/iobroker/blog/495926/

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/DIYRuZ_RT.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
'{"message":[{"dateCode":"20200327","friendly_name":"Coordinator","ieeeAddr":"0x00124b00060e4bfb","lastSeen":1599416678016,"networkAddress":0,"softwareBuildID":"zStack30x","type":"Coordinator"},{"dateCode":"20200405","description":"[DiY CC2530 Zigbee 3.0 firmware](https://habr.com/ru/company/iobroker/blog/495926/)","friendly_name":"0x00124b001e728b58","hardwareVersion":1,"ieeeAddr":"0x00124b001e728b58","lastSeen":1599416671477,"manufacturerID":0,"manufacturerName":"DIYRuZ","model":"DIYRuZ_RT","modelID":"DIYRuZ_RT","networkAddress":60164,"powerSource":"Mains (single phase)","softwareBuildID":"20200405","type":"Router","vendor":"DIYRuZ"}],"type":"devices"}'
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
topic 'zigbee2mqtt/0x00124b001e728b58', payload '{"linkquality":28,"state":"ON","temperature":27.25}'
topic 'zigbee2mqtt/0x00124b001e728b58', payload '{"linkquality":26,"state":"OFF","temperature":27.25}'

```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

topic 'zigbee2mqtt/0x00124b001e728b58/set'  payload: 'ON'

topic 'zigbee2mqtt/0x00124b001e728b58/set' payload: 'OFF'

**Comment by enesbcs** [comment]
Pull request added to support. https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/pull/408

**Comment by stas-demydiuk** [comment]
PR has been merged, thanks!
