### ISSUE TITLE
Support for SmartThings Arrival Sensor

### ISSUE THREAD

**Issue by fielux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#41]
**Device description**
SmartThings Arrival Sensor STS-PRS-251 / STS-PRS-250

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x24fd5b0001056a99","type":"EndDevice","model":"tagv4","friendly_name":"Arrival Sensor"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
 zigbee2mqtt:info 2018-11-24 02:12:33 MQTT publish, topic: 'zigbee2mqtt/Arrival Sensor', payload: '{"presence":true,"linkquality":49,"battery":"20.00","voltage":2600}'
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
@fielux Should be available with latest master branch, could you please update and check

**Comment by fielux** [comment]
Great will do!

Il giorno dom 9 dic 2018 alle ore 12:20 Stanislav Demydiuk <
notifications@github.com> ha scritto:
