### ISSUE TITLE
Innr RS229T devices don't get added after succesful pairing.

### ISSUE THREAD

**Issue by sammyke007** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#410]
**Issue description**
Domoticz won't create any devices for the Innr RS 229 T GU10 spot 350 lm, dimmable, white spectrum after succesful pairing.
They should be supported according to the zigbee2mqtt devices list.
I tried rebooting Pi / Domoticz / Zigbee2mqtt service and the zigbee2mqtt plugin for Domoticz. No solution. 
Factory reset of the bulbs after force removing them doesn't work either. 

**Additional information**
Zigbee2MQTT version: v.1.14.4 (zStack3x0 20200805)
Python version: 2.7
Domoticz version: 2020.2
Plugin version: 0.2.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by sammyke007** [comment]
I added 

`'RS 229 T': DimmableCtBulbAdapter,  # Innr GU10 Spot 350 lm, dimmable, white spectrum`

to /home/pi/domoticz/plugins/zigbee2mqtt/adapters/innr/__init__.py

The devices were created after disabling and enabling the plugin in Domiticz. Will test later today if it works!

**Comment by stas-demydiuk** [comment]
Added support to the plugin, thanks
