### ISSUE TITLE
Plugin self-update feature

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#412]
Dear Stas..
Thanks for the great work you made!!!!

Is there perhaps a option to make a update button in the Domoticz custom page?
Looks a great option for me.

once x time push teh button and then the plugin update..

Or otherwis, can you make the plugin hardcore in domoticz?
Update domoticz everything up to date.:-)

If not possible i should work with cli..

Thanks!!!

**Comment by stas-demydiuk** [comment]
Good idea to have the self-update option within the plugin, will think how to implement it

**Comment by Dylantje** [comment]
Perhaps also a option like the z2m plugin in domoticz. In the selmade weppages in Domoticz. look great to have a display with you plugin and see the devcies of your plugin and the other options that are possible
