### ISSUE TITLE
Ikea E1524/E1810 remote (ON/OFF) switch not working after rPi restart

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#414]
**Issue description**

When I shutdown/start or restart my Raspberry Pi, the "E1524/E1810" remote (ON/OFF switch) in Domoticz does not respond anymore when I hit the on/off button of the physical remote. But when I restart the Zigbee2mqtt and Domoticz service in this order from the console the Switch is back to normal behaviour.

It looks like that is has something to do with the order of starting the mosquitto (zigbee2mqtt) and domoticz services because when I add a startup delay:
`"DAEMON_ARGS="$DAEMON_ARGS -startupdelay 20"`
to "sudo nano /etc/init.d/domoticz.sh", the behaviour after a Pi restart is also back to normal behaviour. (10 seconds are to short)

I have bound the remote to a group of bulbs in zigbee2mqtt, and only use the on/off switch to sync it with the group switch created in Domoticz.

All other zigbee2mqtt devices created with the plug-in have no issues

What could be the problem here?

**Additional information**
Zigbee2MQTT version: 1.14.3
Python version: 3.7.3
Domoticz version: 2020.2 (build 12230)
Plugin version: 0.2.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
Looks like the same issue as #161
