### ISSUE TITLE
Gira no longer supported?

### ISSUE THREAD

**Issue by pcfreak1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#415]
**Issue description**
Put general information here

**Additional information**
Zigbee2MQTT version: v.1.13.0 (zStack12 20190608)
Python version: 3
Domoticz version: 2020.2
Plugin version: latest, just updated

**Logs**
Some time ago support was added for the gira light link buttons, but now after updating i get this:
2020-09-17 12:32:50.162 (zigbee2mqtt1) This plugin does not support zigbee device with model "InstaRemote" yet
and it no longer works, or at least it does not update my switches in domoticz anymore. has something changed? now a lot of my buttons do not work anymore unfortunately.

**Comment by stas-demydiuk** [comment]
Looks like there is an issue with your zigbee2mqtt setup as I don't see device with model `InstaRemote` on their supported devices page https://www.zigbee2mqtt.io/information/supported_devices.html
