### ISSUE TITLE
Suppotr 324131092621Philips Hue dimmer switch RWL021

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#42]
Stas, can you please add 24131092621 Philips Hue dimmer switch.

`2018-11-24 17:42:57.372 (Zigbee Stick) MQTT message: zigbee2mqtt/0x0017880103e4518f {'device': {'type': 'EndDevice', 'friendlyName': '0x0017880103e4518f', 'powerSource': 'Battery', 'manufId': 4107, 'status': 'offline', 'nwkAddr': 51236, 'manufName': 'Philips', 'modelId': 'RWL021', 'ieeeAddr': '0x0017880103e4518f'}, 'linkquality': 39, 'battery': 100, 'action': 'on'}
2018-11-24 17:42:57.376 (Zigbee Stick) Received heartbeat message from device "Zigbee Stick - 0x0017880103e4518f"`

`2018-11-24 17:43:49.629 (Zigbee Stick) MQTT message: zigbee2mqtt/0x0017880103e4518f {'device': {'type': 'EndDevice', 'friendlyName': '0x0017880103e4518f', 'powerSource': 'Battery', 'manufId': 4107, 'status': 'offline', 'nwkAddr': 51236, 'manufName': 'Philips', 'modelId': 'RWL021', 'ieeeAddr': '0x0017880103e4518f'}, 'linkquality': 52, 'battery': 100, 'action': 'off'}
2018-11-24 17:43:49.634 (Zigbee Stick) Received heartbeat message from device "Zigbee Stick - 0x0017880103e4518f"`

`2018-11-24 17:44:10.325 (Zigbee Stick) MQTT message: zigbee2mqtt/0x0017880103e4518f {'device': {'type': 'EndDevice', 'friendlyName': '0x0017880103e4518f', 'powerSource': 'Battery', 'manufId': 4107, 'status': 'offline', 'nwkAddr': 51236, 'manufName': 'Philips', 'modelId': 'RWL021', 'ieeeAddr': '0x0017880103e4518f'}, 'linkquality': 39, 'battery': 100, 'brightness': 100, 'action': 'up-press'}
2018-11-24 17:44:10.330 (Zigbee Stick) Received heartbeat message from device "Zigbee Stick - 0x0017880103e4518f"
2018-11-24 17:44:11.683 (Zigbee Stick) MQTT message: zigbee2mqtt/0x0017880103e4518f {'device': {'type': 'EndDevice', 'friendlyName': '0x0017880103e4518f', 'powerSource': 'Battery', 'manufId': 4107, 'status': 'offline', 'nwkAddr': 51236, 'manufName': 'Philips', 'modelId': 'RWL021', 'ieeeAddr': '0x0017880103e4518f'}, 'linkquality': 23, 'battery': 100, 'brightness': 150, 'action': 'up-press'}
2018-11-24 17:44:11.686 (Zigbee Stick) Received heartbeat message from device "Zigbee Stick - 0x0017880103e4518f"`

`2018-11-24 17:44:31.271 (Zigbee Stick) MQTT message: zigbee2mqtt/0x0017880103e4518f {'device': {'type': 'EndDevice', 'friendlyName': '0x0017880103e4518f', 'powerSource': 'Battery', 'manufId': 4107, 'status': 'offline', 'nwkAddr': 51236, 'manufName': 'Philips', 'modelId': 'RWL021', 'ieeeAddr': '0x0017880103e4518f'}, 'linkquality': 23, 'battery': 100, 'brightness': 100, 'action': 'down-press'}
2018-11-24 17:44:31.276 (Zigbee Stick) Received heartbeat message from device "Zigbee Stick - 0x0017880103e4518f"
2018-11-24 17:44:34.431 (Zigbee Stick) Heartbeating...
2018-11-24 17:44:34.431 (Zigbee Stick) MqttClient::Ping`

**Comment by stas-demydiuk** [comment]
@salopette Sorry it's too hard to add support for this device without having one for testing. Hopefully someone with this device will help.

**Comment by d-EScape** [comment]
I created an adapter to put the controller actions in a selector switch. Having the dimmer switch control an actual (Domoticz) dimmer slider seems pretty useless because you will need some event script anyway to control something else. Creating a slider would limit the functionality for scripting. 

Sorry, my development environment is a mess... so no PR but some code to add:

file named 'dimmer_switch_phlps.py' in adapters/philips:
`from adapters.adapter_with_battery import AdapterWithBattery
from devices.switch.selector_switch import SelectorSwitch

class DimmerSwitchPhlps(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.switch = SelectorSwitch(devices, 'dimmer', 'action')
        self.switch.add_level('off', None)
        self.switch.add_level('down-press', 'down-press')
        self.switch.add_level('down-hold', 'down-hold')
        self.switch.add_level('down-hold-release', 'down-hold-release')
        self.switch.add_level('up-press', 'up-press')
        self.switch.add_level('up-hold', 'up-hold')
        self.switch.add_level('up-hold-release', 'up-hold-release')
        self.switch.add_level('on', 'on')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_MENU)
        self.devices.append(self.switch)
`

Modify the adapters __init__.py accordingly with:
`from adapters.philips.dimmer_switch_phlps import DimmerSwitchPhlps`
and 
`'324131092621': DimmerSwitchPhlps,	# Philips Hue dimmer switch`

**Comment by stas-demydiuk** [comment]
@d-EScape Thanks! Added code to the main codebase
