### ISSUE TITLE
Device SP 220

### ISSUE THREAD

**Issue by BenGost** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#420]
Bonjour,

J'ai rajouté un appareil "Device SP 220" sur domoticz, il apparaît bien, mais le signale reste sur 0 et l'action on/off ne fait rien sur l'interrupteur. Normal ?

Merci

--------------

Hello,

I added a device "Device SP 220" on domoticz, it appears well, but the signal remains on 0 and the on / off action does nothing on the switch. Normal?

Thank you

![image](https://user-images.githubusercontent.com/62108660/94169530-3a4b1900-fe8f-11ea-8ecb-813d98f54afb.png)
![image](https://user-images.githubusercontent.com/62108660/94169602-4cc55280-fe8f-11ea-84b1-78c719a30eec.png)

**Comment by stas-demydiuk** [comment]
Most likely this device is out of range of your zigbee stick
