### ISSUE TITLE
PTVO switch, issue with inputs

### ISSUE THREAD

**Issue by janjansen1** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#421]
First thank you for this great plugin!

I want to use a ptvo switch with the following configuration:
Board type: CC2530 + CC2591
Model ID: ptvo.switch
Location description: Schuur
Power saving mode (PSM): No

Output pins:
P13: Output 1, GPIO, Pull-down, Remember state
P12: Output 2, GPIO, Pull-down, Remember state
P16: Output 3, GPIO, Pull-down, Remember state

Input pins:
P03: Input 1, GPIO, Pull-down, Switch, Link to out 1
P02: Input 2, GPIO, Pull-down, Switch, Link to out 2

After pairing, the following devices are generated:

![image](https://user-images.githubusercontent.com/25150865/94264815-b600a080-ff37-11ea-8876-365b40592147.png)

Results:
switching input 1 (PTVO side PO3) no reaction idx 112 (Domoticz side)
MQTT message: zigbee2mqtt/Schuur {'linkquality': 70, 'state_l1': 'ON', 'state_l2': 'OFF', 'state_l3': 'OFF'}

switching input 2 (PTVO side PO3) no reaction idx 113 (Domoticz side)
MQTT message: zigbee2mqtt/Schuur {'linkquality': 91, 'state_l1': 'OFF', 'state_l2': 'ON', 'state_l3': 'OFF'}

switching idx 114 (Domoticz side) P16 (PTVO side) reacts as desired.
(Zigbee bridge) onCommand: Off, level (0) Color:
(Zigbee bridge) Command "Off" from device "Zigbee bridge - 0x00124b001fc64bd9 (input3)"
(Zigbee bridge) MqttClient::publish zigbee2mqtt/Schuur/l3/set (OFF)
(Zigbee bridge) MQTT message: zigbee2mqtt/Schuur {'linkquality': 93, 'state_l1': 'OFF', 'state_l2': 'ON', 'state_l3': 'OFF'}

**Additional information**
Zigbee2MQTT version:  zigbee2mqtt@1.14.4
Python version: Python 3.7.3
Domoticz version: 12269
Plugin version: latest

Help in realizing working inputs is greatly appreciated.
Thanks in advance!

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458.
Reopen this issue in case of any issues.

**Comment by yurganov** [comment]
it is still not working as desired

after triggering input from zigbee2mqtt and after state of all inputs successfully sended to mqtt, devices not update their state in domoticz
