### ISSUE TITLE
Moes ZK-EU-2U not in Devices

### ISSUE THREAD

**Issue by njkavon** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#422]
Not sure if it's device support problem, but I ran out of googl ideas why it's visible on plugin page, but not in Domoticz devices (Accept new Hardware Devices allowed), three lights accessible with issue. Thanks for checking out.

**Device description**
ZigBee3.0 dual USB wireless socket plug

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/ZK-EU-2U.html

{"description":"ZigBee3.0 dual USB wireless socket plug","friendly_name":"0xec1bbdfffe6c2d13","ieeeAddr":"0xec1bbdfffe6c2d13","lastSeen":1601053617238,"manufacturerID":0,"manufacturerName":"_TYZB01_b1ngbmlm","model":"ZK-EU-2U","modelID":"TS0112","networkAddress":29177,"powerSource":"Mains (single phase)","type":"Router","vendor":"Moes"}],"type":"devices"}'

cSep 25 19:10:21 raspberrypi npm[499]: Zigbee2MQTT:info  2020-09-25 19:10:21: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6c2d13', payload '{"linkquality":115,"state":"OFF"}'
Sep 25 19:10:23 raspberrypi npm[499]: Zigbee2MQTT:info  2020-09-25 19:10:23: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe6c2d13', payload '{"linkquality":118,"state":"ON"}'

**Comment by stas-demydiuk** [comment]
Support is added, could you please update plugin and check

**Comment by njkavon** [comment]
So yeah that was it, works now.
Thanks!
