### ISSUE TITLE
Trust remote ZYCT-202

### ISSUE THREAD

**Issue by 2N3819** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#423]
Hi 
I am not sure if the Trust ZYCT-202 remote control is supported or not.
The supported device list states:
**"Trust -     Trust Remote control"**

The devices have been added to Domoticz:
152	Zigbee_IO	0x00158d00038e5fe1_signal	28	Zigbee_IO - 0x00158d00038e5fe1 (Link Quality)	General	Custom Sensor	0 	-2020-09-27 18:37:36
153	Zigbee_IO	0x00158d00038e5fe1_cell	29	Zigbee_IO - 0x00158d00038e5fe1 (Battery Voltage)	General	Voltage	0 V	-	2020-09-27 18:37:36
154	Zigbee_IO	0x00158d00038e5fe1_btperc	30	Zigbee_IO - 0x00158d00038e5fe1 (Battery)	General	Percentage	0%	-2020-09-27 18:37:36
155	Zigbee_IO	0x00158d00038e5fe1_btn1	31	Remote_Button 1	Light/Switch	Selector Switch	Off	-	-	2020-09-27 18:41:55
156	Zigbee_IO	0x00158d00038e5fe1_btn2	32	Zigbee_IO - 0x00158d00038e5fe1 (Button 2)	Light/Switch	Selector Switch	Off	-2020-09-27 18:37:36
157	Zigbee_IO	0x00158d00038e5fe1_btn3	33	Zigbee_IO - 0x00158d00038e5fe1 (Button 3)	Light/Switch	Selector Switch	Off	-2020-09-27 18:37:36
158	Zigbee_IO	0x00158d00038e5fe1_btn4	34	Zigbee_IO - 0x00158d00038e5fe1 (Button 4)	Light/Switch	Selector Switch	Off	-2020-09-27 18:37:36
159	Zigbee_IO	0x00158d00038e5fe1_btn5	35	Zigbee_IO - 0x00158d00038e5fe1 (Button 5)	Light/Switch	Selector Switch	Off	-2020-09-27 18:37:36
160	Zigbee_IO	0x00158d00038e5fe1_btn6	36	Zigbee_IO - 0x00158d00038e5fe1 (Button 6)	Light/Switch	Selector Switch	Off

The used device (155) does not change state when the button is pressed on the remote control.
The Domoticz log reports:
2020-09-27 18:41:54.435 Status: User: Admin initiated a switch command (155/Remote_Button 1/Set Level)
2020-09-27 18:41:55.188 Status: User: Admin initiated a switch command (155/Remote_Button 1/Set Level)
2020-09-27 18:42:17.616 Error: (Zigbee_IO) 'onMessage' failed 'AttributeError':''NoneType' object has no attribute 'handle_message''.
2020-09-27 18:42:17.619 Error: (Zigbee_IO) ----> Line 263 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-09-27 18:42:17.620 Error: (Zigbee_IO) ----> Line 112 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-09-27 18:42:17.621 Error: (Zigbee_IO) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2020-09-27 18:42:17.622 Error: (Zigbee_IO) ----> Line 183 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2020-09-27 18:42:17.623 Error: (Zigbee_IO) ----> Line 63 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_mqtt_message
2020-09-27 18:42:17.624 Error: (Zigbee_IO) ----> Line 38 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/trust/zyct202.py', function handleMqttMessage 

Any help would be appreciated.
Thank you
Richard

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458.
Reopen this issue in case of any issues.

**Comment by 2N3819** [comment]
Hi

The clone instructions for the V3.0 version of the plugin  on:
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/tree/v3.0
are the same as for the master version.

Should the following be modified?

git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git
zigbee2mqtt

to include:
git fetch
git checkout v3.0

Regards

Richard

**Comment by 2N3819** [comment]
Hi
I updated to the V3.0 plugin and most of my zigbee devices were not working.

The Zigbee devices I have are:
0x00124b001e72891c BASICZBR3 Zigbee smart switch Router 0x00124b001e72891c
2020-12-06 12:11:42
0x00124b001e72899e BASICZBR3 Zigbee smart switch Router 0x00124b001e72899e
2020-12-06 12:12:00

0x00124b001fc94181 ZigUP [CC2530 based ZigBee relais, switch, sensor and
router](https://github.com/formtapez/ZigUP/) Router 0x00124b001fc94181
2020-10-04 15:42:14
0x00158d00038e5fe1 ZYCT-202 Remote control EndDevice 0x00158d00038e5fe1
2020-11-08 19:31:10
0x00158d000429f6ca WSDCGQ11LM Aqara temperature, humidity and pressure
sensor EndDevice 0x00158d000429f6ca 2020-12-06 12:01:16

0x14b457fffe4202d5 SP 222 Smart plug Router 0x14b457fffe4202d5 2020-12-06
11:48:19
0x14b457fffe4afb79 SP 222 Smart plug Router 0x14b457fffe4afb79 2020-12-06
12:09:11
0x14b457fffe4b1117 SP 222 Smart plug Router 0x14b457fffe4b1117 2020-12-06
12:09:11
0x000d6ffffe5cbcba SP 222 Smart plug Router 0x000d6ffffe5cbcba 2020-12-06
12:09:14

0x7cb03eaa0a034813 AC03641 LIGHTIFY LED Classic A60 clear Router
0x7cb03eaa0a034813 2020-11-21 21:43:02
0x7cb03eaa0a04bc9d AC03641 LIGHTIFY LED Classic A60 clear Router
0x7cb03eaa0a04bc9d 2020-11-21 21:43:05

The SP 222 and the BASICZBR3 devices were not working.
Clicking on the domoticz device buttons had no effect
The AC03641 were functional / OK.

The ZigUP and the ZYCT202 devices were not tested.

Before updating the plugin :
I created backup copies of both /opt/zigbee2mqtt and
/home/pi/domoticz/plugins/zigbee2mqtt.
I update ZIGBEE2MQTT to the dev branch and set:

experimental:
  new_api: true

I tested the dev version of ZIGBEE2MQTT with the stable/master plugin - all
appeared OK.

To restore normal operation:
I changed back to the stable/master version of the plugin (by restoring the
backup copy of the plugin)
Restarted domoticz and my devices were functional.

Testing:
I can swap the plugin folders by renaming them.
I can undertake some testing of the V3.0 plugin if you can advise what I
need to do.

Regards
Richard
