### ISSUE TITLE
New device. Dimmer QS-Zigbee-D02-TRIAC-LN

### ISSUE THREAD

**Issue by Krolik1988** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#424]
**Device description**
[Lonsonho Tuya ZigBee 3.0 Smart Dimmer Switch Module With Neutral 1/2 Gang 2 Way Wireless Control Switch Relay](https://www.aliexpress.com/item/4001279149071.html?spm=a2g0s.9042311.0.0.4e2b4c4dxyI2Bn)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-LN.html

**MQTT message with device information**
--
```
{"id":7,"type":"Router","ieeeAddr":"0xbc33acfffe6d82d3","nwkAddr":1218,"manufId":4098,"manufName":"_TYZB01_qezuin6k","powerSource":"Mains (single phase)","modelId":"TS110F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,4,5,6,8],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS110F","manufacturerName":"_TYZB01_qezuin6k","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1601488411171}
```

**MQTT messages from device**

```
Received Zigbee message from '0xbc33acfffe6d82d3', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1,"onTime":0}' from endpoint 1 with groupID 0
Skipping message, definition is undefined and still interviewing
Received Zigbee message from '0xbc33acfffe6d82d3', type 'attributeReport', cluster 'genLevelCtrl', data '{"64512":1023,"currentLevel":255}' from endpoint 1 with groupID 0
Skipping message, definition is undefined and still interviewing
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"modelId":"TS110F"}' from endpoint 1 with groupID 0
Skipping message, definition is undefined and still interviewing
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TYZB01_qezuin6k"}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"appVersion":65}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
Received Zigbee message from '0xbc33acfffe6d82d3', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
```
![20200930_181611](https://user-images.githubusercontent.com/52775223/94725220-b942c480-035b-11eb-88a1-cceff898b61b.jpg)
![20200930_181622](https://user-images.githubusercontent.com/52775223/94725233-bb0c8800-035b-11eb-9eff-38934b73c3b6.jpg)
![20200930_181751](https://user-images.githubusercontent.com/52775223/94725237-bcd64b80-035b-11eb-9d60-c6fa023863ae.jpg)

Needs to add to [domoticz-zigbee2mqtt-plugin/adapters/__init__.py](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/master/adapters/__init__.py)
Line under Lonsonho section:
``
    'QS-Zigbee-D02-TRIAC-LN': DimmableBulbAdapter,  #QS-Zigbee-D02-TRIAC-LN
``
Gonna to connect exhaust fan to it, already checked it by multimeter. Dimmer switch changes voltage on output. 
Thanks,
Kind regards,
Alex.

**Comment by Krolik1988** [comment]
I think I need to confirm thet everything is ok? :))) Still works, everything fine. Can be added. :) Thanks.

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.

**Comment by Krolik1988** [comment]
Hi, and here we are after update:
`2020-12-21 20:51:02.097 Error: (Zigbee2MQTT) 0xbc33acfffe6d82d3: can not process feature type "light"

**Comment by Krolik1988** [comment]
Putted back 
Line under Lonsonho section:
'QS-Zigbee-D02-TRIAC-LN': DimmableBulbAdapter, #QS-Zigbee-D02-TRIAC-LN
Again works. But I think It must be done other way.

**Comment by ciB89** [comment]
@Krolik1988 a little bit off-topic but I've got a quick question about the device. On many product pages it says it only supports rocker switches (on/off) - which means dimming is not possible through a switch. Is that true or just shitty aliexpress store pages?

**Comment by Krolik1988** [comment]
> 
> 
> @Krolik1988 a little bit off-topic but I've got a quick question about the device. On many product pages it says it only supports rocker switches (on/off) - which means dimming is not possible through a switch. Is that true or just shitty aliexpress store pages?

Hi Ci, This one is dimmer! But you can finde same just for switch on/off. I Use it to control exhaust fan in bath. At evenings it works on 80% at day time @100%
