### ISSUE TITLE
Support for Centralite 3310-S Humidity/Temperature sensor

### ISSUE THREAD

**Issue by DJFliX** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#425]
**Device description**
A simple humidity/temperature sensor by Centralite. Data seems to be correct. 

**Zigbee2mqtt page**
There is no page on this sensor yet

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"dateCode":"����������������","description":"Temperature and humidity sensor","friendly_name":"0x000d6f0003267c48","hardwareVersion":1,"ieeeAddr":"0x000d6f0003267c48","lastSeen":1601583708040,"manufacturerID":49887,"manufacturerName":"CentraLite","model":"3310-S","modelID":"3310-S","networkAddress":16639,"powerSource":"Battery","type":"EndDevice","vendor":"SmartThings"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
Zigbee2MQTT:info  2020-10-01 22:01:50: MQTT publish: topic 'zigbee2mqtt/0x000d6f0003267c48', payload '{"humidity":60.93,"linkquality":84,"temperature":25.43}'
Zigbee2MQTT:info  2020-10-01 22:31:47: MQTT publish: topic 'zigbee2mqtt/0x000d6f0003267c48', payload '{"humidity":61.54,"linkquality":81,"temperature":24.42'
```

**MQTT state change commands**
I honestly have no clue what this means

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458.
Reopen this issue in case of any issues.
