### ISSUE TITLE
Very large device in Domotics named api_transport

### ISSUE THREAD

**Issue by jjnh** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#427]
Hi,

I just upgraded to the last version of the zigbee2mqtt plugin. It look great and management in Domoticz is now much better. Great work.

After the upgrade I run into the issue that there is a very big device in the Domiticz device list named api_transport. This contains such a big string that the overview is very hard to use.

![Screenshot 2020-10-03 at 15 40 21](https://user-images.githubusercontent.com/3064265/94993093-d4494a80-058e-11eb-945f-ca5ec3490db4.png)

What can I do about this?

Kr.
John

**Comment by stas-demydiuk** [comment]
This device is required for UI page to work properly
