### ISSUE TITLE
Database error when opening custom plugin Window

### ISSUE THREAD

**Issue by jjnh** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#428]
**Issue description**
After installing the latest and greatest (realy great work!!) zigbee2mqtt plugin, I run into an issue when opening the Custom\Zigbee2mqtt window.

It throws me an error:
![Screenshot 2020-10-03 at 15 43 34](https://user-images.githubusercontent.com/3064265/94993149-3ace6880-058f-11eb-9acf-ed1fcfe81aee.png)

DataTables warning: table id=zigbee2mqtt-devices - Requested unknown parameter 'friendly_name' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

Clicking OK will close the window and everything seems to work fine, but the error keeps coming back.

**Additional information**
Zigbee2MQTT version: 1.5.1
Python version: 3.4/3.5/3.7 installed
Domoticz version: 2020.1
Plugin version: 0.2.0

**Logs**
Nothing showing in the logs

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.

**Comment by jjnh** [comment]
Today upgraded everything and now the error is indeed resolved.
