### ISSUE TITLE
Support for Domoticz's Log

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#43]
I don't see any events from zigbee2mqtt plugin in Domoticz log. So need to have another tool or open Linux console to see the output from Zigbee2mqtt. It would be useful to get zigbee2mqtt events in Domoticz itself to see relationships between different events in the system.

**Comment by stas-demydiuk** [comment]
@loglux What events do you mean, did you try to enable "Debug" mode in the plugin?
