### ISSUE TITLE
QBKG26LM not supported by the plugin

### ISSUE THREAD

**Issue by roykaandorp** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#432]
**Device description**
Put general device information here

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/QBKG26LM.html

**MQTT message with device information**
"ieeeAddr":"0x04cf8cdf3c7abed7","lastSeen":1602096041324,"manufacturerID":4447,"manufacturerName":"LUMI","model":"QBKG26LM","modelID":"lumi.switch.n3acn3","networkAddress":24606,"powerSource":"Mains (single phase)","type":"Router","vendor":"Xiaomi"}],"type":"devices"}'

When I press the left button
topic 'zigbee2mqtt/0x04cf8cdf3c7abed7', payload '{"linkquality":15,"state_left":"ON","state_right":"ON"}'
When I press the middle or right button:
topic 'zigbee2mqtt/0x04cf8cdf3c7abed7', payload '{"linkquality":10,"state_center":"ON","state_left":"OFF","state_right":"ON"}'

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
