### ISSUE TITLE
show current version in GUI

### ISSUE THREAD

**Issue by bartplessers** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#433]
Hi,

I'm very happy with this plugin.
On a similar plugin (IKEA Tradfri Plugin), I noticed that the current version is displayed in "type" in the GUI.

It would be nice to have this functionality also on domoticz-zigbee2mqtt-plugin (see attachment)

Kind regards,
Bart Plessers
![2020-10-09_23-12-50](https://user-images.githubusercontent.com/10470708/95632100-33262c80-0a85-11eb-8278-8178799be463.png)

**Comment by stas-demydiuk** [comment]
Unfortunately, zigbee2mqtt doesn't provide such information
