### ISSUE TITLE
CentraLite 3400

### ISSUE THREAD

**Issue by niekveldhuizen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#436]
**Device description**
Security Keypad

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/3400-D.html

**MQTT message with device information**
info  2020-10-10 10:05:59: Device '0x000d6f000c45684d' joined
info  2020-10-10 10:05:59: Starting interview of '0x000d6f000c45684d'
info  2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000d6f000c45684d"},"type":"device_connected"}'
info  2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6f000c45684d"},"type":"pairing"}'
info  2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x000d6f000c45684d"},"type":"device_announced"}'
info  2020-10-10 10:06:33: Successfully interviewed '0x000d6f000c45684d', device has successfully been paired
info  2020-10-10 10:06:33: Device '0x000d6f000c45684d' is supported, identified as: CentraLite 3-Series security keypad (3400)

**MQTT messages from device**
info  2020-10-10 10:06:46: MQTT publish: topic 'zigbee2mqtt/0x000d6f000c45684d', payload '{"linkquality":47,"temperature":17.37}'
info  2020-10-10 10:09:45: MQTT publish: topic 'zigbee2mqtt/0x000d6f000c45684d', payload '{"action":"disarm","action_code":"0000","action_transaction":10,"action_zone":23,"linkquality":47,"temperature":17.37}'
 
**MQTT state change commands**
?

It should be able to arm-away/disarm/arm-home

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.

**Comment by niekveldhuizen** [comment]
Hi,

I updated to the v3 version. Got some extra functions on my power meter so that is great.

Unfortunately my keypad does not function.. it still send an payload but domoticz does not respond
