### ISSUE TITLE
E1743 Tradfri ON/OFF switch off sync with Group

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#439]
Hi,

In Zigbee2MQTT, I have created a group "Stopcontacten" and added a device "Stopcontact_1" (E1603/E1702 Tradfri control outlet). Then I did bind succesfully a small remote E1743 Tradfri ON/OFF switch to this group.

In Domoticz I have added the Group ON/OFF switch and the Remote On/Off switch as devices.
I also created a script to sync the remote ON/OFF Switch with the Group ON/OFF Switch:

```
return 
{
    on = { devices = {'Stopcontacten'}},

    execute = function(dz)
        local Switch = dz.devices('Small_Remote_1')   

        if dz.devices('Stopcontacten').state == 'On' then 
            Switch.switchOn().checkFirst()
        elseif dz.devices('Stopcontacten').state == 'Off' then
            Switch.switchOff().checkFirst()
        end
        dz.log('Device ' .. Switch.name .. ' state: ' .. Switch.state, dz.LOG_INFO)
        dz.log('Device ' .. dz.devices('Stopcontacten').name .. ' state: ' .. dz.devices('Stopcontacten').state, dz.LOG_INFO)
        dz.notify(dz.devices('Stopcontacten').name,'Cat fence is: ' .. dz.devices('Stopcontacten').state, dz.PRIORITY_NORMAL,'','',dz.NSS_TELEGRAM)
    end
}
```

But if I turn ON or OFF the Group Switch in domoticz (not with the remote), the remote gets off sync with the group according to the notification in the log (and also in zigbee2mqtt).
Although the script sets the state of the remote ON/OFF Switch button in sync with the group ON/OFF Switch button.

It seems (pretty much sure) that the Remote Switch Device, although it is Set to ON/OFF in Domoticz, doesn't report it's status to zigbee2mqtt?

**Comment by heggink** [comment]
Why do you use a script to sync the group and the switch? I had some issues to get lamps to sync but adding "report: true" to the advanced section of configuration. yaml ensured that all devices and groups are updated with the switch...
re the switch: did you update Z2M (and re-incude)?

**Comment by Anjerlaan** [comment]
Ah okay, that is what koenkk meant with "report true"
I tried this, but I thought that I had to turn it off again after the sync in Z2M was equal.
I will turn it one again

**Comment by heggink** [comment]
If you look at the z2m logs when you start it up, you can see that it actually configures the nodes to actively report changes. If you take it out and restart z2m, the opposite probably happens and devices won't report anymore do you need to keep that setting.


Herman Eggink

________________________________

**Comment by Anjerlaan** [comment]
Thanx, i have turned it on again and re-configured the remote. Sync script is not needed anymore.
