### ISSUE TITLE
Proposal for a new branch to mitigate the 255 devices limit

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#440]
Sorry this is rather long. TLDR: please consider offering an alternative branch which creates fewer Domoticz devices for each physical device.

I and others have problems caused by reaching the limit of devices which a Domoticz plugin can create.

There was a discussion earlier in the year about this and the feeling was that quite a bit of work would be needed to raise the limit - either to Domoticz's plugin framework or to the plugin itself.

In my view, the problem, as it affects the Zigbee2MQTT plugin specifically, isn't so much the 255 device limit, but rather it's the way in which the plugin creates multiple Domoticz devices for each physical one. For my needs, many of these of superfluous.

Why do I say "superfluous"? 

Many of my Zigbee devices are battery powered. As is normal in Domoticz each physical device already has a battery-level attribute stored as part of the "main" device.

So my feeling is: why would I want to also have a separate device just to store basically a duplicate of the same information? Only, it's worse than that because the plugin actually creates *two* extra battery-level devices - as well as the _btperc devices it also creates _cell devices to store the battery voltages.

Personally I can manage without them - or at least I can happily do without them when the alternative is not being able to add further devices to my network. 

The changes are trivial and I've been running with them for some time now. Basically I just remove the two "self.devices.append" lines in adapter_with_battery. Following the same reasoning I have removed the _signal device in base_adapter.

The nice thing about doing this is it doesn't disrupt an existing setup. Commenting-out the extra devices in this way just means that if I then delete the ones I don't want - in the usual way using the Domoticz Devices screen - the plugin doesn't recreate them. So, provided people understood what the new branch was for, it wouldn't be a breaking change for people who decided to switch.

To be clear: this is a great plugin and I don't mind at all continuing to "git stash" and "git stash pop" my changes each time I update it, but I think it would be better for others if there was a separate branch available.

What do other people think?

**Comment by heggink** [comment]
It would be great if the battery data could be pulled into the main device itself indeed.

**Comment by stas-demydiuk** [comment]
Done, could you please check the behavior in [new plugin version](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/tree/v3.0)

**Comment by hughb8on** [comment]
Thank you for doing this.
I have tested the behaviour of both of the new options and confirm the extra devices are created as before if they are set to 'Yes', and neither created, nor recreated after deletion, if they are set to 'No'.
So, perfect, thanks.
I have a test system for Domoticz and the plugin, but not for Zigbee2MQTT.io; so as I am not ready to move to the dev branch of the latter, I was testing v3.0 with Zigbee2MQTT v 1.16.1

**Comment by heggink** [comment]
Would it be possible to add the battery data to the main device itself? That's a pretty common approach (e.g. zwave).

**Comment by hughb8on** [comment]
Both signal quality and battery level are already present in the main device. 
That is why the extra devices created by the plugin up to now are arguably superfluous.

**Comment by heggink** [comment]
Missed that completely. That's great!


Herman Eggink

________________________________

**Comment by schurgan** [comment]
Can you make the option for all devices that you determine what you activate and what not?

**Comment by stas-demydiuk** [comment]
@schurgan do you have any ideas on how such config option could look like?

**Comment by schurgan** [comment]
I haven't tested the new option yet, but as I understand you can activate or deactivate the battery and signal quality by setting it to yes or no.  Can't you make the other subdevices so that you always have the main function active and deactivate the rest with "No" if necessary.

**Comment by stas-demydiuk** [comment]
The initial feature has been implemented, please use #325 for further discussion

**Comment by dobber81** [comment]
Would it be possible to add an exclude-file in the plugin directory? Where each line is a sub-device to be ignored?
0x00158d000104201f_cell for example. I know thisis how the plugin for deconz-domoticz does it. Devices in that file would never show up in domoticz and would leave room for other devices.

I'm sorry if this has been suggested before. I read through a few threads about this problem, but could not find anyone suggesteing this as a workaround.

Maybe the list of ignored sub-devices could even be accessed through a tab in "Custom"-"Zigbee2mqtt" alongside devices, groups and network map?
