### ISSUE TITLE
Support for TS0044

### ISSUE THREAD

**Issue by snieuwen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#441]
Comparable to the request for TS0042, I would like love to support the TS0044, which is a 4-button wireless switch. I guess both can be extended from the TS0041 (1-button).
This is the MQTT message that is published once I push button "left_top_single" (i.e. single press), you can imagine the messages by modifying left/right, top/bottom and single/double.
zigbee2mqtt/0xbc33acfffe28bd72 {"action":"left_top_single","battery":100,"linkquality":15,"voltage":3000}

**Comment by snieuwen** [comment]
Is the right forum to get help on this?

**Comment by Roeliooo** [comment]
First check if it is supported by zigbee2mqtt;
https://github.com/koenkk/zigbee2mqtt

**Comment by snieuwen** [comment]
Yes, it definitely is  - https://www.zigbee2mqtt.io/devices/TS0044.html
mqtt messages are flowing to Domoticz, but don't get recognized.

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
