### ISSUE TITLE
ikea KADRILJ blinds are included in domoticz zigbee2mqtt plugin?

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#443]
Dear friend,

I have seen in the devices that support their plugin zigbee2mqtt for domticz and the FYRTUR blind is included, but the KADRILJ blind is not included.

I am thinking of buying a KADRILJ blind. Do you know if it would also work directly with zigbee2mqtt without using the TRÅDFRI gateway? because I understand that the FYRTUR blind works directly with zigbe2mqtt without using TRADFRI. I'm right?
 
I am getting rid of all the gateways and I would not like to have one more 

Would you be kind enough to clarify these doubts for me before making the purchase of the blind and in the event that KADRILJ is not supported by zigbee2mqtt, could you include it in the plugin?  

Thank you very much, nobody knows how to answer these questions. 

A cordial greeting

Best regards

**Comment by pcurt** [comment]
Hi,
KADRILJ is already supported by the plugin. This is the same behavior as FYRTUR. 
I confirm that you don't need the TRADFRI gateway. You only need a zigbee2mqtt adapter:
https://www.zigbee2mqtt.io/getting_started/what_do_i_need.html

**Comment by kitopopo** [comment]
thanks,

Best regards
