### ISSUE TITLE
IKEA E1743 TRADFRI ON/OFF switch - When paring, Domoticz logs "Device doesn't have "model" attribute, skipped"

### ISSUE THREAD

**Issue by FoxConsult** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#444]
**Issue description**
When paring IKEA E1743 TRADFRI ON/OFF switch, Domoticz logs "Device doesn't have "model" attribute, skipped"
Device is added and works despite above message.

**Additional information**
Zigbee2MQTT version: 1.15.0-dev (commit #851aef3)
Python version:            3.7.3
Domoticz version:         V2020.2 (build 12496)
Plugin version:              v.1.15.0-dev (zStack12 20190608)

**Logs**
(Zigbee2MQTT) Received available devices list from bridge
(Zigbee2MQTT) Device 0xec1bbdfffe54564d (0xec1bbdfffe54564d) doesn't have "model" attribute, skipped
(Zigbee2MQTT) This is not the plugin issue, this is issue with your zigbee network

**Comment by stas-demydiuk** [comment]
Try to repair device until issue goes off
