### ISSUE TITLE
IKEA E1743 TRADFRI ON/OFF switch not reporting status to Domoticz when set to "legacy: false in configuration.yaml"

### ISSUE THREAD

**Issue by FoxConsult** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#445]
**Issue description**
When I add "legacy: false" to configuration.yaml as per https://www.zigbee2mqtt.io/devices/E1743.html, the status of the switch is no longer updated in Dozmicz.

When I delete "legacy: false" from configuration.yaml all works fine again.

**Additional information**
Zigbee2MQTT version: 1.15.0-dev (commit #851aef3)
Python version: 3.7.3
Domoticz version: V2020.2 (build 12496)
Plugin version: v.1.15.0-dev (zStack12 20190608)

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by Maik-100** [comment]
Yes, same behaviour for me.
So what is the advice:
-set default "legacy: true" or delete "legacy: false"    or
-set "legacy: false"  like described in https://www.zigbee2mqtt.io/devices/E1743.html

**Comment by heggink** [comment]
when I add  report: true in the advanced section of configuration.yaml, all my ikea devices report their status. I do not have legacy: in my config.

**Comment by FoxConsult** [comment]
Thank you [heggink](https://github.com/heggink), that solved my issue.
/Tommie
