### ISSUE TITLE
IKEA E1743 TRADFRI ON/OFF switch - Domoticz not showing battery level reported by device

### ISSUE THREAD

**Issue by FoxConsult** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#446]
**Issue description**
IKEA E1743 TRADFRI ON/OFF switch - Domoticz not showing battery level reported by device

**Additional information**
Zigbee2MQTT version: 1.15.0-dev (commit #851aef3)
Python version: 3.7.3
Domoticz version: V2020.2 (build 12496)
Plugin version: v.1.15.0-dev (zStack12 20190608)

**Logs**
MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe54564d', payload '{"battery":87,"linkquality":65,"update":{"state":"idle"},"update_available":false}'

**Comment by FoxConsult** [comment]
Fixed in Domoticz build 12497

**Comment by heggink** [comment]
What fix was applied to domoticz? I looked at the commits but could not find anything related to build 12497...
