### ISSUE TITLE
GUI Select USB port

### ISSUE THREAD

**Issue by Di-Ny** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#447]
Hi, Is it possible to integrate a dropdown list in the GUI, same style as the "Permit join" checkbox that goes into the "configuration.yaml" to modify the USB port ? And would it be useful to some of you ? 
In my case the CC2531 is sometimes allocated to /dev/ttyACM0 or ACM1.

**Comment by stas-demydiuk** [comment]
That wouldn't be possible as it is zigbee2mqtt configuration, not plugin one.
I wouldn't recommend to use syntax like `/dev/ttyACM0`, you can use `/dev/serial/by-id/....` instead
