### ISSUE TITLE
Tuya TS0115 "not supported"

### ISSUE THREAD

**Issue by longos** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#449]
**Issue description**
I paired Tuya TS0115 with my zigbee2mqtt, but in Domoticz log I get:

`2020-10-28 12:00:13.270 (Zigbee) This plugin does not support zigbee device with model "TS0115" yet
2020-10-28 12:00:13.270 (Zigbee) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md`

**Additional information**
Zigbee2MQTT version: v.1.15.0 (zStack12 20190608)
Domoticz version: 2020.2
Plugin version: 0.2.0

**Comment by stas-demydiuk** [comment]
Done. Could you please update plugin and check

**Comment by longos** [comment]
Device is called "TS0115" not TS0015.

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
