### ISSUE TITLE
Eurotronic spirit newest devices require change

### ISSUE THREAD

**Issue by heggink** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#452]
**Issue description**
Put general information here
The latest versions of the eurotronic spitir thermostats no longer allow current_heating_setpoint to be written and need to use occupied_heating_setpoint instead. This leads to an invalid_value error

see https://github.com/Koenkk/zigbee2mqtt/issues/4571

somplest chaneg is to change thermostat.py to use occupied_heating_setpoint instead of current for all thermostats as that seems to be a genenic approach that works with all thermostats. Alterantively, make the change in a spirit specific device adapter.

**Additional information**
Zigbee2MQTT version: latest
Python version: 3.7
Domoticz version: latest
Plugin version: latest

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
This is fixed in the latest plugin version
