### ISSUE TITLE
Unble to pair SONOFF SNZB-03 to Zigbee2mqtt

### ISSUE THREAD

**Issue by Rudi1952** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#454]
**Issue description**
I have a SONOFF SNZB-03 motion sensor, but i am not able to pair this product to zigbee2mqtt. I am using domoticz.
I hope that someone can help me with this, i tried this now for several times. Tried within 20 cm of CC2531, removed CC2531 from RPI, changed the battery, but all without any result.

I hope someone can help me wit this.

I already did a 'git pull' to get the newest release of zigbee2mqtt.
When i do "Allow new zigbee devices to join" on the custom page of Domoticz and i click om "Pair Device" i see that MS01 has joined, but unforuntely it is not paired correct. 

**Additional information**
Zigbee2MQTT version: 1.5.1
Python version:  2.7.16
Domoticz version: 2020.2
Plugin version: CC2531 20190608
**Logs**
11/3/2020, 5:52:12 PM - info: Zigbee: allowing new devices to join.
11/3/2020, 5:52:12 PM - info: Zigbee: allowing new devices to join.
11/3/2020, 5:52:12 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"ac3b924","coordinator":20190608,"log_level":"info","permit_join":true}'
11/3/2020, 5:52:12 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"ac3b924","coordinator":20190608,"log_level":"info","permit_join":true}'
11/3/2020, 5:52:57 PM - info: New device 'MS01' with address 0x00124b001c4b6ba5 connected!
11/3/2020, 5:52:57 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00124b001c4b6ba5","meta":{"modelID":"MS01"}}'
11/3/2020, 5:52:57 PM - warn: Device with modelID 'MS01' is not supported.
11/3/2020, 5:52:57 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Checking the files in /opt/zigbee2mqtt/data
configuration.yaml:
  '0x00124b001c4b6ba5':
    friendly_name: '0x00124b001c4b6ba5'
    retain: false

database.db
{"id":14,"type":"EndDevice","ieeeAddr":"0x00124b001c4b6ba5","nwkAddr":41035,"manufId":0,"modelId":"MS01","epList":[1],"status":"online","joinTime":1604422376,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"_id":"uQgxUAvHszm9DLKs"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00124b001c4b6ba5","nwkAddr":41035,"manufId":0,"manufName":"eWeLink","powerSource":"Battery","modelId":"MS01","epList":[1],"status":"online","joinTime":1604422376,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"_id":"uQgxUAvHszm9DLKs"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00124b001c4b6ba5","nwkAddr":41035,"manufId":0,"manufName":"eWeLink","powerSource":"Battery","modelId":"MS01","epList":[1],"zclVersion":1,"appVersion":3,"hwVersion":1,"status":"online","joinTime":1604422376,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{}}},"dateCode":"20191107","_id":"uQgxUAvHszm9DLKs"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00124b001c4b6ba5","nwkAddr":41035,"manufId":0,"manufName":"eWeLink","powerSource":"Battery","modelId":"MS01","epList":[1],"zclVersion":1,"appVersion":3,"hwVersion":1,"status":"online","joinTime":1604422376,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":3},"attrs":{}},"ssIasZone":{"dir":{"value":1},"attrs":{}}}}},"dateCode":"20191107","_id":"uQgxUAvHszm9DLKs"}

state.json
There is no data for this product. All other products are mentioned.

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458.
Reopen this issue in case of any issues.

**Comment by Rudi1952** [comment]
I tried following:
pi@raspberrypi:~/domoticz/plugins/zigbee2mqtt $ git fetch
pi@raspberrypi:~/domoticz/plugins/zigbee2mqtt $ git checkout v3.0
Already on 'v3.0'
Your branch is up to date with 'origin/v3.0'.

I tried to rejoin the product with the same result. No solution until now
