### ISSUE TITLE
TuYa TS0121_plug

### ISSUE THREAD

**Issue by Jelke87** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#455]
**Device description**
TuYa TS0121_plug

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS0121_plug.html

**MQTT message with device information**
,{"dateCode":"","description":"10A UK or 16A EU smart plug","friendly_name":"Stopcontact","hardwareVersion":1,"ieeeAddr":"0x842e14fffe1395bd","lastSeen":1604583352096,"manufacturerID":4098,"manufacturerName":"_TZ3000_g5xawfcq","model":"TS0121_plug","modelID":"TS0121","networkAddress":58772,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"},

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
Zigbee2MQTT:info  2020-11-05 14:57:34: MQTT publish: topic 'zigbee2mqtt/Stopcontact', payload '{"current":0,"energy":1.54,"linkquality":63,"power":0,"state":"ON","voltage":239}'

Zigbee2MQTT:info  2020-11-05 14:57:44: MQTT publish: topic 'zigbee2mqtt/Stopcontact', payload '{"current":0,"energy":1.54,"linkquality":63,"power":0,"state":"ON","voltage":239}'

Zigbee2MQTT:info  2020-11-05 14:57:54: MQTT publish: topic 'zigbee2mqtt/Stopcontact', payload '{"current":0.07,"energy":1.54,"linkquality":63,"power":0,"state":"ON","voltage":239}'
```

**MQTT state change commands**
Zigbee2MQTT:info  2020-11-05 15:01:53: MQTT publish: topic 'zigbee2mqtt/Garage_Stopcontact', payload '{"current":0,"energy":1.54,"linkquality":63,"power":0,"state":"OFF","voltage":239}'

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.
