### ISSUE TITLE
LEGRAND - Netatmo support ?

### ISSUE THREAD

**Issue by Docteur-No** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#456]
Hi,

Legrand Celiane / Netatmo is widely spread in Europ but these components are not accessible by the Domoticz Zigbee2MQTT plugin. However these products are already supported by zigbee2mqtt.io.

Legrand (Netatmo) very useful products:
067776, 067775, 064888, and also 067773, 067774, 067771

https://www.zigbee2mqtt.io/devices/067776.html
https://www.zigbee2mqtt.io/devices/067775.html
https://www.zigbee2mqtt.io/devices/064888.html
and also:
https://www.zigbee2mqtt.io/devices/067773.html
https://www.zigbee2mqtt.io/devices/067774.html
https://www.zigbee2mqtt.io/devices/067771.html

Can we hope using these products with the plugin in a near future ?

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458

**Comment by Docteur-No** [comment]
I modified my configuration. I use Dev version of zigbee2mqtt.io, I use new_API, I use your plugin V3.0 
But no change ?!?!
If I am able to see LEGRAND devices (067775 for example) in zigbee2mqtt, I am always unable to pair them and so they are invisible in Domoticz devices. ?!?!
