### ISSUE TITLE
Nue / 3A HGZB-42-UK / HGZB-41 / HGZB-41-UK

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#461]
Stas can you please include the switch in the plugin.
No subdevices are created in Domoticz.
PS. with v3 it also did not recognize.

![sshot-3](https://user-images.githubusercontent.com/32480002/98482043-ec039680-21fe-11eb-8115-8907c2b4e99c.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/98482044-ec9c2d00-21fe-11eb-8644-97e5145d7cea.jpg)

(z2m) This plugin does not support zigbee device with model "HGZB-42-UK / HGZB-41 / HGZB-41-UK" yet
2020-11-08 21:13:13.052 (z2m) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

`{"id":34,"type":"Router","ieeeAddr":"0x00158d0002926e25","nwkAddr":2646,"manufId":4478,"manufName":"FeiBit","powerSource":"Mains (single phase)","modelId":"FNB56-ZSW01LX2.0","epList":[11],"endpoints":{"11":{"profId":49246,"epId":11,"devId":0,"inClusterList":[0,4,3,6,5,4096,8],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"FNB56-ZSW01LX2.0","manufacturerName":"FeiBit","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20180808","swBuildId":"1000-0001"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20180808","swBuildId":"1000-0001","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1604862203306}
`

**Comment by stas-demydiuk** [comment]
Could you please provide Domoticz log from plugin v.3
