### ISSUE TITLE
Zigbee EcoDim E27 G125 300lm Smokey Glass

### ISSUE THREAD

**Issue by Melissen71** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#462]
**Device description**
Zigbee EcoDim E27 G125 300lm Smokey Glass

**Zigbee2mqtt page**
nnb

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
({"ieeeAddr":"0x00158d0001273925","type":"Router","networkAddress":2813,"model":"50064","vendor":"Paulmann","description":"SmartHome led spot","friendly_name":"0x00158d0001273925","manufacturerID":4137,"manufacturerName":"ZigBee/CCT","powerSource":"Mains (single phase)","modelID":"CCT Light","hardwareVersion":21,"softwareBuildID":"00.00.01","dateCode":"20200505","lastSeen":1605033647909}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
nnb
```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

I only got this line when putting the power on the bulb. Because I don't have any other bridge (or something) I can't turn bulb on/off, dim low/high or change color temp...

**Comment by stas-demydiuk** [comment]
Now the light feature should be properly supported by the latest plugin version. Please post here #548 in case of any issues
