### ISSUE TITLE
BlitzWolf BW-IS3

### ISSUE THREAD

**Issue by artipa** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#463]
**Device description**
Rechargeable Zigbee PIR motion sensor

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/BW-IS3.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
dateCode":"20180727","description":"Rechargeable Zigbee PIR motion sensor","friendly_name":"PIR","hardwareVersion":1,"ieeeAddr":"0xec1bbdfffe302e49","lastSeen":1605196074842,"manufacturerID":0,"manufacturerName":"_TYST11_i5j6ifxj","model":"BW-IS3","modelID":"5j6ifxj\u0000","networkAddress":24692,"powerSource":"Battery","type":"EndDevice","vendor":"BlitzWolf"
```

**MQTT messages from device**
Zigbee2MQTT:info  2020-11-12 16:46:38: MQTT publish: topic 'zigbee2mqtt/PIR', payload '{"linkquality":68,"occupancy":true}'

Zigbee2MQTT:debug 2020-11-12 16:46:46: Received Zigbee message from 'PIR', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":3,"fn":0,"status":0,"transid":103}' from endpoint 1 with groupID null

**Comment by stas-demydiuk** [comment]
The device is supported by the latest plugin and zigbee2mqtt version. Please reopen the ticket in case of any issues.
