### ISSUE TITLE
TuYa TS0115

### ISSUE THREAD

**Issue by artipa** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#464]
**Device description**
Multiprise with 4 AC outlets and 2 USB super charging ports (10A or 16A)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS0115.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
"dateCode":"","description":"Multiprise with 4 AC outlets and 2 USB super charging ports (10A or 16A)","friendly_name":"listwa","hardwareVersion":1,"ieeeAddr":"0x842e14fffefcdc44","lastSeen":1605196465607,"manufacturerID":4098,"manufacturerName":"_TYZB01_vkwryfdr","model":"TS0115","modelID":"TS0115","networkAddress":5536,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"}],"type":"devices"
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
MQTT publish: topic 'zigbee2mqtt/listwa', payload '{"linkquality":69,"state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"OFF","state_l5":"OFF"}'

Zigbee2MQTT:debug 2020-11-12 16:54:24: Received Zigbee message from 'listwa', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 3 with groupID null
```

**MQTT state change commands**
zigbee2mqtt/listwa', payload '{"linkquality":69,"state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'

zigbee2mqtt/listwa', payload '{"linkquality":70,"state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"OFF"}

**Comment by stas-demydiuk** [comment]
The device is supported by the latest plugin and zigbee2mqtt version. Please reopen the ticket in case of any issues
