### ISSUE TITLE
Centralite 3400

### ISSUE THREAD

**Issue by niekveldhuizen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#465]
#436

Device description
Security Keypad

Zigbee2mqtt page
https://www.zigbee2mqtt.io/devices/3400-D.html

MQTT message with device information
info 2020-10-10 10:05:59: Device '0x000d6f000c45684d' joined
info 2020-10-10 10:05:59: Starting interview of '0x000d6f000c45684d'
info 2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000d6f000c45684d"},"type":"device_connected"}'
info 2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6f000c45684d"},"type":"pairing"}'
info 2020-10-10 10:05:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x000d6f000c45684d"},"type":"device_announced"}'
info 2020-10-10 10:06:33: Successfully interviewed '0x000d6f000c45684d', device has successfully been paired
info 2020-10-10 10:06:33: Device '0x000d6f000c45684d' is supported, identified as: CentraLite 3-Series security keypad (3400)

MQTT messages from device
info 2020-10-10 10:06:46: MQTT publish: topic 'zigbee2mqtt/0x000d6f000c45684d', payload '{"linkquality":47,"temperature":17.37}'
info 2020-10-10 10:09:45: MQTT publish: topic 'zigbee2mqtt/0x000d6f000c45684d', payload '{"action":"disarm","action_code":"0000","action_transaction":10,"action_zone":23,"linkquality":47,"temperature":17.37}'

MQTT state change commands
?

It should be able to arm-away/disarm/arm-home with PIN. I upgraded to the next version of the plugin, did not do the trick.

**Comment by stas-demydiuk** [comment]
Should work fine with the latest plugin version (using Universal Adapter, see #458 ). Could you please upgrade and check?

**Comment by niekveldhuizen** [comment]
I upgraded but stil not activating the alarm:

Already deleted the devices and made it rejoin

info  2020-12-16 15:14:31: MQTT publish: topic 'zigbee2mqtt/0x000d6f000c45684d', payload '{"action":"disarm","action_code":"0000","action_transaction":126,"action_zone":23,"linkquality":86,"temperature":20.47,"voltage":2800}'
info  2020-12-16 15:14:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x000d6f000c45684d"},"type":"device_announced"}'

And in Domoticz it does not show "devices" like the tamper switch.

**Comment by stas-demydiuk** [comment]
Do you see any issues in Domoticz log?
