### ISSUE TITLE
ptvo diy switch with CO2 sensor  Senseair S8

### ISSUE THREAD

**Issue by martcs** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#469]
Hi, 
how hard is add support to domoticz plugin, for diy ptvo switch-end device with  Senseair S8 CO2 sensor?
zigbee2mqtt recognize sensor, and send data trought mqtt. 
after connecting domoticz show 5 switch and text sensor, as described in your manual for this type of ptvo device.
just i no idea how add  Senseair S8.

https://ptvo.info/zigbee-configurable-firmware-features/

**MQTT messages from device**
Received Zigbee message from '0x00124b00094a55ae', type 'attributeReport', cluster 'genAnalogInput', data '{"description":"ppm","presentValue":530}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-13 23:34:06: MQTT publish: topic 'z2m/0x00124b00094a55ae', payload '{"l1":530,"linkquality":5,"quality":530}'
Zigbee2MQTT:debug 2020-11-13 23:34:10: Received Zigbee message from '0x00124b00094a55ae', type 'attributeReport', cluster 'genMultistateValue', data '{"stateText":{"data":[254,132,2,242,241],"type":"Buffer"}}' from endpoint 8 with groupID 0

**Comment by stas-demydiuk** [comment]
Could you please update the plugin to the latest version from the master branch and check if your device is properly supported?
