### ISSUE TITLE
Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#47]
This device produces 6 devices in Domoticz.
1. The device subtype 'Pressure' is wrong and should be 'Barometer'
2. There are a 'Temp' and 'Humidity' device and even an total combined device with 'Baro'. It would be nice if the is also a combined device 'Temp/Humidity'

**Comment by stas-demydiuk** [comment]
Should be available with latest master branch
