### ISSUE TITLE
TS130F Zemismart (Lonsonho) Curtain / Blind switch

### ISSUE THREAD

**Issue by Voppis** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#473]
**Device description**
Currently this device is already supported by zigbee2mqtt and I found a workaround to integrate it temporarily into domoticz by using a dummy selector switch with a script that send commands to the switch via mosquitto_pub.

Links to the switch: https://www.zemismart.com/products/zigbee-eu-curtain-wall-light-switch-compatible-with-smartthing-hub-echo-plus-app-phone-voice-control
https://es.aliexpress.com/item/4001190275372.html?spm=a2g0s.9042311.0.0.56d863c0iyL2vS

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS130F.html

**MQTT message with device information**
  '0x842e14fffe9a55a2':
    friendly_name: Living_Room_Sunblind_Switch

**MQTT messages from device**
info  2020-11-20 15:16:20: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":84,"moving":"UP","position":56}'
info  2020-11-20 15:16:23: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":89,"moving":"STOP","position":50}'
info  2020-11-20 15:16:44: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":84,"moving":"STOP","position":25}'
info  2020-11-20 15:16:44: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":86,"moving":"UP","position":50}'
info  2020-11-20 15:16:54: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":81,"moving":"STOP","position":25}'
info  2020-11-20 15:17:00: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":78,"moving":"STOP","position":0}'
info  2020-11-20 15:17:00: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":78,"moving":"UP","position":25}'
info  2020-11-20 15:17:11: MQTT publish: topic 'zigbee2mqtt/Living_Room_Sunblind_Switch', payload '{"calibration":"OFF","linkquality":86,"moving":"STOP","position":0}'

**MQTT state change commands**
Open: mosquitto_pub -m '{"position":100}' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set'
Close: mosquitto_pub -m '{"position":0}' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set'
Open on 25%: mosquitto_pub -m '{"position":25}' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set'
Open on 50%e: mosquitto_pub -m '{"position":50}' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set'
Stop: mosquitto_pub -m 'stop' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set'

For calibration of the switch I use next steps:
1) Open curtains completly
2) Send calibration command to the switch: mosquitto_pub -d -m 'on' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'
3) Press on close button on the switch, wait until curtains are fully closed and press pause
4) mosquitto_pub -d -m 'off' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'

**Comment by luismalddonado** [comment]
Pull request created for this issue:
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/pull/485

**Comment by Voppis** [comment]
Thank you very much! It works!

**Comment by woodchuck84** [comment]
> For calibration of the switch I use next steps:
> 
> 1. Open curtains completly
> 2. Send calibration command to the switch: mosquitto_pub -d -m 'on' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'
> 3. Press on close button on the switch, wait until curtains are fully closed and press pause
> 4. mosquitto_pub -d -m 'off' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'

Tried that on zigbee2mqtt for Lonsonho Curtain Switch but in the zigbee2mqtt log I get this: No converter available for 'calibration' (ON).
What did I mess up?

**Comment by Voppis** [comment]
> > For calibration of the switch I use next steps:
> > 
> > 1. Open curtains completly
> > 2. Send calibration command to the switch: mosquitto_pub -d -m 'on' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'
> > 3. Press on close button on the switch, wait until curtains are fully closed and press pause
> > 4. mosquitto_pub -d -m 'off' -t 'zigbee2mqtt/Living_Room_Sunblind_Switch/set/calibration'
> 
> Tried that on zigbee2mqtt for Lonsonho Curtain Switch but in the zigbee2mqtt log I get this: No converter available for 'calibration' (ON).
> What did I mess up?

Did you do update for zigbee2mqtt? This switch was added recently in the zigbee2mqtt app.
Check in the file: /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices.js  you should have something like this:
` 1462         zigbeeModel: ['TS130F'],
 1463         model: 'TS130F',
 1464         vendor: 'TuYa',
 1465         description: 'Curtain/blind switch',
 1466         supports: 'open, close, stop, position',
 1467         fromZigbee: [fz.cover_position_tilt, fz.tuya_backlight_mode, fz.tuya_cover_options],
 1468         toZigbee: [tz.cover_state, tz.cover_position_tilt, tz.tuya_cover_calibration, tz.tuya_cover_reversal, tz.tuya_backlight_mode],
 1469         whiteLabel: [
 1470             {vendor: 'LoraTap', model: 'SC400'},
 1471         ],
 1472         exposes: [
 1473             e.cover_position_tilt(),
 1474             exposes.enum('moving', 'r', ['UP', 'STOP', 'DOWN']),
 1475             exposes.binary('calibration', 'rw', 'ON', 'OFF'),
 1476             exposes.enum('backlight_mode', 'rw', ['LOW', 'MEDIUM', 'HIGH']),
 1477             exposes.binary('motor_reversal', 'rw', 'ON', 'OFF'),
 1478         ],
 1479     },
`

If you don't, try to update the zigbee2mqtt app (not this plugin, but the application that communicates with the zigbee stick)
