### ISSUE TITLE
Request for Support TS0044 scene switch

### ISSUE THREAD

**Issue by jeroenkl** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#478]
**Device description**
Zigbee Tuya TS0044 scene switch (4 button, with LED control light)

**Zigbee2mqtt page**
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/TS0044.md

**MQTT message with device information**
zigbee2mqtt/0x5c0272fffeaxxxxx : msg.payload : string[67]
"{"action":"1_single","battery":100,"linkquality":30,"voltage":3000}"
25-11-2020 17:50:25node: ts0044

{"action":"4_single","battery":100,"linkquality":57,"voltage":3000}

{"battery":100,"linkquality":63,"voltage":3000}

{"action":"3_double","battery":100,"linkquality":63,"voltage":3000}

{"action":"4_hold","battery":100,"linkquality":69,"voltage":3000}

**Comment by Polo753** [comment]
Hello, I also bought a TS0044 scene switch, would it be possible to integrate it into the plugin?

**Comment by jeroenkl** [comment]
TS0044.py:

`from adapters.adapter_with_battery import AdapterWithBattery
from devices.switch.selector_switch import SelectorSwitch


class TS0044(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.switch = SelectorSwitch(devices, 'action', 'action')
        self.switch.add_level('Off', None)
        self.switch.add_level('Sw_1 Click', '1_single')
        self.switch.add_level('Sw_1 Double Click', '1_double')
        self.switch.add_level('Sw_1 Hold', '1_hold')
        self.switch.add_level('Sw_2 Click', '2_single')
        self.switch.add_level('Sw_2 Double Click', '2_double')
        self.switch.add_level('Sw_2 Hold', '2_hold')
        self.switch.add_level('Sw_3 Click', '3_single')
        self.switch.add_level('Sw_3 Double Click', '3_double')
        self.switch.add_level('Sw_3 Hold', '3_hold')
        self.switch.add_level('Sw_4 Click', '4_single')
        self.switch.add_level('Sw_4 Double Click', '4_double')
        self.switch.add_level('Sw_4 Hold', '4_hold')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_BUTTONS)
        self.switch.disable_value_check_on_update()

        self.devices.append(self.switch)

    def handleCommand(self, alias, device, device_data, command, level, color):
        self.get_device_by_alias(alias).handle_command(device_data, command, level, color)`

[image](https://user-images.githubusercontent.com/37976568/100658071-c6296780-334e-11eb-966b-e095a8d5890c.png)

**Comment by Polo753** [comment]
Thank ! 
A little more information please
Create file TS0044.py  in /home/pi/domoticz/plugins/zigbee2mqtt/devices/switch ?

**Comment by jeroenkl** [comment]
No, add the file TS0044.py in dir /home/pi/domoticz/igbee2mqtt/adapters/tuya

Also add TS0044 in file __init__.py (same dir as above):

- from adapters.tuya.TS0044 import TS0044
- 'TS0044': TS0044,                           # TuYa Wireless switch with 4 button TEST

**Comment by Polo753** [comment]
There must be a error

 2020-11-30 22:41:46.529 Error: (Zigbee2MQTT) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/zigbee2mqtt/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2020-11-30 22:41:46.529 Error: (Zibee2Mqtt) Module Import failed, exception: 'IndentationError'
2020-11-30 22:41:46.529 Error: (Zibee2Mqtt) Import detail: File: /home/pi/domoticz/plugins/zigbee2mqtt/adapters/tuya/TS0044.py, Line: 5, offset: 3
2020-11-30 22:41:46.529 Error: (Zibee2Mqtt) Error Line 'def init(self, devices):
2020-11-30 22:41:46.529 '

**Comment by jeroenkl** [comment]
Yes indeed I see the first part of the code is changed, anyway you fixed it.

**Comment by jeroenkl** [comment]
Ticket is closed but no changes in de code so no support for this device?
