### ISSUE TITLE
SmartHome Led Spot Paulmann 50064

### ISSUE THREAD

**Issue by LPCevaal** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#480]
**Device description**
https://nl.aliexpress.com/item/4000181324534.html?spm=a2g0s.9042311.0.0.32b84c4dixFYmg

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/50064.html; this device uses same model ID, but has completely different look

**MQTT message with device information**
{"dateCode":"20190509","description":"SmartHome led spot","friendly_name":"Schemerlamp","hardwareVersion":21,"ieeeAddr":"0x00158d00012f92e6","lastSeen":1606508945318,"manufacturerID":4137,"manufacturerName":"ZB/GMY-CCT","model":"50064","modelID":"CCT Light","networkAddress":27835,"powerSource":"Mains (single phase)","softwareBuildID":"00.00.01","type":"Router","vendor":"Paulmann"}

**MQTT messages from device**
I cannot find any messages

**MQTT state change commands**
I cannot find any state changes

After some searching, I found the following details on z2m.io in devices.js

zigbeeModel: ['CCT light'],
        model: '50064',
        vendor: 'Paulmann',
        description: 'SmartHome led spot',
        extend: generic.light_onoff_brightness_colortemp,

Does this mean that the device should be supported?

**Comment by jvanderzande** [comment]
I have bought a similar lamp from ecodim/bright with the same specs and simply added this line to the bottom of this list:
```
    # Paulmann
    '50045': DimmableBulbAdapter,       # Paulmann SmartHome Zigbee LED-stripe
    '50049': RGBAdapter,                # Paulmann SmartHome Yourled RGB Controller
    '50064': DimmableBulbAdapter,       # Paulmann SmartHome led CT lamp
```

**Comment by LPCevaal** [comment]
Thanks for the hint! I have added the new line, but this results in the following error message in the Domoticz log:

2020-12-20 10:33:06.792 Error: (Zigbee) SchemerlampTwo: can not process feature type "light"

I do see some new instances in the Zigbee2Mqtt plugin, but none of these interact with the light.

**Comment by LPCevaal** [comment]
Solved, I removed the light from Domoticz and subsequently repaired. This has done the trick and I am now able to interact with it. Thanks for your help!

**Comment by Melissen71** [comment]
Hi,

I got also a problem with this bulbs.

Adding this lines won't help, because Zigbee doesn't work anymore after this.
# Paulmann
    '50045': DimmableBulbAdapter,       # Paulmann SmartHome Zigbee LED-stripe
    '50049': RGBAdapter,                # Paulmann SmartHome Yourled RGB Controller
    '50064': DimmableCtBulbAdapter,       # Paulmann SmartHome led CT lamp

I think I'm missing the Paulmann-directory in the "ADAPTERS-directory".
I can see several maps, but no Paulmann-map

![screen dump](https://user-images.githubusercontent.com/74206325/107127129-4ff83280-68b4-11eb-80a8-47fc4a0f5eaa.png)

What am I doing wrong to get these bulbs to work....

Please help me step by step
