### ISSUE TITLE
Add Support for TS0505A RGB+CCT light controller

### ISSUE THREAD

**Issue by GerardJans** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#481]
**Device description**

TS0505A | RGB+CCT light controller
Light bulb from Silvercrest Lidl

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS0505A.html

**MQTT message with device information**
	{"dateCode":"","description":"RGB+CCT light controller","friendly_name":"0x842e14fffe2a3615","hardwareVersion":1,"ieeeAddr":"0x842e14fffe2a3615","lastSeen":1606561142422,"manufacturerID":4098,"manufacturerName":"_TZ3000_dbou1ap4","model":"TS0505A","modelID":"TS0505A","networkAddress":60502,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"},
	{"dateCode":"","description":"RGB+CCT light controller","friendly_name":"0x588e81fffed401ed","hardwareVersion":1,"ieeeAddr":"0x588e81fffed401ed","lastSeen":1606562112755,"manufacturerID":4098,"manufacturerName":"_TZ3000_dbou1ap4","model":"TS0505A","modelID":"TS0505A","networkAddress":3964,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"}

**MQTT messages from device**
No messages seen from device

**MQTT state change commands**
 Received MQTT message on 'zigbee2mqtt/0x588e81fffed401ed/set' with data '{"brightness": 100}'
 MQTT publish: topic 'zigbee2mqtt/0x588e81fffed401ed', payload '{"brightness":100,"color":{"x":0.476993298233858,"y":0.413675289942435},"color_temp":400,"linkquality":7,"state":"ON"}'

**Comment by ledfreak3d** [comment]
nice one was just about to add it to the list

**Comment by GerardJans** [comment]
I added the device to my local installation and works fine. I'm new to Github. I'm now looking into adding support for the TS1001 remote which is part of the starter pack.

**Comment by ledfreak3d** [comment]
> I added the device to my local installation and works fine. I'm new to Github. I'm now looking into adding support for the TS1001 remote which is part of the starter pack.

hey gerard hoe had je hem handmatig toegevoegd ?

**Comment by Akertree** [comment]
> 
> 
> > I added the device to my local installation and works fine. I'm new to Github. I'm now looking into adding support for the TS1001 remote which is part of the starter pack.
> 
> hey gerard hoe had je hem handmatig toegevoegd ?

Ja, daar ben ik ook benieuwd naar. Ik kan nergens een Pull Request zien waarin dit wordt toegevoegd namelijk.
Heb wel handmatig al de state kunnen zetten maar nog niet verder kunnen inrichten.

**Comment by Anjerlaan** [comment]
> hey gerard hoe had je hem handmatig toegevoegd ?

Here the same question, I have bought 2x LIDL Candle bulbs, also paired as TS0505A.

**Comment by Anjerlaan** [comment]
> **Device description**
> 
> TS0505A | RGB+CCT light controller
> Light bulb from Silvercrest Lidl
> 
> **Zigbee2mqtt page**
> https://www.zigbee2mqtt.io/devices/TS0505A.html
> 
> **MQTT message with device information**
> {"dateCode":"","description":"RGB+CCT light controller","friendly_name":"0x842e14fffe2a3615","hardwareVersion":1,"ieeeAddr":"0x842e14fffe2a3615","lastSeen":1606561142422,"manufacturerID":4098,"manufacturerName":"_TZ3000_dbou1ap4","model":"TS0505A","modelID":"TS0505A","networkAddress":60502,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"},
> {"dateCode":"","description":"RGB+CCT light controller","friendly_name":"0x588e81fffed401ed","hardwareVersion":1,"ieeeAddr":"0x588e81fffed401ed","lastSeen":1606562112755,"manufacturerID":4098,"manufacturerName":"_TZ3000_dbou1ap4","model":"TS0505A","modelID":"TS0505A","networkAddress":3964,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"}
> 
> **MQTT messages from device**
> No messages seen from device
> 
> **MQTT state change commands**
> Received MQTT message on 'zigbee2mqtt/0x588e81fffed401ed/set' with data '{"brightness": 100}'
> MQTT publish: topic 'zigbee2mqtt/0x588e81fffed401ed', payload '{"brightness":100,"color":{"x":0.476993298233858,"y":0.413675289942435},"color_temp":400,"linkquality":7,"state":"ON"}'

These Lidl bulbs have different model names but their hardware is equal to TS0505A
![image](https://user-images.githubusercontent.com/18295963/100917630-b1c4a680-34d7-11eb-8b31-dacf0fd2ec51.png)

Koenkk has made an entry in devices.js which distinguishes (only the E14, not yet the GU10 and E27) the bulb from TS0505A:
https://github.com/Koenkk/zigbee-herdsman-converters/commit/ea8bf9ba8866454dde46a3297efffc977d538602
Only he filled in Silvercrest as vendor but it is Livarno Lux (Lidl has other tuya products with vendor name Silvercrest, but not these bulbs. At least not according to the advertisement and manuals)
It is updated in the dev branch not yet in 1.16.2

So maybe for these devices the original model name should be used in the domoticz-zigbee2mqtt-plugin?
Although it cannot hurt to add TS0505A as well
I am going to reconfigure these devices in z2m

**Comment by Anjerlaan** [comment]
The Z2M team has decided that all Lidl smart home products which exists of 3 different vendor names get vendor name Lidl. A number of devices are recognized as existing Tuya models, but are now available under their own model name:

https://github.com/Koenkk/zigbee2mqtt/issues/5164

**Comment by goliath888** [comment]
If I can help, this is my db info for the GU10 no-RGB light

**Comment by dchwilk** [comment]
Is it normal that the colors are not nearly as bright as the white light?

**Comment by Akertree** [comment]
For the ones who still haven't any success. I did.
Follow these steps:

1. Go to /domoticz/plugins/zigbee2mqtt/adapters/tuya folder
2. Edit the file named '__init__.py' and change it to these content:
`from adapters.on_off_switch_adapter import OnOffSwitchAdapter
from adapters.generic.blind_adapter import BlindAdapter
from adapters.generic.plug import PlugAdapter
from adapters.generic.temp_hum_sensor import TemperatureHumiditySensorAdapter
from adapters.tuya.TS0002 import TS0002
from adapters.tuya.TS0012 import TS0012
from adapters.tuya.TS0013 import TS0013
from adapters.tuya.TS0015 import TS0015
from adapters.tuya.TS0041 import TS0041
from adapters.tuya.TS0601 import TS0601
from adapters.rgb_adapter import RGBAdapter


tuya_adapters = {
    'TS0121': OnOffSwitchAdapter,               # TuYa 10A UK or 16A EU smart plug
    'TS0121_plug': PlugAdapter,                 # TuYa 10A UK or 16A EU smart plug
    'TS0121_switch': OnOffSwitchAdapter,        # TuYa Smart light switch module (1 gang)
    'TS0201': TemperatureHumiditySensorAdapter, # TuYa Temperature & humidity sensor with display
    'TS0002': TS0002,                           # TuYa 2 gang switch
    'TS0011': OnOffSwitchAdapter,               # TuYa Smart light switch - 1 gang without neutral wire
    'TS0012': TS0012,                           # TuYa Smart light switch - 2 gang without neutral wire
    'TS0013': TS0013,                           # TuYa Smart light switch - 3 gang without neutral wire
    'TS0015': TS0015,                           # TuYa Multiprise with 4 AC outlets and 2 USB super charging ports (10A or 16A)
    'TS0041': TS0041,                           # TuYa Wireless switch with 1 button
    'TS0601_curtain': BlindAdapter,             # TuYa Curtain motor
    'TS0601_thermostat': TS0601,                # TuYa Radiator valve with thermostat
    'mcdj3aq': BlindAdapter,                    # TuYa Tubular motor
    'TS011F': OnOffSwitchAdapter,               # Silvercrest LIDL Tuya OnOffSwitchAdapter
    'TS0505A': RGBAdapter,                      # Silvercrest LIDL Tuya RGB light
}
`
I've added the On Off switch adapter and RGB light.
3. Save the file
4. Restart Domoticz

Both devices can be used now.
Do not forget, when updating the plugin after this, the changes will be gone. I will also add a pull request for these changes.

**Comment by stas-demydiuk** [comment]
Now the light feature should be properly supported by the latest plugin version. Please post here #548 in case of any issues
