### ISSUE TITLE
Add support for Silvercrest (LIDL) door sensor TY0203

### ISSUE THREAD

**Issue by bokse001** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#483]
**Device description**
Silvercrest (LIDL) doorsensor model HG06336
https://www.lidl-shop.nl/SILVERCREST-Deur-en-raamsensor-Zigbee-Smart-Home/p100306595

**Zigbee2mqtt page**
https://github.com/Koenkk/zigbee-herdsman-converters/issues/1824

**MQTT message with device information**
{"dateCode":"2019.12.12","description":"SilverCrest door & window contact sensor","friendly_name":"deur","hardwareVersion":1,"ieeeAddr":"0x842e14fffe61c4f1","lastSeen":1606675946921,"manufacturerID":4619,"manufacturerName":"_TZ1800_ejwkn2h2","model":"HG06336","modelID":"TY0203","networkAddress":19120,"powerSource":"Battery","type":"EndDevice","vendor":"Silvercrest"}]

**MQTT messages from device**
Zigbee2MQTT:info  2020-11-29 13:45:12: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe61c4f1', payload '{"battery":100,"battery_low":false,"contact":false,"linkquality":131,"tamper":false}'

---> I made it work by adding this in de adapters folder on my pi:
Files in domoticz plugin zigbee under adapters folder:

createa a Folder silvercrest:
i~/domoticz/plugins/zigbee2mqtt/adapters/silvercrest$ ls
__init__.py  __pycache__  sensor_arrival.py  sensor_door.py
:
~/domoticz/plugins/zigbee2mqtt/adapters/silvercrest$ cat __init__.py
from adapters.silvercrest.sensor_door import SilvercrestDoorSensor

silvercrest_adapters = {
    'HG06336': SilvercrestDoorSensor,    # Silvercrest door & window sensor
}

~/domoticz/plugins/zigbee2mqtt/adapters/silvercrest$ cat sensor_arrival.py
from adapters.adapter_with_battery import AdapterWithBattery
from devices.sensor.contact import ContactSensor

class SensorArrival(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(ContactSensor(devices, 'sensor', 'presence'))

:~/domoticz/plugins/zigbee2mqtt/adapters/silvercrest$ cat sensor_door.py
from adapters.adapter_with_battery import AdapterWithBattery
from devices.sensor.door_contact import DoorContactSensor

class SilvercrestDoorSensor(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(DoorContactSensor(devices, 'sensor', 'contact'))

--------------------------------

In adapters/__init__.py:

Add line:just under the samsung line
from adapters.silvercrest import silvercrest_adapters

At the end add line:
    **silvercrest_adapters,

**Comment by Electr1fying** [comment]
Already added a PR for this: #482

**Comment by stas-demydiuk** [comment]
Should work fine with the latest plugin version (using Universal Adapter, see #458 ). Could you please upgrade and check?

**Comment by luismalddonado** [comment]
Working perfectly for me!!! 

Thanks
