### ISSUE TITLE
Lidl light (TuYa TS0502A) support

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#487]
**Device description**
A ceiling light for Lidl with 3 LED light bulbs separately discovered as 3 times TS0502A

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS0502A.html
This a control from TuYa, but the device is is a light bulb.
https://www.lidl.nl/nl/p/smart-home/led-plafondlamp/p43250

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"dateCode":"","description":"Li
ght controller","friendly_name":"0x588e81fffec9d68d","hardwareVersion":1,"ieeeAddr":"0x588e81fffec9d68d","lastSeen":1606
747477810,"manufacturerID":4098,"manufacturerName":"_TZ3000_el5kt5im","model":"TS0502A","modelID":"TS0502A","networkAddr
ess":50347,"powerSource":"Mains (single phase)","type":"Router","vendor":"TuYa"}

```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
info  2020-11-30 15:49:11: MQTT publish: topic 'zigbee2mqtt/0x588e81fffec9d68d', payload '{"brightness":255,"last_seen":
"2020-11-30T15:49:11+01:00","linkquality":24}'
info  2020-11-30 15:49:15: MQTT publish: topic 'zigbee2mqtt/0x588e81fffec9d68d', payload '{"brightness":255,"last_seen":
"2020-11-30T15:49:15+01:00","linkquality":21,"state":"ON"}'

info  2020-11-30 15:52:54: MQTT publish: topic 'zigbee2mqtt/0x588e81fffec9d68d', payload '{"brightness":255,"color_temp"
:153.84615384615384,"last_seen":"2020-11-30T15:52:54+01:00","linkquality":3,"state":"ON"}'


```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by snieuwen** [comment]
I have bought this https://www.lidl.nl/nl/p/product-recommendation/3-led-inbouwspots/p43251 which contains exactly the same LED spot lights (3x) recognized as TS0502A). They are picked up perfectly by Zigbee2MQTT but the Domoticz bridge only detects 1 device per led light, the one that controls the "Effect", so there is now way to switch it on/off or set color only select an "effect".
![image](https://user-images.githubusercontent.com/16606339/101288954-8f919800-37f9-11eb-805c-fed7768e9f29.png)

**Comment by stas-demydiuk** [comment]
Guys, please post here exposed features for this device

**Comment by stas-demydiuk** [comment]
Now the light feature should be properly supported by the plugin. Please post here #548 in case of any issues
