### ISSUE TITLE
Legrand Netatmo wired shutter switch support

### ISSUE THREAD

**Issue by sly058** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#491]
**Device description**
Netatmo wired shutter switch ref 067776 (legrand).
My model is 067726 (white)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/067776.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
/
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
Zigbee2MQTT:info  2020-12-03 17:02:56: MQTT publish: topic 'zigbee2mqtt/volet baie', payload '{"action":"stopped","linkquality":7,"position":0}'

Zigbee2MQTT:info  2020-12-03 17:04:56: MQTT publish: topic 'zigbee2mqtt/volet baie', payload '{"linkquality":31,"position":100}'

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Please upgrade plugin and zigbee2mqtt to the latest version and post here what you have in the log

**Comment by sly058** [comment]
Thank for the response,
Log domoticz ou log zigbee2mqtt,

**Comment by sly058** [comment]
Hello,
log of domoticz:
2021-01-18 18:04:36.172 Error: (zigbee2mqtt) volet_baie: can not process feature type "cover"

**Comment by stas-demydiuk** [comment]
Could you please enable debug mode in the plugin settings and post the output with feature details?

**Comment by sly058** [comment]
Zigbee2MQTT:debug 2021-02-18 13:58:11: Received Zigbee message from 'volet_baie', type 'attributeReport', cluster 'genBinaryInput', data '{"presentValue":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-02-18 13:58:11: MQTT publish: topic 'zigbee2mqtt/volet_baie', payload '{"action":"moving","linkquality":21,"position":100}'
Zigbee2MQTT:debug 2021-02-18 13:58:16: Received Zigbee message from 'volet_baie', type 'attributeReport', cluster 'genBinaryInput', data '{"presentValue":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-02-18 13:58:16: MQTT publish: topic 'zigbee2mqtt/volet_baie', payload '{"action":"moving","linkquality":31,"position":100}'
Zigbee2MQTT:debug 2021-02-18 13:58:16: Received Zigbee message from 'volet_baie', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":50}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-02-18 13:58:16: MQTT publish: topic 'zigbee2mqtt/volet_baie', payload '{"linkquality":31,"position":50}'
Zigbee2MQTT:debug 2021-02-18 13:58:20: Received Zigbee message from 'volet_baie', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":50}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-02-18 13:58:20: MQTT publish: topic 'zigbee2mqtt/volet_baie', payload '{"linkquality":36,"position":50}'

**Comment by stas-demydiuk** [comment]
Do you still have the issue with the latest plugin version?

**Comment by sly058** [comment]
no, no change

**Comment by stas-demydiuk** [comment]
Now the device is supported by the current version of plugin
