### ISSUE TITLE
Please add DiyRuZ_AirSenese to Domoticz

### ISSUE THREAD

**Issue by yashka1973** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#493]
**Device description**
Put general device information here

**Zigbee2mqtt page**
Insert the device page link on zigbee2mqtt.io i.e. https://www.zigbee2mqtt.io/devices/DIYRuZ_AirSense.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x00124b002202892f","type":"EndDevice","model":"DIYRuZ_AirSense","friendly_name":"CO2_Small_room"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
2020-12-04 04:18:30.658 (cc2538) This plugin does not support zigbee device with model "DIYRuZ_AirSense" yet
2020-12-04 04:18:30.658 (cc2538) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Please update the plugin to the latest version and check (#458)

**Comment by yashka1973** [comment]
Updated, but nothing has changed. I deleted and added the device, and rebooted the system.

**Comment by yashka1973** [comment]
pi@raspberrypi:~/domoticz/plugins/zigbee2mqtt $ sudo git fetch
pi@raspberrypi:~/domoticz/plugins/zigbee2mqtt $ sudo git checkout v3.0
Уже на «v3.0»
Ваша ветка обновлена в соответствии с «origin/v3.0».

**Comment by stas-demydiuk** [comment]
v3.0 branch has been merged to master

**Comment by Creo2005** [comment]
v3.0 branch has been merged to master - where is it?
