### ISSUE TITLE
Tuya TS0601_dimmer

### ISSUE THREAD

**Issue by wilqp** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#495]
**Device description**
It's a Tuya smart dimmer switch EDM-1ZAA-EU (https://www.alibaba.com/product-detail/Earda-EU-Standard-Wall-Dimmer-Electric_1600092367445.html)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/TS0601_dimmer.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
Device successfully paired: {"description":"Zigbee smart dimmer","friendly_name":"Tuya","model":"TS0601_dimmer","supported":true,"vendor":"TuYa"}```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
Zigbee2MQTT:info  2020-12-07 22:06:01: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":139,"level":550,"linkquality":44,"state":"ON"}'
Zigbee2MQTT:info  2020-12-07 22:06:01: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":139,"level":550,"linkquality":39,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:05: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":139,"level":550,"linkquality":36,"state":"ON"}'
Zigbee2MQTT:info  2020-12-07 22:06:10: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":139,"level":550,"linkquality":34,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:14: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":254,"level":1000,"linkquality":23,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:14: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":231,"level":910,"linkquality":21,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:14: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":254,"level":1000,"linkquality":23,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:15: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":231,"level":910,"linkquality":23,"state":"OFF"}'
Zigbee2MQTT:info  2020-12-07 22:06:15: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":231,"level":910,"linkquality":26,"state":"ON"}'
Zigbee2MQTT:info  2020-12-07 22:06:15: MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"brightness":254,"level":1000,"linkquality":26,"state":"ON"}'

```

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here


Thank you

**Comment by wilqp** [comment]
It would be great if you could add it.
Thank you in advance. :)

**Comment by stas-demydiuk** [comment]
Please update the plugin to the latest version and check (#458)

**Comment by wilqp** [comment]
I updated to the latest version, and unfortunately it's not working. Also instead of dimmer it show a state switch.  I renamed it 'Toya'
```
Error: (ZB2MQTT) Tuya: can not process feature type "light"
Error: (ZB2MQTT) 'onMessage' failed 'TypeError':''NoneType' object is not subscriptable'.
 Error: (ZB2MQTT) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
 Error: (ZB2MQTT) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
Error: (ZB2MQTT) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
 Error: (ZB2MQTT) ----> Line 153 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
Error: (ZB2MQTT) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function set_devices
Error: (ZB2MQTT) Tuya: can not process feature type "light"
Error: (ZB2MQTT) Tuya: can not process feature type "light"
 Error: (ZB2MQTT) 'onCommand' failed 'IndexError':'list index out of range'.
 Error: (ZB2MQTT) ----> Line 283 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand
 Error: (ZB2MQTT) ----> Line 91 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand
Error: (ZB2MQTT) ----> Line 65 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_command
Error: (ZB2MQTT) ----> Line 238 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function handle_command
```

**Comment by stas-demydiuk** [comment]
Could you please enable `debug` mode in the plugin and post here the output under `Tuya: can not process feature type "light"` message

**Comment by wilqp** [comment]
Please:
```
2020-12-14 21:56:07.789 Error: (ZB2MQTT) Tuya: can not process feature type "light"
2020-12-14 21:56:22.442 Status: User: admin initiated a switch command (165/Tuya/Set Level)
2020-12-14 21:56:22.504 Error: (ZB2MQTT) 'onCommand' failed 'IndexError':'list index out of range'.
2020-12-14 21:56:22.504 Error: (ZB2MQTT) ----> Line 283 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand
2020-12-14 21:56:22.504 Error: (ZB2MQTT) ----> Line 91 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand
2020-12-14 21:56:22.504 Error: (ZB2MQTT) ----> Line 65 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_command
2020-12-14 21:56:22.504 Error: (ZB2MQTT) ----> Line 202 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function handle_command
```

**Comment by stas-demydiuk** [comment]
What action causes this issue?

**Comment by stas-demydiuk** [comment]
The `light` feature support has been added in scope #548. Please check ant post there in case of any issues.
