### ISSUE TITLE
v3.0 domoticz or Domoticz?

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#499]
I'm trying to get v3.0 working and not succeeding.

One of the problems seems to be that various bits of v3.0 have switched to using 'domoticz' instead of 'Domoticz'.

For example 'import domoticz' in devices_manager.py and 'domoticz.debug' in adapter.py, but there are many others.

This doesn't work on my system, which is running recent development versions of both domoticz and zigbee2mqtt, python 3.8.5, on Ubuntu 20.04.

To be honest I'm rather surprised this is working for anybody, but clearly it must be.

I've been working through the code, "correcting" the capitalization and it gets a lot further, though I'm still hitting hitting a wall later on. However there's no point me asking for help with that at this stage; I need to understand this problem first.

What have I missed?

**Comment by CyberClwn** [comment]
I had an issue with branch v3.0 too.

What i did was move the zigbee2mqtt folder from ~/domoticz/plugins/  to /tmp.
Then did a 
git clone -b v3.0 https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt
in ~/domoticz/plugins/  

And after that i restarted domoticz. then all worked again for me.
Trying to switch branch with fetch or other commands did not work like i expected.
But above sorted it for me, and i suddenly had the correct new devices..

Hope it helps.

**Comment by hughb8on** [comment]
Thank you for that, absolutely spot-on. I now have devices and can continue testing.
Somehow, the way I switched to v3.0 left me with most of the new code, but crucially I was missing domoticz.py.
That missing file explains everything.
Perhaps the README.md for v3.0 could be amended to tell people how to upgrade.

**Comment by Anjerlaan** [comment]
> I had an issue with branch v3.0 too.
> 
> What i did was move the zigbee2mqtt folder from ~/domoticz/plugins/ to /tmp.
> Then did a
> git clone -b v3.0 https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt
> in ~/domoticz/plugins/
> 
> And after that i restarted domoticz. then all worked again for me.
> Trying to switch branch with fetch or other commands did not work like i expected.
> But above sorted it for me, and i suddenly had the correct new devices..
> 
> Hope it helps.

I have performed your steps, all zigbee2mqtt devices are listed in the devices, but the zigbee2mqtt webgui manager is not listing them.....which version of zigbee2mqtt do you run? i have 1.16.2....there seems to be a change here from where the devices are listed

Thro42 commented 9 hours ago
It is the same problem then in master branch. After update Zigbee2Mqtt to 1.16.2, the answer of the request to "bridge/config/devices" is not longer in the "bridge/log" !. File domoticz-zigbee2mqtt-plugin/api/devices.py has to chage, for extracting the Information from the "bridge/config/devices" Message. Same problem will be in domoticz-zigbee2mqtt-plugin/api/groups.py

**Comment by hughb8on** [comment]
We are well off-topic from the original issue I raised and closed, but I am using Zigbee2MQTT v.1.16.2-dev. See my OP for other details.
My devices are listed in Domoticz's devices tab and for the most part are working.
They are also listed in both the Zigbee2MQTT frontend and in the plugin's Custom web page.
So far I've only found one which isn't working - a lightbulb registered by the UniversalAdaptor code. I'll raise a separate issue for that when I've done some more testing.

**Comment by Anjerlaan** [comment]
> We are well off-topic from the original issue I raised and closed, but I am using Zigbee2MQTT v.1.16.2-dev. See my OP for other details.
> My devices are listed in Domoticz's devices tab and for the most part are working.
> They are also listed in both the Zigbee2MQTT frontend and in the plugin's Custom web page.
> So far I've only found one which isn't working - a lightbulb registered by the UniversalAdaptor code. I'll raise a separate issue for that when I've done some more testing.

I am running the release of 1.16.2 and set the experimental new_api to true and frontend. The Zigbee2MQTT frontend is visible
I started from scratch in domoticz:
Removed the zigbee2mqtt hardware in domoticz.
Uninstalled the plugin with plug-in manager.
then the `git clone -b v3.0 https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt` in the plugins folder, and opened the frontend of the plugin....no listing was shown and in the domoticz settings/devices tab only the zigbee Group devices were created.

Might there be a difference between the DEV version and the release of 1.16.2? because I have a lot of strange errors.

**Comment by hughb8on** [comment]
I doubt if that is what is causing your problem - I too was only seeing the Group devices created until I re-installed the plugin - and I was on the DEV version the whole time, so whatever was causing the strange plugin behaviour, it wasn't Zigbee2MQTT causing it.

**Comment by hughb8on** [comment]
I've just had a thought, but it needs somebody who understands python much better than me to answer it.

Is it possible the problem is due to cached bytecode of the old code branch in __pycache__ ?

That would explain why the normal git checkout of the new branch leaves a broken plugin. It also explains why manually deleting the plugin and re-cloning it fixes the problem.

I believe deleting the contents of the __pycache__ folder is completely safe, it will just be recreated next time the code is run. If you don't feel you have anything left to lose, try that, otherwise wait for somebody to agree or disagree with me :)
