### ISSUE TITLE
V3.0 Universal Adapter creates inappropriate device for Philips Hue 9290018216

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#502]
This is a newish Philips Hue dimmable white bulb.

For our purposes it is identical to older ones like 8718699673147. 

Unlike the older ones, this one isn't in adapter_by_model so its creation is handled by the UniversalAdapter code.

That code is creating only an _effect device. It should be creating a _light device.

Zigbee2MQTT exposes the following for both this new bulb and its older cousins: -

[{'features': [{'access': 7, 'description': 'On/off state of this light', 'name': 'state', 'property': 'state', 'type': 'binary', 'value_off': 'OFF', 'value_on': 'ON', 'value_toggle': 'TOGGLE'}, {'access': 7, 'description': 'Brightness of this light', 'name': 'brightness', 'property': 'brightness', 'type': 'numeric', 'value_max': 254, 'value_min': 0}], 'type': 'light'}, {'access': 2, 'description': 'Triggers an effect on the light (e.g. make light blink for a few seconds)', 'name': 'effect', 'property': 'effect', 'type': 'enum', 'values': ['blink', 'breathe', 'okay', 'channel_change', 'finish_effect', 'stop_effect']}, {'access': 1, 'description': 'Link quality (signal strength)', 'name': 'linkquality', 'property': 'linkquality', 'type': 'numeric', 'unit': 'lqi', 'value_max': 255, 'value_min': 0}]

**Comment by stas-demydiuk** [comment]
Could you please update the plugin and try again

**Comment by hughb8on** [comment]
Will do, but I’m currently not seeing a v3.0 branch.

**Comment by stas-demydiuk** [comment]
It is now part of `master` one

**Comment by hughb8on** [comment]
No change, the plugin still creates an _effec device for this bulb.

**Comment by Anjerlaan** [comment]
> No change, the plugin still creates an _effec device for this bulb.

I also have this for the Philips Hue white ambiance E14 (with Bluetooth) 9290022944.

@stas-demydiuk, It looks like this only happens to Color and White Ambiance bulbs, because I also added a Hue Filament Standard A60/E27 bluetooth Bulb 8718699688820...this creates the device properly.

**Comment by hughb8on** [comment]
I don't think this is confined to colour / ambiance bulbs - mine is neither, it's just a warm white dimmable.

I believe the common factor is "new" bulbs which are handled by the new Universal Adapter code.

Your bulb, like mine, falls into that category.

My feeling is the Universal Adaptor code should still be in a beta-test branch, not the main one.

**Comment by Anjerlaan** [comment]
> I don't think this is confined to colour / ambiance bulbs - mine is neither, it's just a warm white dimmable.
> 
> I believe the common factor is "new" bulbs which are handled by the new Universal Adapter code.
> 
> Your bulb, like mine, falls into that category.
> 
> My feeling is the Universal Adapter code should still be in a beta-test branch, not the main one.

I think you are right.
When I look in my log the following error is shown:

```
2020-12-21 15:32:18.867 Error: (Zigbee2MQTT) Hoek_Lamp1: can not process feature type "light"
2020-12-21 15:32:18.868 Error: (Zigbee2MQTT) Hoek_Lamp2: can not process feature type "light"
2020-12-21 15:32:18.868 Error: (Zigbee2MQTT) Hoek_Lamp3: can not process feature type "light"
```

I am not a programmer, but is seems the feature `'type': 'light'` is not declared in this part of adapter.py:

```
def _add_devices(self, items):
        for item in items:
            if item['type'] == 'binary':
                self.add_binary_device(item)
                continue

            if item['type'] == 'enum':
                self._add_selector_device(item['name'][0: 5], item)
                continue

            if item['type'] == 'numeric':
                self.add_numeric_device(item)
                continue

            if item['type'] == 'switch':
                self._add_devices(item['features'])
                continue

            if item['type'] == 'lock':
                self._add_devices(item['features'])
                continue

            if item['type'] == 'climate':
                self._add_devices(item['features'])
                continue

            domoticz.error(self.name + ': can not process feature type "' + item['type'] + '"')
            domoticz.debug(json.dumps(item))
```

**Comment by Anjerlaan** [comment]
The access property in exposes.md is not easy to understand.
https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/exposes.md#exposes

**Access**

The access property is a 3-bit bitmask.

Bit 1: The property can be found in the published state of this device.
Bit 2: The property can be set with a /set command
Bit 3: The property can be retrieved with a /get command (when this bit is true, bit 1 will also be true)
Examples:

A Xiaomi WSDCGQ01LM climate sensor exposes a numeric temperature sensor. Since the device is sleeping most of the time it cannot be retrieved with a /get command. Access will be 1 (binary: 0b001).
A Philips 7146060PH Hue Go light exposes brightness. This can be /get, /set and is also in the published state. Access will be 7 (binary: 0b111)
A Philips 7146060PH Hue Go light exposes effect (e.g. to trigger a flashing effect). This can only be /set. Access will be 2 (binary: 0b010)
A Xiaomi ZNCZ02LM power plug exposes a numeric power sensor. This can be /get and is published in the state. Access will be 5 (binary: 0b101)

I also can’t figure out how this is implemented in adapter.py
In the exposes.md the access value of numeric and binary types is 7 and the enum (effect) type is 2

In adapter.py access values are declared here (I guess)

```
ACCESS_STATE = 0
ACCESS_WRITE = 1
ACCESS_READ = 2
```
but I wonder how the access value 7 is calculated if you look at this snippet of adapter.py:

```
def _has_access(self, access, access_type):
        mask = 1 << access_type
        return bool(access & mask)

    def add_binary_device(self, feature):
        state_access = self._has_access(feature['access'], ACCESS_STATE)
        write_access = self._has_access(feature['access'], ACCESS_WRITE)

or

def add_numeric_device(self, feature):
        state_access = self._has_access(feature['access'], ACCESS_STATE)
        write_access = self._has_access(feature['access'], ACCESS_WRITE)
```

**Comment by hughb8on** [comment]
Forgive me if I'm telling you something obvious, but while we wait for a solution, the quickest way to fix this and other problems with the Universal Adapter code is to add "new" devices into the appropriate adapters file, in our case adapters/philips/__init__.py. 

That way it gets handled by the old, tried-and-tested, code.

**Comment by Anjerlaan** [comment]
It looks like the 2 underscores at both sides assume it is a bold text just like ** **
3 underscores at both sides is cursive bold ___cursive___

**Comment by stas-demydiuk** [comment]
Guys, could you please update plugin and try again

**Comment by hughb8on** [comment]
It's better but it's not usable yet. 

It's better because a _light device is now created. It's  not usable yet because when the bulb changes to an "Off" state this is not reflected in the Domoticz device.

So, using the _light device to change the bulb's brightness works. Using it to turn the bulb off works too, but that status change is not reflected back to the Domoticz device. So it still shows as "On" when it is in fact now "Off".

The result of that you then can't turn the bulb back on by tapping/clicking the _light device - doing so just sends another "Off" command.

**Comment by stas-demydiuk** [comment]
Support for `light` feature has been significantly improved in scope #548. Please upgrade the plugin to the latest version and check. Please post there in case of any issues.

**Comment by Anjerlaan** [comment]
@stas-demydiuk in Z2M 1.17.0, the new_api is mandatory so in the configuration.yaml it is not needed anymore to add:

```
experimental:
new_api: true
```
Therefor you can remove this also in the read.me file of the plug-in I guess?
