### ISSUE TITLE
Devices don't get status updates. no device list, correct network map

### ISSUE THREAD

**Issue by jefdemas** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#503]
after upgrading to 1.16.2
devices aren't getting any updates from the status.

same problem after clean install.
i can see that de updates are comming in on the mqtt broker.

device list in plugin stays empty while network map is showing up correctly.

how to solve this problem

**Comment by Anjerlaan** [comment]
In Zigbee2mqtt 1.16.2 this has been changed:
https://github.com/Koenkk/zigbee2mqtt/issues/4466#issuecomment-742709335

So a fresh install of v0.2.1 i.c.w 1.16.2 will probably generate these problems.

**Comment by Emmanuel-FR** [comment]
It's always great to have feedback from people knowing the hardcore stuff !

I have the same issue after upgrading to 1.16.2. At some place, I couldn't reach my zigbee devices (which was bad), until I had the idea to trigger manually on of my zigbee plugs. I'm not sur I understood the fix by modification of the python script (#496). I will give it a try even if it'd be wiser to wait for the new api.
A more simple fix would be to downgrade, but is it possible and if so how ?

**Comment by stas-demydiuk** [comment]
Please update the plugin to the latest version and check (#458)

**Comment by Anjerlaan** [comment]
> Please update the plugin to the latest version and check (#458)

@stas-demydiuk, this is working now, although I have a feeling that the exposure function is not yet working for all devices properly yet. For a lot of bulbs only an effect device is created.
I am not sure if this has to do with Z2M 1.16.2 or your plug-in.
I don’t run the Dev version. Maybe the exposure function works better with the 1.16.2-Dev version i.c.w. v3.0?

**Comment by stas-demydiuk** [comment]
The process of adding all device features is in progress so it is ok that something might be missed at the moment
