### ISSUE TITLE
remove devices from Domoticz interface. 

### ISSUE THREAD

**Issue by Gerard-Oedzes** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#505]
Hallo, 

To keep The domoticz interface as clean as possible, i would love to have an option to remove divices witch i dont use. 
For example: for scripting i only use light groups, the group i create in the frotnend of zigbee2mqtt so for me all the sepperated light devices do not make sense in domoticz interface. 

I know i can use the remove button, but after restart they allways show up again. 

Is there somehow in the plugin a way to delete them?

**Comment by stas-demydiuk** [comment]
No, there is no such option for now, but I will think how to add something

**Comment by Gerard-Oedzes** [comment]
Would be wonderfull! thnx!! 

P.S thx for all the hard working on this plugin! you make Domoticz great!

**Comment by stas-demydiuk** [comment]
@Gerard-Oedzes You can now use the blacklist to avoid such creation of such devices. It was implemented in scope of #594
