### ISSUE TITLE
HG06337 Silvercrest smart plug (EU, CH, FR, BS)

### ISSUE THREAD

**Issue by bverlinden** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#508]
**Device description**
Smartplug Silvercrest (Lidl)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/HG06337.html

**MQTT message with device information**
{"id":40,"type":"Router","ieeeAddr":"0xbc33acfffe56a260","nwkAddr":970,"manufId":4098,"manufName":"_TZ3000_wamqdr3f","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":266,"inClusterList":[0,3,4,5,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_wamqdr3f","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cbff70","endpointID":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1607938233101}

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'MQTT publish: topic \'zigbee2mqtt/0xbc33acfffe56a260\', payload \'{"linkquality":90,"state":"OFF"}\''}
2020-12-14 11:21:20.246 (CC2652RB) MQTT message: zigbee2mqtt/0xbc33acfffe56a260 {'linkquality': 90, 'state': 'OFF'}

MQTT message: zigbee2mqtt/0xbc33acfffe56a260 {'linkquality': 90, 'state': 'OFF'}
2020-12-14 11:25:02.502 (CC2652RB) This plugin does not support zigbee device with model "HG06337" yet

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

 MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'MQTT publish: topic \'zigbee2mqtt/0xbc33acfffe56a260\', payload \'{"linkquality":90,"state":"OFF"}\''}
2020-12-14 11:25:02.502 (CC2652RB) MQTT message: zigbee2mqtt/0xbc33acfffe56a260 {'linkquality': 90, 'state': 'OFF'}

MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'MQTT publish: topic \'zigbee2mqtt/0xbc33acfffe56a260\', payload \'{"linkquality":93,"state":"ON"}\''}
2020-12-14 11:27:16.894 (CC2652RB) MQTT message: zigbee2mqtt/0xbc33acfffe56a260 {'linkquality': 93, 'state': 'ON'}

**Comment by CyberClwn** [comment]
Hi,

If you switch to the v3.0 branch (using the steps mentioned in https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/499) then the device is supported.

**Comment by bverlinden** [comment]
Ok,Will do. Last time I checked there was no coding for silvercrest yet.

**Comment by CyberClwn** [comment]
That's correct too.

But with v3.0 there is support for "Universal adapter". 

I have a HG06337 (and HG06338) and both are working with the v3.0 branch, if installed correctly

**Comment by CyberClwn** [comment]
ps. this is also mentioned in https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/488

with the same device in the subject/ title ....

**Comment by stas-demydiuk** [comment]
Please update the plugin to the latest version and check (#458)

**Comment by bverlinden** [comment]
@stas-demydiuk what am I doing wrong? I've updated to the V3 branch (after moving the old zigbee2mqtt plugin to another folder) but my device is still unsupported. I removed it and rejoined it, restarted without any luck.

**Comment by stas-demydiuk** [comment]
V3 branch has been merged to master now. Do you see any errors in log?

**Comment by bverlinden** [comment]
2020-12-14 21:52:57.736 (CC2652RB) MQTT message: zigbee2mqtt/0xbc33acfffe56a161 {'linkquality': 96, 'state': 'OFF'}
2020-12-14 21:52:57.736 (CC2652RB) This plugin does not support zigbee device with model "HG06337" yet
2020-12-14 21:52:57.737 (CC2652RB) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by stas-demydiuk** [comment]
It looks like you are not using the latest plugin version. Could you please double-check that you have the latest version from `master` branch

**Comment by bverlinden** [comment]
I did remove the old and installed the v3. But in my hardware tab I see a double entry 'Zigbee2mqtt'. I will try to revert to the master.

**Comment by stas-demydiuk** [comment]
Could you please upgrade the plugin and check
