### ISSUE TITLE
QS-Zigbee-S04-2C-LN

### ISSUE THREAD

**Issue by dheuts90** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#510]
Lonsonho 2 Gang Zigbee Switch Module With Neutral
https://www.zigbee2mqtt.io/devices/QS-Zigbee-S04-2C-LN.html

{"description":"2 gang switch module with neutral wire","friendly_name":"0x60a423fffeab59f8","model":"QS-Zigbee-S04-2C-LN","supported":true,"vendor":"Lonsonho"}

**Comment by stas-demydiuk** [comment]
Please update the plugin to the latest version and check (#458)

**Comment by dheuts90** [comment]
Thanks for your message. I read it is recommended to first remove the old plugin from hardware before installing the new plugin (updateing). Will I keep my devices in Domoticz or do I have to do it all again? 

I use Blockly and it would be a lot of work when I have to add all the devices again in all the scripts.
Hope to hear from you, thanks a lot.

**Comment by luismalddonado** [comment]
Tested and working great with domoticz
