### ISSUE TITLE
Universal Adapter creates some devices with new names, orphans old ones.

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#514]
I’ve been testing v3.0, and now the main branch with the Universal Adapter changes merged in.

The naming of many devices has changed. The plugin creates new devices with these new names and stops updating the old ones.

Examples: -

 Some _switch devices now called _state, e.g. E1603/E1702, BASICZBR3, SNZB-04
 Some _switch devices now called _actio, e.g. SNZB-01
 Some _action devices now called _actio, e.g. QBKG04LM

This is a breaking change.

**Comment by BastiaanNaber** [comment]
I had the same. Indeed a breaking change

**Comment by stas-demydiuk** [comment]
Yes it expected and it is breaking change after upgrading from 0.2.x version. Just remove old devices from Domoticz manually
