### ISSUE TITLE
 So the group switch works!

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#515]
Hello, it is very good now! So the group switch works!

But it is not created on the z2m side, but is only available in the entire overview.

![sshot-1](https://user-images.githubusercontent.com/32480002/99577746-1235ed00-29dc-11eb-81cc-f0d79dba5bc3.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/99577749-13671a00-29dc-11eb-9ce4-1296a0efe4f0.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/99577751-13671a00-29dc-11eb-82c9-6a2d84afe891.jpg)

_Originally posted by @salopette in https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/458#issuecomment-729901347_

**Comment by stas-demydiuk** [comment]
@salopette, could you please explain in more detail what the issue is? I'm not sure I got it

**Comment by salopette** [comment]
I think it's done. No more problems so far!

THX
