### ISSUE TITLE
Some errors in first installation of zigbee2mqtt pluging  domoticz under W10

### ISSUE THREAD

**Issue by vicen60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#518]
Hello
**System domoticz 2020.2 build 12731 under windows10 + Python 3.5.2
Sniffer CC2531 flashed with CC2531_default_20190608.zip installed node.js V14.15.1 
Downloaded zigbee2mqtt in directory domoticz\plugins\zigbee2mqtt**
**npm ci produce some error seems some missing files** 

> C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\unix-dgram>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
>   unix_dgram.cc
>   win_delay_load_hook.cc
> c:\program files (x86)\domoticz\plugins\zigbee2mqtt\node_modules\unix-dgram\src\unix_dgram.cc(9): fatal error C1083: No
>  se puede abrir el archivo incluir: 'unistd.h': No such file or directory [C:\Program Files (x86)\Domoticz\plugins\zigb
> ee2mqtt\node_modules\unix-dgram\build\unix_dgram.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Windows_NT 10.0.19042
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\unix-dgram
> gyp ERR! node -v v14.15.1
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> added 825 packages in 55.792s

**mpm start failure strating zigbee_herdsman**
_Zigbee2MQTT:info  2020-12-15 15:03:30: Logging to console and directory: 'C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\data\log\2020-12-15.15-03-29' filename: log.txt
Zigbee2MQTT:info  2020-12-15 15:03:31: Starting Zigbee2MQTT version 1.16.2 (commit #0514204)
Zigbee2MQTT:info  2020-12-15 15:03:31: Starting zigbee-herdsman (0.13.37)
Zigbee2MQTT:error 2020-12-15 15:03:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-12-15 15:03:31: Failed to start zigbee
Zigbee2MQTT:error 2020-12-15 15:03:31: Exiting...
Zigbee2MQTT:error 2020-12-15 15:03:31: Error: Error while opening serialport 'Error: Opening \\.\COM3: Access denied'
    at Znp.<anonymous> (C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\dist\adapter\z-stack\znp\znp.js:136:32)
    at Generator.next (<anonymous>)
    at C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\dist\adapter\z-stack\znp\znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\dist\adapter\z-stack\znp\znp.js:23:12)
    at SerialPort.<anonymous> (C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\dist\adapter\z-stack\znp\znp.js:134:49)
    at SerialPort._error (C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\node_modules\@serialport\stream\lib\index.js:198:14)
    at C:\Program Files (x86)\Domoticz\plugins\zigbee2mqtt\node_modules\zigbee-herdsman\node_modules\@serialport\stream\lib\index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.16.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.16.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vicen\AppData\Roaming\npm-cache\_logs\2020-12-15T14_03_31_593Z-debug.log_
 
other question in my domoticz hardware don't appear zigbee2mqtt
Really I don't know how to follow, thanks for some help I only an starting user.
Vicen60

**Comment by stas-demydiuk** [comment]
This issue is related to zigbee2mqtt installation, not the plugin one, please report the issue to zigbee2mqtt authors in case you still have the one
