### ISSUE TITLE
Plugin stop working

### ISSUE THREAD

**Issue by detxm80** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#52]
Hi, my zigbee2mqtt service works perfectly and send regular updates but my domoticz plugin after a while stops working and seems not to receive data, anyone that have this issue?
Thanks

**Comment by stas-demydiuk** [comment]
@detxm80 Were you able to identify what causes plugin crash?

**Comment by stas-demydiuk** [comment]
Ok, please reopen the issue if you will be able to reproduce it again
