### ISSUE TITLE
Lightbulb LIDL HG06492c does not appear in Domoticz as lightbulb

### ISSUE THREAD

**Issue by Rudi1952** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#520]
**Issue Description:**
Impossible to add LIDL Livarno Lux E27 bulb CCTof type HG06492C to Domoticz

I tried to pair the LIDL Livarno Lux E27 bulb CCTof type HG06492C into zigbee2mqtt. It succeeded vey well, in my Zigbee2mqtt list I see:

0x842e14fffe1b894b | HG06492C | Livarno Lux E27 bulb CCT | Router | 0x842e14fffe1b894b | 2020-12-18 10:51:08
-- | -- | -- | -- | -- | --

But it does not appear in Domoticz as a bulb, but it appears with Type=Light/Switch, SubType= Selector switch, though I thought it should be a dimmable bulb
![image](https://user-images.githubusercontent.com/35039914/102603038-95a14600-4122-11eb-858b-25f9d4b9f332.png)
**Additional info:**
Domoticz: V2020.2
Zigbee: v.16.1.2-dev (zStack30x 20190425)
Plugin version 3.0.0
Can you help me with this?

**Comment by Anjerlaan** [comment]
This is basically the same issue (I have the candle version)...only I am not on the dev branch. So the device is still recognized as a TuYa TS0505 device, which is the same hardware as the Lidl livarnolux models.

I think somebody may have made a pull request here which may cause the error

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/519#issue-769137527

**Comment by hughb8on** [comment]
I think this is related to issue #502 - the Universal Adapter code creates an "_effec" device for a lightbulb.

But amongst other naming changes it now creates a mixture of "_state" devices and "_actio" devices for devices previously created as switches and _actio devices for ones previously called _action, (see issue #514 ) so  perhaps this is deliberate?

**Comment by Rudi1952** [comment]
Today i tried to join this bulb again:
Domoticz Version: 2020.2
Python Version: 3.7.3
Zigbee2MQTT version 1.17.0 (zStack30x 20190425)
zigbee-herdsman (0.13.46)
adapter: CC2531

But it is still not possible to join this bulb in the right way, though things have changed since januari 1st

**_On my Zigbee2mqtt i see that a new device is created:_**
0x842e14fffe1b894b	HG06492C	Livarno Lux E27 bulb CCT	Router	0x842e14fffe1b894b	2021-01-08 08:41:40

**_In my devices list of DOMOTICZ i see that 4 devices were created for this bulb_**
529	Zigbee2MQTT	0x842e14fffe1b894b_signal	60	Zigbee2MQTT - 0x842e14fffe1b894b (Link Quality)	General	Custom Sensor	0	-	-	   	2021-01-08 08:41:40
528	Zigbee2MQTT	0x842e14fffe1b894b_effec	59	Zigbee2MQTT - 0x842e14fffe1b894b (effect)	Light/Switch	Selector Switch	Off	-	-	   	2021-01-08 08:41:40
527	Zigbee2MQTT	0x842e14fffe1b894b_light	58	Zigbee2MQTT - 0x842e14fffe1b894b (brightness)	Light/Switch	Switch	Off	-	-	   	2021-01-08 08:41:40
526	Zigbee2MQTT	0x842e14fffe1b894b_state	57	Zigbee2MQTT - 0x842e14fffe1b894b (state)	Light/Switch	Switch	Off	-	-	   	2021-01-08 08:41:40

**_In_ my domoticz logfile i see this error:_**
2021-01-08 08:41:40.438 Error: (Zigbee2MQTT) 0x842e14fffe1b894b: can not process numeric item "color_temp"

**_Zigbee2mqtt logfile:_**
info  2021-01-08 08:41:17: Zigbee: allowing new devices to join.
info  2021-01-08 08:41:17: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"07cdc9d","coordinator":{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":201904$
debug 2021-01-08 08:41:18: Received MQTT message on 'zigbee2mqtt/bridge/config/permit_join' with data 'true'
info  2021-01-08 08:41:18: Zigbee: allowing new devices to join.
info  2021-01-08 08:41:18: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"07cdc9d","coordinator":{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":201904$
info  2021-01-08 08:41:38: Device '0x842e14fffe1b894b' joined
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe1b894b","ieee_address":"0x842e14fffe1b894b"},"type":"device_joined"}'
info  2021-01-08 08:41:38: Starting interview of '0x842e14fffe1b894b'
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe1b894b","ieee_address":"0x842e14fffe1b894b","status":"started"},"type":"de$
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x842e14fffe1b894b"},"type":"device_connected"}'
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x842e14fffe1b894b"},"type":"pairing"}'
debug 2021-01-08 08:41:38: Received MQTT message on 'zigbee2mqtt/bridge/config/devices/get' with data ''
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":161009$
debug 2021-01-08 08:41:38: Received MQTT message on 'zigbee2mqtt/bridge/config/devices' with data '[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":$
info  2021-01-08 08:41:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":161009$
debug 2021-01-08 08:41:39: Device '0x842e14fffe1b894b' announced itself
info  2021-01-08 08:41:39: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe1b894b","ieee_address":"0x842e14fffe1b894b"},"type":"device_announce"}'
info  2021-01-08 08:41:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x842e14fffe1b894b"},"type":"device_announced"}'
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"modelId":"TS0502A"}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3000_49qchf10"}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"appVersion":80}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:39: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:40: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:40: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
debug 2021-01-08 08:41:40: Received Zigbee message from '0x842e14fffe1b894b', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
info  2021-01-08 08:41:40: Successfully interviewed '0x842e14fffe1b894b', device has successfully been paired
info  2021-01-08 08:41:40: Device '0x842e14fffe1b894b' is supported, identified as: Lidl Livarno Lux E27 bulb CCT (HG06492C)
info  2021-01-08 08:41:40: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Livarno Lux E27 bulb CCT","exposes":[{"features":[{"access":7,"description$
info  2021-01-08 08:41:40: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload '[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings$
info  2021-01-08 08:41:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Livarno Lux E27 bulb CCT","friendly_name":"0x842e14fffe1b$
debug 2021-01-08 08:41:40: Received MQTT message on 'zigbee2mqtt/bridge/config/devices/get' with data ''
info  2021-01-08 08:41:40: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":161009$
debug 2021-01-08 08:41:40: Received MQTT message on 'zigbee2mqtt/bridge/config/devices' with data '[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":$
info  2021-01-08 08:41:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190425","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9ead3","lastSeen":161009$
debug 2021-01-08 08:41:47: Received Zigbee message from 'CC2530.ROUTER', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 8 with groupID 0
info  2021-01-08 08:41:47: MQTT publish: topic 'zigbee2mqtt/CC2530.ROUTER', payload '{"led":true,"linkquality":118}'
debug 2021-01-08 08:42:04: Received MQTT message on 'zigbee2mqtt/bridge/config/permit_join' with data 'false'
info  2021-01-08 08:42:04: Zigbee: disabling joining new devices.

**Comment by Rudi1952** [comment]
I added folowing line to: /home/pi/domoticz/plugins/zigbee2mqtt/adapters/silvercrest/__init__.py

    'HG06492C': DimmableCtBulbAdapter,  # Silvercrest bulb E27

The bulb appears now in domoticz as a 'Color Switch' WW
