### ISSUE TITLE
Add support für MOES BHT-002-GCLZB Thermostat

### ISSUE THREAD

**Issue by alexkiddde** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#523]
**Device description**
BHT-002-GCLZB from Moes, ZigBee Version of WiFi BHT-002
Wall Thermostat for Floor Heating and others

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html

**MQTT message with device information**
 {'dateCode': '', 'description': 'Moes BHT series Thermostat', 'friendly_name': 'Thermostat Wohnzimmer', 'hardwareVersion': 1, 'ieeeAddr': '0x5c0272fffeedc29b', 'lastSeen': 1608405993604, 'manufacturerID': 4098, 'manufacturerName': '_TZE200_aoclfnxz', 'model': 'BHT-002-GCLZB', 'modelID': 'TS0601', 'networkAddress': 62169, 'powerSource': 'Mains (single phase)', 'type': 'Router', 'vendor': 'Moes'}], 'type': 'devices'}

**MQTT messages from device**
MQTT message: zigbee2mqtt/Thermostat Wohnzimmer {'current_heating_setpoint': 0, 'heat': 'OFF', 'linkquality': 68, 'local_temperature': 24.5, 'max_temperature_limit': 45, 'preset_mode': 'hold', 'system_mode': 'heat'}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Are you using the latest plugin version (3.0)?

**Comment by alexkiddde** [comment]
Yes, after updating, the device works fine. Sorry for bothering you.

**Comment by Johnny-Terrano** [comment]
**Device description**
Moes BHT-002-GCLZB Thermostat.

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html

**MQTT message with device information**
{
"dateCode": "",
"description": "Moes BHT series Thermostat",
"friendly_name": "Thermostat",
"hardwareVersion": 1,
"ieeeAddr": "0x60a423fffeb2808c",
"lastSeen": 1606244059702,
"manufacturerID": 4098,
"manufacturerName": "_TZE200_aoclfnxz",
"model": "BHT-002-GCLZB",
"modelID": "TS0601",
"networkAddress": 41792,
"powerSource": "Mains (single phase)",
"type": "Router",
"vendor": "Moes"
}

**MQTT messages from device**
Zigbee2MQTT:info 2020-11-24 19:53:32: MQTT publish: topic 'zigbee2mqtt/Thermostat', payload '{"current_heating_setpoint":18,"heat":"OFF","linkquality":34,"local_temperature":"19.0","preset_mode":"hold","system_mode":"heat"}'

Received Zigbee message from 'Thermostat', type 'commandGetData', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":
[0,0,0,18],"type":"Buffer"},"dp":528,"fn":0,"status":0,"transid":106}' from endpoint 1 with groupID 0

MQTT publish: topic 'zigbee2mqtt/Thermostat', payload
'{"child_lock":"LOCKED","current_heating_setpoint":23,"heat":"ON","linkquality":118,"local_temperature":"20.5","preset_mode":"program","system_mode":"heat"}

**MQTT state change commands**
zigbee2mqtt/Thermostat/set {"preset": "program"} (schedule mode)
zigbee2mqtt/Thermostat/set {"preset": "hold"} (manual mode)
zigbee2mqtt/Thermostat/set {"child_lock": "LOCK"}
zigbee2mqtt/Thermostat/set {"child_lock": "UNLOCK"}
zigbee2mqtt/Thermostat/set {"system_mode": "off"}
zigbee2mqtt/Thermostat/set {"system_mode": "heat"}
zigbee2mqtt/Thermostat/set {"current_heating_setpoint": "15"} (value as character)
zigbee2mqtt/Thermostat/set {"current_heating_setpoint": 15} (value as numeric)
zigbee2mqtt/Thermostat/set {"current_heating_setpoint": "15.5"} (decimal value doesn't work. Setpoint set to 0)
zigbee2mqtt/Thermostat/set {"current_heating_setpoint": 15.5} (decimal value doesn't work. Setpoint set to 0)

Thanks a lot.

**Comment by MiloshCZ** [comment]
Hi,
is it possible to add _HEAT_ parameter?
`{
    "child_lock": "UNLOCKED",
    "current_heating_setpoint": 21,
    "heat": "ON",
    "last_seen": 1614617473687,
    "linkquality": 76,
    "local_temperature": 20.5,
    "preset": "hold",
    "preset_mode": "hold",
    "program": [
        {
            "p1": "6h:0m 40°C"
        },
        {
            "p2": "11h:30m 42°C"
        },
        {
            "p3": "13h:30m 44°C"
        },
        {
            "p4": "17h:30m 46°C"
        },
        {
            "sa1": "6h:0m 48°C"
        },
        {
            "sa2": "12h:0m 46°C"
        },
        {
            "sa3": "14h:30m 44°C"
        },
        {
            "sa4": "17h:30m 42°C"
        },
        {
            "su1": "6h:0m 38°C"
        },
        {
            "su2": "12h:30m 40°C"
        },
        {
            "su3": "14h:30m 42°C"
        },
        {
            "su4": "18h:30m 40°C"
        }
    ],
    "system_mode": "heat"
}`
