### ISSUE TITLE
Dimmer QS-Zigbee-D02-TRIAC-LN can not process feature type "light"

### ISSUE THREAD

**Issue by Krolik1988** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#527]
Hi, after I installed update of the plugin #458. I got problem
 2020-12-21 21:55:08.336 Error: (Zigbee2MQTT) 0xbc33acfffe6d82d3: can not process feature type "light" 

Dimmer was added here: #424.

Now it's impact me, because I use this dimmer for ventilation. Hope for your respond.

Thanks you and have a good day.

**Comment by Krolik1988** [comment]
Putted back 
Line under Lonsonho section:
'QS-Zigbee-D02-TRIAC-LN': DimmableBulbAdapter, #QS-Zigbee-D02-TRIAC-LN
Again works. But I think It must be done other way.

**Comment by stas-demydiuk** [comment]
What version of plugin are you using?

**Comment by stas-demydiuk** [comment]
The `light` feature support has been added in scope of #548

**Comment by Krolik1988** [comment]
> 
> 
> What version of plugin are you using?

Last one on on moment of topick was open. Now updated. Thanks.

**Comment by stas-demydiuk** [comment]
Now the feature should work fine, please post here #548 in case of any issues
