### ISSUE TITLE
Sonoff SNZB-02

### ISSUE THREAD

**Issue by sebanast** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#529]
Hello
I have new Sonoff SNZB-02 temperature and humidity sensor working with cc2531 (zigbee2mqtt).
Almost everything is ok but domoticz do not create any device.
Can You help me, please. Here are the logs:

Zigbee2MQTT:info  2020-12-25 13:23:52: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b001949ae97","lastSeen":1608899032304,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20200718","description":"Temperature and humidity sensor","friendly_name":"Sonoff","hardwareVersion":1,"ieeeAddr":"0x00124b00224146da","lastSeen":1608898767900,"manufacturerID":0,"manufacturerName":"eWeLink","model":"SNZB-02","modelID":"TH01","networkAddress":61141,"powerSource":"Battery","type":"EndDevice","vendor":"SONOFF"}]' 

Zigbee2MQTT:info  2020-12-25 13:23:51: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"0514204","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.16.2"}'

**MQTT messages from device**

Zigbee2MQTT:info  2020-12-25 18:00:37: MQTT publish: topic 'zigbee2mqtt/Sonoff', payload '{"battery":100,"humidity":58.86,"linkquality":97,"temperature":22.03,"voltage":3200}'

Thank You.

**Comment by stas-demydiuk** [comment]
Which version of plugin do you use?

**Comment by sebanast** [comment]
Hello.
I use the latest (v.0.2.1). It`s weird. I see the devices from Zigbee2mqtt but it creates only some General Text device. Thank you for your answer.
![Zrzut](https://user-images.githubusercontent.com/76594463/103316881-1d902580-4a2a-11eb-844f-4741cdb557ab.png)
![Zrzut2](https://user-images.githubusercontent.com/76594463/103316894-27198d80-4a2a-11eb-8170-bb48e6dbf8e7.png)

**Comment by stas-demydiuk** [comment]
Please upgrade to the plugin version from the `master` branch (it is 3.0 now)

**Comment by sebanast** [comment]
Hello. It works !!!
But the problem was in my zigbee2mqtt configuration.yaml file. I don`t know how it happened. You know how it is when all is checked and you start to dig deeper and deeper. Thanks a lot. Best wishes and happy new year from coast of Poland:)
