### ISSUE TITLE
Connection problem Xiaomi Aqara Sensor DJT11LM

### ISSUE THREAD

**Issue by leoduth** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#532]
**Issue description**

Hello, 

I integrated my first sensor DJT11LM in Domoticz via Zigbee2MQTT, however I have some problems. 

![image](https://user-images.githubusercontent.com/58000981/103219995-6c9d6400-491f-11eb-8e6b-424c8f8db8ed.png)

Here's how it appears, and I can't use the sensor. How can I do it?

Thanks in advance!

**Additional information**
Zigbee2MQTT version: 1.16.2
Python version: 
Domoticz version: 2020.2
Plugin version: 0.2.1

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
This device is not your sensor, this is a system device required for plugins' UI
