### ISSUE TITLE
Support Nue ZW-EU-01 / 3A Smart Home / Zemismart DE LXN59-1S7LX1.0 1 gang switch

### ISSUE THREAD

**Issue by russdan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#537]
**Device description**
1 Gang switch - branded sold under Nue / 3A brands

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/LXN59-2S7LX1.0.html

**MQTT message with device information**
```
{"dateCode":"20200519","description":"Smart light relay - 1 gang","friendly_name":"0x086bd7fffe5d0588","hardwareVersion":0,"ieeeAddr":"0x086bd7fffe5d0588","lastSeen":1609335787564,"manufacturerID":4478,"manufacturerName":"3A Smart Home DE","model":"LXN59-1S7LX1.0","modelID":"LXN59-1S7LX1.0","networkAddress":16212,"powerSource":"Unknown","type":"Router","vendor":"Nue / 3A"}],"type":"devices"}'

```
**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here
```
info  2020-12-30 13:41:09: MQTT publish: topic 'zigbee2mqtt/0x086bd7fffe5d0588', payload '{"linkquality":80,"state":"ON"}'
info  2020-12-30 13:41:11: MQTT publish: topic 'zigbee2mqtt/0x086bd7fffe5d0588', payload '{"linkquality":80,"state":"OFF"}'
```

**Comment by russdan** [comment]
@stas-demydiuk the implementation of this is pretty simple:

add the following to `adapters/zemismart`

`from adapters.on_off_switch_adapter import OnOffSwitchAdapter`

and add to 
```
zemismart_adapters = {
'LXN59-1S7LX1.0': OnOffSwitchAdapter,  # 3A Smart Home DE LXN59-1S7LX1.0 1 gang switch adapter
```

the on/off switch device is then added in Domoticz - it shows as a Router in the Device Manager but this is the information it receives from zigbee2mqtt - it doesn't affect the device which will then function as a light switch as needed.

**Comment by stas-demydiuk** [comment]
This device is already supported by the latest plugin version from master branch
