### ISSUE TITLE
Hive SLR2/SLT2 Support.

### ISSUE THREAD

**Issue by roadsnail** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#538]
### **Device description**
Hive Active Controller/Thermostat (SLR2/SLT2)

### **Zigbee2mqtt page**
Device pair.

Controller
https://www.zigbee2mqtt.io/devices/SLR2.html

and

Thermostat
https://www.zigbee2mqtt.io/devices/SLT2.html

Also this may help. Please see my notes on SLR2/SLT2 controlling at https://github.com/roadsnail/Hive-SLR2-SLT2-Zigbee2MQTT-with-node-RED#relay-control---hot-water

(The node-RED flow indicates the MQTT topic/messages)

The SLR2 appears to require a sequence of mqtt messages to switch on/off relays. (See below)

### **MQTT messages from device**

Device (SLR2 and SLT2) status may be read from device:-

Subscribing to MQTT topic zigbee2mqtt/FRIENDLY_NAME             allows the SLR2 status to be read.

#### CH/HW Relay Status
The status of each relay, 'idle' == relay is Off       OR   'heat' == relay is On,    can be determined from 
running_state_heat                        
 and 
running_state_water 

#### CH Thermostat Setting
Heating Thermostat setpoint  Temperature in deg C.          eg    22.5           Can be read from 
occupied_heating_setpoint_heat

#### Thermostat (SLT2) Temperature
Temperature detected by thermostat (SLT2)  Can be read in degrees C     eg   19.43       from 
local_temperature_heat

### MQTT state change commands

The controller has 2 relays. Central Heating (CH) and Hot Water (HW):-

#### HW RELAY Switching

To Switch off HW Relay send 3 mqtt message sequence (SLT2 displays 'Off'):-

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                  Message {"system_mode_water": "off"}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/get                  Message {"system_mode_water": ""}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                   Message {"temperature_setpoint_hold_water": "0"}

To Switch on HW Relay send 3 mqtt message sequence (SLT2 displays 'On'):-

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                   Message {"system_mode_water": "heat"}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/get                  Message {"system_mode_water": ""}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                   Message {"temperature_setpoint_hold_water": "1"}

#### CH RELAY Switching

To Switch off CH Relay send 3 mqtt message sequence (SLT2 displays 'Off'):-

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                   Message {"system_mode_water": "off"}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/get                  Message {"system_mode_water": ""}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                   Message {"temperature_setpoint_hold_water": "0"}

To Switch on CH Relay send 3 mqtt message sequence (SLT2 displays 'Manual'):-

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                    Message {"system_mode_heat": "heat"}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/get                   Message {"system_mode_heat": ""}

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set                    Message {"temperature_setpoint_hold_heat": "1"}

Now that CH Relay 'Manual' mode is selected, the relay may be switched by changing the thermostat SP value. To achieve this, send a thermostat set value message:-

Topic   zigbee2mqtt/FRIENDLY_NAME/heat/set/occupied_heating_setpoint_heat           Message VALUE        
(VALUE is Thermostat setpoint in degrees C (eg. 20.5))

**Comment by stas-demydiuk** [comment]
Please post the Domoticz log with `debug` mode activated in the plugin
