### ISSUE TITLE
Add support for `battery_low` feature

### ISSUE THREAD

**Issue by CodingEJ** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#539]
One of my devices (TS0601) can only indicate that the battery state is low through binary property 'battery_low'. The AdapterWithBattery does not support these messages. 

I made a quick patch to support battery_low, using a ContactSensor, such that the low battery is indicated by 'Open' and full battery by 'Closed'. It's not very beautiful, but works for now (see code below).
Would it be possible to add such support for real?

Code (adapter_with_battery.py):

import domoticz
from adapters.base_adapter import Adapter
from devices.sensor.voltage import VoltageSensor
from devices.sensor.percentage import PercentageSensor
from devices.sensor.contact import ContactSensor

class AdapterWithBattery(Adapter):
    def __init__(self, devices):
        super().__init__(devices)

        if domoticz.get_plugin_config('useBatteryDevices'):
            self.devices.append(VoltageSensor(devices, 'cell', 'battery_voltage', ' (Battery Voltage)'))
            self.devices.append(PercentageSensor(devices, 'btperc', 'battery', ' (Battery)'))
            self.devices.append(ContactSensor(devices, 'btlow', 'battery_low', ' (Battery Low)'))

    def update_battery_status(self, device_data, message):
        if domoticz.get_plugin_config('useBatteryDevices') == False:
            return

        if 'battery_low' in message.raw:
            device = self.get_device_by_alias('btlow')
            device.handle_message(device_data, message)

        if 'battery_voltage' in message.raw:
            device = self.get_device_by_alias('cell')
            device.handle_message(device_data, message)

        if 'battery' in message.raw:
            device = self.get_device_by_alias('btperc')
            device.handle_message(device_data, message)

    def convert_message(self, message):
        message = super().convert_message(message)

        if 'voltage' in message.raw:
            message.raw['battery_voltage'] = message.raw['voltage'] / 1000

        return message

**Comment by stas-demydiuk** [comment]
Closed in favor of #513
