### ISSUE TITLE
Xiaomi Window Sensor Multiple Devices?

### ISSUE THREAD

**Issue by joshdinsdale** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#54]
Hi Guys

Finally got the components and go this up and running, very excited!

Anyway I've added my first device, a Xiaomi Window Sensor. Its added the device fine, but I also get two additional devices, one which is link quality and another which is battery voltage. Is this correct behaviour and can I remove these from Domoticz?
Also, if I remove these additionals, will the sensor alert Domoticz on Low battery?

Many Thanks

Josh

**Comment by stas-demydiuk** [comment]
@joshdinsdale these additional devices is required to monitor additional device stats. If you remove additional devices, plugin will recreate them after next restart
