### ISSUE TITLE
Add support for `local_temperature_calibration` feature

### ISSUE THREAD

**Issue by salopette** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#541]
Hello Stas, battery error message is already known on many devices. Now there is also the message from local_temperature_calibration.

```
2021-01-05 15:32:07.699 Error: (z2m) Juli-TRV: can not process binary item "battery_low"
2021-01-05 15:32:07.700 Error: (z2m) Juli-TRV: can not process numeric item "local_temperature_calibration"
2021-01-05 15:38:49.585 (z2m) {"access": 1, "description": "Indicates if the battery of this device is almost empty", "name": "battery_low", "property": "battery_low", "type": "binary", "value_off": false, "value_on": true}
2021-01-05 15:38:49.585 (z2m) {"access": 3, "description": "Offset to be used in the local_temperature", "name": "local_temperature_calibration", "property": "local_temperature_calibration", "type": "numeric", "unit": "\u00b0C"}
```

Local temperature calibration feature
```
{
   "access":3,
   "description":"Offset to be used in the local_temperature",
   "name":"local_temperature_calibration",
   "property":"local_temperature_calibration",
   "type":"numeric",
   "unit":"\u00b0C"
}
```

**Comment by stas-demydiuk** [comment]
`battery_low` feature will be covered in #513

**Comment by Bartekn86** [comment]
and other finctions, too please 
![Bez tytułu](https://user-images.githubusercontent.com/69695376/104806630-41e55380-57d9-11eb-8e6d-d89b994e15f7.png)

**Comment by Bartekn86** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69695376/104806646-56295080-57d9-11eb-9126-ece2b1cd61b4.png)

**Comment by Bartekn86** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/69695376/104806659-722cf200-57d9-11eb-9029-2f35638ec684.png)

**Comment by salopette** [comment]
![sshot-1](https://user-images.githubusercontent.com/32480002/104806754-1f076f00-57da-11eb-840c-de0afed053e8.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/104806755-1fa00580-57da-11eb-8656-ad074072667d.jpg)

**Comment by Bartekn86** [comment]
that photo you just send (ts601) is not all functions that are in valve - Koenkk make a web panel - there are probably all functions

**Comment by stas-demydiuk** [comment]
@salopette / @Bartekn86 what Domoticz control would you expect to control this parameter as Domoticz doesn't have native number input control. I guess another thermostat device could be used for that but I'm not sure

**Comment by salopette** [comment]
for local_temperature_calibration maybe something like +/-? or simply where you can enter a value yourself in 0.5 steps.

**Comment by SargonofAssyria** [comment]
Now I think about it. Should not this "local_temperature_calibration" be solved in Z2M because it is a one time setting like in other temperature devices?
