### ISSUE TITLE
Device NAS-AB02B0 is missing duration.

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#545]
This device https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html#neo-nas-ab02b0 is missing the exposed duration.
Please add it.
{
  "alarm": false,
  "duration": 10,
  "humidity": 36,
  "last_seen": "2021-01-07T17:16:37+01:00",
  "linkquality": 48,
  "humidity": 37,
  "last_seen": "2021-01-07T17:16:40+01:00",
  "linkquality": 51,
  "melody": 14,
  "temperature": "22.3",
  "temperature_alarm": false,
  "volume": "low"
}

And there are some other settings exposed. Like temperature_max and temperature_min and humidity_max and humidity_min
{
  "alarm": false,
  "humidity": 36,
  "humidity_max": 80,
  "humidity_min": 20,
  "last_seen": "2021-01-07T17:19:35+01:00",
  "last_seen": "2021-01-07T17:19:41+01:00",
  "linkquality": 138,
  "melody": 14,
  "temperature": "22.3",
  "temperature_alarm": false,
  "temperature_max": 35,
  "temperature_min": 5,
  "volume": "low"
}

**Comment by stas-demydiuk** [comment]
Could you please post the data about device from zigbee2mqtt, including exposed features
