### ISSUE TITLE
GLEDOPTO GL-C-008 / GL-S-008Z

### ISSUE THREAD

**Issue by ArJay60** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#55]
**Device description**
GLEDOPTO dimmer for rgbww strip / E27 RGBWW spot

**MQTT message with device information**
{"ieeeAddr":"0x00124b001b6aeae5","type":"Router","model":"GL-C-008","friendly_name":"Kleur_1"}]

**Comment by stas-demydiuk** [comment]
@ArJay60 could you please update plugin and check?

**Comment by ArJay60** [comment]
Hi Stas, No new device appearing in Domoticz. although it says creating the device. This is what the verbose logs in Domoticz says about the device (Kleur_1) is the friendly name I gave the device:

2018-12-22 14:06:10.270 (Zigbee @ PI) Device GL-C-008 0x00124b001b6aeae5 (Kleur_1)
2018-12-22 14:06:10.270 (Zigbee @ PI) Creating domoticz device to handle "linkquality" key for device with ieeeAddr 0x00124b001b6aeae5
2018-12-22 14:06:10.271 (Zigbee @ PI) Creating device 'Kleur_1 (Link Quality)'.
2018-12-22 14:06:10.271 (Zigbee @ PI) Creating domoticz device to handle "state_brightness_color" key for device with ieeeAddr 0x00124b001b6aeae5
2018-12-22 14:06:10.271 (Zigbee @ PI) Creating device 'Kleur_1'.

**Comment by stas-demydiuk** [comment]
They should appear on devices page after this, where you can manually set whether device is used or not. Have you checked the devices page?

**Comment by ArJay60** [comment]
Yes. Checked it. Other devices (earlier added) where found. see part of devices page for found devices:

324 | Zigbee @ PI | 0x00158d0002b95e6d_lux | 3 | Zigbee @ PI - Beweging | Lux | Lux | 52 Lux | 3 | 100 |   | 2018-12-23 14:04:39
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 323 | Zigbee @ PI | 0x00158d0002b95e6d_motion | 2 | Zigbee @ PI - Beweging | Light/Switch | Switch | Off | 3 | 100 |   | 2018-12-23 14:04:39
  | 322 | Zigbee @ PI | 0x00158d0002722cc0_sensor | 1 | Zigbee @ PI - Voordeur | Light/Switch | Switch | Closed | 2 | 100 |   | 2018-12-23 14:10:20

I don't know why the GL-C-008 doesn't.

**Comment by ArJay60** [comment]
Hoi Stas. My problem. I had to set open Domoticz for recognizing new devices on the Settings/System page. I didn't expect it being sensitive for that. Issue solved. Start testing the LED bulb let you know i it's working fine.

**Comment by ArJay60** [comment]
Everything works fine. Thanks for the integration Stas.

**Comment by ArJay60** [comment]
Hoi Stas. I have an additional issue here. If the light is switched on in Domoticz it does not maintain its status in Domoticz. It always says it is off.  If the light intensity is set with the slider in the Dimmer and you refresh the screen the set value is lost. So you can set al kind of settings, (and that is fine) but if you later come back in Domoticz the status is not maintained. So in Domoticz yoy can't see if the light is set to on. Can something be done about that?

**Comment by stas-demydiuk** [comment]
@ArJay60 could you please check in zigbee2mqtt log if device sends message with current status right after you update it?

**Comment by ArJay60** [comment]
HI Stas,

Switching off the bulb is giving these lines in the log (the second line after 30 secs). Bulb is reacting correct by going off.

2019-1-7 16:55:48 - info: Zigbee publish to '0x00124b001b6aeb31', genOnOff - off - {} – null
……
2019-1-7 16:56:18 - error: Zigbee publish to '0x00124b001b6aeb31', genOnOff - off - {} - null failed with error Error: Timed out after 30000 ms


Switching the bulb to a certain setting give the next lines, with the last tree again after 30 secs. Bulb is going to correct setting.

2019-1-7 17:12:32 - info: Zigbee publish to '0x00124b001b6aeae5', genOnOff - on - {} - null
2019-1-7 17:12:32 - info: Zigbee publish to '0x00124b001b6aeae5', genLevelCtrl - moveToLevel - {"level":2,"transtime":0} - null
2019-1-7 17:12:32 - info: Zigbee publish to '0x00124b001b6aeae5', lightingColorCtrl - moveToColorTemp - {"colortemp":491,"transtime":0} – null
…
2019-1-7 17:14:14 - error: Zigbee publish to '0x00124b001b6aeae5', genOnOff - on - {} - null failed with error Error: Timed out after 30000 ms
2019-1-7 17:14:14 - error: Zigbee publish to '0x00124b001b6aeae5', genLevelCtrl - moveToLevel - {"level":2,"transtime":0} - null failed with error Error: Timed out after 30000 ms
2019-1-7 17:14:14 - error: Zigbee publish to '0x00124b001b6aeae5', lightingColorCtrl - moveToColorTemp - {"colortemp":491,"transtime":0} - null failed with error Error: Timed out after 30000 ms

May I conclude that Zigbee2MQTT is awaiting at status message on the commands but is not getting that within a certain time?

**Comment by stas-demydiuk** [comment]
Yes looks like a connection issue between your stick and device because zigbee2mqtt doesn't receive response on control commands
```
2019-1-7 17:14:14 - error: Zigbee publish to '0x00124b001b6aeae5', lightingColorCtrl - moveToColorTemp - {"colortemp":491,"transtime":0} - null failed with error Error: Timed out after 30000 ms
```

**Comment by ArJay60** [comment]
Hi Stas.

Updated zigbee2mqtt and is now receiving state info (at least on-off)
2019-1-7 19:58:44 - info: Zigbee publish to '0x00124b001b6aeae5', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - 12
2019-1-7 19:58:44 - info: MQTT publish: topic 'zigbee2mqtt/Kleur_1', payload '{"state":"On"}'

Will  go further into zigbee2mqtt. I expect that things like color or colortemp or level also need to come from there. Thanks for putting me on track.
