### ISSUE TITLE
Please add extra support for Xiaomi ZNCZ02LM

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#551]
Please add extra support for https://www.zigbee2mqtt.io/devices/ZNCZ02LM.html#xiaomi-zncz02lm
The error in Domoticz is:
2021-01-17 15:34:29.698 Error: (Zigbee) UPS: can not process numeric item "energy"
2021-01-17 15:34:29.699 Error: (Zigbee) UPS: can not process binary item "power_outage_memory"

This is exposed:
![2021-01-17_18-54-26](https://user-images.githubusercontent.com/24824113/104851480-7c441300-58f5-11eb-831d-4f49d57744e5.png)

**Additional information**
Zigbee2MQTT version:
Python version: 3.7.3.
Domoticz version: 2020.2 build 12844
Plugin version: 3.0.0. latest.

**Logs**
info  2021-01-17 18:55:00: MQTT publish: topic 'zigbee2mqtt/UPS', payload '{"consumption":26.54,"energy":26.54,"last_seen":"2021-01-17T18:55:00+01:00","linkquality":132,"power":0,"state":"OFF","temperature":30,"voltage":221}'

**Comment by stas-demydiuk** [comment]
Support for `power_outage_memory` has been in scope of #547, please upgrade plugin and check. Looks like all features of the device are currently supported by plugin

**Comment by SargonofAssyria** [comment]
Tnx, the power_outage_memory is present as a device. So this device is complete now.
