### ISSUE TITLE
Ksentry Electronics KS-SM001

### ISSUE THREAD

**Issue by njkavon** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#554]
**Device description**
Zigbee OnOff Controller; Ksentry Electronics KS-SM001

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/KS-SM001.html

**MQTT message with device information**
```
{"description": "-", "friendly_name": "0x00124b002265e1b7", "ieeeAddr": "0x00124b002265e1b7", "lastSeen": 1611317403220, "manufacturerID": 0, "networkAddress": 27310, "type": "Router", "vendor": "-"}]}```

Thanks!

**Comment by stas-demydiuk** [comment]
This device is already supported. Please make sure you are using the latest plugin version from `master` branch

**Comment by njkavon** [comment]
I made the update right before posting, I'll look into it further. Thank you.
