### ISSUE TITLE
Get https working on other port than 8883

### ISSUE THREAD

**Issue by dgrostoto** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#555]
Hello,

could it be possible to have a field in plugin configuration (hardware tab in domoticz), that let choose between mqtt and mqtts
instead of the code in mqtt.py : 
Protocol="MQTTS" if self.port == "8883" else "MQTT"
?

Thanks in advance for your response.

**Comment by stas-demydiuk** [comment]
Unfortunately, there is no free config fields left for the plugin setup
