### ISSUE TITLE
Wrong Domoticz UI folder

### ISSUE THREAD

**Issue by Freekers** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#556]
**Issue description**
I installed the plugin according to the README. The plugin itself works; devices can be added and work as intended. However, the UI (to, for example, show the network map) does not show up. The entire 'Custom --> Zigbee2MQTT' menu is missing

I'm running Domoticz 2020.2 as Docker using the amd64 image by LinuxServer.io: https://github.com/linuxserver/docker-domoticz . Python is available/installed in the Docker image (Python3.8 + Python3.9).

**Additional information**
Zigbee2MQTT version: Latest
Python version: 3.8+3.9
Domoticz version: 2020.2
Plugin version: Latest (v0.2.1)

**Logs**
No errors or warning in logs.

**Comment by stas-demydiuk** [comment]
Maybe it is related to the image you use. You could check my image which I use for my Domoticz instance, hopefully, there will be no issues https://hub.docker.com/repository/docker/demydiuk/domoticz/general

**Comment by Freekers** [comment]
I tried your Docker image and indeed, it works; the custom page with the map etc shows up using your image.
I compared your image to the LinuxServer.io image and found the following:

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/27f689cd538e3ddfb113f5a5df8152f9e9c9f804/plugin.py#L207
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/blob/27f689cd538e3ddfb113f5a5df8152f9e9c9f804/plugin.py#L208

In your Docker, the paths are as follows:
`source_path = os.path.dirname(os.path.abspath(__file__)) + '/frontend'` corresponds to: `/opt/domoticz/plugins/zigbee2mqtt/frontend`
`templates_path = os.path.abspath(source_path + '/../../../www/templates')` corresponds to: `/opt/domoticz/www/templates`

But with LinuxServer.io Docker, the paths are different, namely:
`source_path = os.path.dirname(os.path.abspath(__file__)) + '/frontend'` corresponds to: `/config/plugins/zigbee2mqtt/frontend`
`templates_path = os.path.abspath(source_path + '/../../../www/templates')` corresponds to: `/config/plugins/www/templates` but that path does not exist.
Instead, it should be: `/usr/share/domoticz/www/templates`

So to make it work with LinxuServer.io Docker there are two approaches
1. First check if the templates_path exist before copying the files
2. Symbolic link between `/usr/share/domoticz/www/templates` and `/opt/domoticz/www/templates`, like so: `ln -s /usr/share/domoticz/www/templates /opt/domoticz/www/templates`

**Comment by DavidTre07** [comment]
For your information there is the same problem with the official Domoticz docker image (domoticz/domoticz).
The paths are differents.

**Comment by stas-demydiuk** [comment]
Now should be better. Could you please update plugin and check

**Comment by DavidTre07** [comment]
I tested it but it seems I don't know how to update the plugin...
What I've done:
- From the plugins manager page clicked on the trash icon
- On disk removed the folder plugins-manager in plugins
- Restarted domoticz

Still the custom menu is there with Plugins Manager in it, but doesn't work. Which is the expected behaviour as I removed the folder.

Next steps I've done:
- Switched off domoticz
- Git cloned this repo in the plugin folder
- Switched on domoticz

But domoticz do nothing with the plugin, it's seems it doesn't see it...
I tried to chmod +x plugin.py, restarted domoticz but nothing more append...

I'm probably doing something bad but I don't know what...

**Comment by olivierberthomme** [comment]
Duplicate #490

**Comment by Freekers** [comment]
> 
> 
> Now should be better. Could you please update plugin and check

I updated the plugin using `git pull` and restarted Domoticz. Now the Custom --> Zigbee2Mqtt page shows up, but none of the three tabs are working. All show 'Loading...' like in the screenshot below. Zigbee2Mqtt devices work and there is no error in the logging

https://i.imgur.com/Tf4sYSC.png

**Comment by stas-demydiuk** [comment]
@Freekers please check that websocket connection in Domoticz works properly in your setup. Anyway this issue isn't related to the original one, so closing the ticket.

**Comment by olivierberthomme** [comment]
> 
> 
> Now should be better. Could you please update plugin and check

Perfectly working for me (linux server domoticz image on synology). Many thanks ! 👍
