### ISSUE TITLE
SONOFF SNZB-04 contact open/close reversed at v3.0

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#557]
A fix was supplied at 0.2.1 (see issue #378 ) so that this device correctly reported its open/close state in domoticz. At v3.0 that behaviour has reappeared - the contact shows as open when it's closed and closed when it's open.

I have tried completely deleting the device and re-pairing it etc.

the zigbee2mqtt.io messages report the state correctly; for example for closed it reports: -

{
    "battery": 100,
    "battery_low": false,
    "contact": true,
    "tamper": false,
    "voltage": 3200,
    "device": {
        "applicationVersion": 3,
        "dateCode": "20191107",
        "friendlyName": "TEST.CONTACT",
        "hardwareVersion": 1,
        "ieeeAddr": "0x00124b001f90ef20",
        "manufacturerID": 0,
        "manufacturerName": "eWeLink",
        "model": "SNZB-04",
        "networkAddress": 15442,
        "powerSource": "Battery",
        "type": "EndDevice",
        "zclVersion": 1
    },
    "linkquality": 147
}

.. and for open it reports: -

{
    "battery": 100,
    "battery_low": false,
    "contact": false,
    "tamper": false,
    "voltage": 3200,
    "device": {
        "applicationVersion": 3,
        "dateCode": "20191107",
        "friendlyName": "TEST.CONTACT",
        "hardwareVersion": 1,
        "ieeeAddr": "0x00124b001f90ef20",
        "manufacturerID": 0,
        "manufacturerName": "eWeLink",
        "model": "SNZB-04",
        "networkAddress": 15442,
        "powerSource": "Battery",
        "type": "EndDevice",
        "zclVersion": 1
    },
    "linkquality": 147
}

**Comment by stas-demydiuk** [comment]
Could you please also provide device definition data. You can find it in the zigbee2mqtt response with the list of your devices

**Comment by hughb8on** [comment]
I think this is what you want

{"dateCode":"20191107","description":"Contact sensor","friendly_name":"TEST.CONTACT","hardwareVersion":1,"ieeeAddr":"0x00124b001f90ef20","lastSeen":1611822485250,"manufacturerID":0,"manufacturerName":"eWeLink","model":"SNZB-04","modelID":"DS01","networkAddress":15442,"powerSource":"Battery","type":"EndDevice","vendor":"SONOFF"}

**Comment by stas-demydiuk** [comment]
the most important property `definition` is missed there. Are you sure you use zigbee2mqtt 1.17?

**Comment by hughb8on** [comment]
Yes definitely 1.17. Here’s another try: -

{"date_code":"20191107","definition":{"description":"Contact sensor","exposes":[{"access":1,"description":"Indicates if the contact is closed (= true) or open (= false)","name":"contact","property":"contact","type":"binary","value_off":true,"value_on":false},{"access":1,"description":"Indicates if the battery of this device is almost empty","name":"battery_low","property":"battery_low","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Indicates whether the device is tampered","name":"tamper","property":"tamper","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"SNZB-04","vendor":"SONOFF"},"endpoints":{"1":{"bindings":[{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b001caabd48","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","ssIasZone","genPowerCfg"],"output":["genIdentify"]},"configured_reportings":[{"attribute":"batteryVoltage","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}]}},"friendly_name":"TEST.CONTACT","ieee_address":"0x00124b001f90ef20","interview_completed":true,"interviewing":false,"model_id":"DS01","network_address":15442,"power_source":"Battery","supported":true,"type":"EndDevice"}

**Comment by stas-demydiuk** [comment]
Yes, that's what I need. Updated plugin, could you please update and check

**Comment by hughb8on** [comment]
Hi, yes, that fixes the problem. Thank you!
