### ISSUE TITLE
Device list doesn't load when legacy_api set to false

### ISSUE THREAD

**Issue by lwalbert** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#560]
**Issue description**
When setting legacy_api : false in Zigbee configuration.yaml and restarting zigbee2mqtt service, the device list doesn't load any more.
<img width="1247" alt="Skjermbilde 2021-02-03 kl  09 56 00" src="https://user-images.githubusercontent.com/64552548/106723713-b147a980-6607-11eb-9d21-2ab8017ace37.png">

Setting legacy_api: true, and restart zigbee2mqtt service, the device list loads again.
<img width="1200" alt="Skjermbilde 2021-02-03 kl  09 57 17" src="https://user-images.githubusercontent.com/64552548/106723965-f8ce3580-6607-11eb-9e3d-9d0340f349c6.png">

**Additional information**
Zigbee2MQTT version: v.1.17.0 (ConBee2/RaspBee2 0x264a0700)
Python version: 3.7.3
Domoticz version: V2020.2 (build 12896)
Plugin version: (Zigbee) Initialized version 3.0.0

**Comment by Anjerlaan** [comment]
Why do you want legacy api? In >1.17.0 the new api is mandatory, so you can remove the line from configuration.yaml

**Comment by lwalbert** [comment]
Hi @Anjerlaan, thanks for reply.
Well, logically I believe setting a parameter (true/false) eg. legacy_api = false means I don't want it.
I found that default setting for the legacy_api is true if not set in configuration.yaml
So by removing the setting in configuration it will become true.

Br
Lennart

**Comment by Anjerlaan** [comment]
> Hi @Anjerlaan, thanks for reply.
> Well, logically I believe setting a parameter (true/false) eg. legacy_api = false means I don't want it.
> I found that default setting for the legacy_api is true if not set in configuration.yaml
> So by removing the setting in configuration it will become true.
> 
> Br
> Lennart

If you remove this line in configuration.yaml, the new API is true...you don't need this line to tell you want to use the new API.

Try it and see if the list is populated

**Comment by Anjerlaan** [comment]
By the wat did you follow the Guise by deleting the plug-in first in the domoticz hardware tab?

**Comment by lwalbert** [comment]
Hi, the plugin works great.
 
After som further checks, issue seems to origin from zigbee2mqtt not reporting devices to plugin when legacy_api = false.
So I should probably ask the question in zigbee2mqtt forum.

Anyway the default value of legacy_api is actually true by default.
if you check /opt/zigbee2mqtt/lib/util/settings.js:
<img width="476" alt="Skjermbilde 2021-02-07 kl  19 58 52" src="https://user-images.githubusercontent.com/64552548/107156712-41774d00-6980-11eb-93d0-acd302d10975.png">
<img width="768" alt="Skjermbilde 2021-02-07 kl  20 25 43" src="https://user-images.githubusercontent.com/64552548/107157141-c6636600-6982-11eb-9d50-4631032b3606.png">

so removing the legacy_api from configuration.yaml is the same as adding the legacy_api = true. ;-)

You can try adding legacy_api = false, restart service and see if it works as expected.

But as mentioned, the plugin works great, so I'm closing this issue :)

Br
Lennart
