### ISSUE TITLE
Osram Smart+ issue

### ISSUE THREAD

**Issue by jvrrr** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#565]
Hi,

I installed the latest version of this plugin, after that the Osram Smart+ plug does not work anymore.
When I try to switch it on or off in Domoticz it does not work.
But after I change the type of switch from "on/off" to "push on" button, I'm abele to switch it on. (and if I switch the type to "push off" button I can switch it off)

How can I fix this?

Kind regards,
Jasper

**Comment by d-EScape** [comment]
Hi Jasper,

This can probably be solved by allowing the creation of new devices in the domoticz settings and restarting the plugin. Manually delete the obsolete devices afterwards. 
I think the release notes warned us about changes that might require devices te be recreated.

You do not need te re-pair them (that would only be needed if this was an zigbee2mqtt issue and it is not). Just recreate devices in domoticz.

The latest version seems to have changed some names. The working device for the Osram plug is now called xxxxxx_state. Before that it was xxxxxxxx_switch. I don't know why this has been changed for the Osram plug and not for other plugs. My innr plugs still use _switch.

**Comment by jvrrr** [comment]
I removed the device from zigbee2mqtt and from Domoticz.  The I reinstalled the device...still same result.

**Comment by jvrrr** [comment]
Okay, did some testing...
It looks like the status of the switch is not detected.

If the switch is OFF, I can switch it ON, but it is not showing it is ON. (It stays grey and it not showing red)
Result is that I'm not able to switch it OFF...because Domoticz is thinking it is Off

Thanks again

**Comment by jvrrr** [comment]
I could not wait .....   ;-)

I went to .../domoticz/plugins/zigbee2mqtt/adapters/osram/ and replace te files with a older version.
The adapters are working fine again.

So there is realy a bug in one of these files.

**Comment by d-EScape** [comment]
I have three of those Osram plugs that are recognized as AB3257001NJ. Besides the naming change I described they are all working without any issues. To further investigate your issue I have just updated both zigbee2mqtt and the zigbee2mqtt plugin to the latest stable version and domoticz to the latest beta. The plugs just kept working through all those separate updates. 
The domoticz device operating the plug has an id like:  0x84182600000aa11a_state.

I don't know what's going wrong in your setup, but it does nog seem to be a bug in the plugin. Using an older version of the adapter file would probably work around the naming issue, but since you completely recreated the devices the names should already match. Did you try updating zigbee2mqtt itself? Maybe there is some other weird mismatch(?)

**Comment by jvrrr** [comment]
Thanks for your answer!

I use:
Version of Zigbee2Mqtt: 1.17.1
Coordinator version: CC1352P-2   20210120 
Domoticz: Version: 2020.2 (I'm not sure the last beta's are stable enough for daily use?!?So I use the last stable release.)
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

Model is Plug 01 by OSRAM.
Hardware version is 1.
Firmware version is V1.05.09.
This device type is Router

**Comment by d-EScape** [comment]
We have different controllers and domoticz versions, but I don't think those differences would explain the different behaviour.
Can you test this:
After a clean install of the latest version of the plugin, removing the existing devices in Domoticz related to the Osram plug and restarting Domoticz. Check if a device has been created on Domoticz with an id like 0x84182600000aa11a_state (ending with _state). What are Domoticz and zigbee2mqtt log messages when you try to operate the device from Domoticz?

**Comment by jvrrr** [comment]
I have updated te plugin and zigbee2mqtt to 18.1
After that I remove the Osram switches and reinstall them. 

Now they have _state at the end and they are function now.

Thanks a lot!!!
