### ISSUE TITLE
remote control LeTv 

### ISSUE THREAD

**Issue by NE8XT** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#568]
Hey! Stas, please add the remote control LeTv to the plugin 
https://www.zigbee2mqtt.io/devices/FreePad_LeTV_8.html

**Comment by stas-demydiuk** [comment]
Any useful data in the Log?

**Comment by NE8XT** [comment]
Z2M button8 and button1 as as a sample :
Zigbee2MQTT:info  2021-02-11 13:21:41: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_single","battery":47,"linkquality":51,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:45: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_double","battery":47,"linkquality":54,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:48: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_triple","battery":47,"linkquality":57,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:51: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_quadruple","battery":47,"linkquality":54,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:55: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_hold","battery":47,"linkquality":51,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:56: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"battery":46,"linkquality":51,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:21:56: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_8_release","battery":46,"linkquality":51,"voltage":2900}'

Zigbee2MQTT:info  2021-02-11 13:22:01: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"battery":46,"linkquality":75,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:36: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_single","battery":46,"linkquality":69,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:39: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_double","battery":46,"linkquality":66,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:43: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_triple","battery":46,"linkquality":15,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:48: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_quadruple","battery":46,"linkquality":27,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:51: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_hold","battery":46,"linkquality":42,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:52: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"action":"button_1_release","battery":46,"linkquality":21,"voltage":2900}'
Zigbee2MQTT:info  2021-02-11 13:22:57: MQTT publish: topic 'zigbee2mqtt/0x00124b000adb10c9', payload '{"battery":63,"linkquality":78,"voltage":2900}'

**Comment by NE8XT** [comment]
![image](https://user-images.githubusercontent.com/77930301/111772019-ab9ede00-88ac-11eb-9d27-5718c2c44f15.png)

**Comment by NE8XT** [comment]
![123](https://user-images.githubusercontent.com/77930301/113470614-47a51980-9457-11eb-9673-9ea550a7982a.jpg)
