### ISSUE TITLE
Plugin stop working

### ISSUE THREAD

**Issue by detxm80** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#57]
hi guys, issue come back:

when restart domoticz service, sometimes plugin start correctly but not receive data from zigbee2mqtt that send info right.

**Comment by guykes83** [comment]
Hello,

First of all, thanks for your great work @stas-demydiuk!

I'm afraid I'm having a bit of the same, difficult to analyze, issue. I'm running the latest stable domoticz together with zigbee2mqtt (master branch) and the domoticz plugin. When I start the domoticz-service, everything works great, but after 1-1,5 days, domoticz becomes unresponsive.

At first, I restarted my RPI and everything was working again. Later I found out that the zigbee2mqtt service remains running correctly and keeps receiving messages. 

Domoticz however, seems to hang at some point. When I try to open the dashboard, it keeps connecting. However, if I run 'sudo systemctl status domoticz' from bash, it seems that domoticz is running. I can 'resolve' it by simply restarting domoticz ('sudo systemctl stop domoticz' and then 'sudo systemctl start domoticz').

What can I do to figure out what goes wrong?

Many thanks!

Guy

**Comment by stas-demydiuk** [comment]
Since domoticz releases stable versions very rarely, could you please try the same setup with Domoticz beta?

**Comment by detxm80** [comment]
I’m running on beta

**Comment by guykes83** [comment]
Switches to beta, Ill keep jou guy posted 😉
