### ISSUE TITLE
after update to v3.0 doesn't works some xiomi devices

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#571]
**Issue description**
Dear friend, 

After upgrade to v.3.0 zigbe2mqtt-plugin some xiaomi devices doesnt't works. in the previous version v.0.2.1 all works correctly

- Xiaomi WXKG01LM doen't work. when i push the button domoticz don't receive anything in the log (zigbee2mqtt shows correctly the pulsation). Also, i try to force the xiaomi pulsation in the domoticz widget/icon and doesn't work any pulsation. the device has died.

- I hace some xiaomi plugs, when i press the domoticz icon to power on /off the plug, doesn't work. i can see in the log my push but the device doens't works- No message mqtt appears in the log of zigbe2mqtt.

Maybe more devices are failing.

Can you repair the plugin? whats happend in this version? i need to make a downgrade to the previos version 0.2.1 for all my devices works.

Thanks in advanced 

**Additional information**
Zigbee2MQTT version: the last
Python version: 2.7.16 
Python3 version: 3.7.2
Domoticz version: Version: 2020.2 (build 12927)
                              Build Hash: 5c76d5189-modified
                              Compile Date: 2021-02-09 07:56:31
                              dzVents Version: 3.1.4
                              Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Plugin version: 3.0

**Comment by hughb8on** [comment]
When you went from 0.2.1 to v3.0, did you just upgrade (git pull) the new version? Did you also remove the plugin from Domoticz Hardware before the upgrade, and re-add it after?

**Comment by kitopopo** [comment]
Thanks for you repply. I only made git pull for uodate. I didn't remove the plugin . At night i will try to remove the plugin and add again. Thanks

**Comment by hughb8on** [comment]
Just be aware that removing and re-adding the plugin will delete all your zigbee devices. 

If that is a problem then there is an alternative, but it may not work in all cases - which I guess is why the author suggests deleting/re-adding is simplest/safest. If that's the case for you then I suggest you follow his advice, otherwise read on!

Some of your devices, particularly switches and sockets get new names at v3.0. If your Domoticz Settings allow new devices to be created then what you will see is that the plugin has created devices with these new names and stopped using/updating the ones with the old names. 

For example, your Xiaomi switches used to have names ending in "_switch"; these will now have names ending in "_actio". If you find the "_actio" device for your Xiaomi WXKG01LM you will probably find it works perfectly. You could then delete the old "_switch" device (from Domoticz Devices screen).

Similarly, your Xiaomi plugs will, have had names ending with "_switch"; these probably now have names ending with "_state". Again, you are likely to find the new devices work perfectly and you can delete the old ones.

If this doesn't work for you then deleting the plugin and re-adding it definitely *will* work. I have many Xiaomi / Aqara devices and have been very pleased with V3.0.

**Comment by kitopopo** [comment]
> Just be aware that removing and re-adding the plugin will delete all your zigbee devices.
> 
> If that is a problem then there is an alternative, but it may not work in all cases - which I guess is why the author suggests deleting/re-adding is simplest/safest. If that's the case for you then I suggest you follow his advice, otherwise read on!
> 
> Some of your devices, particularly switches and sockets get new names at v3.0. If your Domoticz Settings allow new devices to be created then what you will see is that the plugin has created devices with these new names and stopped using/updating the ones with the old names.
> 
> For example, your Xiaomi switches used to have names ending in "_switch"; these will now have names ending in "_actio". If you find the "_actio" device for your Xiaomi WXKG01LM you will probably find it works perfectly. You could then delete the old "_switch" device (from Domoticz Devices screen).
> 
> Similarly, your Xiaomi plugs will, have had names ending with "_switch"; these probably now have names ending with "_state". Again, you are likely to find the new devices work perfectly and you can delete the old ones.
> 
> If this doesn't work for you then deleting the plugin and re-adding it definitely _will_ work. I have many Xiaomi / Aqara devices and have been very pleased with V3.0.



> Solo tenga en cuenta que eliminar y volver a agregar el complemento eliminará todos sus dispositivos zigbee.
> 
> Si eso es un problema, entonces hay una alternativa, pero puede que no funcione en todos los casos, y supongo que es por eso que el autor sugiere que eliminar / volver a agregar es lo más simple / seguro. Si ese es tu caso, te sugiero que sigas su consejo; de lo contrario, ¡sigue leyendo!
> 
> Algunos de sus dispositivos, en particular conmutadores y enchufes, reciben nuevos nombres en la v3.0. Si su configuración de Domoticz permite la creación de nuevos dispositivos, lo que verá es que el complemento ha creado dispositivos con estos nuevos nombres y dejó de usar / actualizar los que tenían los nombres antiguos.
> 
> Por ejemplo, sus interruptores Xiaomi solían tener nombres que terminaban en "_switch"; estos ahora tendrán nombres que terminen en "_actio". Si encuentra el dispositivo "_actio" para su Xiaomi WXKG01LM, probablemente encontrará que funciona perfectamente. A continuación, puede eliminar el antiguo dispositivo "_switch" (de la pantalla de dispositivos Domoticz).
> 
> De manera similar, sus enchufes Xiaomi tendrán nombres que terminen con "_switch"; estos probablemente ahora tienen nombres que terminan con "_state". Nuevamente, es probable que descubra que los nuevos dispositivos funcionan perfectamente y puede eliminar los antiguos.
> 
> Si esto no funciona para usted a continuación, eliminar el plugin y volver a agregar que sin duda _va a_ trabajar. Tengo muchos dispositivos Xiaomi / Aqara y estoy muy satisfecho con V3.0.

Hi dear @hughb8on , thanks for your answer, 

Now all devices works correctly with v3.0.  What does power outage memory in the xiaomi plugs mean? 

By the way, we have lost the many clicks function in the xiaomi switch (WXKG01LM). this type of clicks is very useful and is detected by domoticz as "many" but the error appears (zigbe2mqtt) Unable to find selector switch level for value "many" Could you or @stas-demydiuk add this type of click in position 70 (for example) of the selector? If you need it, I can open a new request to add a new function to a device.

thanks in advanced

Best regars

**Comment by hughb8on** [comment]
Hi, I'm not a developer, I'm just a user like yourself, so I can't help with code changes.
Look at the description for your plug at zigbee2mqtt.io to find out what the options for power-on behaviour are.

**Comment by kitopopo** [comment]
Ok. Thanks for your answer. Best regards
