### ISSUE TITLE
many clicks were loss with plugin zigbee2mqtt v.3.0 update in the Xiaomi WXKG01LM 

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#572]
Dear @stas-demydiuk ,

I have tested the new plugin v3.0 with domoticz. In the Xiaomi WXKG01LM . We have lost the many clicks function in the xiaomi switch (WXKG01LM). this type of clicks is very useful and is detected by domoticz as "many" but the error appears:

`(zigbe2mqtt) Unable to find selector switch level for value "many" `

Could you add this type of click in position 70 (for example) of the selector? 

Thanks in advanced

**Comment by stas-demydiuk** [comment]
Could you please provide target device definition from zigbee2mqtt log

**Comment by kitopopo** [comment]
thanks for answer, this is the zigbe2mqtt log:

feb 10 23:02:15 raspberrypi npm[486]: Zigbee2MQTT:info  2021-02-10 23:02:15: MQTT publish: topic 'zigbee2mqtt/Switch mesita', payload '{"action":"many","battery":100,"linkquality":76,"voltage":3072}'

It is a function that was already implemented in the previous version 0.2.1. with the update to version v3.0 the plugin has disappeared

thanks in advanced.

Best regards

**Comment by stas-demydiuk** [comment]
Starting from 3.0 plugin doesn't implement individual behavior for each device, now it uses the definition provided by zigbee2mqtt to create appropriate devices in Domoticz (see #458).

In order to check wherever there is an error, I need this definition. You could take it from the message with all devices that zigbee2mqtt sends

**Comment by kitopopo** [comment]
> Starting from 3.0 plugin doesn't implement individual behavior for each device, now it uses the definition provided by zigbee2mqtt to create appropriate devices in Domoticz (see #458).
> 
> In order to check wherever there is an error, I need this definition. You could take it from the message with all devices that zigbee2mqtt sends

Dear friend @stas-demydiuk ,

I made the query to Mr. koenkk (zigbe2mqtt) but he does not know what "definition provided by zigbee2mqtt - target device" you refers to. 
Could you explain how I can get this definition? I have tried to find information but I do not understand anything. The "many click" type of click was already working in the previous version of the plugin- 

Thanks in advance

Best regards

**Comment by stas-demydiuk** [comment]
You need to do the following steps:
1. Connect to mqtt server via any mqtt client
2. Subscribe to `zigbee2mqtt/bridge/#` topic
3. After that you'll receive message with topic `zigbee2mqtt/bridge/devices` and with all your devices in the body
4. Find a record about your Xiaomi WXKG01LM device
5. In this record find `definition` property and post it here

The additional information you could find here: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgedevices

**Comment by kitopopo** [comment]
thanks for your answer @stas-demydiuk , i found this:

`{"definition":{"description":"MiJia wireless switch","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single","double","triple","quadruple","hold","release"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"WXKG01LM","vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"Switch salon","ieee_address":"0x00158d000418cd86","interview_completed":true,"interviewing":false,"model_id":"lumi.sensor_switch","network_address":24485,"power_source":"Battery","supported":true,"type":"EndDevice"},{"date_code":"20161128",`

The strange thing is that in the definition the type of click is not defined "many click" but when I make a physical push of the switch "many clicks" I can read this message in zigbe2mqtt

`feb 12 10:41:26 raspberrypi npm[486]: Zigbee2MQTT:info  2021-02-12 10:41:26: MQTT publish: topic 'zigbee2mqtt/Switch mesita', payload '{"action":"many","battery":100,"linkquality":86,"voltage":3072}'
`
I understand that this push still works but it is not included in the new v3.0 plugin. And as I have already told you in the version prior to the v3.0 plugin, this function worked correctly. If I go back to the previous version of the plugin this type of click works correctly, i attach some pictures

Thanks in advanced.

Best regards

![foto1](https://user-images.githubusercontent.com/51416982/107753034-d337df00-6d1f-11eb-9dbe-93f90c56dbb7.jpg)
![foto2](https://user-images.githubusercontent.com/51416982/107753042-d632cf80-6d1f-11eb-833f-91946aa02757.jpg)

**Comment by kitopopo** [comment]
Dear @stas-demydiuk ,

It can be seen in the picture that we have lost the 70 position of the selector switch with respect to that of the previous plugin version 0.2.1.
If you need it, can I ask @koenkk to modify the zigbe2mqtt definition of the switch due to it doensn't appear "many clicks" in the zigbee2mqtt definition? I await your news, thanks in advance

Best regards

![switch](https://user-images.githubusercontent.com/51416982/107872892-0f994580-6eae-11eb-9b12-12a1a03a9a3d.jpg)

**Comment by stas-demydiuk** [comment]
Yes, the plugin relies on values of this feature:

```
{
  "access":1,
  "description":"Triggered action (e.g. a button click)",
  "name":"action",
  "property":"action",
  "type":"enum",
  "values":[
     "single",
     "double",
     "triple",
     "quadruple",
     "hold",
     "release"
  ]
 },
```

As you can see there is no `many` or any other additional value available. So, please ask zigbee2mqtt authors for required changes

**Comment by kitopopo** [comment]
dear @stas-demydiuk ,

The dear @Koenkk has modified the definitions/exposes . Can you add again  the "many click" to the v3.0 plugin?
Now the many click works in the level 70 but it is not showed in the domoticz log. 

`2021-02-14 18:50:44.305 Status: dzVents: Info: Handling events for: "Switch salon new", value: ""`

the level 70 also not is showed inside of levels switch in domoticz inside of device (no level 70 appear)

can you implement it? thanks in advanced. Best regards.


`{"definition":{"description":"MiJia wireless switch","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single","double","triple","quadruple","hold","release","many"]},{"access":1,"description":"Measured electrical potential value","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"WXKG01LM","supports_ota":false,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"Switch mesita","ieee_address":"0x00158d00xxxxxxx","interview_completed":true,"interviewing":false,"model_id":"lumi.sensor_switch","network_address":56769,"power_source":"Battery","supported":true,"type":"EndDevice"},

`

**Comment by stas-demydiuk** [comment]
Just remove the switch device from Domoticz and restart the plugin

**Comment by kitopopo** [comment]
thanks dear @stas-demydiuk , now all works correctly.

Thanks a lot.

Best regards
