### ISSUE TITLE
Innr 165 Bulb odd behaviour

### ISSUE THREAD

**Issue by joshdinsdale** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#58]
I have an Innr 165 White bulb as part of my setup, it mostly works, however its status is reported weirdly in domoticz.
When i turn the light on at the socket, it comes on at full brightness (expected behavior), however Domoticz shows the light as off with the dimmer showing 0%. If i move the slider up to say 50%, the light will show as on and the light will dim. However if i then go back to adjust the light a short time later, it will show off and on 0% again (even though its on and at 50% for example). Its like something is just setting the display value to off but not actually triggering the bulb itself..?

**Comment by stas-demydiuk** [comment]
Could you please enable Debug mode for plugin and share your zigbee2mqtt and Domoticz log

**Comment by stas-demydiuk** [comment]
Please reopen the ticket if issue is still occurs
