### ISSUE TITLE
`duration` feature support

### ISSUE THREAD

**Issue by nefsolive** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#582]
**Issue description**
Hello,
I bought it, Neo Siren, like this one https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html, on domoticz, it shows all zigbee2mqtt devices on devices tab, except, the duration of the alarm! On page description, they have the 'duration' and on Z2M Log, they show the duration code insert, but dont appers on domoticz devices.  So I am not able to configure the duration of the alarm.

Can help, how too add the duration?

**Additional information**
Zigbee2MQTT version: Last
Python version: 3.7.3
Domoticz version: 2020.2

**Logs**
Dont have any error on log

**Comment by dobber81** [comment]
It has been asked before. 
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/545#issuecomment-761183554
I think stas-demydiuk never got the answer.

**Comment by nefsolive** [comment]
Hi dobber!
Thanks for the information! I hadn't seen that the question had been asked before.
The duration does not really appear and it was important to be able to set the duration of the alarm.
I will wait if the stas-demydiuk updates so that it can work! I hope. 
Thanks again for the info.

**Comment by dobber81** [comment]
In my case I just set it to 300 in the zigbee2mqtt gui. But a slider in domoticz would be nice!

**Comment by nefsolive** [comment]
Yes it was :) what´s the name off the file i can put the value 300s?

**Comment by dobber81** [comment]
It's no file. It's the gui for zigbee2mqtt. This post has an image of what you are looking for: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/389#issuecomment-748968653

**Comment by nefsolive** [comment]
Ok i see dobber81!  
I go take a look. Thanks.

**Comment by nefsolive** [comment]
dobber81 i see the https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/389#issuecomment-748968653.
Im new whit zigbee2mqtt. 
how did he get to that image in order to change the duration? How to get gui?
Ty

**Comment by dobber81** [comment]
You need to add these lines to your config:
frontend:
  port: 8880
experimental:
  new_api: true

After restart web gui is available on http://ip:8880

**Comment by nefsolive** [comment]
dobber, thank´s for the tips!
i go config the Frontend.

**Comment by nefsolive** [comment]
dobber81, now yes! Duration ON!
And like you say, "slider in domoticz would be nice!" ;)
Ty
