### ISSUE TITLE
WXKG02LM_rev1 SUPPORT

### ISSUE THREAD

**Issue by noureddin212** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#584]
**Device description**
Put general device information here
(zigbee2MQTT) This plugin does not support zigbee device with model "WXKG02LM_rev1" yet

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/WXKG02LM_rev1.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0x00158d0001bd0e35","type":"EndDevice","model":"WXKG01LM","friendly_name":"0x00158d0001bd0e35"}
```
Zigbee2MQTT:info  2021-02-16 03:18:58: MQTT publish: topic 'zigbee2mqtt/xia_swi_Chambre_free', payload '{"action":"single_left","battery":100,"click":"left","linkquality":81,"voltage":3015}'
  '0x00158d000170da9a':
    friendly_name: xia_swi_Chambre_free

cAN YOU PLEASE help

**Comment by stas-demydiuk** [comment]
This device is supported. Please make sure you are using the latest plugin and zigbee2mqtt versions
