### ISSUE TITLE
Is possible to include the groups created in zigbe2mqtt in the domoticz plugin?

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#590]
Hello dear friend @stas-demydiuk ,

 I have a question. Is it possible to include the groups created in zigbe2mqtt in the domoticz plugin?

For example I have 4 philips bulbs and I have created a group in zigbe2mqtt called "lamps". I would like to know if this group of lamps can be added to domoticz since there are 4 equal lamps and for example that I from domoticz moving the color palette or the color circle of the "lamps group" created that I could act on the 4 bulbs at the same time . This is possible? Similar with the hue bridge, i can select my 4 lamps and i can move de color circle an test all colors. i atach a picture of paletee colors.

Thank you for your dedication and support.- Kind regards

![paleta](https://user-images.githubusercontent.com/51416982/108493378-89627200-72a6-11eb-9971-77b769686e2c.jpg)

**Comment by JanJaapKo** [comment]
Hi @kitopopo , please see the front page here on github for the description as it is already supported. You just need to apply the correct suffix to group name to have the plugin pick it up.

**Comment by kitopopo** [comment]
> Hi @kitopopo , please see the front page here on github for the description as it is already supported. You just need to apply the correct suffix to group name to have the plugin pick it up.


Thanks for your answer dear friend, yes , now it is supported:


    Suffix | Device Type | Example

_dimmer | Dimmer Switch | mygroup_dimmer

I don't understand if I have to create a virtual dummy in domoticz. My zigbe2mqtt group is called "lamps", so I have created a virtual rgb dimmer dummy called "lamps_dimmer" but it doesn't work, do I have to do something else? thanks in advance I don't really understand how this new feature works

**Comment by JanJaapKo** [comment]
You have to add the suffix to the name of the group in zigbee2mqtt and the plugin will create the domoticz device widget for you, automatically.

**Comment by kitopopo** [comment]
ohh yeaaaahhh, nice feature .thanks very much @JanJaapKo @stas-demydiuk .

Best regads
