### ISSUE TITLE
Python Plugin System: (zigbe2mqtt) MqttClient::ping

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#592]
Dear friend @stas-demydiuk ,

Every 10 seconds i receive in domoticz log the following message:

Python Plugin System: (zigbe2mqtt) MqttClient::ping

if i change the zigbe2mqtt debug to false the message dissapear. your plugin that is polling every 10 seconds?

thanks in advance

Best regards

**Comment by stas-demydiuk** [comment]
It is a system message. Domoticz polls plugin every 10 seconds to check its availability
