### ISSUE TITLE
Cannot see device information

### ISSUE THREAD

**Issue by pedrooliveiraJumia** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#596]
**Issue description**
Hi guys congrats for amazing job!! 
Maybe I am stupid, but on my Domoticz I only get this 

2021-03-03 10:22:21.794 (Zigbee) Received 2 bytes of data
2021-03-03 10:22:21.794 (Zigbee) d0 00 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. Ю

and I cannot decode the information to a sensor in Domoticz.
I am doing something wrong ?

**Additional information**
Zigbee2MQTT version: Last one
Python version:  3.7.3
Domoticz version: 2020.2
Plugin version:

**Comment by stas-demydiuk** [comment]
What kind of device information you need?

**Comment by pedrooliveiraJumia** [comment]
The sensor motion, temperature, humidity. :/

**Comment by stas-demydiuk** [comment]
Could you please tell what actions you've already done and what's the result?

**Comment by pedrooliveiraJumia** [comment]
I have the Tasmota Zigbee on my son off bridge. 
I have installed the Zigbee2MQTT on my domoticz.

**Comment by stas-demydiuk** [comment]
If you mean `Zigbee2Tasmota` then probably it is not compatible with zigbee2mqtt

**Comment by pedrooliveiraJumia** [comment]
Yes Zigbee2Tasmota :/ there is some way to make it work in domoticz ?

**Comment by stas-demydiuk** [comment]
Not with this plugin at least, try to look for another one for zigbee2tasmota
