### ISSUE TITLE
Dimmer EcoDim Eco-Dim.07

### ISSUE THREAD

**Issue by ReneOverkleeft** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#599]
**Device description**
Zigbee & Z-wave wall dimmer Eco-Dim.07

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/Eco-Dim.07.html

**MQTT message with device information**
Device '0x086bd7fffe5cecf6' is supported, identified as: EcoDim Zigbee & Z-wave dimmer  (Eco-Dim.07)

{"dateCode":"20200701","description":"Zigbee & Z-wave dimmer ","friendly_name":"0x086bd7fffe5cecf6","hardwareVersion":1,"ieeeAddr":"0x086bd7fffe5cecf6","lastSeen":1615309065623,"manufacturerID":4714,"manufacturerName":"EcoDim BV","model":"Eco-Dim.07","modelID":"Dimmer-Switch-ZB3.0","networkAddress":63379,"powerSource":"Mains (single phase)","softwareBuildID":"3.09","type":"Router","vendor":"EcoDim"}],"type":"devices"}'

**MQTT messages from device**
zigbee2mqtt:info 2021-03-09 20:58:09 MQTT publish, topic: 'zigbee2mqtt/Dimmer Hal', payload: '{"brightness":79,"linkquality":87,"state":"OFF"}'

zigbee2mqtt:info 2021-03-09 20:59:11 MQTT publish, topic: 'zigbee2mqtt/Dimmer Hal', payload: '{"brightness":79,"linkquality":99,"state":"ON"}' 

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

Thank you so much for your great work on this plugin!
Rene

**Comment by stas-demydiuk** [comment]
Such device is already supported by the plugin. Please make sure that you are using the latest versions of zigbee2mqtt and plugin
