### ISSUE TITLE
Add Ikea Tradfri wireless dimmer

### ISSUE THREAD

**Issue by MiloshCZ** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#6]
Hi, please add TRADFRI wireless dimmer
`{"brightness":255,"device":{"ieeeAddr":"0x000b57fffe29ee14","friendlyName":"0x000b57fffe29ee14","type":"EndDevice","nwkAddr":6252,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI wireless dimmer","status":"online"}}
`

**Comment by stas-demydiuk** [comment]
@MiloshCZ if I understand correctly this is read only device which means there is no ability to somehow change its state from domoticz?

**Comment by MiloshCZ** [comment]
Yes, it is only one way. And it send only "brightness".
Model is "ICTC-G-1" https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices

**Comment by stas-demydiuk** [comment]
What from domoticz devices do you think fit better for this wireless dimmer: Dimmer switch or custom sensor with brightness as value?

**Comment by MiloshCZ** [comment]
I think, that dimmer switch is ok

**Comment by stas-demydiuk** [comment]
@MiloshCZ could you please check if is works properly in latest master

**Comment by MiloshCZ** [comment]
Hi, tested, everything is OK. Thank you very much
