### ISSUE TITLE
AQARA Wall Plug ZNCZ12LM

### ISSUE THREAD

**Issue by Docteur-No** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#602]
**Device description**
Aqara Smart Plug - Supports More Powerful Zigbee 3.0 Protocol

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/ZNCZ12LM.html

I was unable to find informations about this product. Does your plugin support ZNCZ12LM (EU version)

**Comment by stas-demydiuk** [comment]
Hi @Docteur-No, this device is supported by plugin, feel free to use it
