### ISSUE TITLE
Aqara temperature/humidity sensor not updating

### ISSUE THREAD

**Issue by brjhaverkamp** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#604]
**Issue description**
I am running a zigbee network for a few months now, with zigbee2mqtt(z2m) and the domoticz domoticz-zigbee2mqtt-plugin.
All devices work excelent, except for my 2 aqara temperature/humidity/presure sensors.
They are correctly connected to the zigbee coordinator. I see very regular updates from the sensors in the z2m logs.
I even see the update timestamp in the list in domoticz when I check in the z2m plugin list of devices.
But the connected devices in Domoticz don't show the updated temperature/humidity readings. The latest update there is from a month or so back.

So the issue seems to be at the domoticz side, either in the plugin, or domoticz itself.
No resetting and repairing has helped sofar. 

I found one similar issue https://github.com/Koenkk/zigbee2mqtt/issues/3603. So I might not be alone.

Any help/hint/suggestion is welcome. I can provide loging or dig a bit deeper if you can tell me where to look.

**Additional information**
Zigbee2MQTT version:1.18.1
Python version:
Domoticz version: latest
Plugin version: just did a git pull

**Logs**

**Comment by Peerkersezuuker** [comment]
Hi,
Same issue here.
The Aqara is added, devices are created, but no update of data.
In the zigbee2mqtt log is see the data transmitted :
`info  2021-03-20 11:31:35: MQTT publish: topic 'zigbee2mqtt/Filament Box 1 Temp/Hum', payload '{"battery":100,"humidity":27.17,"linkquality":76,"pressure":1028,"temperature":20.96,"voltage":3075}'
info  2021-03-20 11:31:35: MQTT publish: topic 'zigbee2mqtt/Filament Box 1 Temp/Hum', payload '{"battery":100,"humidity":27.46,"linkquality":76,"pressure":1028,"temperature":20.96,"voltage":3075}'
info  2021-03-20 11:31:35: MQTT publish: topic 'zigbee2mqtt/Filament Box 1 Temp/Hum', payload '{"battery":100,"humidity":27.46,"linkquality":76,"pressure":1028,"temperature":20.96,"voltage":3075}'
`
no update of the devices in domoticz.

Additional information
Zigbee2MQTT version: 1.18.1-dev 
Python version: 3.7.3
Domoticz version: 2020.2 build 13051
Plugin version: latest

**Comment by Peerkersezuuker** [comment]
Hmm, My bad.
Had a / in the name of the sensor : Filament Box 1 Temp/Hum
After some trouble shooting, I decided to rename the device (Filament Box 1), and voila it worked again...
Regards,
Peer

**Comment by brjhaverkamp** [comment]
Hi Peer,

Good to hear it is solved on your side. I'll try the renaming. I also use a slash, "Zigbee2mqtt/temperature/templiving"
Meanwhile, attached are 2 screenshots. 
One from the Zigbee2mqtt screen which shows a very recent last seen
and One from the devices screen, which shows an ancient view. 
I did give the the devices a friendly name in the past. But I also removed some of the devices in Domoticz. the Z2M plugin re-adds them, but getting any data remains a problem.

![Screenshot from 2021-03-21 08-44-49](https://user-images.githubusercontent.com/3051118/111897797-3c4afa80-8a22-11eb-84e8-863db4104ef6.png)
![Screenshot from 2021-03-21 08-44-29](https://user-images.githubusercontent.com/3051118/111897811-4f5dca80-8a22-11eb-8b51-39d3ac8e07b5.png)

**Comment by brjhaverkamp** [comment]
Great work Peer,
I just took out the extra topic level so my device name went from "temperature/templiving" to "templiving"
And voila, it worked! :-)
@Stanislav, This looks indeed like there is a problem in the topic handling. 

Greets from Elsoo, Limburg

Bert

**Comment by stas-demydiuk** [comment]
Nice catch, added `/` symbol support to the device name. But anyway noticed that you need to restart zigbee2mqtt service each time after you rename the device
