### ISSUE TITLE
Plug HEIMAN HS2SK don't work correctly

### ISSUE THREAD

**Issue by Docteur-No** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#607]
**Issue description**
ON command works but no feedback to Domoticz, OFF command don't work ?!?!
Using MQTTBOX on my PC all commands work properly : ON, OFF, TOGGLE
Right now , I don't know for VOLTAGE, CURRENT, POWER
**Additional information**
Zigbee2MQTT version: Last
Python version: 3.7
Domoticz version: 2020.2
Plugin version: last (yesterday)

**Comment by bricololo44** [comment]
Is the same for me.

Issue description
Plug command don't works no feedback for all my plugs(2 versions) : 
Xiaomi ZNCZ02LM
Lidl HG06337

Additional information
Zigbee2MQTT version: Last
Python version: 3.7
Domoticz version: 2020.2
Plugin version: V3

**Comment by stas-demydiuk** [comment]
If you recently upgraded the plugin, probably there could be one more switch in your devices created, because of the fix for #605, please check

**Comment by bricololo44** [comment]
I removed plugin for ugrade to V3.
On first appearing, the plug has been recognized.
I have only one switch created.
It worked fine for 1 hour but then it disconnected.
Since then, at each re-pairing, the device appears well but it is marked unknow. And it does not work.
He didn't recognize the Lidl plug :
Modele : N/A
Typ : Unknow
The IEEE address is OK
I restarted zigbee2mqtt and it's the same

**Comment by bricololo44** [comment]
I just noticed that my xiaomi plugs are also disconnecting, they have to be re-paired for it to work. (this does not work for the lidl plug). If I rename them, it disconnects again. I migrated from CC2531 Migration to CC2652R, is this the problem?

**Comment by Docteur-No** [comment]
Strange issue ?!?!
Works after reboot

**Comment by bricololo44** [comment]
When I rename a sensor, it no longer updates. I don't know if this is from the plugin or from zigbee2mqtt. It is then very difficult to re-pair it.
It seems to works after reboot.

**Comment by stas-demydiuk** [comment]
Yes, when you rename the sensor you need to restart zigbee2mqtt to make it work again
