### ISSUE TITLE
Support for specific dimmer

### ISSUE THREAD

**Issue by gert3d** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#608]
**Device description**
I am planning to test two dimmers that look similar/equal to several dimmers that already are listed. I wonder whether compatibility is also dependent on the brand name of a dimmer, or whether similar dimmers of different brands will make use of a common script

One device in question is from Amazon:
https://www.amazon.nl/gp/product/B07XPJ22W3/ref=ox_sc_act_title_1
which is similar to several types listed:
**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/4512700.html
https://www.zigbee2mqtt.io/devices/12AB.html
https://www.zigbee2mqtt.io/devices/98425031.html
https://www.zigbee2mqtt.io/devices/ROB_200-004-0.html
and a couple more ..

Do I have to follow:    https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
to add the new (similar) devices with their own brand name, if not listed?

Once done, should I mention the finding somewhere?

**Comment by stas-demydiuk** [comment]
If this device is supported by zigbee2mqtt then it will be supported by this plugin as well
