### ISSUE TITLE
OSRAM SMART+ classic E27 dimmable (light) - blocky

### ISSUE THREAD

**Issue by gert3d** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#610]
After pairing the lamp shows up in the devices list (3x: switch, effects, link quality) and also under the Switches tab (dimmable light and effect) 

However it cannot be found in Events/Blocky in the devices list.

**Device description**
OSRAM SMART+ classic E27 dimmable (light)

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/AC10786-DIM.html

**MQTT message with device information**
Mar 24 20:56:49 raspberrypi npm[472]: Zigbee2MQTT:info  2021-03-24 20:56:49: MQTT publish: topic 'zigbee2mqtt/0x7cb03eaa0a04a565', payload '{"brightness":71,"linkquality":52,"state":"ON","update":{"state":"available"},"update_available":true}'

**Comment by gert3d** [comment]
Also: under the Switches tab the lamp can be set to various dimming %
It DOES show up in scenes and can be set to dimming %
so, probably that is the way to go?

**Comment by stas-demydiuk** [comment]
I see all devices in Blockly script so maybe try to restart Domoticz hopefully it would help. And also please make sure that you've set all required devices as "Used" in Domoticz as the plugin creates all of them as "unused" by default

![image](https://user-images.githubusercontent.com/2734836/112713868-0d2fff80-8ee0-11eb-865d-3bcf01e9e109.png)

In this screenshot first device is "used" and second is "unused"

**Comment by gert3d** [comment]
Hi Stanislav, 

thanks for your answer. !
The solution to the problem of not seeing the device in Blocky apeared  to be: : clearing the cache of Firefox !
The other thing I mentioned:
 Under the Switches tab the lamp can be set to various dimming %However that is not possible in Blocky, what works is ON and OFF, but not something like "50%"


These choices dp however show up in Scenes section, there the lamp can be set to a dimming %.Is this typical for Blocky and  should I use dzVentsif I want to use dimming % in Events?

regards,Gert



    On Saturday, March 27, 2021, 8:39:06 AM GMT+1, Stanislav Demydiuk ***@***.***> wrote:  
 
 


I see all devices in Blockly script so maybe try to restart Domoticz hopefully it would help. And also please make sure that you've set all required devices as "Used" in Domoticz as the plugin creates all of them as "unused" by default



In this screenshot first device is "used" and second is "unused"
