### ISSUE TITLE
Error: Python Plugin System: (ZigBee) 'onDeviceModified' failed 'JSONDecodeError'.

### ISSUE THREAD

**Issue by kovainfo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#611]
<img width="1213" alt="Снимок экрана 2021-03-25 в 17 19 23" src="https://user-images.githubusercontent.com/36986231/112488112-540de000-8d8e-11eb-84ff-dc99279affd5.png">

Domoticz: 2020.2 (build 13116)
Build Hash: 402ce8ddb
Build Date: 2021-03-25 15:56:25

**Comment by stas-demydiuk** [comment]
What's exactly causing this error?

**Comment by kovainfo** [comment]
Hello!

I have updated zigbee2mqtt to version 1.18
I have updated the plugin to the latest version.
I updated Domoticz 2020.2 (build 13117)

When you try to enter the plugin settings Custom -> zigbe2mqtt, a blank page opens, and there is such an error in the log.

About Domoticz
Version: 2020.2 (build 13117)
Build Hash: af2a7788f
Compile Date: 2021-03-25 18:20:48
dzVents Version: 3.1.7
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by stas-demydiuk** [comment]
Looks like the JSON request from your Domoticz UI can't be parsed properly, I'm not sure why. If you are familiar with Chrome dev tools, could you please share requests that are sent to `/json.htm` when you open zigbee2mqtt page on UI

**Comment by kovainfo** [comment]
everything worked by itself 🤷🏻‍♂️
