### ISSUE TITLE
On WSDCGQ01LM, no more _th or _all

### ISSUE THREAD

**Issue by stefstef2000** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#612]
First, thanks for your job !!
I try to upgrade to 3.0.0 but my temp sensor WSDCGQ01LM but Z2M don't expose _th or _all value anymore.
There's only : _volt, _temp, _hum, _btperc, _signal.

On WSDCGQ11LM, there is all others + _all and _th (temp + hum).

**Comment by hannuf1** [comment]
Same here, took a while to figure it out, hoping a fix soon thanx :)

**Comment by dobber81** [comment]
I have the same issue. 
As a work-around I use this dzvents-script to combine temp+hum in to one combined dummy: 
https://github.com/papo-o/domoticz_scripts/blob/master/dzVents/scripts/xiaomiTHBsensors.lua

**Comment by BRSS73** [comment]
You can use the following workaround :
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/621#issuecomment-817170817

**Comment by stas-demydiuk** [comment]
Clone of #628
