### ISSUE TITLE
Zemismart Blind switch inverted after update

### ISSUE THREAD

**Issue by jvrrr** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#613]
I own a couple of Zemismart Blind switches. (Zemismart ZM-CSW002-D (TS0302)
After updating the plugin, they al work inverted.

Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

Thanks!!!

**Comment by stas-demydiuk** [comment]
Could you please share device definition from zigbee2mqtt for your device

**Comment by jvrrr** [comment]
switch manualy:
open= position 100
close=position 0

Switch Domoticz:
open= position 0	
close=position 100

Model is TS0302 by _TYZB01_dazsid15.
Hardware version is 1.
Firmware version is unknown.
This device type is Router

**Comment by odelma** [comment]
Hello, I have the same issue with IKEA KADRILJ roller blinds. May help in some way to solve it?

**Comment by stas-demydiuk** [comment]
Should be fixed by #638
