### ISSUE TITLE
TS0201	Temperature & humidity sensor with display doesn't update values in domoticz

### ISSUE THREAD

**Issue by jefdemas** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#616]
**Issue description**
TS0201	Temperature & humidity sensor with display doesn't update values in domoticz

**Additional information**
Zigbee2MQTT version: 18.2
Python version: latest
Domoticz version: latest stable
Plugin version: latest

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

Keuken | TS0201 | Temperature & humidity sensor with display | EndDevice | 0xbc33acfffe28b2c3 | 2021-04-04 15:08:02
 latest update in plugin

after updating plugin and zigbee2mqqt it doesn't update to domoticz other Temp and Hum devices are working correctly

**Comment by jefdemas** [comment]
Seperate values are updated but not temp  hum in 1 device for domoticz

**Comment by dobber81** [comment]
I made a PR to fix this.
#629

**Comment by stas-demydiuk** [comment]
Clone of #628
