### ISSUE TITLE
BlitzWolf BW-SHP13 doesn't add devices

### ISSUE THREAD

**Issue by MarcusKlerks** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#617]
I just received a new BlitzWolf BW-SHP13 (aka Tuya TS0121_plug) power plug that I successfully paired using the Zigbee2MQTT Plugin. Alas it doesn't add any device. Looking in the Zigbee2MQTT frontend everything is exposed and working.
What could be wrong?

**Comment by heggink** [comment]
Mine work fine. What versions are you running?

**Comment by MarcusKlerks** [comment]
Thanks for asking. Both Zigbee2MQTT and Zigbee2MQTT Plugin latest versions.

**Comment by heggink** [comment]
Did you switch on debug in the plugin? Anything in the logs?

**Comment by MarcusKlerks** [comment]
Now I did, should have thought of that before :(

Log shows that the device is skipped because it is in blacklist. Now this is the BlitzWolf device id: 0x60a423fffef8da74,
and this is in my blacklist: 0x00158d000450f413_volt;0x04cf8cdf3c77bf5f_cell;0x04cf8cdf3c77df0a_autoff;0x04cf8cdf3c77df0a_pwrmem;0x04cf8cdf3c77df0a_nled;0x04cf8cdf3c77df0a_consmr;0x00158d00023e5fc5_volt;0x00158d00044451be_all;0x00158d00044451be_th;0x00158d00044451be_pres;0x00158d00044451be_cell;

So no occurrence there.!

Deleted the blacklist, et voila, there they are. So I guess there is something going on in the processing of the blacklist. For now I'm good and if I can be of any help in further investigating, let me know. 

And thanks for your assistance.

**Comment by heggink** [comment]
Glad it worked!
