### ISSUE TITLE
`color_hs` feature support for RGBW bulbs

### ISSUE THREAD

**Issue by dobber81** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#620]
**Issue description**
LIGHTIFY LED CLA60 E27 RGBW identified as WW by plugin in domoticz.
Changing color works just as normal in zigbee2mqtt gui.
Ikea Trådfri RGB bulb works as expected.
It stopped working at an update the last week or 2.

**Additional information**
Zigbee2MQTT version: v.1.18.2-dev (zStack3x0 20210120)
Python version: 3.7.3
Domoticz version: 2020.2 13149
Plugin version: latest from today.

**Logs**
Before readding the light and getting WW, I tried sending command color red from domoticz:
When set to color red in domoticz this is received in mqtt:
MQTT publish: topic 'zigbee2mqtt/Fönster Uppe', payload '{"brightness":134,"color":{"hue":305,"saturation":100,"x":0.313059507478705,"y":0.323172994053855},"color_mode":"color_temp","color_temp":153,"linkquality":57,"state":"ON","update":{"state":"idle"},"update_available":false}'

Sent from domoticz:
Status: setcolbrightnessvalue: ID: 32b, bri: 53, color: '{m: 3, RGB: ff0300, CWWW: 0000, CT: 0}'

**Comment by stas-demydiuk** [comment]
Could you please try to remove the device and let the plugin to create it one more time. If the issue persists then could you please share the device definition from zigbee2mqtt for your device (see #548 for reference)

**Comment by dobber81** [comment]
Still added as WW in domoticz. Latest plugin, latest domoticz nightly, latest dev zigbee2mqtt from today.

MQTT publish: topic 'zigbee2mqtt2/bridge/event', payload '{"data":{"definition":{"description":"LIGHTIFY LED CLA60 E27 RGBW","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":153},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":526}],"property":"color_temp","type":"numeric","unit":"mired","value_max":526,"value_min":153},{"access":7,"description":"Color temperature after cold power on of this light","name":"color_temp_startup","presets":[{"description":"Coolest temperature supported","name":"coolest","value":153},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":526},{"description":"Restore previous color_temp on cold power on","name":"previous","value":65535}],"property":"color_temp_startup","type":"numeric","unit":"mired","value_max":526,"value_min":153},{"description":"Color of this light expressed as hue/saturation","features":[{"access":7,"name":"hue","property":"hue","type":"numeric"},{"access":7,"name":"saturation","property":"saturation","type":"numeric"}],"name":"color_hs","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"AC03645","supports_ota":true,"vendor":"OSRAM"},"friendly_name":"0x7cb03eaa00a8a1d6","ieee_address":"0x7cb03eaa00a8a1d6","status":"successful","supported":true},"type":"device_interview"}'

**Comment by stas-demydiuk** [comment]
Now I see, it has color property as `color_hs` while the plugin works only with `color_xy`. It would be hard for me to add that support without having the device for debugging but I'll do my best

**Comment by dobber81** [comment]
Did something change in zigbee2mqtt ta make it _hs instead of _xy? The bulb was working fine with the plugin just a month ago.

**Comment by dlarge51** [comment]
Hi, I'm using two Miboxer Fut039z, and have the same problem as @acaonweb in topic #747 
I hope this can be fixed somehow. 
Thanks!

**Comment by Helevetti** [comment]
Hi!. Any idea when this color_hs feature comes out? I have couple of these lightify bulbs and the rgb side wont work..

**Comment by MiloshCZ** [comment]
Hi, do you have any plans with support color_hs?

**Comment by dlarge51** [comment]
> Hi, do you have any plans with support color_hs?

I am waiting on this as well, so I hope so.
