### ISSUE TITLE
Devices doens't update anymore or wrong.

### ISSUE THREAD

**Issue by rolfie23** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#621]
**Issue description**
After update, I did get an new voltage sensor. But there are problems with, the value is showing incorrect. It says now 3025V instead of 3.025V. I think the small item can't deliver 3000V or there must be some breaktrough.

Also the _all device isn't beining updated anymore (so the temp hum combined device). Want those 2 together, just like it was.

**Additional information**
Zigbee2MQTT version: 1.18.2
Python version: 3.7.3
Domoticz version: 2020.2
Plugin version: 3.0.0

**Comment by rolfie23** [comment]
For the combined sensor:
2 pieces in my home are working perfectly and update the combined sensor. This is the Xiaomi WSDCGQ11LM, it's with baro meter and uses device type lumi.weather.

All the other so without baro meter are the Xiaomi WSDCGQ01LM and have as device type lumi.sensor_ht in zigbee2mqtt.

Since the face the 2 working good, and with normal reading of volt, is it possble they work the same like it was? So as lumi.weather type?

**Comment by rolfie23** [comment]
For now, made an new file `WSDCGQ01LM.py` in `adapters/lumi` with the following tekst:
`from adapters.adapter_with_battery import AdapterWithBattery
from devices.sensor.temperature import TemperatureSensor
from devices.sensor.humidity import HumiditySensor
from devices.temperature_humidity_sensor import TemperatureHumiditySensor

# Xiaomi Aqara temperature and humidity sensor
class WSDCGQ01LM(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(TemperatureSensor(devices, 'temp', 'temperature', ' (Temperature)'))
        self.devices.append(HumiditySensor(devices, 'hum', 'humidity', ' (Humidity)'))
        self.devices.append(TemperatureHumiditySensor(devices, 'th', 'combined', ' (Temperature + Humidity)'))

    def convert_message(self, message):
        message = super().convert_message(message)

        if 'temperature' in message.raw and 'humidity' in message.raw:
            message.raw['combined'] = {
                'temperature': message.raw['temperature'],
                'humidity': message.raw['humidity']
            }

        return message
`

In the same folder, did at the following tekst to `__init__.py`
`from adapters.lumi.WSDCGQ01LM import WSDCGQ01LM
'WSDCGQ01LM': WSDCGQ01LM,           # Xiaomi Aqara temperature and humidity sensor`

And there where presented new devices in domoticz with temp and hum combined. those i can replace!

**Comment by elpaul** [comment]
@rolfie23 
In my case, the data is not updated. Still 0,0;50
![image](https://user-images.githubusercontent.com/9497662/114687773-5a033b00-9d14-11eb-855c-6051c9324f79.png)

**Comment by rolfie23** [comment]
I see now the code messed up here! If everything went okay, you get an new device which you can replace with the old one.

**Comment by elpaul** [comment]
![image](https://user-images.githubusercontent.com/9497662/114691154-a7cd7280-9d17-11eb-800f-45b7ac6d4f47.png)

**Comment by bramvreugd** [comment]
When I copied the fix from rolfie23 it did not work for me.
Inspecting the code I saw that the text i've copied had on line 9 and 10 a `def init` and it should be a `def __init__`
The HTML formatter removed the underscores
Here is the full text 

```
from adapters.adapter_with_battery import AdapterWithBattery
from devices.sensor.temperature import TemperatureSensor
from devices.sensor.humidity import HumiditySensor
from devices.temperature_humidity_sensor import TemperatureHumiditySensor
import Domoticz

#Xiaomi Aqara temperature and humidity sensor
class WSDCGQ01LM(AdapterWithBattery):
   def __init__(self, devices):
     super().__init__(devices)
     self.devices.append(TemperatureSensor(devices, 'temp', 'temperature', ' (Temperature)'))
     self.devices.append(HumiditySensor(devices, 'hum', 'humidity', ' (Humidity)'))
     self.devices.append(TemperatureHumiditySensor(devices, 'all', 'combined', ' (Temperature + Humidity)'))
     self.devices.append(TemperatureHumiditySensor(devices, 'th', 'combined', ' (Temperature + Humidity)'))

   def convert_message(self, message):
      message = super().convert_message(message)
      if 'temperature' in message.raw and 'humidity' in message.raw:
         message.raw['combined'] = {
            'temperature': message.raw['temperature'],
            'humidity': message.raw['humidity']
         }

      return message
```

**Comment by rolfie23** [comment]
> When I copied the fix from rolfie23 it did not work for me.
> Inspecting the code I saw that the text i've copied had on line 9 and 10 a `def init` and it should be a `def __init__`
> The HTML formatter removed the underscores
> Here is the full text
> 
> ```
> from adapters.adapter_with_battery import AdapterWithBattery
> from devices.sensor.temperature import TemperatureSensor
> from devices.sensor.humidity import HumiditySensor
> from devices.temperature_humidity_sensor import TemperatureHumiditySensor
> import Domoticz
> 
> #Xiaomi Aqara temperature and humidity sensor
> class WSDCGQ01LM(AdapterWithBattery):
>    def __init__(self, devices):
>      super().__init__(devices)
>      self.devices.append(TemperatureSensor(devices, 'temp', 'temperature', ' (Temperature)'))
>      self.devices.append(HumiditySensor(devices, 'hum', 'humidity', ' (Humidity)'))
>      self.devices.append(TemperatureHumiditySensor(devices, 'all', 'combined', ' (Temperature + Humidity)'))
>      self.devices.append(TemperatureHumiditySensor(devices, 'th', 'combined', ' (Temperature + Humidity)'))
> 
>    def convert_message(self, message):
>       message = super().convert_message(message)
>       if 'temperature' in message.raw and 'humidity' in message.raw:
>          message.raw['combined'] = {
>             'temperature': message.raw['temperature'],
>             'humidity': message.raw['humidity']
>          }
> 
>       return message
> ```

Yes, GitHub did strange with the code symbols. Forgot it, but found solution now, so good text what I use is now in the post.

**Comment by dobber81** [comment]
PR #629 to make use of the generic temp/hum template for xiaomi and tuya devices.

**Comment by stas-demydiuk** [comment]
Clone of #628
