### ISSUE TITLE
request for a new feature

### ISSUE THREAD

**Issue by turin400** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#622]
I am thinking about the problem with the bulbs that I have from ikea when the power is removed and when they are connected they turn on. I have read in Zigbee2mqtt the option of availability_timeout and availability_passlist that generate an Online / Ofline similar to LWT of mqtt and that I think I could use with the option of Used = 1 or 0 of Domoticz.
In this way we could remove all the dashboard bulbs that are not powered and thus know that they are off or Ofline and show again when they are powered or online.
To avoid problems the plugin would have to have an option similar to the Zigbee2mqtt availability_passlist and put the same devices on both.
I do not know what you think for me it is a problem to open domoticz or the app and see bulbs or devices that are not operational. In addition to the ack errors that are generated when trying to act a device that is not Online.
I think there is something similar in HA.
Regards and thanks for everything.

**Comment by SargonofAssyria** [comment]
Why would you remove power from a zigbee bulb? It has impact on the mesh network.

**Comment by turin400** [comment]
In my case it has happened to me because when cleaning with the vacuum cleaner the lamp has been disconnected. Then it appears in domoticz but if you try to turn it on, ack errors appear because it cannot find it. If, as indicated when disconnecting, send an offline to domoticz and remove it from the list, you would have information that it is disconnected and you would also have no errors when trying to activate it.

**Comment by SargonofAssyria** [comment]
In a normal mesh network the bulb that was disconnected and after some time gets power, it should normally connect to the network as if nothing has happened. 1 or 2 times a year the power company where I live 'decides' to cut power, so all power connected device are disconnected. If power comes on again, then all devices should join the mesh network again.
I never had any trouble with that, so better check your bulb or your wiring if it does not work.

**Comment by turin400** [comment]
For example, it may happen that when leaving a second home you disconnect some electrical circuits and some light bulbs run out of power. And yet in your domoticz all appear with the option to turn on without indicating anything, offline or timeout, nothing.

**Comment by stas-demydiuk** [comment]
Currently, there is no such API for plugins to tell that the device is offline so I don't see any way how such behaviour can be implemented in the plugin. All other workarounds like you suggested can be implemented by custom scripts as well, so no need to modify plugin for that reason.
