### ISSUE TITLE
SNZB-02 Temp + Humidity (combined) not reporting only works seperatly

### ISSUE THREAD

**Issue by Belaial** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#623]
**Issue description**
Since I updated my plugin I noticed today (like 2 weeks later) that my SNZB-02	does work but that the combined Temp + Humidity has stopped updating, they are updating but only separately, I have attached a image to show what I mean.

![SNZB-02](https://user-images.githubusercontent.com/58330971/114703484-056cb980-9d2e-11eb-8f73-f7297b786d91.jpg)

As you an see in the image all the different devices that belong to this unit is updating except for the "_all" and the "_cell" one (Idx 4991 & 4987), those stopped the day I updated the plugin. Is this intended? I saw some other reports about similar stuff but nothing about the SNZB-02 specifically so that is why I decided to make my own ticket.

I am mostly wondering about the "_all" device since those are the ones I have been adding to Domoticz to graph the temperature and humidity. When I tested to add a brand new SNZB-02 the "_all" never got created so maybe this is a intended change?

**Additional information**
Zigbee2MQTT version: 1.18.1
Python version: Python 2.7.16
Domoticz version: 2020.2
Plugin version: 3.0.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by stas-demydiuk** [comment]
Clone of #628
