### ISSUE TITLE
Sunricher wall switch not working

### ISSUE THREAD

**Issue by bengtner** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#627]
**Issue description**
I'm new in the Zigbee world but not with Domoticz. Decided to try out some Zigbee stuff since I'm extremely tired of 433MHz devices. I have added a cc2652 dongle to my Rasp, installed zigbee2mqtt, Mosguito mqtt broker and this Domoticz plugin. I have also managed to set up a Agara temp&humidity sensor and it works fine as far as I can see. Next on my list is to integrate a wall-switch. I have added Sunricher ZG9100A-S switch which should be a supported by zigbee2mqtt. Pairing is OK. However, the only thing that shows up in the list in zigbee2mgtt tab is a router, no end device. I![Screenshot from 2021-04-24 08-58-10](https://user-images.githubusercontent.com/18145417/115984471-825a2780-a5a7-11eb-80e3-f8d0186fef7c.png)
![Screenshot from 2021-04-24 09-04-05](https://user-images.githubusercontent.com/18145417/115984474-85edae80-a5a7-11eb-8d2f-0bb9cf043af8.png)
![Screenshot from 2021-04-24 09-04-05](https://user-images.githubusercontent.com/18145417/115984484-9867e800-a5a7-11eb-97b1-f335c145610d.png)
![Screenshot from 2021-04-24 08-58-10](https://user-images.githubusercontent.com/18145417/115984485-9c940580-a5a7-11eb-852b-c235a50504eb.png)

Looking in my zigbee2mqtt logs, it seems like the switch is paired but it is not supported. => Zigbee model 'HK-SL-RELAY-A' and manufacturer name 'Sunricher' is NOT supported. 

So it looks like a zigbee2MQTT issue to begin with. It is a bit strange, since this switch should be supported according to this page: https://www.zigbee2mqtt.io/devices/SR-ZG9100A-S.html

I have tried to follow the guide to change settings in the devices.js file, but have not suceeded yet.

Does anyone know a wall switch supported by zigbee2mgtt and Domoticz by means of this plugin? 

Edit: I think I figured out the answer myself since I found the list of supported devices. I will give Sonoff a try. Both switch and temperature sensors.

**Additional information**
info  2021-04-23 09:04:49: Starting Zigbee2MQTT version 1.18.2 (commit #abd8a092)
info  2021-04-23 09:04:49: Starting zigbee-herdsman (0.13.88)
info  2021-04-23 09:05:07: zigbee-herdsman started
info  2021-04-23 09:05:07: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20201026,"transportrev":2},"type":"zStack3x0"}'

Python version: 2.7.16
Domoticz version: 2021.1

Plugin version:
Latest, downloaded a few days ago (where do I find this info? Would be nice to have this on the zigbee2mqtt web page in Domoticz)

```
**Logs**
info  2021-04-23 20:16:41: Device '0x60a423fffec8a4d8' joined
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffec8a4d8","ieee_address":"0x60a423fffec8a4d8"},"type":"device_joined"}'
info  2021-04-23 20:16:41: Starting interview of '0x60a423fffec8a4d8'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffec8a4d8","ieee_address":"0x60a423fffec8a4d8","status":"started"},"type":"device_interview"}'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x60a423fffec8a4d8"},"type":"device_connected"}'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x60a423fffec8a4d8"},"type":"pairing"}'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffec8a4d8","ieee_address":"0x60a423fffec8a4d8"},"type":"device_announce"}'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x60a423fffec8a4d8"},"type":"device_announced"}'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20201026","friendly_name":"Coordinator","ieeeAddr":"0x00124b0021cc46cb","lastSeen":1619201801843,"networkAddress":0,"softwareBuildID":"zStack3x0","type":"Coordinator"},{"dateCode":"20191205","description":"Aqara temperature, humidity and pressure sensor","friendly_name":"0x00158d000588cd68","hardwareVersion":30,"ieeeAddr":"0x00158d000588cd68","lastSeen":1619201503171,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ11LM","modelID":"lumi.weather","networkAddress":59174,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"-","friendly_name":"0x60a423fffec8a4d8","ieeeAddr":"0x60a423fffec8a4d8","lastSeen":1619201801824,"networkAddress":13799,"type":"Unknown","vendor":"-"}]'
info  2021-04-23 20:16:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20201026","friendly_name":"Coordinator","ieeeAddr":"0x00124b0021cc46cb","lastSeen":1619201801851,"networkAddress":0,"softwareBuildID":"zStack3x0","type":"Coordinator"},{"dateCode":"20191205","description":"Aqara temperature, humidity and pressure sensor","friendly_name":"0x00158d000588cd68","hardwareVersion":30,"ieeeAddr":"0x00158d000588cd68","lastSeen":1619201503171,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ11LM","modelID":"lumi.weather","networkAddress":59174,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"-","friendly_name":"0x60a423fffec8a4d8","ieeeAddr":"0x60a423fffec8a4d8","lastSeen":1619201801824,"networkAddress":13799,"type":"Unknown","vendor":"-"}],"type":"devices"}'
info  2021-04-23 20:16:43: Successfully interviewed '0x60a423fffec8a4d8', device has successfully been paired
warn  2021-04-23 20:16:43: Device '0x60a423fffec8a4d8' with Zigbee model 'HK-SL-RELAY-A' and manufacturer name 'Sunricher' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
info  2021-04-23 20:16:43: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x60a423fffec8a4d8","ieee_address":"0x60a423fffec8a4d8","status":"successful","supported":false},"type":"device_interview"}'
info  2021-04-23 20:16:43: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x60a423fffec8a4d8","supported":false},"type":"pairing"}'
```

**Comment by hughb8on** [comment]
The log you've posted indicates a problem with zigbee2mqtt itself, so it might be best to ask for help there first. When that's fixed it is possible the plugin will be ok too.

https://github.com/Koenkk/zigbee2mqtt/issues

**Comment by bengtner** [comment]
Ok, my conclusion as well. I have posted an issue on Koenkk's github
