### ISSUE TITLE
Support for OSRAM Flex RGBW

### ISSUE THREAD

**Issue by niekvdg** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#63]
**Device description**
Can you please add support for the OSRAM Flex RGBW Ledstrip

**MQTT message with device information**

```
{"ieeeAddr":"0x7cb03eaa00a3796a","type":"Router","model":"4052899926110","friendly_name":"LedStrip"}
```

**MQTT messages from device**

Device does not send any updates.

**MQTT state change commands**
```
{"state":"ON","brightness":249,"color_mode":1,"color":{"x":0.252,"y":0.656}}

{"state":"ON","brightness":48,"color_mode":1,"color":{"x":0.162,"y":0.133}}

{"state":"Off","brightness":198,"color_mode":1,"color":{"x":0.162,"y":0.133}}
```

**Comment by stas-demydiuk** [comment]
@niekvdg Could you please update plugin and check

**Comment by niekvdg** [comment]
Thanks for the fast update, it works!
