### ISSUE TITLE
IKEA LED1623G12 # Model LED1623G12  Not showing up properly

### ISSUE THREAD

**Issue by HJKLMN** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#633]
**Issue description**
When I add the LED1623G12 it does not show up as expected. It shows up awith 2 swtiches, one with selector, and another one that shoud be the dimmer.   Unfortunatly I can not tutn of the light

**Additional information**
Zigbee2MQTT version:  Zigbee2MQTT version 1.18.3 (commit #f2e39af1)
Python version: 3.8.5.
Domoticz version:  Latest
Plugin version: Latest

**Comment by stas-demydiuk** [comment]
Could you please update plugin and try one more time

**Comment by HJKLMN** [comment]
Fixed, lights are dimmable now

**Comment by stas-demydiuk** [comment]
Yes, please raise a new issue as looks like it is a different one

**Comment by HJKLMN** [comment]
Will raise new issue
