### ISSUE TITLE
Devices blacklist prohibits addition of new Domoticz devices.

### ISSUE THREAD

**Issue by MarcusKlerks** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#634]
As earlier experienced with a Blitzwolf Power Plug (issue 617), the plugin prohibits adding of new Domoticz devices when there are items listed on the Devices Blacklist of the plugin. Now experienced the same when adding new Zigbee devices (Gledopto, Xiaomi). Pairing the devices using the plugin goes without any problem, except there are no new Domoticz devices created. 
Temporarily emptying the Devices Blacklist and restarting (Update) the plugin solves the issue by creation of the Domoticz devices. Of course also the blacklisted and deleted devices are recreated which is unwanted.

Please advice.

**Additional information**
Zigbee2MQTT version: 1.18.1
Python version:  3.7.3
Domoticz version: 2021.1 (build 13243)
Plugin version:  3.0.0

**Comment by hughb8on** [comment]
From looking at your earlier issue #617 I suspect your blacklist ends with a semicolon. If so I suggest removing it because it seems to cause the problem you are havng.

I have raised #636 for this issue.

**Comment by MarcusKlerks** [comment]
I did have a semicolon at the end of the list, don't know why but it was there. I removed it and re-added one of the devices and can confirm that this was the problem. 
Thanks for helping.
