### ISSUE TITLE
Blind "state" changes do the opposite of what is expected

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#638]
I think there may be a problem in the way the plugin translates between zigbee2mqtt.io blind states and domoticz blind states.

zigbee2mqtt.io works on the basis of "how much is the blind open", so fully open is 100% or "On".

domoticz "Blind Percentage" devices work on the basis of "how much is the blind closed", so fully open is 0%, or "Off".

The plugin sits in the middle and correctly inverts the "position" percentages going between zigbee2mqtt.io and domoticz so they can talk to each other. So 10% becomes 90%, 60% becomes 40% etc.

However, it doesn't invert the "state" (On/Off Open/Closed ) values. I think it needs to invert those too.

Coded as it is now, "position" changes work correctly but "state" changes don't.

So dragging the slider in the domoticz control anywhere except the extremes works just fine, but ..

.. Clicking on the icon of the closed blind in the domoticz control results in the blind opening. 
.. Clicking on the icon of the open blind results in it closing.
.. Dragging the slider all the way to the right or left results in the exact opposite of what it should.

Note that changing the domoticz device to "Blinds Percentage Inverted" doesn't help, it just results in different set of incorrect behaviours. Again I believe this is because plugin is only inverting "position", not "state".

I have corrected this on my system by inverting the on/off logic in devices/switch/blind_percentages_switch.py like this: -

if cmd == 'ON':
            return {
                state_value_key: self.state_feature['value_off']
            }
        elif cmd == 'OFF':
            return {
                state_value_key: self.state_feature['value_on']

.. with that change everything works correctly.
Edit:corrected filename, thank you Electr1fying.

**Comment by hughb8on** [comment]
Here's the device definition for my blind

{
    "date_code": "",
    "definition": {
      "description": "Curtain motor/roller blind motor/window pusher/tubular mo>
      "exposes": [
        {
          "features": [
            {
              "access": 3,
              "name": "state",
              "property": "state",
              "type": "binary",
              "value_off": "CLOSE",
              "value_on": "OPEN"
            },
            {
              "access": 3,
              "description": "Position of this cover",
              "name": "position",
              "property": "position",
              "type": "numeric",
              "value_max": 100,
              "value_min": 0
            }
          ],
          "type": "cover"
        },
        {
          "features": [
            {
              "access": 3,
              "description": "Motor speed",
              "name": "motor_speed",
              "property": "motor_speed",
              "type": "numeric",
              "value_max": 255,
              "value_min": 0
            }
          ],
          "name": "options",
          "property": "options",
          "type": "composite"
        },
        {
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "TS0601_cover",
      "supports_ota": false,
      "vendor": "TuYa"
    },
    "endpoints": {
      "1": {
        "bindings": [],
        "clusters": {
          "input": [
            "genBasic",
            "genGroups",
            "genScenes",
            "manuSpecificTuya"
          ],
          "output": [
            "genOta",
            "genTime"
          ]
        },
        "configured_reportings": []
      }
    },
    "friendly_name": "MAINBED.BLIND",
    "ieee_address": "0x5c0272fffec2099b",
    "interview_completed": true,
    "interviewing": false,
    "model_id": "TS0601",
    "network_address": 41773,
    "power_source": "Battery",
    "supported": true,
    "type": "EndDevice"
  }

**Comment by Electr1fying** [comment]
Where exactly did you change this behavior? The location/file you mentioned does not exist. 

/Adapters/Generic/blind_adapter.py however does and seems to contain references you mentioned.

I have the same issue and it would be nice if the states are reported correctly.

**Comment by hughb8on** [comment]
blind_percentages.py *is* where I said, in devices/switch : -
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/tree/master/devices/switch

**Comment by hughb8on** [comment]
.. but though making the change I suggested may fix the problem for me and you, it may not work for everyone because the real problem may lie elsewhere. I'm not familiar enough with the code to be sure.

**Comment by stas-demydiuk** [comment]
@hughb8on applied the fix you've suggested, could you please check if now everything works correct

**Comment by hughb8on** [comment]
Yes, that's fixed it for me, the slider extremes and the icons in the domoticz control now work correctly.
Thank you!
