### ISSUE TITLE
Misconfigured climate sensors

### ISSUE THREAD

**Issue by philibertc** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#644]
**Issue description**
![image](https://user-images.githubusercontent.com/57588282/118500462-1727ef00-b728-11eb-8d2b-fa96895aaf77.png)
Humidity is in Celsius.
![image](https://user-images.githubusercontent.com/57588282/118500571-30c93680-b728-11eb-9b0d-7f7abd79319f.png)
Pressure is in Bar (the value is hPa normally).

**Additional information**
Zigbee2MQTT version: v.1.18.3 (zStack3x0 20200925)
Python version: 3.7.3
Domoticz version: 2021.1
Plugin version: latest
Tested with these sensors: SNZB-02, Aqara WSDCGQ11LM
Well configured with the "all" entity :
![image](https://user-images.githubusercontent.com/57588282/118501272-d54b7880-b728-11eb-8051-ad91c1cba950.png)

**Comment by stas-demydiuk** [comment]
I see that these devices have been updated at different time, is there any reason for that?

**Comment by philibertc** [comment]
> I see that these devices have been updated at different time, is there any reason for that?
Hello, this is because the temperature changed after the addition, but not the pressure.

**Comment by SargonofAssyria** [comment]
I have the same.
![2021-05-19_18-35-50](https://user-images.githubusercontent.com/24824113/118850566-331ac480-b8d1-11eb-9aea-767ebab7fd38.png)
In my Domoticz database I see 5 values: 27.3;40.5;0;1014;0

**Comment by philibertc** [comment]
Yeah. 1014 bar!!!!!!

**Comment by SargonofAssyria** [comment]
And in the Domoticz.log I see a warning message:
2021-05-19 18:48:26.454 Status: Warning: Expecting svalue with at least 4 elements separated by semicolon, 3 elements received ("26.8;40.3;0"), notification not sent (Hardware: 33 - Zigbee, ID: xxx_all, Unit: 10, Type: 54 - Temp + Humidity + Baro, SubType: 16 - Weather Station)

**Comment by stas-demydiuk** [comment]
@SargonofAssyria that most likely because the previous version of the plugin used `_all` device of your sensor for Temp+Hum+Baro sensor but the current version uses it for Temp+Hum (for the widest compatibility reason) and `_thb` for Temp+Hum+Baro. You just need to remove `_all` device manually and let the plugin to recreate it with proper settings. You also could try to replace it with `_thb` one in case you'd like to keep historical data.

**Comment by SargonofAssyria** [comment]
I want to keep historical data, so I renamed the ID to xxxx_OLD_all etc., so that I could transfer data to new devices. That did not help they still are updated. Humidity still gets updated with 0 (zero) and Pressure still gets updated instead of the Barometer device.

**Comment by stas-demydiuk** [comment]
yes, plugin uses the last part to extract the name, so try to rename to something like xxxx_all_OLD

**Comment by SargonofAssyria** [comment]
Unfortunately This will not work I get these kind of errors:
2021-05-20 09:59:20.024 Error: (Zigbee) Device creation failed, Hardware/Unit combination (33:7) already exists in Domoticz.

**Comment by SargonofAssyria** [comment]
I did delete all the concerning device, but got a pressure device back instead of a Barometer device.

**Comment by SargonofAssyria** [comment]
With the newly created device is a "_hum" device, but the device in Domoticz is a temperature device.
Type 80 Subtype 5 I think that is not correct.

**Comment by SargonofAssyria** [comment]
There is a type in "temperature_humidity_barometer_sensor.py"  the value 996 should be 966 the compleet 'formula' should be.
`
if (pres < 966) {
    forecast = "4";
} else if (pres < 993) {
    forecast = "3";
} else if (pres < 1007) {
    forecast = "2";
} else if (pres < 1013) {
    forecast = "3";
} else if (pres < 1033) {
    forecast = "0";
} else {
    forecast = "1";
}
`

**Comment by stas-demydiuk** [comment]
Updated value to 966

**Comment by SargonofAssyria** [comment]
Tnx.
