### ISSUE TITLE
Plugin crashes when blacklisting a device.

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#649]
I want to blacklist a device because I want to update a THB device by nodered.
I blacklisted the device by "0x00158d00022cbcad_.*"
Immediately after the restart of Domoticz it crashed directly after the zigbee plugin thread is crashed.
When I remove the blacklisted device Domoticz run as normal.

I also test on a test system with only the zigbee devices. No crash so far, but have to wait. Devices are update when the are created, despite the fact that the device is blacklisted. If I do the blacklisting at the start of the hardware creation then the blacklisted devices are not created.

B.t.w. Domoticz crashes every other day also by a crash of the zigbee plugin thread. I think that has to do with some of the remaining errors in the plugin.

**Additional information**
Zigbee2MQTT version: 1.18.3-dev commit: 5195f5f2
Python version: 3.7.3
Domoticz version: 2021.1 (build 13243)
Plugin version: latest.

**Comment by stas-demydiuk** [comment]
The idea of blacklist is just to avoid plugin to create specific device, if device is already created most likely it'll keep updating
