### ISSUE TITLE
Only ".*_effec" item in "Devices blacklist" is actually being blocked

### ISSUE THREAD

**Issue by jilles** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#650]
**Issue description**
Only ".*_effec" item in "Devices blacklist" is actually being blocked
`.*_effec;.*_pwrmem;.*_volt;.*_consmr;.*_autoff;.*_nled;.*_pres;.*_thb;.*_cell`

Doesn't matter in which order I place this list. Wherever I put effec, it is the only one being blacklisted (not showing up in list of devices)...

**Additional information**
_Zigbee2MQTT version_: v.1.18.3 (zStack3x0 20201026)
_Python version: Python Version_: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
_Domoticz version_: Version: 2021.1 (Build Hash: 8547c5b7e)
_Plugin version:_ v.3.0.0

**Logs**
- Devices blacklist
![image](https://user-images.githubusercontent.com/196457/119620820-ba05fa80-be05-11eb-93ae-d5b624fa25c9.png)
- Devices still shown (example)
![image](https://user-images.githubusercontent.com/196457/119620724-9a6ed200-be05-11eb-887b-2c49aca510b9.png)
- Log snippet (only blocking effec)
[log_snippet.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/6544670/log_snippet.txt)

PS Thanks alot for the great work on this plugin btw! Loving it so much that the 255 limit is now holding me back :D, hence this issue ;)

**Comment by hughb8on** [comment]
Hi, to be clear, if you delete the devices you've included in your blacklist, do they get recreated?

**Comment by jilles** [comment]
That's embarrassing, I really thought I tried that. Apparently only with the effect devices. So long story short: it works. I'm just an idiot. Thanks!
