### ISSUE TITLE
WSDCGQ11LM humidity data 0% in domoticz after update the plugin

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#652]
**Issue description**
Dear @stas-demydiuk ,

After update to the new plugin version no humidity data appears in the sensor xiaomi WSDCGQ11LM.
I made a downgrade to the previous plugin version and the humidity data is Ok. I attach a picture.

![sensores humedad](https://user-images.githubusercontent.com/51416982/120100009-c14b4200-c13e-11eb-821b-95a74a8507d6.jpg)

in the zigbee2mqtt log shows correctly the humidity data. 

Could you check the plugin and solve the problem? We would be very grateful to you. thanks in advanced.
Best regards

**Additional information**
Zigbee2MQTT version: 1.18.3-dev
Python version: Python 2.7.16 / Python 3.7.3
Domoticz version: the last beta

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by SargonofAssyria** [comment]
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Humidity
Possibly a mixup with parameters and/or int vs string

**Comment by kitopopo** [comment]
Yes, i know we have this possibility but i need the separate value. It has always worked correctly, now shows 0%. Thanks in advanced. Best regards

**Comment by SargonofAssyria** [comment]
I Just commented to get it fixed.

**Comment by kitopopo** [comment]
> I Just commented to get it fixed.

thanks dear @SargonofAssyria . Dear @stas-demydiuk , Any change or update on this problem? thanks in advanced. Best regards

**Comment by SargonofAssyria** [comment]
I just updated, (git pull and restart of Domoticz build 13311) but the "standalone" humidity sensor still show 0%.
And the THB sensor still  shows "Prediction: Heavy snow"
I life in the Netherlands, and current temperature is 24 Degrees Celsius.

**Comment by SargonofAssyria** [comment]
https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting#Humidity_sensor
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Humidity
Humidity is a Number (nValue) and the Humidity Status is a String (sValue)
I think those are mixed-up.

**Comment by stas-demydiuk** [comment]
I have the same WSDCGQ11LM device in my setup and all values look fine to me

![image](https://user-images.githubusercontent.com/2734836/121780007-05126280-cba7-11eb-9352-bcf41bc84d83.png)

**Comment by HansOtten** [comment]
Updated and looks goeod for me, Humidity is showing fine. temperature + humidity + barometer talk about prediction heavy snow, but values all look good sofar.

**Comment by SargonofAssyria** [comment]
I deleted the plugin directory and did a fresh clone. Now my humidity sensor shows the right data.
"Heavy Snow" is still present on the THB device.
Pressure device is not changed to "Barometer"
In your picture 984.0 Bar looks not OK. In a Barometer device it will show 984.0 hPa which is OK.
But still it also shows "Heavy Snow" in the Barometer device.
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Barometer
https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting#Barometer_sensor

**Comment by kitopopo** [comment]
Dear friends,

These weeks I have been away on a trip, I just updated the zigbe2mqtt plugin and now it correctly shows the humidity values ​​as before. Thank you so much @stas-demydiuk  you job  and dedication. Best regards
