### ISSUE TITLE
Zigbee2MQTT python plugin devices are not share to master domoticz 

### ISSUE THREAD

**Issue by baahver** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#653]
I've seen this issue before, but then you pointed to the domoticz forum.
I've found this issue on github domoticz page: [link](https://github.com/domoticz/domoticz/issues/2642)
And I'm not an expert but it looks like you are pointing to each other. 
Could you please have a look at it?

**Comment by stas-demydiuk** [comment]
As I know Domoticz currently doesn't support that feature for python plugins
