### ISSUE TITLE
no support for Sonoff Devices 

### ISSUE THREAD

**Issue by Vonkentrekker** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#657]
**Issue description**
After update to v3.x there is no support for Sonoff devices any more 
BasicZBR3 , Sonoff wireless button are not working any more in domoticz 
trying to use old library plug-in chrashes  

**Additional information**
Zigbee2MQTT version:1.83
Python version:3.73
Domoticz version:2021.1
Plugin version:latest

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by HansOtten** [comment]
works fine for me, all Sonoff Zigbee types work. Pair again? Needs to be close to Zigbee controller to pair.

**Comment by Vonkentrekker** [comment]
I have a brand new one straight out of the box ,zigbee2qmtt says pairing oke , supported oke .
But no support in Domoticz , the one i used before is sitting on a difficult place to replace him .
The Sonoff button was also working fine until the update to V3.x , there is no map in adapters for sonoff anymore
On the moment i use a few Node-Red routines witch i use for unsupported devices in domoticz to get them working again

**Comment by stas-demydiuk** [comment]
Do you have any errors in Domoticz log regarding your device?

**Comment by Vonkentrekker** [comment]
No , the new ZBR3 don't get any number created in the Domoticz database , the ZBR3 old one  just don't react on commands of Domoticz .
Also there is no status update or the button commands are working .
On the moment i use Node-red to send the status en commands between domoticz and zigbee2Mqtt using virtual switches.
I am more a hardware guy , trying to get understanding the program, and just starting with Phyton .
i am from the basic and lisp era  so just starting again :)

**Comment by Vonkentrekker** [comment]
I have discovered the problem there are 3 things creating it .
First the limit of 255 inside Domoticz for a plug-in.
I am using about 54 devices inside zigbee2mqtt and have already moved several devices to my Hue hub.
Second in the new version of the plug-in  for every switch there are 2 action buttons created **_switch** and **_state** 
**_switch** is the old existing action  but doesn't work any more inside Domoticz.
**_state**  is the new action for Domoticz and working.
But both are created so to lower the used space and getting everything working again i must remove all unused entry's .
After deleting them i have some space until the next reboot , then all the deleted entry's are back again with new numbers.

**Comment by Vonkentrekker** [comment]
I have put **_switch** in the blacklist , and disabled signal quality .
now i am using just 140 Zigbee entry's  so i have left 115 entry's witch i can use .
maybe i must create another separate Zigbee server  for X-Mas :)
