### ISSUE TITLE
TRADFRI SHORTCUT Button  (IKEA E1812)

### ISSUE THREAD

**Issue by BIIINO** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#659]
**Device description**
IKEA E1812
Shortcut ikea button action: on
 TRADFRI SHORTCUT Button

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example

How can i find it ? I dont know

```
'zigbee2mqtt/Ikea button', payload '{"action":"on","battery":16,"linkquality":36,"update":{"state":"idle"},"update_available":false}'
```

**MQTT messages from device**

MQTT publish: topic 'zigbee2mqtt/0x00124b001ae043b8', payload '{"description":"40639/0x84FD27FFFE1B8493","led":false,"linkquality":31,"rssi":95,"type":"CHILD_RFD"}'

**MQTT state change commands**
{
    "linkquality": 39,
    "battery": 16,
    "action": "on",
    "update": {
        "state": "idle"
    },
    "update_available": false
}

**Comment by Dylantje** [comment]
Hope this device is going to work also:-)

Thanks..

**Comment by stas-demydiuk** [comment]
@Dylantje, do you have any issues with this device, I guess it should work just fine with the latest plugin?

**Comment by Dylantje** [comment]
> @Dylantje, do you have any issues with this device, I guess it should work just fine with the latest plugin?

Sorry i did order a few of this devices, only they where not on stock so i wait until have this one and then report

**Comment by stas-demydiuk** [comment]
Ok, I'll close the ticket for now, feel free to reopen or create another one in case of any issues
