### ISSUE TITLE
Support for Smart Plugs

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#66]
I checked the support devices list and found no mention of smart plugs except Chinese type Xiaomi plugs. I was going to buy one of the ZigBee smart plugs with an energy meter mentioned in the zigbee2mqtt list: https://koenkk.github.io/zigbee2mqtt/information/supported_devices.html

Is there any possibility to extend supported devices by this plugin. It would be very appreciated.

**Comment by stas-demydiuk** [comment]
Yes, there shouldn't be any issues with adding support for new plugs, just need examples of MQTT messages from them
