### ISSUE TITLE
Version number 

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#660]
Dear Stas..
Thanks again for the great work...

Perhaps a option to make visible in the plugin what version there is running.
Now i need to look with putty or something???

Perhaps in the code make a option that the version is visible in domoticz

Hope you can make something like that

**Comment by stas-demydiuk** [comment]
Hi, I'll take a look if it is possible to display a version.
As a workaround, you can also use this plugin https://github.com/stas-demydiuk/domoticz-plugins-manager to keep your plugins up to date

**Comment by hughb8on** [comment]
I think it would be an excellent idea to *have* version numbers.

**Comment by stas-demydiuk** [comment]
Now the version is displayed on Hardware and on plugin UI pages

**Comment by Dylantje** [comment]
Great Thanks
