### ISSUE TITLE
Bug with Domoticz Version 13329

### ISSUE THREAD

**Issue by VBill45** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#661]
**Issue description**
Crash of domoticz version 13329 with plugin zigbee2mqtt 3.0.0
deactivating the plugin removes the problem but the hardware managed by zigbee2mqtt is no longer accessible

**Additional information**
Zigbee2MQTT version: 
Python version:
Domoticz version: 13329
Plugin version: 3.0.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by VBill45** [comment]
Domoticz 13329 is the last version, i have udate to this version yesteday
before no problème
Domoticz running on raspberry 4 with raspbian uptodate

**Comment by snorro80** [comment]
Problem is within Domoticz. 
Fix is on the way: https://github.com/domoticz/domoticz/issues/4861

**Comment by JanJaapKo** [comment]
Issue is solved with Domoticz build 13330. This issue can be closed.
