### ISSUE TITLE
Incompatibility with zigbee2mqtt 1.20.0 - Cover states ON and OFF now generate plugin errors

### ISSUE THREAD

**Issue by hughb8on** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#665]
zigbee2mqtt.io version 1.20.0 has made a change to the way it exposes cover states and this is causing errors in the plugin.

See: zigbee2mqtt.io #2651 Expose cover state as enum (OPEN, CLOSE and STOP) instead of binary (OPEN and CLOSE)

The error generated in the plugin is as follows: -

2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) 'onCommand' failed 'KeyError'.
2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) ----> Line 301 in '/home/hugh/domoticz/plugins/zigbee2mqtt/plugin.py'
2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) ----> Line 104 in '/home/hugh/domoticz/plugins/zigbee2mqtt/plugin.py'
2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) ----> Line 75 in '/home/hugh/domoticz/plugins/zigbee2mqtt/devices_manager.py'
2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) ----> Line 328 in '/home/hugh/domoticz/plugins/zigbee2mqtt/adapter.py'
2021-07-02 16:13:25.761 Error: Zigbee: (Zigbee) ----> Line 33 in '/home/hugh/domoticz/plugins/zigbee2mqtt/devices/switch/blind_percentages_switch.py' 

I don't know how to fix this or I would try!

**Comment by Fab-ME** [comment]
Hello,
I have the same issue. Have you found a solution to go round the problem?

**Comment by hughb8on** [comment]
I have fixed the problem on my own system by editing ..devices/switch/blind_percentages_switch.py

You can either wait for the official fix, or change lines 33 and 37 to look like this: -

     31         if cmd == 'ON':                                                                                                                                         
     32             return {                                                                                                                                            
     33                 state_value_key: 'close'                                                                                                                        
     34             }                                                                                                                                                   
     35         elif cmd == 'OFF':                                                                                                                                      
     36             return {                                                                                                                                            
     37                 state_value_key: 'open'     
     
And restart domoticz of course.

**Comment by Fab-ME** [comment]
Thank you, 
On my side, I had to swap line 33 and 37 otherwise the blinds were closing with opening instruction.

**Comment by hughb8on** [comment]
That's surprising. Did your blinds open and close as expected before upgrading to 1.20.0?

**Comment by Fab-ME** [comment]
Yes, they were properly working before this upgrade. Note: I'm not in inverted blind. 
No worry, I'll wait for the fix, and meanwhile it works for me. 
Thank you very much for your help.

**Comment by heggink** [comment]
@hughb8on why not create a pull request?

**Comment by hughb8on** [comment]
I have raised a pull request #666
I do not know the plugin code well enough to know if this is the only change needed to maintain compatibility betweern the plugin and zigbee2mqtt 1.20.0 so @stas-demydiuk definitely needs to look at this.
