### ISSUE TITLE
YSR-MINI-01

### ISSUE THREAD

**Issue by borisbme** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#667]
**Device description**
RGB led strip controller

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/YSR-MINI-01_rgbcct.html

**MQTT message with device information**
PUT here the device data you receive when publish message with topic

Device successfully paired: {"friendly_name":"0x00124b0022ed10ec","model":"YSR-MINI-01","supported":true,"description":"Zigbee LED controller (RGB+CCT)","vendor":"YSRSAI"}

**Comment by stas-demydiuk** [comment]
Please upgrade plugin to the latest version to get the device supported
