### ISSUE TITLE
PSBZS A1	Parkside smart watering timer	EndDevice	0x847127fffed4ac9b

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#669]
Please make the:
PSBZS A1 | Parkside smart watering timer | EndDevice | 0x847127fffed4ac9b
Working in the plugin.
[https://www.zigbee2mqtt.io/devices/PSBZS_A1.html](url)

In z2m working
Only not visible in the plugin.

**Comment by stas-demydiuk** [comment]
This device should be properly supported by the plugin, do you see any issues with that?

**Comment by Dylantje** [comment]
I do have the 255 problem so i need to update firts the plugin [ al little bit scarry ]
The parkside can i run from domoticz only after x seconds the device is goin to close without that i push the button in domoticz.
And when i manual push the parkside button the device react in domoticz not.

I think fisrt update the plugin

**Comment by Dylantje** [comment]
Error after plugin update:
`
2021-09-04 14:37:42.511 Error: DMP Z2M: (DMP Z2M) Buiten Waterslot: can not process numeric item "timer"
`

**Comment by stas-demydiuk** [comment]
This feature is not yet supported by the plugin, feel free to create an additional [ticket](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?assignees=&labels=new+feature&template=new-device-feature-support.md&title=%60feature_name%60+feature+support) for that
