### ISSUE TITLE
Lidl E14 Candle RGB not doing colour

### ISSUE THREAD

**Issue by sundodger** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#670]
Hi, I recently had to do a full backup restore on my raspberry pi.
Following updating zigbee2mqtt plugin my E14 bulb no longer seems to respond to colour requests and even the white colour temp does not match what i am asking domoticz to send.
This is the sent command from zigbee2mqtt log
Jul 13 11:23:13 raspberrypi npm[19087]: Zigbee2MQTT:info  2021-07-13 11:23:13: MQTT publish: topic 'zigbee2mqtt/0x588e81fffed5ec0f', payload '{"brightness":254,"color":{"x":0.1507,"y":0.0682},"color_mode":"xy","linkquality":28,"state":"ON"}'
I am missing something i am sure but i am at the end on my knowledge so any help appreciated.
I am on the Dev branch.

**Comment by stas-demydiuk** [comment]
What plugin and zibee2mqtt version do you use, is it a clean install or upgrade from the previous version?

**Comment by sundodger** [comment]
Thanks for responding.
I am running the latest Domoticz 2021.1
And zigbee2mqtt Koenkk 1.20
The backup was 6 months old so i updated all. 
So this would be an upgrade rather than a clean install.
I have since found two GU10 Lidl bulbs are not being recognised also. These were working previously.
The log shows this
 2021-07-18 21:13:35.014 Zigbee: (Zigbee) 0x588e81fffef65e3e: device definiton not found, skipping...
2021-07-18 21:13:35.014 Zigbee: (Zigbee) 0x842e14fffe19a755: device definiton not found, skipping... 
The rest of my zigbee devices are working fine.

**Comment by stas-demydiuk** [comment]
Probably there is no definition for them on zigbee2mqtt side, plugin now relies on definitions provided rather than individual device support

**Comment by sundodger** [comment]
Probably, what is throwing me is that they worked fine with the older version.
Will post a question over there.
Thanks for the reply

**Comment by sundodger** [comment]
Hi, i still am having no luck with this.
It seems to be the similar to the problems in #520
If i set a colour via the colour wheel i get some type of white, but if i then select an effect from the effect dropdown it changes to the previously selected colour.
I saw a solution re adding a line to the silvercrest/init.py file but i do not have that file.
If i create one will it fix the problem or does the plugin work differently now?
Domoticz is the latest Beta
Thanks.

**Comment by stas-demydiuk** [comment]
What is in the Domoticz log?

**Comment by sundodger** [comment]
if i select blue in the colour wheel the log gives
2021-09-12 12:52:14.502 Status: setcolbrightnessvalue: ID: 79, bri: 1, color: '{m: 3, RGB: 0304ff, CWWW: 0000, CT: 0}'
The light switches on and it is white/warm white 
If i then select an effect from the effect drop down i get 
2021-09-12 12:53:38.168 Status: User: Admin (IP: 192.168.1.130) initiated a switch command (101/Zigbee - 0x588e81fffed5ec0f (effect)/Set Level)
This changes the light to the colour i selected in step 1 above, it also does the effect e.g blink once.
