### ISSUE TITLE
Lidl moodlight 14148906L see as effec not as color lamp.

### ISSUE THREAD

**Issue by stack0423** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#676]
Hello,
My lidl mood light 14148906L is seen as effec not, as a color lamp,   with this version v.1.19.1-dev (zStack12 20190608).
would be nice if this would work as a color lamp.

**Comment by stas-demydiuk** [comment]
@stack0423 if you still have the issue please provide zigbee definitions for your device. Feature definition could be retrieved from mqtt message when you publish message with topic `zigbee2mqtt/bridge/config/devices`
