### ISSUE TITLE
Develco (Frient) HESZB-120 test mode/error

### ISSUE THREAD

**Issue by Theo-NL** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#678]
Hello,

I have two Frient HESZB-120 heat detectors installed (recognized and installed as Develco HESZB-120), both work within Domoticz and the plugin. However in the Domoticz log appears the message "... Error: Zigbee2MQTT: (Zigbee2MQTT) Brandmelder keuken: can not process binary item "test" and "... Error: Zigbee2MQTT: (Zigbee2MQTT) Brandmelder schuur: can not process binary item "test".

I assume this is related to the test mode on the detectors, because by pushing the test button on the detector the alarm sound of the detector go's on, but nothing happens in Domoticz? The only way to test the working of the detector in Domoticz is by simulating a fire with a sigarette lighter at the detector. 

My Heiman HS1SA-E smoke detectors  (recognised as HS3-SA) for example works flawlessly (including testmode).,  

RaspberryPi 3b
Domoticz Version: 2021.1
Python Version: 3.7.3
Plugin Version 3.0.0.
Zigbee2mqtt v.1.20.0 (zStack12 20190608)
Everything updated.

What could be the problem ?

Thanks in advance !

Regards, Theo (NL).

**Comment by stas-demydiuk** [comment]
That's not an issue, you could ignore these messages
