### ISSUE TITLE
Xiaomi Aqara water leak sensor SJCGQ11LM wrong behavior

### ISSUE THREAD

**Issue by ericsboro** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#68]
After joining sensor shows correct state "Closed", but after ~5-10 minutes it turns to "Open"
 even if there's no water under sensor. 
journal shows:
zigbee2mqtt:info 1/16/2019, 11:15:27 PM MQTT publish: topic 'zigbee2mqtt/water_leak', payload '{"water_leak":false,"linkquality":60,"battery":100,"voltage":3035}'

Re-pairing doesn't help.
Please help to resolve the issue

Many thanks in advance

**Comment by stas-demydiuk** [comment]
It's because Domoticz doesn't have native water leak sensor, the plugin uses general contact sensor. And if there is no water leakage contact is open with corresponding status. Water leakage will close the contact.

**Comment by ericsboro** [comment]
Many thanks for prompt clarification! So the only way is to wait until Domoticz will create own leakage sensor, otherwise reverting status settings will impact open door sensors and similar... really pity :(

Anyway, thanks for the great job your doing!
