### ISSUE TITLE
Xiaomi Aqara TVOC

### ISSUE THREAD

**Issue by nickman80** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#680]
**Device description**

VOCKQJK11LM Xiaomi Aqara TVOC air quality monitor

**Zigbee2mqtt page**

https://www.zigbee2mqtt.io/devices/VOCKQJK11LM.html

**MQTT message with device information**

zigbee2mqtt/0x54ef441000107069\', payload \'{"battery":100,"humidity":50.25,"linkquality":153,"temperature":26.6,"voc":72,"voltage":3000}\''}

**MQTT messages from device**

2021-08-02 18:02:44.937 zigbee: (zigbee) MQTT message: zigbee2mqtt/0x54ef441000107069 {'battery': 100, 'humidity': 50.25, 'linkquality': 153, 'temperature': 26.6, 'voc': 72, 'voltage': 3000}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
@nickman80 / @Dylantje I guess the only feature that is missed for that device in the current plugin version is `voc` data, so could you please provide feature info in this ticket #692
