### ISSUE TITLE
Tuya TS0601_air_quality_sensor

### ISSUE THREAD

**Issue by odelma** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#684]
Device description

Tuya TS0601  air quality sensor

Zigbee2mqtt page

https://www.zigbee2mqtt.io/devices/TS0601_air_quality_sensor.html#tuya-ts0601_air_quality_sensor

MQTT message with device information

'zigbee2mqtt/0x0c4314fffe84e0a4', payload '{"co2":359,"formaldehyd":1,"humidity":62.3,"linkquality":84,"temperature":21.1,"voc":14}'

MQTT messages from device

'zigbee2mqtt/0x0c4314fffe84e0a4', payload '{"co2":359,"formaldehyd":1,"humidity":62.3,"linkquality":84,"temperature":21.1,"voc":14}'

MQTT state change commands
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by SargonofAssyria** [comment]
+1
CO2 sensor -> Custom sensor with axis label ppm
VOC sensor -> Custom sensor with axis label ppb
Formaldehyd sensor -> Custom sensor with axis label ppm (probably)

**Comment by SargonofAssyria** [comment]
Sorry for CO2 there is already a device with type 'Airquality' and SubType 'Voltcraft CO-20'

**Comment by odelma** [comment]
I noticed a feature with this device (the round model at least) that is quite incovenient. It seems to spam updates to zigbee network every second or two seconds, sometimes several times per second. I'm afraid that could lead into all sorts of problems like slower reacting network, logs exploding in size etc. So I would say best to avoid the round model unless there is some firmware update coming...

**Comment by SargonofAssyria** [comment]
I see the same. I wonder if someone has experience with the square item?

**Comment by stas-demydiuk** [comment]
@odelma / @SargonofAssyria could you please provide feature details for related tickets #691  #692
