### ISSUE TITLE
Please add IKEA LED1934G3



### ISSUE THREAD

**Issue by Sh800904** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#685]
**Device description**
TRADFRI LED bulb E27 WW clear 250 lumen, dimmable

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/LED1934G3.html

**Comment by heggink** [comment]
This should be included in the universal adapter?

**Comment by Sh800904** [comment]
Thanks you for your answer. The bulbs work like a charm!
