### ISSUE TITLE
Push buttons are not going back to off

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#687]
Latest z2m 
Latest domoticz
Latest z2m plugin

I do have some push buttons from xiaomi and aqara
Only the buttons are nog going to off.
When i look into z2m dashboard they are going back to off.
Other strange thing, i give in Domoticz a extra off after 4 seconds, and still the button stays to on.

the domoticz  log says no thing about the push button

And i the z2m dashborad log i can see teh button:
```
Info MQTT publish: topic 'zigbee2mqtt/Ryan Druk Plaatje', payload '{"action":"single","battery":100,"click":"single","linkquality":42,"voltage":3025}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Druk Plaatje', payload '{"action":"double","battery":100,"click":"double","linkquality":45,"voltage":3025}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Druk Plaatje', payload '{"battery":100,"linkquality":39,"voltage":3025}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Plaatje', payload '{"consumer_connected":true,"consumption":2.93,"current":0,"energy":2.93,"linkquality":93,"power":0,"state":"OFF","temperature":20,"voltage":216}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Plaatje', payload '{"consumer_connected":true,"consumption":2.93,"current":0,"energy":2.93,"linkquality":90,"power":0,"state":"OFF","temperature":20,"voltage":216}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Druk Plaatje', payload '{"action":"double","battery":100,"click":"double","linkquality":48,"voltage":3025}'
Info MQTT publish: topic 'zigbee2mqtt/Ryan Druk Plaatje', payload '{"action":"single","battery":100,"click":"single","linkquality":48,"voltage":3025}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Ryan Druk Plaatje"},"error":"Device 'Ryan Druk Plaatje' cannot be configured","status":"error","transaction":"rk8as-1"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Ryan Druk Plaatje"},"error":"Device 'Ryan Druk Plaatje' cannot be configured","status":"error","transaction":"rk8as-2"}'
```

So i think in z2m plugin there is something wrong

**Comment by Verysimply** [comment]
Same issue after updating z2m plugin  : 
Domoticz - custom - (plugin) zigbee2mqtt : screen keeps loading ...

Also : 
Lamps are still working an reacting, but switches do not work anymore...

Domoticz V2021.1 (c)2012-2021 GizMoCuz
Status: Build Hash: 8547c5b7e, Date: 2021-04-17 17:29:11
Status: Startup Path: /home/pi/domoticz/
Status: PluginSystem: Started, Python version '3.7.3'.

Plugin version V3.0.1 (recent git pull)

Zigbee2MQTT version : 1.21.0 commit: 70891ee
Coordinator type : zStack3x0
Coordinator revision :20210708
Frontend version : 0.5.18

Loggin domoticz switch : 
zigbee2mqtt: (zigbee2mqtt) MQTT message: zigbee2mqtt/bridge/logging {'level': 'debug', 'message': "Received Zigbee message from 'Z2M-sw-klein01', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 901"}
zigbee2mqtt: (zigbee2mqtt) MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'MQTT publish: topic \'zigbee2mqtt/Z2M-sw-klein01\', payload \'{"action":"on","battery":34,"linkquality":114,"update":{"state":"idle"}}\''}
zigbee2mqtt: (zigbee2mqtt) MQTT message: zigbee2mqtt/Z2M-sw-klein01 {'action': 'on', 'battery': 34, 'linkquality': 114, 'update': {'state': 'idle'}}

So, i'm also thinking there is something wrong in z2m plugin

**Comment by hughb8on** [comment]
Hi, 

I have several push-buttons, including Aqara ones. Mine don't send "Off" either, but I don't expect them to. 

The buttons just report what's been pressed - single, double, long. etc They don't know what those presses mean because they can't know that. For example a single press might mean "On" or it might mean "Off". 

It's up to you to use Domoticz  Selector Levels or scripts to interpret those presses and cause whatever you want to happen.

Of course, I may be missing something because I don't see why you might think this is related to the "Device limit per plugin" (Dylantje) or "Domoticz - custom - (plugin) zigbee2mqtt : screen keeps loading" (Verysimply). Perhaps if you explain that it would help.

**Comment by Dylantje** [comment]
I know that the buttons are made for single double etc.
Only my buttons functioning very good.

Until last week somewhere

Did servel update with domoticz and did a update vor z2m en z2m plugin.
So i cannot get the problem because i did not  need the buttons, so after all the update..

And whn you hae a single click and teh device stays in singel klick?
Even when i set in Domotica a off after 4 seconds.

**Comment by hughb8on** [comment]
I don't understand all of what you are saying, but I think you are asking: why does the device stay in single click state after you've single-clicked it?

The device will stay in the same state until until you put it in a different state. Communication is one-way, so the only way to change its state is manually, by pressing the switch again.

**Comment by Dylantje** [comment]
After last update, the button is stil not ging back to off:
![image](https://user-images.githubusercontent.com/5214969/132094757-955bd582-b573-4c1d-bd9c-7ad3c15325b4.png)

Should going back to 0 when the timer from Domoticz is finisht?
![image](https://user-images.githubusercontent.com/5214969/132094782-1b054664-aa0d-49e0-b385-e92b98d12cca.png)

**Comment by stas-demydiuk** [comment]
They won't go back to off automatically, the plugin just changes the device value to what is received from zigbee2mqtt as @hughb8on described.

For example, for myself, I've created an additional Domoticz script that switches the values back to off

**Comment by Dylantje** [comment]
I know they stays on the value i set them.
Only the 4 seconds off did the trick always.

What can i otherwise do with the 4 seconds off?
Or is this a Domoticz issue then? [ get this problem after last time i did a z2 plugin update ]

What is your script? perhaps that s ok for me

**Comment by stas-demydiuk** [comment]
Here is example of my dzVents script

```
return {
    on = {
        devices = {
            'Cinema switch',
        }
    },
    data = {
        receiverMode = { initial = 200 }
    },
    execute = function(domoticz, device)
        if (device.state == 'single') then
            device.switchOff()
            domoticz.devices('LED').toggleSwitch()
        end
        
        if (device.state == 'double') then
            receiver = domoticz.devices('Yamaha RX-V683 - Straight Mode')
            receiver.toggleSwitch()
            device.switchOff()
        end
        
        if (device.state == 'hold') then
            device.switchOff()
        end
    end
}
```

**Comment by stas-demydiuk** [comment]
Closing the ticket as there is nothing to do with the plugin to address that
