### ISSUE TITLE
Issue when running with Python 3.9

### ISSUE THREAD

**Issue by gbordier** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#689]
using raspberry pi 3 on raspbian  bullseye and domoticz version 2021.1 
  zigbee2mqtt: (zigbee2mqtt) MqttClient::open
Fatal Python error: Segmentation fault
Error: siginfo address=0x31bc, address=(nil)
2021-09-02 17:23:20.896  Error: Did not find stack frame for thread (LWP 12744)), printing full gdb output:

Current thread 0x6f4fe220 (most recent call first):
  File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 55 in _open
  File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 34 in __init__
  File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 81 in onStart
  File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 277 in onStart

**Comment by gbordier** [comment]
works fine on docker image probably linked python3.9 being default in bulleye

**Comment by Fab-ME** [comment]
Hello what is the version of python supported ?

**Comment by svde** [comment]
I'm experiencing the same issue, on a python-3.10.0 based system (fedora 35). The moment the plugin tries to connect to the MQTT server, it crashes:

```
Nov 13 10:55:19 localhost.localdomain domoticz[1342]: 2021-11-13 10:55:19.392  Zigbee2MQTT: Connected to MQTT Server: void.eijk.nu:1883
Nov 13 10:55:19 localhost.localdomain domoticz[1342]: Fatal Python error: Segmentation fault
Nov 13 10:55:19 localhost.localdomain domoticz[1342]: Current thread 0x00007f465affd640 (most recent call first):
Nov 13 10:55:19 localhost.localdomain domoticz[1342]:   <no Python frame>
Nov 13 10:55:19 localhost.localdomain domoticz[1342]: Extension modules: DomoticzEx (total: 1)
Nov 13 10:55:24 localhost.localdomain systemd[1]: domoticz.service: Main process exited, code=killed, status=11/SEGV
Nov 13 10:55:24 localhost.localdomain systemd[1]: domoticz.service: Failed with result 'signal'.
```

This also happens with other plugins that use / are based on the same way to connect to MQTT. Other open issues on the topic: https://github.com/domoticz/domoticz/issues/4967 & https://github.com/emontnemery/domoticz_mqtt_discovery/issues/44

**Comment by mooninite** [comment]
I am unable to comment on [domoticz #4967 ](https://github.com/domoticz/domoticz/issues/4967) for an unknown reason otherwise I would comment there.

I have updated the Fedora domoticz package to support Python 3.10. There were some deprecated changes in 3.10 that Domoticz needed to be updated to handle. The Fedora update is available now in the testing repo.

https://bodhi.fedoraproject.org/updates/FEDORA-2021-82de4e72f1

**Comment by stas-demydiuk** [comment]
Closing the issue, as it is not related to the plugin itself
