### ISSUE TITLE
 Domoticz is offline after configuration

### ISSUE THREAD

**Issue by FRFrancisqueti** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#69]
Hello Stanislav,
I followed the tutorial https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin and also the https://www.domoticz.com/wiki/Zigbee2MQTT. I have the zigbee2mqtt running on localhost: 1883 with cc2531 running and receiving data from my zigbee device (HEIMAN - HS1DS-E) on the terminal. After including the zigbee2mqtt hardware and setting up as localhost: 1883 on Domoticz it stopped working. When I try to open the localhost: 8080 it appears as offline. Would you help me? What can I have done wrong in setup? I resubmitted the Domoticz several times but it did not help.

Thank you.

**Comment by SBTephan** [comment]
it looks like the same issue I have,

could you try:

delete the plugin zigbee2mqtt from the plugin folder. go to the domoticz folder and
run ./updaterelease
then delete the zigbee2mqtt hardware plugin from the hardware tab

**Comment by stas-demydiuk** [comment]
Solution from #72 should work for this case as well
