### ISSUE TITLE
Barometer Forecast incorrect (due to Domoticz documentation error)

### ISSUE THREAD

**Issue by waltervl** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#690]
**Issue description**
Barometer Forecast incorrect (due to Domoticz documentation error)

In temperature_humidity_barometer_sensor.py there is a reference to the incorrect values of the forcast. type 84 subtype 16 has the folowing forecast values. So calculations should get other values.
Forecast: 0 = Heavy Snow, 1 = Snow, 2 = Heavy Rain, 3 = Rain, 4 = Cloudy, 5 = Some Clouds, 6 = Sunny, 7 = Unknown, 8 = Unstable, 9 = Stable 

        if (value < 966):
            return 3  # Rain
        elif (value < 993):
            return 4  # Cloudy
        elif (value < 1007):
            return 5  # Some Clouds
        elif (value < 1013):
            return 6  # Sunny
        else:
            return 7  # No Info

**Comment by stas-demydiuk** [comment]
Do you know what barometer value should be used for each state?

**Comment by waltervl** [comment]
I put the correct values in the calculation. 
 To extend with snow: If temp < 1 degree Celsius rain will change in snow.  I checked in the Domoticz source code but could not find good calculations of the other values.

**Comment by waltervl** [comment]
Just for info, found the domoticz source code of the right calculation, but it depends on the pressure change rate. So you will need some extra work to handle this.
https://github.com/domoticz/domoticz/blob/c997900e7c92c62946f600ec863b97fab16fbe61/main/BaroForecastCalculator.cpp

So for the time being the basic calculation as already present in temperature_humidity_barometer_sensor.py is fine it only needs other state id's (as indicated in the first post).

The device type in barometer.py is a different one ( TypeName="Barometer") and there the weathers states are fine.
