### ISSUE TITLE
`voc` feature support

### ISSUE THREAD

**Issue by stas-demydiuk** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#692]
**Feature description**
Measured VOC value.

**Feature definition**
```
TBD
```

**Related Devices**
https://www.zigbee2mqtt.io/devices/TS0601_air_quality_sensor.html#tuya-ts0601_air_quality_sensor
https://www.zigbee2mqtt.io/devices/VOCKQJK11LM.html

**Additional notes**
Custom sensor with axis label ppb could be used as a logical device in Domoticz

**Comment by Dylantje** [comment]
@stas-demydiuk 
My voc sensor is not function wel i think:
![image](https://user-images.githubusercontent.com/5214969/132094246-9daee85d-6335-4778-9d1a-e07845be64e5.png)

![image](https://user-images.githubusercontent.com/5214969/132094255-c0d86c24-4b0f-47d1-a295-3f4f7276bc08.png)

Import the new devices only no status update

**Comment by Dylantje** [comment]
Did a new pairing, only still no status update

**Comment by Dylantje** [comment]
@stas-demydiuk 
Still only:
![image](https://user-images.githubusercontent.com/5214969/133994270-5dfd0bca-cb2f-4576-a365-8f0b65826cf9.png)
No update..
 And i did insert new batterys

**Comment by stas-demydiuk** [comment]
`voc` feature is now supported by plugin
