### ISSUE TITLE
Strange behavoire HUE light after plugin update

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#693]
All last betas.

This is a HUE white light 
![image](https://user-images.githubusercontent.com/5214969/132094493-1ec0408f-dc3e-416c-911a-b51c6e4733c8.png)

I have some hue and other light that not working fine
@stas-demydiuk Hope i do not have to let the hue light give some sound :-)
Think in the last beta something wrong

Lights are not functioning any more on my Domoticz scrits.
When i use the domoticz device slider or on off they work.
Only not with the scripts etc..

**Comment by stas-demydiuk** [comment]
>When i use the domoticz device slider or on off they work.

Maybe there is some issue with your script? Could you please share it as well

**Comment by Dylantje** [comment]
![image](https://user-images.githubusercontent.com/5214969/132094719-a359a2a2-74ac-4091-9104-f586ee8e773d.png)

This work for years...
Only how can i let play a Hue light some sound?

**Comment by stas-demydiuk** [comment]
Yes, interested as well )))
Maybe some issue in Domoticz Beta, because I don't see anything related in the plugin code, especially assuming that switches work fine

BTW what is the device we are talking about?

**Comment by Dylantje** [comment]
![image](https://user-images.githubusercontent.com/5214969/132094908-b010fa72-d414-4a3e-b75d-eb17010efc22.png)
Hue:
![image](https://user-images.githubusercontent.com/5214969/132094918-f45c8ffa-806d-4d76-8c8b-938b105b4a52.png)

The blocklye works for years, still error after latest z2m plugin update.
Strange part, a light with sound :-)
Think my wife kills me :-)

**Comment by Dylantje** [comment]
@stas-demydiuk 
Did servel reboot
And did a new update for the plugin and Domoticz...
Now this problem is solved
