### ISSUE TITLE
`feature_name` feature support

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#694]
Fort his device:
[https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/669](url)
**Feature description**
`2021-09-04 14:37:42.511 Error: DMP Z2M: (DMP Z2M) Buiten Waterslot: can not process numeric item "timer"`

I think a timer option in this device

I see in mqtt explorer:
`{"linkquality":75,"state":"ON"}
`

**Related Devices**
There is also a strange behvoire between domoticz and this devce.
The off only in the device to hear, only in domoticz device is not going off.
When i use the button on the device there is no action in the Domoticz/plugin.

**Comment by stas-demydiuk** [comment]
Closing as there are no enough details for the feature implementation. Feel free to update the first message and reopen the ticket
