### ISSUE TITLE
Saswell SEA801-Zigbee/SEA802-Zigbee does not give setpoint device

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#696]
This device https://www.zigbee2mqtt.io/devices/SEA801-Zigbee_SEA802-Zigbee.html#saswell-sea801-zigbee%252Fsea802-zigbee
Previous
![04 09 2021_19 23 20_REC](https://user-images.githubusercontent.com/24824113/132103308-fd844727-816b-404c-9b2e-e3fb8e69631c.png)
New
![04 09 2021_19 26 40_REC](https://user-images.githubusercontent.com/24824113/132103321-45c6fdd9-5051-4dc1-89e3-4f8b9e9b3da2.png)

**Comment by stas-demydiuk** [comment]
That's strange, I also see that there are 2 devices for `state`, is it expected?

**Comment by SargonofAssyria** [comment]
No just one state device, the other one should be the setpoint device, as with the first picture.
The device was working good.

**Comment by stas-demydiuk** [comment]
Could you please share all device definitions? You could get them when you publish mqtt message with topic `zigbee2mqtt/bridge/config/devices`

**Comment by SargonofAssyria** [comment]
info  2021-09-04 21:24:13: MQTT publish: topic 'zigbee2mqtt/Hobbykamer', payload '{"anti_scaling":"ON","away_mode":"OFF","battery_low":false,"child_lock":"UNLOCK","current_heating_setpoint":28,"frost_detection":"ON","last_seen":"2021-09-04T21:24:13+02:00","linkquality":63,"local_temperature":21.9,"local_temperature_calibration":0,"preset_mode":"none","system_mode":"auto","window_detection":"ON"}'
