### ISSUE TITLE
Memory usage issue since 3.1.0-beta

### ISSUE THREAD

**Issue by dobber81** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#698]
**Issue description**
Memory leak? From when I updated to 3.1.0-beta the memory usage is increasing every hour until domoticz is restarted.. See attached graph. The memory usage increase stops when disabling domoticz-zigbee2mqtt plugin.
Normal memory usage for domoticz for my installation is 75-85MB. After 12 hours running with the plugin enabled it's about 900MB.
Confirmed on my fresh installed test-setup also.

**Additional information**
Zigbee2MQTT version: v.1.21.1-dev
Python version: 3.7.3
Domoticz version: 13491
Plugin version: 3.1.0-beta

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs
![image](https://user-images.githubusercontent.com/7099281/132139789-939d9f0d-825b-43e4-b4d4-3a50ddf2da4f.png)

**Comment by Bartekn86** [comment]
i have same issiue

**Comment by jilles** [comment]
Me too. Will take up all my ram if I don't kill it with fire

**Comment by pipiche38** [comment]
From what I have seen this version is starting using the new Domoticz.Configure() API and found some similar issues on other plugins

**Comment by dobber81** [comment]
I reverted and problem gone. Definitely an issue introduced with 3.1.0-beta.

**Comment by stas-demydiuk** [comment]
Checked but couldn't find anything in the plugin code, so created the ticket in the Domoticz repo. If anyone has any details regarding the issue or how to debug it, please share

**Comment by jilles** [comment]
> I reverted and problem gone. Definitely an issue introduced with 3.1.0-beta. I'll keep using 3.1.0-beta on my test-setup, but for daily driver 3.0.0 is better for now.

Same here.

**Comment by pipiche38** [comment]
If you are using the Configure() Api, I'm able to reproduce a memory leak with a simple plugin
https://domoticz.com/forum/viewtopic.php?f=65&t=36956

**Comment by Eddie-BS** [comment]
same problem here, with this new version my domoticz hangs within 12 hours and I needed to adjust monit to reboot ...

**Comment by hughb8on** [comment]
I have the same issue.

**Comment by stas-demydiuk** [comment]
Should be now resolved with the latest Domoticz beta, I wonder if someone could check and confirm

**Comment by Eddie-BS** [comment]
waiting for this becomes availiable ... updatebeta gives me no newer version yet

**Comment by dobber81** [comment]
Compiled 13495 on my test-pi. No memory increase for 30 minutes now with v.3.1.0-beta. Will check again in a few hours to make sure.

**Comment by Eddie-BS** [comment]
Running 13495 now, looks good, 79MB in 30min ....

**Comment by dobber81** [comment]
I'm on 4 hours. No issues. I think we can close this ticket.

**Comment by Eddie-BS** [comment]
after 3hours, 87MB, looks pretty normal to me
