### ISSUE TITLE
Question about domoticz events

### ISSUE THREAD

**Issue by flatsiedatsie** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#7]
I wasn't able to create an issue in the Domoticz repository, so here instead: how about adding a blockly  import-export function to the events interface? That way beginning users can share wysiwyg automations.

I have built this functionality into the Aurora theme already. Feel free to use it.
https://github.com/flatsiedatsie/domoticz-aurora-theme/blob/master/blockly_import_export.js

**Comment by stas-demydiuk** [comment]
@flatsiedatsie great idea! added to PR
https://github.com/domoticz/domoticz/pull/2755
