### ISSUE TITLE
device supported list

### ISSUE THREAD

**Issue by Bartekn86** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#705]
Hi,
I wonder if instead of adding unknown devices each time, it is not possible to get this data directly from the zigbee2mqtt converter database? I think practically all the work of adding devices would be gone

B.

**Comment by stas-demydiuk** [comment]
The plugin already works this way, it supports individual features of the device (like state, temperature, brightness, etc.) rather than individual devices
