### ISSUE TITLE
HG06337 / Silvercrest smart plug is recognized but no devices created in Domoticz

### ISSUE THREAD

**Issue by odelma** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#707]
**Issue description**
HG06337 / Silvercrest smart plug (EU, CH, FR, BS, DK) is correctly recognized and operational via zigbee2mqtt bridge. Also this plugin recognizes it and adds to list devices under the zigbee2mqtt custom page. However, it does not create any actual domoticz devices for it. Is there a way to try to force that again or what should be done in this case? I tried stopping and starting the plugin and then Domoticz.

**Additional information**
Zigbee2MQTT version: v.1.21.0-dev (zStack3x0 20201026)
Domoticz version: 2021.1 (build 13360)
Build Hash: eee333c30
Compile Date: 2021-07-04 12:58:11
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Plugin version: 3.0 (updated a few month ago, not a DomoticzEx supported version)

Nothing special in the logs.

I run out of time as this installation is at our summer cottage and needed to leave. I will probably next try to update everything (Domoticz, zigbee2mqtt, this plugin) and remove and try to add the device again. But I was wondering if in hurry and something like this happens, is there something you should/could do quickly to try to force creating the corresponding devices....

**Comment by stas-demydiuk** [comment]
The plugin creates logical devices in Domoticz based on definitions provided by zigbee2mqtt. Could you please check that they exist for your device and post them there. Feature definition could be retrieved from mqtt message when you publish message with topic `zigbee2mqtt/bridge/config/devices`

**Comment by odelma** [comment]
`{"dateCode":"","description":"Silvercrest smart plug (EU, CH, FR, BS, DK)","friendly_name":"0xec1bbdfffeb61bad","hardwareVersion":1,"ieeeAddr":"0xec1bbdfffeb61bad","lastSeen":1631563142351,"manufacturerID":4098,"manufacturerName":"_TZ3000_kdi2o9m6","model":"HG06337","modelID":"TS011F","networkAddress":13472,"powerSource":"Mains (single phase)","type":"Router","vendor":"Lidl"}],"type":"devices"}'`

Is this what you are looking for? I get this published to zigbee2mqtt/bridge/log when I post empty/dummy payload to zigbee2mqtt/bridge/config/devices (/or zigbee2mqtt/bridge/config/devices/get).

**Comment by odelma** [comment]
I also tried to remove and add it again - still the same result of not getting devices created even though plugin sees it (tested with two plugs):
![image](https://user-images.githubusercontent.com/10372952/133152286-67f32828-5eb4-4e99-a7f5-e283a94680d8.png)

**Comment by odelma** [comment]
Hmm, now the same is happening with Gledopto garden lamp 12W.

`{"dateCode":"20131206","description":"Zigbee 12W Garden Lamp RGB+CCT (plus)","friendly_name":"0x00124b0021417b74","hardwareVersion":1,"ieeeAddr":"0x00124b0021417b74","lastSeen":1631642030395,"manufacturerID":0,"manufacturerName":"GLEDOPTO","model":"GL-G-001ZS","modelID":"GL-G-001ZS","networkAddress":39464,"powerSource":"Mains (single phase)","softwareBuildID":"2.0.0","type":"Router","vendor":"Gledopto"}],"type":"devices"}' `

I have 206 zigbee devices so it should not be about that? Although I’ve had more along the way, removed and re-added. Now the number is 206. And I was able to add Aqara Opple switch (creates 9 devices) between the Lidl plug and Gledopto garden lamp.

**Comment by Dunkie66** [comment]
I have exactly the dame issue, but with 3 Ikea Tradfri controle outlets (E1603). The are visible in the Customer menu, but no devices are created. I also have Aqara door sensors and there are created devices for. I'am curious about the solution for this issue.

**Comment by stas-demydiuk** [comment]
Do you have anything in Domoticz log, and could you please make sure you allow to create new devices in settings.

@odelma I also see that you aren't using the latest version of the plugin

**Comment by odelma** [comment]
You mean at the time of pairing, is there anything in the logs? I don’t think so but I can test again when I have a chance. I have new devices allowed all the time so it is not about that.

In this setup (at our cottage) we rely very much on selector switches so I cannot update to DomoticzEx version due to #708. I can update to last version before that change if it helps? Can you point me to correct version in this case?

**Comment by Dunkie66** [comment]
Allow create new devices was in. In the meanwhile I have upgraded to version 3.0.0 instead of 0.2.1, dus a restart of Domoticz and now the Ikea devices are created and working fine. I also have no DomoticzEx, so not running the latest version of the plug-in.

**Comment by odelma** [comment]
Hello,

I put debuggin on and tried to re-pair:

On pairing pop-up I see:

```
{"message":"announce","meta":{"friendly_name":"0xec1bbdfffeb61bad"},"type":"device_announced"}
Once you close the window, "pair mode" will be disabled on the bridge
```

Then in the log:
```
2021-09-17 14:29:03.170 Zigbee2MQTT: (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'MQTT publish: topic \'zigbee2mqtt/bridge/log\', payload \'{"message":"announce","meta":{"friendly_name":"0xec1bbdfffeb61bad"},"type":"device_announced"}\''}
2021-09-17 14:29:03.170 Zigbee2MQTT: (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/log {'message': 'announce', 'meta': {'friendly_name': '0xec1bbdfffeb61bad'}, 'type': 'device_announced'}
```

Then after a while the normal(?) message of general status:
`2021-09-17 14:29:51.630 Zigbee2MQTT: (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/info {'commit': 'fc2e8304', 'config': {'advanced': {'adapter_concurrent': None, 'adapter_delay': None, 'availability_blacklist': [], 'availability_blocklist': [], 'availability_passlist': [], 'availability_timeout': 0, 'availability_whitelist': [], 'cache_state': True, 'cache_state_persistent': True, 'cache_state_send_on_startup': True, 'channel': 11, 'elapsed': False, 'ext_pan_id': [221, 221, 221, 221, 221, 221, 221, 221], 'homeassistant_discovery_topic': 'homeassistant', 'homeassistant_legacy_entity_attributes': True, 'homeassistant_legacy_triggers': True, 'homeassistant_status_topic': 'hass/status', 'ikea_ota_use_test_url': True, 'last_seen': 'disable', 'legacy_api': True, 'log_directory': '/opt/zigbee2mqtt/data/log/%TIMESTAMP%', 'log_file': 'log.txt', 'log_level': 'info', 'log_output': ['console', 'file'], 'log_rotation': True, 'log_symlink_current': False, 'log_syslog': {}, 'pan_id': 6754, 'report': False, 'rtscts': False, 'soft_reset_timeout': 0, 'timestamp_format': 'YYYY-MM-DD HH:mm:ss'}, 'ban': [], 'blocklist': [], 'device_options': {}, 'devices': {'0x000d6f00149137cd': {'friendly_name': '0x000d6f00149137cd'}, '0x00124b001ed01cb0': {'friendly_name': '0x00124b001ed01cb0'}, '0x00124b001ef67495': {'friendly_name': '0x00124b001ef67495'}, '0x00124b00210b6b1c': {'friendly_name': '0x00124b00210b6b1c'}, '0x00124b00210b76fc': {'friendly_name': '0x00124b00210b76fc'}, '0x00124b00213f3c27': {'friendly_name': '0x00124b00213f3c27'}, '0x00124b0021417b4a': {'friendly_name': '0x00124b0021417b4a'}, '0x00124b0021417b74': {'friendly_name': '0x00124b0021417b74'}, '0x00124b002141a96b': {'friendly_name': '0x00124b002141a96b'}, '0x00124b00222dea19': {'friendly_name': '0x00124b00222dea19'}, '0x00124b00222deb08': {'friendly_name': '0x00124b00222deb08'}, '0x00124b002263f46c': {'friendly_name': '0x00124b002263f46c'}, '0x00158d00011049be': {'friendly_name': '0x00158d00011049be'}, '0x00158d00014d6123': {'friendly_name': '0x00158d00014d6123'}, '0x00158d00016d0110': {'friendly_name': '0x00158d00016d0110'}, '0x00158d000232991b': {'friendly_name': '0x00158d000232991b'}, '0x00158d000418320f': {'friendly_name': '0x00158d000418320f'}, '0x00158d00041e25cb': {'friendly_name': '0x00158d00041e25cb'}, '0x00158d00044bc3b0': {'friendly_name': '0x00158d00044bc3b0'}, '0x00158d0004aad90e': {'friendly_name': '0x00158d0004aad90e'}, '0x00158d000533e145': {'friendly_name': '0x00158d000533e145'}, '0x00158d00053eb7eb': {'friendly_name': '0x00158d00053eb7eb'}, '0x00158d00053eb862': {'friendly_name': '0x00158d00053eb862'}, '0x00158d00068b8f00': {'friendly_name': '0x00158d00068b8f00'}, '0x04cf8cdf3c798188': {'friendly_name': '0x04cf8cdf3c798188'}, '0x04cf8cdf3c798198': {'friendly_name': '0x04cf8cdf3c798198'}, '0x04cf8cdf3c798207': {'friendly_name': '0x04cf8cdf3c798207'}, '0x04cf8cdf3c7d4725': {'friendly_name': '0x04cf8cdf3c7d4725'}, '0x04cf8cdf3c7d64d4': {'friendly_name': '0x04cf8cdf3c7d64d4'}, '0x04cf8cdf3c7d7463': {'friendly_name': '0x04cf8cdf3c7d7463'}, '0x0c4314fffe84e0a4': {'friendly_name': '0x0c4314fffe84e0a4'}, '0x588e81fffe3f15cc': {'friendly_name': '0x588e81fffe3f15cc'}, '0x588e81fffe6dd841': {'friendly_name': '0x588e81fffe6dd841'}, '0x588e81fffe72e1ce': {'friendly_name': '0x588e81fffe72e1ce'}, '0x588e81fffe75b924': {'friendly_name': '0x588e81fffe75b924'}, '0x680ae2fffe1ae739': {'friendly_name': '0x680ae2fffe1ae739'}, '0x680ae2fffe2ec0bf': {'friendly_name': '0x680ae2fffe2ec0bf'}, '0x680ae2fffe7acca5': {'friendly_name': '0x680ae2fffe7acca5'}, '0x680ae2fffe95802a': {'friendly_name': '0x680ae2fffe95802a'}, '0x7cb03eaa0a018007': {'friendly_name': '0x7cb03eaa0a018007'}, '0x7cb03eaa0a0181df': {'friendly_name': '0x7cb03eaa0a0181df'}, '0x7cb03eaa0a078e9a': {'friendly_name': '0x7cb03eaa0a078e9a'}, '0x842e14fffe064cb2': {'friendly_name': '0x842e14fffe064cb2'}, '0x842e14fffe065fe1': {'friendly_name': '0x842e14fffe065fe1'}, '0x842e14fffe57d342': {'friendly_name': '0x842e14fffe57d342'}, '0x842e14fffe5a1d1d': {'friendly_name': '0x842e14fffe5a1d1d'}, '0x842e14fffe5b9524': {'friendly_name': '0x842e14fffe5b9524'}, '0x842e14fffe76987a': {'friendly_name': '0x842e14fffe76987a'}, '0x842e14fffea78044': {'friendly_name': '0x842e14fffea78044'}, '0xec1bbdfffe2c30ca': {'friendly_name': '0xec1bbdfffe2c30ca'}, '0xec1bbdfffe993e4e': {'friendly_name': '0xec1bbdfffe993e4e'}, '0xec1bbdfffe9ed68f': {'friendly_name': '0xec1bbdfffe9ed68f'}, '0xec1bbdfffeb61bad': {'friendly_name': '0xec1bbdfffeb61bad'}, '0xec1bbdfffee15501': {'friendly_name': '0xec1bbdfffee15501'}}, 'experimental': {'new_api': True, 'output': 'json'}, 'external_converters': [], 'frontend': {'port': 8081}, 'groups': {'0': {'devices': ['0x588e81fffe3f15cc/1', '0x588e81fffe6dd841/1', '0x588e81fffe72e1ce/1', '0x588e81fffe75b924/1'], 'friendly_name': 'Keittiön kattovalot_ct'}, '1': {'devices': ['0x00124b002141a96b/11', '0x00124b0021417b4a/11', '0x00124b00213f3c27/11', '0x00124b001ef67495/11', '0x00124b001ed01cb0/11'], 'friendly_name': 'Sohvapöydän valot_rgbw'}, '2': {'devices': ['0x00124b00210b76fc/11', '0x00124b00210b6b1c/11'], 'friendly_name': 'Ruokapöydän valot_rgbw'}}, 'homeassistant': False, 'map_options': {'graphviz': {'colors': {'fill': {'coordinator': '#e04e5d', 'enddevice': '#fff8ce', 'router': '#4ea3e0'}, 'font': {'coordinator': '#ffffff', 'enddevice': '#000000', 'router': '#ffffff'}, 'line': {'active': '#009900', 'inactive': '#994444'}}}}, 'mqtt': {'base_topic': 'zigbee2mqtt', 'force_disable_retain': False, 'include_device_information': False, 'server': 'mqtt://localhost:1883'}, 'ota': {'disable_automatic_update_check': False, 'update_check_interval': 1440}, 'passlist': [], 'permit_join': True, 'serial': {'disable_led': False, 'port': '/dev/ttyUSB0'}, 'whitelist': []}, 'config_schema': {'definitions': {'device': {'properties': {'debounce': {'description': 'Debounces messages of this device', 'title': 'Debounce', 'type': 'number'}, 'debounce_ignore': {'description': 'Protects unique payload values of specified payload properties from overriding within debounce time', 'examples': ['action'], 'items': {'type': 'string'}, 'title': 'Ignore debounce', 'type': 'array'}, '`

But no new devices created in Domoticz

**Comment by odelma** [comment]
> Allow create new devices was on. In the meanwhile I have upgraded to version 3.0.0 instead of 0.2.1, did a restart of Domoticz and now the Ikea devices are created and working fine. I also have no DomoticzEx, so not running the latest version of the plug-in.

To which version did you update? I need to avoid the DomoticzEx one as long as the selectors do not work...

**Comment by Dunkie66** [comment]
I did not clone the repository. I downloaded the ZIP-file en WinFTP'd it to the directory. So git reflog does not work.
It's the V.3.0.0 version released on 27 mar.

**Comment by acaonweb** [comment]
Same problem here with a BTicino L4003c 
Zigbee2mqtt recognize it perfectly and I can switch using web gui,
See there

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/720
