### ISSUE TITLE
Selector switches do not trigger the associated action anymore

### ISSUE THREAD

**Issue by odelma** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#708]
**Issue description**
Selector switches do not trigger the associated action anymore. I have for example a json call as a selector switch action but after updating to latest version, this does not trigger anymore. The selector switch state changes according to e.g. what button is pressed but the associated action does not trigger.

Here I can see a mention of similar behavior: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/687#issuecomment-907814317 => 

> Lamps are still working an reacting, but switches do not work anymore...

In my case I can see similar behavior. As such the (selector)switches work as the state changes while button is pressed for some reason the action is not triggering. I reverted back to previous (on my installation) which was 3a490e5.

Domoticz version:
Version: 2021.1 (build 13491)
Build Hash: 9afde0154
Compile Date: 2021-08-31 17:11:40
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

zigbee2mqtt version:
1.21.1 commit: 4a51e0c0

plugin version:
Update to 12a7fae -> not working, revert to 3a490e5 -> working again (well, noticed I am now getting all kinds of errors related to blinds but at least selectors are again working 😅)

Unfortunately there was nothing particular in logs about this. Based on them, everything seemed to be ok.

**Comment by stas-demydiuk** [comment]
@odelma as switch states are updated in Domoticz fine I don't think that it is something related to the plugin code, likely it could be connected to the new DomoticzEx framework for plugins that plugin currently use. I would suggest finding a scenario that is easy to reproduce and create an issue in Domoticz repo itself.

**Comment by odelma** [comment]
Yeah, makes sense. I will raise an issue in Domoticz repo as well...
