### ISSUE TITLE
Domoticz not starting after installing plugin

### ISSUE THREAD

**Issue by SBTephan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#72]
After installing the plugin in domoticz, domoticz won'start.

this is wat the log said:

2019-01-26 14:49:19.893 Error: Domoticz received fatal signal 11 !...
2019-01-26 14:49:19.911 Error: /home/pi/domoticz/domoticz() [0x262154]
2019-01-26 14:49:19.911 Error: /home/pi/domoticz/domoticz(_Z14signal_handleri+0x4c) [0x26220c]
2019-01-26 14:49:19.912 Error: /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0) [0xb6c1b180]

Any ideas?

Best regards,
Stephan

**Comment by stas-demydiuk** [comment]
What python version is installed?

сб, 26 янв. 2019 г. в 19:15, SBTephan <notifications@github.com>:

**Comment by SBTephan** [comment]
ok. already installed 3.6.7. will try to run domoticz on that version

**Comment by SBTephan** [comment]
installing 3.6.7 seems to be working.. 

I already added a lightbulb to zigbee2mqtt, when the plugin wasn't installed. is it possible to add that device in domoticz?

**Comment by stas-demydiuk** [comment]
There is no such requirement to have Domoticz and MQTT on the same server. Could you please try plugin with Domoticz beta as well?

**Comment by SBTephan** [comment]
I have installed a new domoticz setup on a Pi3 with Python 3.5.3. Everything works fine there.
Looks like the problem is indeed with Domoticz or python
