### ISSUE TITLE
Bticino L4003c isn't added to Domoticz Device

### ISSUE THREAD

**Issue by acaonweb** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#720]
Zigbee2MQTT version 1.21.0 commit: 70891eec
Coordinator type zStack3x0
Coordinator revision 20210120
Frontend version 0.5.18
Domoticz Version: 2021.1 (build 13669)
Build Hash: f30dc726c
Compile Date: 2021-10-01 18:47:35
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
stas-demydiuk
domoticz-zigbee2mqtt-plugin 3.0.0

after pairing, the hardware L4003c is recognized from zigbee2mqtt, but no domoticz  devices is added

![Immagine 2021-10-02 105520](https://user-images.githubusercontent.com/22882393/135709921-c9953220-e3cc-4deb-8b98-3c77bdbbd6b7.png)

**Comment by stas-demydiuk** [comment]
Did you try to just restart the plugin?

**Comment by acaonweb** [comment]
Yes, I've restarted everything, plug-in, domoticz, raspberry .

**Comment by stas-demydiuk** [comment]
Try to enable `debug` mode in the plugin, restart and check Domoticz log, is there any useful information?

**Comment by acaonweb** [comment]
Verbose debug mode?

**Comment by acaonweb** [comment]
2021-10-02 18:26:29.370 Zigbee2MQTT: (Zigbee2MQTT) This plugin does not support zigbee device with model "K4003C/L4003C/N4003C/NT4003C" yet
2021-10-02 18:26:29.370 Zigbee2MQTT: (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md
2021-10-02 18:26:29.572 Zigbee2MQTT: (Zigbee2MQTT) This plugin does not support zigbee device with model "K4003C/L4003C/N4003C/NT4003C" yet

**Comment by stas-demydiuk** [comment]
You need to update the plugin version, it doesn't seem that you have a v3.0 plugin

**Comment by acaonweb** [comment]
Log from zigbee2mqtt switching on off

Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":66,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":66,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":69,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/Vibration1_zb', payload '{"angle":5,"angle_x":3,"angle_x_absolute":87,"angle_y":-1,"angle_y_absolute":91,"angle_z":87,"battery":86,"linkquality":138,"sensitivity":"high","strength":42,"voltage":2975}'
Info MQTT publish: topic 'zigbee2mqtt/CC2531ROUTER', payload '{"led":true,"linkquality":66}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":15,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":15,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":15,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":15,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":18,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":12,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"identify","linkquality":18,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"off","linkquality":18,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":15,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"on","linkquality":30,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":54,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/CC2531ROUTER', payload '{"led":true,"linkquality":75}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"off","linkquality":30,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":21,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":33,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"identify","linkquality":27,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"action":"on","linkquality":27,"state":"OFF"}'
Info MQTT publish: topic 'zigbee2mqtt/BTicinoL4003C', payload '{"linkquality":36,"state":"ON"}'

**Comment by acaonweb** [comment]
I've updated from  domoticz plug in manager, but how the right procedure?

**Comment by acaonweb** [comment]
I’ve done with sudo git pull 
cd domoticz/plugins/zigbee2mqtt
git pull

**Comment by acaonweb** [comment]
![image](https://user-images.githubusercontent.com/22882393/135725458-b3a9db32-8cf3-4532-8843-b2e29206a6b3.png)

**Comment by stas-demydiuk** [comment]
Do you have the same message in the log?

**Comment by acaonweb** [comment]
Yes

2021-10-02 19:11:35.275 Zigbee2MQTT: (Zigbee2MQTT) This plugin does not support zigbee device with model "K4003C/L4003C/N4003C/NT4003C" yet
2021-10-02 19:11:35.275 Zigbee2MQTT: (Zigbee2MQTT) If you would like plugin to support this device, please create ticket by this link: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?labels=new+device&template=new-device-support.md

**Comment by stas-demydiuk** [comment]
That means that you have another folder with the plugin, or your folder is corrupted as in plugin v3.1 there is no such message "This plugin does not support zigbee device with model ..." anymore

Try to completely remove the folder and install the plugin from scratch

**Comment by acaonweb** [comment]
Ok done from scratch
Now I have that 
![image](https://user-images.githubusercontent.com/22882393/135728416-f16c38fa-5bed-4790-ac07-709367e7eae3.png)

**Comment by stas-demydiuk** [comment]
Now you need to clear browser cache

**Comment by acaonweb** [comment]
Works!
Thanks
