### ISSUE TITLE
sonoff motion zigbee sensor does not work

### ISSUE THREAD

**Issue by rumpibandi** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#722]
hi!
"(Zigbee2mqtt) This plugin does not support zigbee device with model "SNZB-03" yet"
it is a simple sonoff dome motion sensor:
https://itead.cc/product/sonoff-snzb-03-zigbee-motion-sensor/
please if possible fix this and add this also among the supported devices.
THX

**Comment by rumpibandi** [comment]
hi, oh no issue i updated the plugin... it works
THX

**Comment by peteralm097** [comment]
Does it create a history in domoticz log? Can you see when the sensor has been activated?

**Comment by mcmellow** [comment]
> hi! "(Zigbee2mqtt) This plugin does not support zigbee device with model "SNZB-03" yet" it is a simple sonoff dome motion sensor: https://itead.cc/product/sonoff-snzb-03-zigbee-motion-sensor/ please if possible fix this and add this also among the supported devices. THX

Hi,  I have paired the Sonoff SNZB-03 with the zzh CC2652R z2m coordinator.  The SNZB-03 is visible in the zigbee2mqtt tab. But there is no device made in Domoticz.  I am on the latest update of the plugin. How can I use this motion sensor in Domoticz?
