### ISSUE TITLE
[3.1-beta] Domoticz does not show the friendly names correctly in notifications

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#724]
dear @stas-demydiuk , I hadn't updated the plugin for 3 months, after the last update to the 3.1 plugin version I have seen an implementation in the plugin configuration through JSON. But I am not able to make domoticz show or detect the "friendly name", if not that it is sent as the device name of the "device id", is it possible to continue using the friendly name adding some data to the JSON structure?
the friendly name continues to be configured correctly in zigbee2mqtt and is displayed in the device table.

```
{
    "domoticz": {
        "device_id": String     // Domoticz Device ID (not idx) in Domoticz
        "legacy_alias": String  // Alias, legacy key that was used in zigbee2mqtt plugin <= 3.0, required to support logical devices that were created before
        "unit": Number          // Domoticz Device Unit
    },
    "zigbee": {
        "address": String       // Zigbee IEEE Address
        "endpoint": String      // Zigbee endpoint (for devices that have multiple ones like switches with several buttons)
        "feture": String        // zigbee2mqtt feature name (power, state, temperature, etc.)
    }
}
```

thanks in advance, i wait news from you.

Best regards

**Additional information**
Zigbee2MQTT version: zigbee2mqtt: v.1.21.1-dev (zStack3x0 20210120)
Version: 2021.1 (build 13626)
Build Hash: da57df49b
Compile Date: 2021-09-28 07:54:37
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by stas-demydiuk** [comment]
This configuration is just an internal structure that the plugin uses under the hood, could you please explain why do you need friendly_name there?

**Comment by kitopopo** [comment]
> This configuration is just an internal structure that the plugin uses under the hood, could you please explain why do you need friendly_name there?

Dear friend,

I don't know if I need the implementation through the new JSON configuration. What I know so far is that with the old version of the zigbee2mqtt plugin I could correctly see the names in domoticz (friendly name), now and after updating the plugin to version 3.1 I do not see the names in telegram notifications that reach me. It is with the name of zigbee2mqtt as you can see in the example:

```
plugin with previous versions:
2021-10-03 16:31:54.304 Status: Notification: Sensor1 Salon Closed
2021-10-03 16:31:54.479 Status: dzVents: Info: Handling events for: "Sensor1 Salon", value: "Closed"

with plugin 3.1 updated
2021-10-03 16:42:56.378 Status: Notification: 0x00158d000273b8c6_sensor Open
2021-10-03 16:42:56.489 Status: dzVents: Info: Handling events for: "Sensor1 Salon", value: "Open"
```

I would like the names of my zigbee devices to show up as before and I don't know how to solve it.
After update to the new JSON settings, the messages from my telegram bot arrive as 0x00158d000273b8c3_sensor closed.
The notification is sent directly by domoticz through the device itself within the notifications menu of the device. I have 40 zigbee sensors and i lost the friendly names in the notifications. How i can solve it?

Thanks in advanced, best regards

**Comment by stas-demydiuk** [comment]
Please share your devices list and script that you are running. I suppose that you just need to rename your device on devices tab

**Comment by kitopopo** [comment]
> Please share your devices list and script that you are running. I suppose that you just need to rename your device on devices tab

Dear friend, I do not have any script to send notifications from the zigbee opening sensors. It is the domoticz itself who is responsible for sending the notification through the opening sensor menu. I attach some photos so that you can understand me. I have tried to change the name of the opening sensor itself but the telegram notification remains the same.

![1](https://user-images.githubusercontent.com/51416982/135760284-31af00f4-67f8-452a-96f5-bba25fec5d1b.jpg)
![2](https://user-images.githubusercontent.com/51416982/135760286-ca60137b-614b-4b10-9559-0f806579b679.jpg)
![3](https://user-images.githubusercontent.com/51416982/135760291-505f6e2e-9384-47cf-bf99-254700ab566c.jpg)
![4](https://user-images.githubusercontent.com/51416982/135760293-6e77832c-82b3-4c19-89ac-7e0086bc3ed5.jpg)
.

Thanks in advanced

**Comment by kitopopo** [comment]
Dear @stas-demydiuk , any idea or solution? Thanks in advanced. Best regards

**Comment by stas-demydiuk** [comment]
Yes, it only confirms the assumption that the root cause is somewhere in migration to the DomoticzEx framework. At the moment I have no idea what could cause it, but maybe some of you could find the reason.

https://www.domoticz.com/wiki/Developing_a_Python_plugin

**Comment by kitopopo** [comment]
Dear @stas-demydiuk ,

you were right, the problem with the name of the notifications was solved with the latest beta 13828.  But now is impossible to access to custom --> zigbee2mqtt. I have commented on this in the other issue that I opened for domoticz. Thanks for you support. Best regards

**Comment by stas-demydiuk** [comment]
It's a known issue, see #729

**Comment by kitopopo** [comment]
> It's a known issue, see #729

thanks again. Best regards
