### ISSUE TITLE
Groups won't be created/recognized in Domoticz after upgrade to 3.1

### ISSUE THREAD

**Issue by sammyke007** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#732]
**Issue description**
So... I had major issues with Z2M without any reason.
I decided to update Z2M plugin to 3.1, but I didn't read that the plugin needed the latest beta's to work... So I updated Domoticz to latest beta (coming from 2021.1 stable) and everything from zigbee devices stopped working.
I removed Z2M plugin in Domoticz and readded it. What a joy to create all of my Z2M devices again :-(.

Now:
- the Custom Z2M page in Domoticz doesn't load anymore (cleared cache, different browser, ...)
- I have 2 Z2M device groups, but the plugin won't create their devices/IDXs. (Yes, they're named XYZ_ct as requested, it always worked in the past. 

**Additional information**
Zigbee2MQTT version: 1.21.2
Python version: 3.7.3
Domoticz version: Version: 2021.1 (build 13788)
Plugin version: 3.1 (pulled today)

**Comment by stas-demydiuk** [comment]
Should be fixed now, could you please check

**Comment by sammyke007** [comment]
Will check ASAP when I get home next week! Tnx for following up!

**Comment by sammyke007** [comment]
Ok, took longer than expected, sorry.

Updated from f8c22fc... to latest commit and it seems to work fine (after adding device "api_transport", maybe writhe tis in red in the installation guide). Groups ok, switches ok, custom menu ok. I'll report back after more testing. Tnx!

**Comment by sammyke007** [comment]
Seems to work OK! Tnx!
