### ISSUE TITLE
Unable to generate network map.

### ISSUE THREAD

**Issue by piotr333k** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#735]
At current config (as follows) zigbee2mqtt plugin is not generating a network map.
The plugin sends a request to "zigbee2mqtt/bridge/networkmap/routes'".
However zigbee2mqtt listens on 
"zigbee2mqtt/bridge/request/networkmap"

**Additional information**
Zigbee2MQTT version: 1.21
Python version: 3.7.3
Domoticz version: 13743
Plugin version: newest 3.0.0

**Comment by sammyke007** [comment]
You have to be patient. For me (with +30 zigbee routers and enddevices) the map takes +- 1 minute to be generated.

**Comment by piotr333k** [comment]
Is the topic correct? I've been waiting for over 10 minutes (mosquitto_sub -t zigbee2mqtt/#) and I 've got no map.

**Comment by stas-demydiuk** [comment]
Updated the network map API that plugin uses, could you please check now

**Comment by mcmellow** [comment]
Just did an update of the plugin. A map is made on my site. I must admit it took a few minutes. As far as I can see it works.
Mostly I use the zigbee2mqtt Frontand page.

**Comment by piotr333k** [comment]
> Updated the network map API that plugin uses, could you please check now

After an update to the plugin it works. Thank you
