### ISSUE TITLE
domoticz does not show individual logs of zigbee devices 

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#738]
Dear friend,

Since the last update of the zigbee2mqtt plugin to version 3.1 domoticz does not show the individual logs of zigbee devices such as xiaomi opening sensors, xiaomi motion sensors, xiaomi smart plugs, xiaomi vibration sensors , philips hue bulbs... 
the temperature graphs if they are displayed correctly from the xiaomi zigbee temperature sensors and xiaomi plugs.

I should also open an issue to domoticz so that mr @dnpwwo check again domoticzEx framework?  or this time if it is a problem with the zigbee2mqtt 3.1 update plugin? or maybe @koenkk must check zigbee2mqtt? 

All the individual log data of the aforementioned xiaomi devices appears empty but the rest of the individual logs of virtual switches or shelly devices appear correctly please see atach picture. any update from november 2.

![log](https://user-images.githubusercontent.com/51416982/141879574-184152ba-f779-4fee-8d46-dff8d154bbca.jpg)

thanks again for your work and dedication. 

Best regards

**Comment by Claude2666** [comment]
Same here. Only switch devices have no log. The Temperature, Weather and Utility devices are logged correctly.
Seems to have started when I updated the plugin to 3.1.

**Comment by kitopopo** [comment]
> Same here. Only switch devices have no log. The Temperature, Weather and Utility devices are logged correctly. Seems to have started when I updated the plugin to 3.1.

I am glad that someone else with zigbee2mqtt I have the same problem, I opened this issue 12 days ago and I have not received any response from the mr. @stas-demydiuk  or mr. @dnpwwo.

I think this is a very important problem, we cannot see the log of almost any device. I'm starting to get tired of zigbee2mqtt, one problem after another problem. 

We do not know if the problem is with the zigbee2mqtt plugin or with the domoticzEx framework. 

I'm on a domoticz forum and no one uses zigbee2mqtt anymore, everyone uses conbeeII. If they don't solve the problem, I'm going to migrate to conbeII. I asked them and no one has any kind of problem and they comment that they have much more stability. I am very happy with zigbee2mqtt but I have seen the latest problems and that they do not solve because we will have to change systems in the short term. I do not know if @gizmocuz is aware of this problem.

Nobody gets involved with this problem, maybe the next step would be to open a new issue to domoticz since in the last one I opened about a problem with domoticzEx framework nobody answered either.

https://github.com/domoticz/domoticz/issues/5000

Hopefully someone from all those mentioned above can solve the problem soon. I once again thank all of them for their work and dedication and I thank them very much in advance. a cordial greeting

**Comment by Oleg-Sob** [comment]
For me, too, the Zigbee switch logs have ceased to be kept, help fix this.

**Comment by odelma** [comment]
This is due to the new way that extended plugin framework handles logging. @stas-demydiuk would need to update the plugin, but I fear he does not have too much motivation to keep this plugin updated when there is the native autodiscovery implemented. That's a shame as this plugin handled certain things like multi-button switches much better than auto discovery.

**Comment by Oleg-Sob** [comment]
Switched to automatic detection in mqtt, logging appeared. I like the Zigbee2mqtt plugin better than the automatic detection in mqtt. I think that someday this plugin will be finalized.

**Comment by kitopopo** [comment]
Dear friend, i have opened this issue 29 days ago, can you fix this problem please? thanks in advanced. Best regards

**Comment by stas-demydiuk** [comment]
Just pushed an update based on @dnpwoo comment [here](https://www.domoticz.com/forum/viewtopic.php?p=280998#p280998). Could you please check if it helps?

**Comment by kitopopo** [comment]
> Just pushed an update based on @dnpwoo comment [here](https://www.domoticz.com/forum/viewtopic.php?p=280998#p280998). Could you please check if it helps?

I have the lastest beta from yesterday. Same problem

**Comment by Oleg-Sob** [comment]
Updated, the logs are not filling.

**Comment by kitopopo** [comment]
Dear friend,

Thanks, after plugin update now domoticz show the device logs. Thanks again

**Comment by Oleg-Sob** [comment]
After updating the plugin, I still have no logs in the switches.

**Comment by kitopopo** [comment]
> After updating the plugin, I still have no logs in the switches.

Dear friend, 

In my particular case, the logs of the devices prior to the plugin update do not appear, it is necessary to cause new changes in the devices so that it appears reflected in the individual log. Can you test?

**Comment by Oleg-Sob** [comment]
Thanks, everything worked, the logs appeared.

**Comment by Claude2666** [comment]
I confirm. After update to the latest plugin, all new events are properly logged. 
Thank you.
