### ISSUE TITLE
How can i change the update frequency of my Tuya Thermo devices

### ISSUE THREAD

**Issue by lansi002** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#739]
**Issue description**
I have a Tuya thermovalve device and got it working with zigbee2mqtt in Domoticz.

What i see is that the device is queried every 2 minutes.

Like this
Like this:
Nov 16 21:33:51 aolrpi4b1 npm[3602]: Zigbee2MQTT:info  2021-11-16 21:33:51: MQTT publish: topic 'zigbee2mqtt/Radiator Master', payload '{"anti_scaling":"ON","away_mode":"OFF","battery_low":false,"child_lock":"LOCK","current_heating_setpoint":20,"frost_detection":"ON","linkquality":0,"local_temperature":19.5,"local_temperature_calibration":0,"preset_mode":"none","system_mode":"heat","window_detection":"ON"}'

Can i change the frequency of the device query, because i want to save the device battery.

I only need the device information once an hour.

Thank you for your help.

**Comment by stas-demydiuk** [comment]
There is nothing you could do with that on a plugin side, try to check that ability from zigbee2mqtt itself
