### ISSUE TITLE
Support for Müller E27 color Led from startset 43952

### ISSUE THREAD

**Issue by jbrouns** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#74]
**Device description**
Müller E27 color Led from startset 43952
(https://www.mueller-licht.de/produktinformationen/artikel/404000/)
The Led lamp in the set is probably the same as the separately sold 404000

**MQTT message with device information**

{"ieeeAddr":"0x00158d000340f000","type":"Router","model":"404000/404005/404012","friendly_name":"0x00158d000340f000"}

**MQTT messages from device**
zigbee2mqtt/0x00158d000340f000
{"state":"ON","brightness":100,"color_temp":556,"color":{"x":0.2,"y":0.2,"saturation":80.7,"hue":228},"color_mode":1}

**Comment by JochemLangerak** [comment]
Hi,

These Müller Tint devices are for sale at ALDI in the Netherlands at the moment. 

Just add the following lines in the __init__.py in ~/domoticz/plugins/zigbee2mqtt/adapters:

    # Müller Tint / Aldi
    '404006/404008/404004': DimmableCtBulbAdapter, # Aldi/Müller Tint,  dimmable, white spectrum
    '404000/404005/404012': RGBWAdapter, # Aldi/Müller Tint E27,  dimmable, white spectrum/RGB Color

I've only tested it with the GU10 white dimmable and these are added in my device list 👍 

If someone has a any idea how to connect both zigbee2mqtt and the remote control which comes with the starter set I would be very happy.

**Comment by jbrouns** [comment]
Hi,

My device comes from Aldi-Süd in Germany, they were on sale there last week.

Your solution works perfect. Thank you very much!
I hope it will soon be part of the official release :-)

And yes, if someone has a working solution for the remote, that would be great!

best,
Julien

**Comment by stas-demydiuk** [comment]
@jbrouns these devices are now available in latest master branch

**Comment by jbrouns** [comment]
Thank you very much!
