### ISSUE TITLE
Support for led dimmer

### ISSUE THREAD

**Issue by Marcel-lo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#740]
Would it be possible to add this zigbee 3.0 LED dual white dimmer to domoticz please?
Miboxer
Model: FUT035Z

Zigbee2mqtt plugin recognized it but in log file it says that it is not supportet yet.
Or is there any docu I could follow to add adapter and support for new device please?

**Comment by stas-demydiuk** [comment]
Looks like you are using an old plugin version, after you upgrade to the latest one the device should work fine. Please note that there were several breaking changes in the plugin so it might require to remove the old plugin instance from Domoticz Hardware before upgrading to a new one
