### ISSUE TITLE
Domoticz beta crashes

### ISSUE THREAD

**Issue by olivierperdaens** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#741]
**Issue description**
Domoticz beta (13872) crashes when plugin zigbee2mqtt (beta 3.1.0) is added

**Additional information**
Zigbee2MQTT version: 1.22.0 commit: df0543d4
Python version: 3.9.2
Domoticz version: beta (13872)
Plugin version: (beta 3.1.0)

**Logs**
2021-11-25 10:59:19.659  Status: Zigbee2MQTT: Initialized version 3.1.0-beta
2021-11-25 10:59:19.661  Error: Domoticz(pid:17317, tid:17365('Zigbee2MQTT')) received fatal signal 11 (Segmentation fault)
2021-11-25 10:59:19.661  Error: siginfo address=0x43a5, address=(nil)
2021-11-25 10:59:21.349  Error: Did not find stack frame for thread (LWP 17365)), printing full gdb output:

**Comment by ariekanarie2005** [comment]
Issue description
Domoticz beta (13872) crashes when plugin zigbee2mqtt (beta 3.1.0) is added

Additional information
Zigbee2MQTT version: 1.22.0 commit: df0543d4
Python version: 3.9.2
Domoticz version: beta (13872)
Plugin version: (beta 3.1.0)

Domoticz wont start after added plugin.

**Comment by ariekanarie2005** [comment]
Maybe the plugin is not the problem but domoticz and python 3.9 and plugins using python, see this: https://www.domoticz.com/forum/viewtopic.php?f=6&t=37376

**Comment by KoenJanssen** [comment]
It seems the actual issue is discussed here: https://www.domoticz.com/forum/viewtopic.php?f=6&t=37376

**Comment by stas-demydiuk** [comment]
Looks like the same issue as #689, closing this one
