### ISSUE TITLE
Moes MS-105BZ brightness not exposed in Domoticz Z2M plugin

### ISSUE THREAD

**Issue by ptaudio** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#743]
The Moes MS105BZ dimmer does not have the brightness feature exposed so it can't be controlled from Domoticz.
Only the state and link quality are exposed. According the description here : https://www.zigbee2mqtt.io/devices/MS-105B.html
this should be available.
I'm running v.1.22.0 (zStack30x 20190425) and Domoticz version 2021.1
CC2531 is connected through 2 meter extension cable.
I'm able to control the brightness with the hardware button,so dimmer is working fine.
Also when adjust i the brightness with the hardware button the dimmer slider in Domoticz moves.

What happened : no brightness control
What did you expect to happen : be able to control brightness
How to reproduce it (minimal and precise) : nothing to reproduce. Brightness is not exposed
Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: CC2531
Adapter firmware version: Z-stack3.0.x

![Schermafbeelding 2021-11-28 om 21 52 14](https://user-images.githubusercontent.com/17804745/143785562-f1aa6826-4018-47e6-ac18-4a3ef9e5dc44.png)

**Comment by ptaudio** [comment]
@stas-demydiuk can you please look at this issue ?? Thanks :-)

**Comment by Pumba1970** [comment]
I Have the same Issue. Slider is not working in Domoticz.  
Control from zigbee2mqtt frondend is working and updating. Seems somthing in mqtt comunication.
