### ISSUE TITLE
No menu in Domoticz 

### ISSUE THREAD

**Issue by Sarcas666** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#748]
**Issue description**
I managed to install my zigbee usb stick on my rpi4 and installed the plugin via the plugin manager. My zigbee device was found and added to domoticz, and it works. The issue is that nothing happens when I choose the Zigbee2MQTT pull down menu in domoticz. I see the screen with tabs, but it only says 'Loading...". Nothing else happens. 

**Additional information**
Zigbee2MQTT version: don't know. Fresh installed yesterday. 
Python version: 3.7.3
Domoticz version: 2021.1 13872
Plugin version: 3.1.0 bet

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by Bram81** [comment]
I'm struggeling too since a fresh install yesterday, but I just managed to fix the same issue you are having. In domoticz go to the devices tab, search for the transport api (a text device) and add it as a device. Restart domoticz and there should me a menu.

**Comment by Oleg-Sob** [comment]
![77](https://user-images.githubusercontent.com/71137109/146573247-3d6055dd-104b-4c12-93b4-691f274eba7e.JPG)

**Comment by Flappiee** [comment]
I'm experiencing the same issue:

Domoticz: Version: 2021.1 (build 13949)
Zigbee2MQTT: 1.22.1-dev commit: 53003b3d
Zigbee2MQTT Domoticz Plugin: v3.1.0 beta

After adding the api_transport as device, it works as expected. You can also add this device as hidden device by using an $ sign before the name of the device, so it doesn't show up under other devices.

**Comment by Oleg-Sob** [comment]
Thanks for the hint about the $ sign, I didn't know about this before.

**Comment by Sarcas666** [comment]
> After adding the api_transport as device, it works as expected. You can also add this device as hidden device by using an $ sign before the name of the device, so it doesn't show up under other devices.

I forgot to reply. Your solution worked. Thanks!
