### ISSUE TITLE
TS0121_plug does not display power

### ISSUE THREAD

**Issue by Oleg-Sob** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#749]
**Issue description**

Power socket https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121-plug does not display power

![33](https://user-images.githubusercontent.com/71137109/146570248-3673e2ce-fd0d-41ba-86f3-cdb5136cf42b.JPG)

MQTT-Explorer has it.

![55](https://user-images.githubusercontent.com/71137109/146570517-99eb12b2-8068-4f80-8450-dd6fb5bb2471.JPG)

Is it possible to add power readings to the plugin?

**Additional information**
Zigbee2MQTT version: v.1.22.1
Domoticz version: 2021.1.13947  2021-12-17
Plugin version: v.3.1.0-beta

**Comment by sammyke007** [comment]
It's a bug in the plugin that tries to read the power_outage_memory value instead of the power value. Temp workaround is filtering the attribute power_outage_memory in the Z2M frontend (select device --> settings --> "Filter attributes from publish payload." --> click + --> type power_outage_memory

You'll have to do this for each device in the Z2M frontend.

**Comment by stas-demydiuk** [comment]
Does the issue still persist?

**Comment by sammyke007** [comment]
I still have to filter "power_outage_memory", yes.

**Comment by stas-demydiuk** [comment]
Are you sure you are using the latest plugin version as I don't see such an issue with my TS0121 Plug

<img width="891" alt="image" src="https://user-images.githubusercontent.com/2734836/166112436-1237c47f-f958-453e-863c-33701233da1b.png">

**Comment by sammyke007** [comment]
I'll try to update to the latest commit ASAP

**Comment by sammyke007** [comment]
I'm a little bit afraid to update to v3.1 as it removes the "_th" temp + hum devices and creates T + H + B  devices which I don't need. I lost a complete days some months ago after an unssuccesful update. I only have a live setup running, no test environment...

**Comment by sammyke007** [comment]
Updated to latest v3.1 plugin today and it's fixed indeed. No need to filter the attribute anymore. Tnx
