### ISSUE TITLE
IKEA TRADFRI control outlet - no verification of response message

### ISSUE THREAD

**Issue by tabnul** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#75]
**Issue description**
When switching this device, the command seems to be fire and forget. It doesnt look properly on the response. When the device is unavailable, domoticz just switches it without error. (see last log row)

**Additional information**
Zigbee2MQTT version: 1.1.1
Python version: 2.7.13
Domoticz version: 4.9700
Plugin version: 0.0.17

**Logs**
MQTT Log:
`
Feb 11 19:23:55 raspberrypi npm[10814]: zigbee2mqtt:info 2/11/2019, 7:23:55 PM Zigbee publish to device '0x000d6ffffec7d1f9', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null
Feb 11 19:23:56 raspberrypi npm[10814]: zigbee2mqtt:error 2/11/2019, 7:23:56 PM Zigbee publish to device '0x000d6ffffec7d1f9', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.`

Domoticz Log:
In debug mode only the first publish is posted, versus two publishes on a correct switch.

**Comment by stas-demydiuk** [comment]
This behavior comes from zigbee2mqtt not from the plugin, so I can do nothing about it here.

**Comment by tabnul** [comment]
@stas-demydiuk 
Zigbee2mqtt handles the situation correct. It throws an error.
Under normal circumstances a second message is received from the outlet, if the switch went ok.

Shouldnt domoticz honorate response messages? Thats the whole point of zigbee (else you could just use 433 mhz, no response, shoot and forget)

**Comment by stas-demydiuk** [comment]
What is your vision for this case assuming that zigbee2mqtt doesn't replicate specified error over mqtt, so plugin will never receive it?

**Comment by tabnul** [comment]
It does replicate a succesfull switch (the outlet confirms by sending the status after the switch).
If it doesnt confirm, it didnt switch right.
