### ISSUE TITLE
ZVG1 not all devices created successfully 

### ISSUE THREAD

**Issue by demono10000** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#750]
![image](https://user-images.githubusercontent.com/48636182/146807470-0acfa69c-f873-4877-a510-97afff3dabf1.png)
![image](https://user-images.githubusercontent.com/48636182/146808290-1980bd7a-7f7b-483d-a5a8-aae9a4bbad74.png)
Does someone know how to fix that error?

**Comment by stas-demydiuk** [comment]
That's expected, not all device features are supported by the plugin, feel free to create feature request for each feature you need using this [template](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?assignees=&labels=new+feature&template=new-device-feature-support.md&title=%60feature_name%60+feature+support)
