### ISSUE TITLE
Zigbee2mqtt in Kubernetes

### ISSUE THREAD

**Issue by airmonitor** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#751]
Hello.

At first thx for your time put in that project :)

I'm wondering if you could share more light on using domoticz with your plugin in Kubernetes?

Asking because I got everything working with docker-compose when I have 3 containers:

- mqtt
- zigbee2mqtt
- domoticz + zigbee2mqtt plugin

When I switched to k8s with the same architecture as in docker-compose I wasn't able to see any Zigbee devices in domoticz (custom tab). I feel that plugin weren't able to communicate with the zigbee2mqtt container.

In docker-compose every pod can communicate using localhost I think, but in K8s this is achieved via service names (dns).

From top of your head do you remember what address your plugin is using to connect to the zigbee2mqtt?

Or maybe any oder idea? :)

Regads
Tom

**Comment by stas-demydiuk** [comment]
The plugin communicates with zigbee2mqtt via MQTT protocol, so you could use `MQTT Server address` field in plugin settings to configure your own address
