### ISSUE TITLE
Several "can not process" messages appear in the Domoticz log

### ISSUE THREAD

**Issue by TheLion** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#752]
**Issue description**
Several "can not process" messages appear in the Domoticz log

**Additional information**
Zigbee2MQTT version: 1.22.0
Python version: 3.7.3
Domoticz version: 2021.1 build 13949
Plugin version: 3.1.0-beta

**Logs**
[Domoticz_log.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/7774183/Domoticz_log.txt)

Do these messages appear in the log because they are not (yet) supported/processed by the plugin?

**Comment by stas-demydiuk** [comment]
That's expected, not all device features are supported by the plugin, feel free to create feature request for each feature you need using this [template](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/new?assignees=&labels=new+feature&template=new-device-feature-support.md&title=%60feature_name%60+feature+support)
