### ISSUE TITLE
last_valve_open_duration feature support

### ISSUE THREAD

**Issue by demono10000** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#755]
**Feature description**
Time the valve was open

**Feature definition**
{
    "access":1,
    "description":"Time the valve was open when state on",
    "name":"last_valve_open_duration",
    "property":"last_valve_open_duration",
    "type":"numeric",
    "unit":"min",
}

**Related Devices**
https://www.zigbee2mqtt.io/devices/ZVG1.html

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by demono10000** [comment]
It is working, thanks!
