### ISSUE TITLE
Xiaomi Aqara devices with temperature/humudity not updating in Domoticz

### ISSUE THREAD

**Issue by Flappiee** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#757]
**Issue description**
I have a few Xiaomi Aqara temperature sensors. Alle of there sensors stopped updating it's temperature and humudity in Domoticz.
The Zigbee2MQTT interface is showing the correct values. If i check my devices in Domoticz, it showed up as "0x00158d0002c77714_th" This device doesn't have the correct values. The device "0x00158d0002c77714" has the correct values.
Howver, i always use the _the device which only shows temp and humity (and not the device that shows pressure)

**Additional information**
Zigbee2MQTT version: 1.22.1 (and also tried latest dev: 1.22.1-dev commit: b0585172)
Python version: pi@domoticz:~ $ python --version: Python 2.7.16   |   pi@domoticz:~ $ python3 --version:  Python 3.7.3
Domoticz version: Version: 2021.1 (build 13949)
Plugin version: 3.1.0 BETA

For example, as you can see, the device ending with "_th" isn't updated anymore:
![2021_12_26_21_37](https://user-images.githubusercontent.com/55132512/147419502-d02c5751-5efe-4229-a8a5-d8975676adc6.png)

Zigbee2MQTT Web Gui is showing the correct values:
![2021_12_26_21_38_13](https://user-images.githubusercontent.com/55132512/147419512-62328991-8c6f-4873-bd31-2f8f8093e777.png)

It looks like it stopped working around 9 december. Can't remember what exaclty changed. I think it whas the update to Zigbee2MQTT version 1.22.1 and the latest BETA plugin of Zigbee2MQTT plugin. Howver, it shows up correctly in Zigbee2MQTT web gui, so i think there is something broken in the plugin.

**Comment by sammyke007** [comment]
Yeah stas, can you please fix this? Since 3.1 the "_th" devices are not used any longer. I don't need pressure.
See commit [(https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/commit/1fd64f27dc322238de5a7407aa15f252bdd930c1)]
WSDCGQ11LM is the device.

**Comment by stas-demydiuk** [comment]
Try to just remove this `_th` device from Domoticz and restart the plugin, after that plugin should re-create the broken device

**Comment by Flappiee** [comment]
When removing the device i will lose all history. Is there an other option to fix this?

**Comment by sammyke007** [comment]
> Try to just remove this `_th` device from Domoticz and restart the plugin, after that plugin should re-create the broken device

AFAIK it only creates a T+H+B device and not a T+H device. Is that correct?

**Comment by Flappiee** [comment]
I removed 3 temperature sensors and restarted Domoticz to get them recreated.
They all show this information (so no temp and so on):
![2022_01_17_12_34_13](https://user-images.githubusercontent.com/55132512/149762537-1bc7ea6a-4f07-48df-a1c9-d1eed45f00ec.png)

**Comment by sammyke007** [comment]
It didn't work for me neither, but did you wait at least 50 minutes to receive a device update? Aqara/Xiaomi battery devices send data every 50 minutes.

**Comment by Flappiee** [comment]
Yes, thank you. I see most of them are updated now. 2 are missing and i think their battery needs to be replaced.
But what happend with the plugin? Looks like things has changed since i don't have _th devices anymore.
They all show their zigbee address as id an the plugin creates unit numbers.

**Comment by sammyke007** [comment]
Any update on this? Are temp+hum devices created again or only temp+hum+bar? I'm still on v3.0 because of this...

**Comment by Flappiee** [comment]
I'm on latest beta 3.1. i removed the devices and they are recreated and after this they are working again. You will lose your history by recreating the devices.

**Comment by sammyke007** [comment]
Are they created as temp + humidity only or as temp + humidity + barometer? Or both?

**Comment by Flappiee** [comment]
I have:
Temp
Temp + Humidity
Humidity
Temp + Humidity + Baro
Baro

**Comment by rolfie23** [comment]
@stas-demydiuk can we get the _th device back again? year ago or so we also asked for it. You made the _th device back. 
Don't want to deleted it because of the log of 4 years and longer. It makes now an thb device, but you can't replace those in domoticz.

**Comment by sammyke007** [comment]
@rolfie23, I have updated and the plugin created a temp, hum, barom, temp+hum and a temp+hum+barom device for each Aqara temperature sensor. I'm on the latest commit. Working fine except the SQL errors, but everything works.

**Comment by rolfie23** [comment]
> @rolfie23, I have updated and the plugin created a temp, hum, barom, temp+hum and a temp+hum+barom device for each Aqara temperature sensor. I'm on the latest commit. Working fine except the SQL errors, but everything works.

Okay, here that didn't happen. Going to look when I have some time. Reverted back to dev branche, errors also gone. Definitely not stable yet.
