### ISSUE TITLE
Xiaomi Plug ZNCZ02LM - voltage

### ISSUE THREAD

**Issue by Creo2005** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#767]
Domoticz - last beta
zigbee2mqtt - last from git
zigbee2mqtt-plugin - last from git

Voltage is present:
![Снимок экрана 2022-01-09 в 14 17 17](https://user-images.githubusercontent.com/10849149/148682158-cfaab8da-887d-4375-9f6d-e4fde52eb91b.png)
But in Domoticz - Devices not present!

**Comment by stas-demydiuk** [comment]
Any issues in the Domoticz log?
