### ISSUE TITLE
3.0.0 Plugin won't load Custom/Zigbee2MQTT "Allow new Zigbee Devices to join" option is not present

### ISSUE THREAD

**Issue by McGyver64** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#770]
After a week of trying en re-installing I have Raspberry Pi running with Buster, Mosquitto 1.5.7, Zigbee2MQTT 1.22.2, Python 3.7, Domoticz (Stable) and Zigbee2MQTT-Plugin 3..0.0 (downgrade like suggested) . I also tried with Mosquitto 2.0.0 but the result is the same.

**What happened?**

ZigBee2MQTT is recognized by Domoticz and added to devices
Custom Button is present, Zigbee2mqtt Button is Present
"Allow new Zigbee Devices to join" is not present and devices is waiting........ 

Did a full clean install according " https://contactkring.nl/phpbb/viewtopic.php?t=941&start=40 " changed npm ci --production for npm ci (according koenkk) [Koenkk/zigbee2mqtt/issues/10877]

PI OS = Buster (incl update&upgrade)
Mosquitto 1.5.7 (also tried 2.0.0)
zigbee2mqtt=1.22.2
firmware=20211217
node=v12.22.9
npm=6.14.15
python 3.7.3
Domoticz=2021.1
python zigbee plugin= 3.0.0 (downgrade https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin )

ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Jan 18 16:45 usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_37_E9-if00-port0 -> ../../ttyUSB0

I tried Safari, Edge, Crome, refreshed caches etc. But it wil not show the "allow new zigbee devices to join" option for adding new devices. 

<img width="1264" alt="Schermafbeelding 2022-01-14 om 12 22 08" src="https://user-images.githubusercontent.com/69874589/149507670-1cc54946-72e4-4238-b25a-b7b84c485183.png">

**Comment by McGyver64** [comment]
I installed all again for the xx time. did a upgrade to Domoticz beta and used de beta 3.1.0 plugin. This is the only way to get the Custom button "Allow new zigbee devices to join" available

<img width="1199" alt="Schermafbeelding 2022-01-20 om 13 43 13" src="https://user-images.githubusercontent.com/69874589/150341172-ca75e742-6377-48d1-b4f4-a29f755fc8fb.png">

But when I select "allow new zigbee devices..."  I get a new pop-up showing "pairing.      waiting for new device"  but there is nog info shown of new device. When I close it after some time (1-5 min) it shows a new device. 

<img width="791" alt="Schermafbeelding 2022-01-20 om 13 52 02" src="https://user-images.githubusercontent.com/69874589/150342093-d6c4e449-497b-4721-9b21-ccb5e41da604.png">

When I close the window, the new device is added

<img width="1208" alt="Schermafbeelding 2022-01-20 om 13 53 15" src="https://user-images.githubusercontent.com/69874589/150342365-2102872e-0147-4606-b7ad-76d8b2c35160.png">

Also if I want to remove a device (does not matter if do/don't select force remove) the device is not removed and stil shows in device list

<img width="692" alt="Schermafbeelding 2022-01-20 om 13 54 53" src="https://user-images.githubusercontent.com/69874589/150342735-2e50ffd8-2d9a-4dd2-a590-5a97b5c4a0ee.png">



What am I missing?  in the past week I did 20-30 new fresh installs, every time following the same instruction wich I used before early 2021, but every time I only get the Custom button and " Allow new zigbee devices" to appear when I install the Domoticz Beta version with plugin 3.1.0 Beta . The default Domoticz with downgrade 3.0.0 plugin does not show " Allow new zigbee devices" att all and keeps on displaying " Loading........"

**Comment by TB404** [comment]
I bumped into the same problem as originally described but even checking out a commit from last year will not fix the problem. The buttons dont appear. 

I really prefer not to upgrade my Domoticz itself, but a git checkout 3725a295e12531e5c5f68d03d3e6f0c1f646b1ca  Aug 2021 submit, which was mentioned to be ok, does stop the python3.7 error to appear, but it still does not load the Custom/Zigbee2MQTT page.

Tried older ones as well, but all give the same issue.

Anyone an idea how to get the plugin to work with 2021.1?

**Comment by McGyver64** [comment]
I think I got it working, the plugin works and is showing "Allow new Zigbee Devices to join" Also the remove from database is working and all with the non beta Domoticz and 3.0.0 version plugin. 
Yesterday I finished to 20 + install. Here is what I did

I Installed an older Raspbian version 2020-02-13
http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2020-02-14/
I ran update&upgrade&dist-upgrade
Raspberry firmware: 
   sudo apt rpi-update
Domoticz install curl: 
   -L https://install.domoticz.com | bash 
Install Zigbee2mqtt: 
   https://www.zigbee2mqtt.io/guide/installation/01_linux.html
After [sudo apt-get install -y nodejs npm git make g++ gcc] I get node Version 10.x and npm Version 5.x
I updated node and npm to v14 and v6 with: 
   sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - 
   sudo apt-get install -y nodejs
I use log2ram to reduce writing to SD card. I got some errors which were gone after:
   wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add
again did an update&upgrade and reboot
Continue with:
   git clone https://github.com/Koenkk/zigbee2mqtt.git
After configuring 
   nano /opt/zigbee2mqtt/data/configuration.yaml
I did a reboot and installed mosquitto (NPM would not start, maybe mosquitto needed installed earlier)
This gave me mosquitto version 1.5.7
Finished zigbee2mqtt installation

Installed Domoticz plugin:
   git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt
Installed Python
   https://www.domoticz.com/wiki/Using_Python_plugins
Restart Domoticz
Downgrade Zigbee plugin from 3.1.0 beta  to 3.0.0
   https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
   cd domoticz/plugins/zigbee2mqtt 
   git reset --hard f8c22fc330229b39f06ff11bbfcea38e3a492306cd
Reboot Pi

Add the Zigbee2MQTT hardware to Domoticz 

Reboot again, and now the function should be available 

<img width="1193" alt="Schermafbeelding 2022-01-21 om 12 22 32" src="https://user-images.githubusercontent.com/69874589/150518820-097b9de1-3454-41d6-80ed-f5eab7bef2aa.png">

<img width="1211" alt="Schermafbeelding 2022-01-21 om 12 24 39" src="https://user-images.githubusercontent.com/69874589/150519105-8e26f651-1288-4e3d-a7f1-4158352cee2c.png">

<img width="1200" alt="Schermafbeelding 2022-01-21 om 12 25 52" src="https://user-images.githubusercontent.com/69874589/150519251-9b1d7149-9076-4e93-8b8a-30f74ed5d1f0.png">

<img width="638" alt="Schermafbeelding 2022-01-21 om 12 26 58" src="https://user-images.githubusercontent.com/69874589/150519378-d7f8493e-8ea5-487d-ae41-2a27c482c47a.png">

<img width="1190" alt="Schermafbeelding 2022-01-21 om 12 27 51" src="https://user-images.githubusercontent.com/69874589/150519484-a494e368-1286-4528-848a-99223e4fc841.png">

<img width="593" alt="Schermafbeelding 2022-01-21 om 12 28 44" src="https://user-images.githubusercontent.com/69874589/150519607-10fd8283-9315-4916-8014-989ad57367f8.png">

**Comment by TB404** [comment]
@McGyver64 

If I try to change the plugin to previous version ( git reset --hard f8c22fc330229b39f06ff11bbfcea38e3a492306cd )

I get:
fatal: ambiguous argument 'f8c22fc330229b39f06ff11bbfcea38e3a492306cd': unknown revision or path not in the working tree.
I did complete remove and checkout the plugin again (to master)

**Comment by McGyver64** [comment]
I am sorry, but I can't help you with this. My solution is based on trial and error (not deep linux knowledge) and after 2 weeks of trying, the solution as described worked for me. 

Did you do a "gift pull" like described in (https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin)
Maybee a reboot and update&&upgrade&&dist-upgrade?

**Comment by TB404** [comment]
The webpage still doesnt work,but controlling devices does work with manually joining to Zigbee2MQTT (using the configuration.yaml options.)

What I see now is that groups are no longer added as device in Domoticz. This is quite a big challenge for me.

Running on git checkout f8c22fc

I do see some errors appearing, but that is more related to colors of devices:
022-01-23 16:36:07.304 Error: Zigbee: (Zigbee) IKEA.bulb.color.1: can not process numeric item "color_temp_startup"
2022-01-23 16:36:07.306 Error: Zigbee: (Zigbee) IKEA.bulb.white.spectrum.1: can not process numeric item "color_temp_startup"
2022-01-23 16:36:07.308 Error: Zigbee: (Zigbee) IKEA.bulb.white.spectrum.2: can not process numeric item "color_temp_startup"
2022-01-23 16:36:07.309 Error: Zigbee: (Zigbee) IKEA.bulb.white.spectrum.3: can not process numeric item "color_temp_startup"
2022-01-23 16:36:07.310 Error: Zigbee: (Zigbee) IKEA.bulb.white.spectrum.4: can not process numeric item "color_temp_startup"

I am not too concerned about that specific part.
Those 4 lights are in 1 and the same lamb, and controlling as one device would be highly prefered. The groupname_ct is not joined to Domoticz, but there is also no error.

The group is working with a zigbee dimmer bound to that group ID, so the group itself works in Zigbee2MQTT
