### ISSUE TITLE
Plugin update error

### ISSUE THREAD

**Issue by Theo-NL** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#775]
Hello,

I (beginner) did the plugin update as described
- cd domoticz/plugins/zigbee2mqtt
- git pull

Works fine but at the end I get this error
“error: The following untracked working tree files would be overwritten by merge:
        .github/ISSUE_TEMPLATE/new-device-feature-support.md
        api/plugin.py
        bridge.py
        configuration.py
        frontend/libs/ace_json_mode.js
        frontend/libs/ace_worker_json.js
        frontend/plugin_config.js
Please move or remove them before you merge.
Aborting”

My configuration:
RaspberryPi 3b
Domoticz Version: 2021.1
Python Version: 3.7.3
Plugin Version 3.0.0.
Zigbee2mqtt v.1.22.2 (zStack12 20190608)

What could be the problem ?

Thanks in advance !

Regards, Theo (NL).

**Comment by stas-demydiuk** [comment]
try to run `git reset --hard` before the `git pull`

**Comment by Theo-NL** [comment]
Thanks for reponding.

Tried "git reset --hard" and then "git pull", but error stays:

pi@raspberrypi-TJB:~/domoticz/plugins/zigbee2mqtt $ git reset --hard
HEAD is now at f85ebbe Fix rgb feedback for Philips Hue (Lily) (#683)
pi@raspberrypi-TJB:~/domoticz/plugins/zigbee2mqtt $ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
   f09463a..6fa6eb5  master     -> origin/master
Updating f85ebbe..6fa6eb5
error: The following untracked working tree files would be overwritten by merge:
        .github/ISSUE_TEMPLATE/new-device-feature-support.md
        api/plugin.py
        bridge.py
        configuration.py
        frontend/libs/ace_json_mode.js
        frontend/libs/ace_worker_json.js
        frontend/plugin_config.js
Please move or remove them before you merge.
Aborting

**Comment by Theo-NL** [comment]
Remark: After posting my comment, I see now that some rules were (unintentionally) crossed out. This was not the case in my original text. My mistake (copy and paste via Word, as a result of spell check).

**Comment by stas-demydiuk** [comment]
You also could just completely remove the plugin folder and clone it agian

**Comment by Theo-NL** [comment]
Ok, thanks, I will try that.

Before doing that: 
I assume by removing en reinstalling the plugin all my many devices, settings, etc. in “/opt/zigbee2mqtt” will be lost or overwritten, or filled with duplicated devices?
How do I prevent this lost of settings/devices/data/etc and unwanted new devices? 

If action is needed possibly by:
- stop Domoticz
- copy the whole zigbee2mqtt folder (“/opt/zigbee2mqtt”) to another temporary folder
- delete the current zigbee2mqtt folder  (“/opt/zigbee2mqtt”)
- delete the whole plugin folder ("home/pi/domoticz/plugins/zigbee2mqtt")
- (re)installing the plugin as described on your Github page
- restart Domoticz
- stop Domoticz
- delete the current (new created?) zigbee2mqtt folder  (“/opt/zigbee2mqtt”)
- replace the early backup zigbee2mqtt folder
- restart Domoticz

Thanks again.

**Comment by Theo-NL** [comment]
Problem plugin updating error solved:

I deleted the files (at first I stopped Domoticz):
.github/ISSUE_TEMPLATE/new-device-feature-support.md
api/plugin.py
bridge.py
configuration.py
frontend/libs/ace_json_mode.js
frontend/libs/ace_worker_json.js
frontend/plugin_config.js

Then git pull and everything updated and new files were created.

Theo.
