### ISSUE TITLE
Dimmer EcoDim Eco-Dim.07 (brightness)

### ISSUE THREAD

**Issue by michaelblaas** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#777]
**Issue description**
This device seems to work fine except that it doesn't hold the brightness value in the dimmer switch within Domoticz. If set, the lamp responds as expected but the dimmervalue in Domoticz immediately is reset to 0 (whilst the lamp stays on). Hope this can be fixed.

**Additional information**
Zigbee2MQTT version: **v.1.22.2 (zStack3x0 20210708)**
Python version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Domoticz version: **2021.1 (build 14105)**
Plugin version: **v.3.1.0-beta**

**Logs**
Exposure from Z2M:
`{
    "brightness": 79,
    "linkquality": 57,
    "state": "ON"
}`

Logging from Z2M frontend upon switching on:
`Debug: Received MQTT message on 'zigbee2mqtt/Stekkerdimmer 01-Dressoir/set' with data '{"state": "ON", "brightness": 78}'
Debug: Publishing 'set' 'brightness' to 'Stekkerdimmer 01-Dressoir'
Debug: Received Zigbee message from 'Stekkerdimmer 01-Dressoir', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Info:  MQTT publish: topic 'zigbee2mqtt/Stekkerdimmer 01-Dressoir', payload '{"brightness":74,"linkquality":51,"state":"ON"}'
Info:  MQTT publish: topic 'zigbee2mqtt/Stekkerdimmer 01-Dressoir', payload '{"brightness":78,"linkquality":51,"state":"ON"}'
Debug: Received Zigbee message from 'Stekkerdimmer 01-Dressoir', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":78}' from endpoint 1 with groupID 0
Debug: Received Zigbee message from 'Stekkerdimmer 01-Dressoir', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":79}' from endpoint 1 with groupID 0
Info:  MQTT publish: topic 'zigbee2mqtt/Stekkerdimmer 01-Dressoir', payload '{"brightness":78,"linkquality":54,"state":"ON"}'
Info:  MQTT publish: topic 'zigbee2mqtt/Stekkerdimmer 01-Dressoir', payload '{"brightness":79,"linkquality":54,"state":"ON"}'
`

**Comment by odelma** [comment]
I think this is in essence same issue as in:  https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/714

**Comment by stas-demydiuk** [comment]
Closing as clone of #714
