### ISSUE TITLE
Problem upgrading Zigbee2MQTT

### ISSUE THREAD

**Issue by gert3d** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#778]
I used the legacy intallation of the gateway software of Zigbee2mqtt next to mosquitto and domoticz to end up with a finely working Zigbee network.
Raspian GNU/Linux 10 (buster) kernel version 5.10.17-u7+
ARMv7 Processor rev 5 (v71)
Zigbee2MQTT version 1.18.1 zStack30x20201010
cc2538 stick as gateway, more thann 20 devices paired.

Now I wanted to upgrade Zigbee to allow more recent devices to be recognised for pairing, using:
https://www.zigbee2mqtt.io/guide/installation/01_linux.html#optional-running-as-a-daemon-with-systemctl

The steps taken show no problems, however none of the devices in the network were still paired
Then I thought I needed to upgrade teh linux version, which I did:
sudo apt update
sudo apt dist-upgrade
sudo reboot

This also made the Zigbee network to fail.

What did I do wrong, or what should I do? Thanks

**Comment by odelma** [comment]
Hi, this git repository is for Domoticz plugin that uses zigbee2mqtt. You should refer the question to https://github.com/Koenkk/zigbee2mqtt/issues.

So, you went through with this:
```
# Stop Zigbee2MQTT and go to directory
sudo systemctl stop zigbee2mqtt
cd /opt/zigbee2mqtt

# Backup configuration
cp -R data data-backup

# Update
git checkout HEAD -- npm-shrinkwrap.json
git pull
npm ci

# Restore configuration
cp -R data-backup/* data
rm -rf data-backup

# Start Zigbee2MQTT
sudo systemctl start zigbee2mqtt
```

And it does not start anymore? Are you sure you restored the data folder from the backup correctly (cp -R data-backup/* data)? I experienced something similar once and only thing I was able to conclude is that something went wrong with backing up / restoring this folder. I needed to reinlcude every device...

**Comment by stas-demydiuk** [comment]
Closing the ticket as there is no response from the author
