### ISSUE TITLE
Crash after update, any step by step to solve it?

### ISSUE THREAD

**Issue by darrepac** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#779]
Hello

I have updated Domoticz to latest stable version 2022.1 and I did the same with z2mqtt plugin (git pull) and now my devices are not working and I have the following errors in the log:
`2022-02-02 22:49:01.195 Error: Zigbee2MQTT: Exception traceback:
2022-02-02 22:49:01.196 Error: Zigbee2MQTT: ----> Line 302 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand
2022-02-02 22:49:01.196 Error: Zigbee2MQTT: ----> Line 104 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onCommand`

I have seen here and there others with similar problem (seems link to moving from <3.0 version to >3.0 version) but did not find a simple step by step guide to solve it. Could someone post one?

**Comment by stas-demydiuk** [comment]
What plugin version are you using?

**Comment by darrepac** [comment]
I was using the latest from 3 branch (git pull) but now I go back to old branch in order to have everything back to work.
I think I should have updated the zigbee2mqtt as well (not only the plugin) and seems in any case everything has to be restarting from scratch when you updated to new 3 branch...
I think a step by step guide would be useful
