### ISSUE TITLE
Domoticz crash after installing the zigbee2mqtt plugin

### ISSUE THREAD

**Issue by dolf182** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#782]
I downloaded the latest domoticz plugin version 2022.1
Installed the latest mqtt
installed the latest mqtt2zigbee.
Connection to my zigbee receiver works fine.
Domoticz works fine.
After installing the plugin and restarting domoticz every is just fine.
When i add the zigbee device using this plugin domoticz won't start up again.
After removing the zigbee2mqtt plugin folder domoticz works again.
Tried the release of domoticz and the beta version nothing seems to help.

Has anybody else this issue?

Arjan

**Comment by stas-demydiuk** [comment]
Any issues in the log?

**Comment by dolf182** [comment]
I will collect log this evening an attached it.

**Comment by dolf182** [comment]
[domoticz.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/8008098/domoticz.txt)

**Comment by Berend95** [comment]
Same issue with crashing. Python 3.9 might caues it?

**Comment by stas-demydiuk** [comment]
Yes, most likely that's the issue as there were several messages that Domoticz doesn't work well with Python 3.9

**Comment by dolf182** [comment]
Tried serveral things after putting the log here. 

* Not using the installer but building domoticz on the raspberry pi. did not fix the issue.
End of 2021 there were some issues with the installer causing several issues.

Changed the system default python to 3.8 but domoticz is still using 3.9.
I have to look into this how to set the domoticz default python.

Apperenty the python version seems to cause issues when domoticz is loading plugins.

It seems to be not related to this plugin. Thank you for your fast response.

Arjan

**Comment by fiktouf** [comment]
Facing the same problem as dolf182.
Any suggestions?
Thks

**Comment by dolf182** [comment]
Got it working now...

The issue is raspberry pi bullseye

* First we have to make an image with buster lite or desktop it doesn't matter.
*  install the mosquitto mqtt broker: https://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi/
* install zigbee2mqtt: https://www.zigbee2mqtt.io/guide/installation/01_linux.html
* install python 3.7 buster comes with 2.7: https://installvirtual.com/install-python-3-7-on-raspberry-pi/
* install the libpython : sudo apt-get install python3.7 libpython3.7 python3.7-dev -y
*  install domoticz:  https://www.domoticz.com/wiki/Raspberry_Pi
*  restart the pi
* get the plugin from this website
* restart domoticz
* add device

as every went ok you have  working zigbee again on your pi.

Until the issues with bulleye aren't fix this should  be a solution

Kind Regards

Arjan

**Comment by fiktouf** [comment]
Hi Arjan,
Thank you for your feedbak 
I'll try your solution this evening. 
Thks

**Comment by dolf182** [comment]
Hello,

Just a short update

So i tried to install python 3.7 on bullseye. That works fine but domoticz is using the:

libpython and python dev for loading in the plugins.

the 3.7 versions are not availible anymore for bullseye.

If i install the 3.8 versions domoticz crashes on the plugins again the same with version 3.9.

The solution for now is to keep it on buster until they fix it in domoticz.

You get warnings during the npm and node.js install. Because of the versions supported by buster. So the zigbee is a little bit buggy.

Arjan

**Comment by fiktouf** [comment]
Hi Arjan,
thanks a lot for you feedback.
I've tried python 3.8 as well yesterday . same conclusion as yours...
So it Works fine on Buster
thank you again

**Comment by waltervl** [comment]
Python support on Bullsye could be fixed in latest beta with commit https://github.com/domoticz/domoticz/commit/8f01ed77d5831090f34ad59d22ef1f7cd4d740f2 But try out in a beta environment first as it is early beta changes.

Please report issues in https://www.domoticz.com/forum/viewtopic.php?f=6&t=38086

**Comment by dolf182** [comment]
Thank you. 

This fixed the issue for me on bullseye
