### ISSUE TITLE
message in the log

### ISSUE THREAD

**Issue by 2N3819** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#786]
After upgrading to Plugin version 3.1-beta I have messages relating to linkquality in the domoticz log for most if not all the zigbee devices.

For example:
 2022-02-06 15:00:36.513 Zigbee_IO: Alias for handling linkquality(endpoint: n/a) feature of device 0x00124b001e72899e already exists in plugin configuration but Domoticz logical device with ID 0x00124b001e72899e(unit: 1) is not found. If you have removed device and want plugin to recreate it, please remove alias from configuration as well.

Can I please ask for advice on how to remove the cause of the messages?

Zigbee2MQTT version: 1.23.0
Python version: 3.7.3
Domoticz version: 2022.1
Plugin version: 3.1-beta

**Comment by stas-demydiuk** [comment]
In order to fix the issue, you need to open the configuration tab in the plugin UI and manually remove record related to 0x00124b001e72899e link quality

**Comment by 2N3819** [comment]
Hi
Thank you responding. I do not see a configuration tab:
![plugin](https://user-images.githubusercontent.com/59396086/152693523-83533f5a-3ab8-4d03-8162-c40a8bf3bb89.png)
Is that where the configuration should be?

**Comment by stas-demydiuk** [comment]
Looks like the old UI has been cached by the browser, try to clear the browser cache and check again

**Comment by 2N3819** [comment]
Ah my fault. 
Deleting the browser cache allowed the configuration tab to be displayed.
I have now edited the alias after some trial and error :-)
