### ISSUE TITLE
Tuya TS011F_plug_3 on/off state in plugin not working after update zigbee2mqtt 1.24.0

### ISSUE THREAD

**Issue by jupstra** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#795]
**Issue description**
I've got some nice TS011F_plug_3 Tuya's, but after updating Z2M to v1.24.0 the on/off switch doesn't work anymore in Domoticz. It remains off / switches back immediately to off. In the Z2M Frontend the plugs are working properly. Updating the plugin to 3.1 beta is not an option, since in that one doesn't load in domoticz, see issue #780. Thanks!

**Additional information**
Zigbee2MQTT version: 1.24.0
Python version: 3.7.3
Domoticz version: 2022.1
Plugin version: 3.0

**Comment by SargonofAssyria** [comment]
Same for the NAS-WR01B which presents it self as a TS011F_plug_1 in Z2M 1.24.0-dev commit: [0cd02c74]
Also using the 'OLD' plugin version.

**Comment by SargonofAssyria** [comment]
I found a temporarily solution by removing some lines in Z2M see here: https://github.com/Koenkk/zigbee2mqtt/issues/11939

**Comment by SargonofAssyria** [comment]
Probably found the culprit. This device is a powerplug with a child_lock. 
@stas-demydiuk  How can I make a powerplug definition  with a child_lock?

**Comment by jupstra** [comment]
> I found a temporarily solution by removing some lines in Z2M see here: [Koenkk/zigbee2mqtt#11939](https://github.com/Koenkk/zigbee2mqtt/issues/11939)

Thanks @SargonofAssyria for puzzling on this. I removed the child_lock line (and also indicator_mode) under the plug_3 device in tuya.js (the one in devices folder). Unfortunately the issue remains... Maybe you could be somewhat more precise in what you actually removed? Many thanks!

**Comment by SargonofAssyria** [comment]
You only have to remove the child_line part on the following places.
the 'fromZigbee', 'toZigbee' and the exposes part.

**Comment by awalsum** [comment]
> You only have to remove the child_lock part on the following places. the 'fromZigbee', 'toZigbee' and the exposes part.

Unfortunately, this didn't work for me.

**Comment by SargonofAssyria** [comment]
The other solution is for me to add attached external converter in Z2M under Settings -> External converters.
Remove the .txt so the filename is TS001_TZ3000.js
[TS011F_TZ3000.js.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/8967589/TS011F_TZ3000.js.txt)
.

**Comment by awalsum** [comment]
> The other solution is for me to add attached external converter in Z2M under Settings -> External converters. Remove the .txt so the filename is TS001_TZ3000.js Place the file in the data dir. [TS011F_TZ3000.js.txt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/8967589/TS011F_TZ3000.js.txt) .

I haven't tried this yet and missed this comment. I will try it out soon. Thanks.

**Comment by awalsum** [comment]
This works for me. Thanks!
