### ISSUE TITLE
Aqara WSDCGQ11LM sensor missing function after git pull

### ISSUE THREAD

**Issue by McGyver64** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#796]
I did an update update to find missing feature for a ZigbeeRGBW light. After the update all my Aqara WSDCGQ11LM stopped temperature and humidity measurement, causing some domoticz functions to stop (temerature dependent switching)
After I did a re-pair of the device, it was found, but the specific temperature/humidity reading is not present anymore. I have to use an other setting to get it working again. Also I noticed there are 2 functions/readings missing and also battery and voltage % is not been read anymore. How can I get the Aqara WSDCGQ11LM to be correctly be read in domoticz?

I went back to a SD image of 1 month ago and saw that that version did not have the plugin v.3.1.0-beta, so I did a downgrade with 
cd domoticz/plugins/zigbee2mqtt
git reset --hard f8c22fc330229b39f06ff11bbfcea38e3a492306

And the Aqara functions are back. 

I thought I was an Zigbee2MQTT item, so I posted there also 
https://github.com/Koenkk/zigbee2mqtt/issues/11834

**Additional information**
plugin: v.3.1.0-beta, zigbee2mqtt: v.1.22.2 (zStack3x0 20211217)

Version: 2022.1
Build Hash: c9526851b
Compile Date: 2022-01-31 09:34:32
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Below is the "old" function. As you can see the temp/hum (idx 794) is not been updated since 2022-03-11, while the temp and humidity is read ok. (idx 1193) Also battery an voltage are stil updated, but this is lost after a re-pair , wich gives different/less setting

<img width="1208" alt="Schermafbeelding 2022-03-13 om 15 13 18" src="https://user-images.githubusercontent.com/69874589/158067030-d97d8b4f-77de-4380-91d7-d8254941c397.png">

I did a re-pair for 1 temperature sensor and got different settings back. the combined function temp/hum was not available anymore (but after the downgrade, they were back again for the "not re-paired items and the re-paired item is extended) 

<img width="1202" alt="Schermafbeelding 2022-03-13 om 16 33 07" src="https://user-images.githubusercontent.com/69874589/158067196-a84f74a0-8888-454c-83e5-80033046d479.png">

**Comment by klarf-pixel** [comment]
Hi,
Same thing here. I returned on the 3.0.0 version.

**Comment by sammyke007** [comment]
After upgrading from v3.0 to v3.1 it's best to completely remove the Z2M plugin from the Domoticz Hardware page and add it again. CAUTION: this removes all of your Z2M devices/IDXs and recreates them with a new IDX. It was a hell of a job as I had timers, script, ... to edit, but it worked.

**Comment by saper-2** [comment]
I have 2pcs 11LM, I had to completely remove them from Devices and in Custom->Z2M->Plugin Config you have to remove entries for them too (aliases?)

**Comment by klarf-pixel** [comment]
Hi, i test to update the plugin but I have already the same problem with the WSDCGQ11LM device.
No news about to fixing the problem ?

**Comment by stas-demydiuk** [comment]
It doesn't seem like a plugin problem, more likely something wrong with the configuration, have you tried the clean install (remove the plugin hardware from domoticz and then add it again after plugin update)?

**Comment by klarf-pixel** [comment]
Hi,
I have too many device in the plugin, I can't start a clean install without lost the log of too many device.
It's not possible to change the configuration of the device manually ?

**Comment by stas-demydiuk** [comment]
Yes, it is definitely possible. You could use the Configuration tab in the plugin UI, but you must first figure out what's wrong with the existing configuration. I'd assume that some aliases are incorrect and point to non-existing Domoticz devices

**Comment by klarf-pixel** [comment]
It's the configuration with this device :

`		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_temp",
				"legacy_alias": "temp",
				"unit": 21
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "temperature"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_hum",
				"legacy_alias": "hum",
				"unit": 22
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "humidity"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_pres",
				"legacy_alias": "pres",
				"unit": 23
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "pressure"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_all",
				"legacy_alias": "all",
				"unit": 117
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "temp+hum"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98",
				"legacy_alias": "thb",
				"unit": 1
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "temp+hum+bar"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_btperc",
				"legacy_alias": "btperc",
				"unit": 26
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "battery"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_cell",
				"legacy_alias": "cell",
				"unit": 25
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "voltage"
			}
		},
		{
			"domoticz": {
				"device_id": "0x00158d0004658c98_signal",
				"legacy_alias": "signal",
				"unit": 28
			},
			"zigbee": {
				"address": "0x00158d0004658c98",
				"endpoint": "n/a",
				"feature": "linkquality"
			}
		},`

I don't see where are a problem in the configuration ?
Thank you for your help !

**Comment by stas-demydiuk** [comment]
And what is the Domoticz device you have issues with?

**Comment by klarf-pixel** [comment]
Here it's the 3.1.0 plugin :
![3 1 0](https://user-images.githubusercontent.com/91114794/178925390-453c66f8-97ae-4e11-a8f7-657602f5dcba.jpg)
And the 3.0.0 plugin :
![3 0 0](https://user-images.githubusercontent.com/91114794/178925413-04511376-c24e-4ed9-93c9-15719d9666d5.jpg)

Thanks !

**Comment by sammyke007** [comment]
What I did was add the 3.1 plugin as new hardware (and keep the 3.0 plugin). It created all new devices with new IDXes. I then replaced the old IDXes with the new IDXes. This transfers the history/log to the new IDX.
