### ISSUE TITLE
SNBZ-02 device definition not found

### ISSUE THREAD

**Issue by elpaul** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#799]
Good day.
I bought two SNBZ-02 sensors, when I try to pair I get the information in logs: **device definition not found, skipping...**
Where is the problem? In the Home Assistant works as normal.

![image](https://user-images.githubusercontent.com/9497662/159895189-32bd5076-a553-4daa-825c-b72165f76288.png)

![image](https://user-images.githubusercontent.com/9497662/159894917-19725de4-9593-4ef5-8e23-917eb875302e.png)

**Additional information**
Zigbee2MQTT version: 1.24.0
Python version: 3.7.3
Domoticz version: 2022.1 (build 14294)
Plugin version: 3.1.0-beta

**Comment by JanJaapKo** [comment]
hi @elpaul , thios device seems not to be supported by zigbee2mqtt ([supported devices](https://www.zigbee2mqtt.io/supported-devices/)), so you'll need to follow the steps described there to get it supported. The Domoticz plugin simply takes the output of zigbee2mqtt to configure itself.

**Comment by elpaul** [comment]
The problem was solved after manually removing the sensors in "plugin configuration" and re-pairing.
