### ISSUE TITLE
device-availability feature support

### ISSUE THREAD

**Issue by jpveen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#802]
First of all Stanislav, how are you doing during this awful war? Are you healthy with you and your family?

**Feature request description**
Enables the view of offline zigbee devices in domoticz.

Koekk added a device-availability optional feature a while ago. If activated zigbee2mqtt checks if devices are available. When a device is not online a payload offline will be published to /device-xxx/availability.  

Example:
State "Offline" of the device, instead of the last-known state.

**Feature definition**
Set domoticz state to Offline when a availability payload offline is received and set state back to the state back to the current state when a availability online payload is received.

zigbee2mqtt log:
```
info  2022-05-02 11:04:02: MQTT publish: topic 'zigbee2mqtt/Hue-4/availability', payload 'offline'
info  2022-05-02 11:25:26: MQTT publish: topic 'zigbee2mqtt/Hue-4/availability', payload 'online'

```

**Comment by stas-demydiuk** [comment]
@jpveen do you have any examples of such "Offline" state in other Domoticz plugins/devices, I'm not sure that Domoticz really supports that

**Comment by jpveen** [comment]
Hi, from what I have found domoticz has around 20 device statusses, but not a specific Offline status. But you could probable use the STOP nvalue 19 for that. 
So it would be very helpfulm if the z2m plugin could send a nvalue=19 to domoticz when a availability payload offline is received for a device. No need to handle the 'online' payload, as when a device gets online the plugin already triggers a state change.
Thx!
