### ISSUE TITLE
Plugin unsupported bulb aqara ZNLDP12LM ?

### ISSUE THREAD

**Issue by NE8XT** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#81]
- Zigbee2MQTT version: 1.1.1
- Python version: 3.5.3
- Domoticz beta version: 4.10447
- Plugin version: 0.0.17

===========
**Zigbee2mqtt: Ok!**

![123](https://user-images.githubusercontent.com/6293406/53287239-ad535180-3779-11e9-8e96-42c06ad5686c.jpg)

**Domoticz: A new device 0x00158d0002b61873 is not added**.

![1234](https://user-images.githubusercontent.com/6293406/53287246-c3f9a880-3779-11e9-916a-4ac05f73ea48.jpg)

**Comment by stas-demydiuk** [comment]
Plugin has support for this device. I could recommend to restart plugin, it should force to create new devices.

**Comment by NE8XT** [comment]
restarted, upgraded, reinstalled the plug-in, new devices not added!

**Comment by NE8XT** [comment]
it Work
