### ISSUE TITLE
Domoticz die after add new hardware

### ISSUE THREAD

**Issue by Mr-Victor16** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#813]
Domoticz die (status active (exited) ) after add a new Zigbee2MQTT hardware.

**Comment by stas-demydiuk** [comment]
Could you please provide more details about your setup?

**Comment by stas-demydiuk** [comment]
Then the issue is definitely in Domoticz itself, try to raise the ticket in Domoticz repo, maybe someone will be able to help
