### ISSUE TITLE
PF-PM02D-TYZ

### ISSUE THREAD

**Issue by ediplug** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#814]
Hello,
i need Support to integrate the PF-PM02D-TYZ Valve into Domoticz. Can Sombody help me?
The State can i see and i can control it manual by using the commands in zigbee2mqtt.
I want to create a Switch.
Greetings, Sepp

**Comment by stas-demydiuk** [comment]
What's the current issue with Domoticz? my assumption is that at least some features should work out of the box with the latest plugin
