### ISSUE TITLE
Sonoff SNZB-01 button isn't a switch

### ISSUE THREAD

**Issue by marillat** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#815]
Zigbee2MQTT version: 1.27.0
`Python` version: 3.9.13
Domoticz version: 2022.1 build 14360
Plugin version: 3.1.0-beta

As I'm saying this device is a button and not a switch.
The state should  return to off after be pressed, otherwise it's manageable as the button always return the latest status.

**Comment by mmikee02** [comment]
Hello, 
it's normal, button stay in last state when pushed .
To compensate it, in your favorite domotic program (mine is domoticz) just create a blocly or a script which re-put the button to the "off " state when pushed,  after, per example 1 second.

**Comment by marillat** [comment]
I'm also working with domoticz. I don't know why my previous script was not working,
but today a new blockly script do what I want. The previous script also included a set to off state.
