### ISSUE TITLE
Running  v.3.2.0-beta, should I "upgrade" to 3.1.0?

### ISSUE THREAD

**Issue by TheLion** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#821]
Hi,

I'm running the plugin v.3.2.0-beta, no idea how this came to be ;-)

Should I "upgrade"  to the latest 3.1.0 release? And if yes, how?

Or should I wait for the regular 3.2.0 update?

A regular "git pull" broke everything, which makes sense.

**Comment by platte-73** [comment]
I did also update from 3.0 stable and now I'm on 3.2 beta. I'm not getting the 3.1 version. Zigbee sensors not working on the 3.2 beta

**Comment by diazovitch** [comment]
How to install a specific version like 3.0 for example? Because if I do a git pull, automatically the 3.2.0-betta is installed.
Thank you

**Comment by stas-demydiuk** [comment]
3.2.0-beta and 3.1.0 are the same at the moment

You could download the particular plugin version on [releases](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/releases) page
