### ISSUE TITLE
Ikea "E1603/E1702/E1708" not supported (anymore) message 

### ISSUE THREAD

**Issue by geeano** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#822]
Log message:  This plugin does not support zigbee device with model "E1603/E1702/E1708" yet.
(although it has been running for a couple of years)

> running a separate domoticz application on a linux machine connected to the MQQT server running at the PI does support this device.

At my Raspberry that runs zigbee2mqtt and domoticz based on domoticz version 2022.1 and 
zigbee2mqtt plugin upgraded to  Plugin (v. 3.1.0-beta) this problem remains.

I upgraded the plugin with the latest version. Deleted the "plugin hardware" and created new Zigbee2MQTT "hardware" did not resolved the issue.

---------------------------------
Version: 2022.1
Build Hash: c9526851b
Compile Date: 2022-01-31 09:34:32
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by stas-demydiuk** [comment]
`This plugin does not support zigbee device with model "XYZ" yet` there is no such message in the plugin code anymore, probably the upgrade did go wrong, try to completely remove the plugin folder and fetch the latest plugin version

**Comment by geeano** [comment]
Thank you for the response. Do I have to follow the install or the upgrade procedure ?

**Comment by stas-demydiuk** [comment]
Just fully delete the `domoticz/plugins/zigbee2mqtt` directory and then follow `install` steps

**Comment by geeano** [comment]
The issue occured even with the new version: Zigbee2MQTT Plugin (v. 3.2.0-beta) indicated in the UI.
But anyhow, after several attemps issue resolved.

Thanks for advice

**Comment by geeano** [comment]
Issue can be closed
