### ISSUE TITLE
Where is configuration?

### ISSUE THREAD

**Issue by majki09** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#827]
Hi.

I accidentally deleted pressure unit for my Aqara sensor from domoticz. Now I'm getting this in domoticz log:
`2022-10-13 07:49:27.462 Zigbee2MQTT: Alias for handling pressure(endpoint: n/a) feature of device 0x00158d0001d7298a already exists in plugin configuration but Domoticz logical device with ID 0x00158d0001d7298a(unit: 2) is not found. If you have removed device and want plugin to recreate it, please remove alias from configuration as well.`

In the plugin's readme there is:
`in case if you manually remove the device or want a custom association please make sure that you've updated the configuration accordingly`

I've been looking for "Configuration" in domoticz, plugin frontend, file system... I did not found any json configuration.
What I need to do to have my sensors back in domoticz without loosing historical data?

**Comment by stas-demydiuk** [comment]
It's in plugin UI, the tab called Plugin Configuratuion

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2734836/195593923-dc31bca6-95e5-4dd4-839e-5214eda6f4c2.png">

**Comment by majki09** [comment]
Sorry, but I have completely different UI:

![zigbee2mqtt](https://user-images.githubusercontent.com/14251340/195595444-4d1c465f-3772-4cff-83b8-ac80caa9a2e1.jpg)

**Comment by stas-demydiuk** [comment]
It is the zigbee2mqtt UI, the plugin UI lives in Domoticz under Custom tab

<img width="216" alt="image" src="https://user-images.githubusercontent.com/2734836/195694814-682bb9f0-3ac1-4ae2-bfd8-e8c6885ad645.png">

**Comment by majki09** [comment]
Finally found this.
In Domoticz you can enable "Custom" menu - I did not know that. Maybe it's just only me, but anyway it was not straight forward to know from reading your repo readme. You mentioned about plugin UI. There is also plugin zigbee2mqtt and it has also it's own UI (a.k.a. frontend). So this is also a plugin and it also has UI, so you can call it "plugin UI". Right?
Anyway...
Lost so many time to find this, but finally I have your UI.
However, it's displaying "Loading..." all the time. Yes, I need to add api_transport by clicking the arrow... (really dirty way to handle data). No "Loading..." message anymore, hooray!
Last tab, "Plugin configuration", lot of json... Finally there... I've edit what I wanted and clicked Save. Simple.

And boom:
![zigbee2mqtt_failed](https://user-images.githubusercontent.com/14251340/195778368-aa1df477-d444-4193-ab85-550e14a1fa0e.jpg)

I have no more patience for this.

At the end I have resolved my issue by editting a domoticz database and manually restoring removed device.
Bang, it works like before.
And it took 5 minutes.
