### ISSUE TITLE
Domoticz 14567: Blinds commands changed

### ISSUE THREAD

**Issue by HenriMatthijssen** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#828]
With latest betas of Domoticz the Blinds behavior has been changed.:

Before the percentage info is translated to the following commands:

% Command
0: Off
1: Set Level
99: Set Level
100: On

In the 'current' new situation the translation is as follows:

% Command
0: Close
1: Set Level
99: Set Level
100: Open

This will now result in next message when 'Open' or 'Close' action is given:

`okt 14 11:34:24 domoticz npm[2337]: Zigbee2MQTT:error 2022-10-14 11:34:24: Invalid message 'null', skipping...`

Solution is to adapt next source-file of plugin:

zigbee2mqtt\devices\switch\blind_percentage_switch.py

Change 'cmd == 'ON' into 'cmd == 'CLOSE'
Change 'cmd == 'OFF' into 'cmd == 'OPEN'

Zigbee2MQTT version: v1.27.2
Python version: 3.7.3
Domoticz version: 14567
Plugin version: V3.2.0-beta

**Comment by odelma** [comment]
Maybe you could create a pull request for this fix, I’m sure @stas-demydiuk is happy to merge it ☺️

**Comment by HenriMatthijssen** [comment]
Probably solution should be made more generic by checking Domoticz Version to which value 'cmd' should check. I believe that since 14549 the blind commands changed.

**Comment by sundodger** [comment]
Do you think this also affects the Tradfri up/down switch that comes with the blinds?
Mine has stopped working. 
I had used it to switch on or off a group controlling multiple blinds with one button. 
Thanks for information above also. Fixed my problem controlling the blinds via Domoticz

**Comment by platte-73** [comment]
> With latest betas of Domoticz the Blinds behavior has been changed.:
> 
> Before the percentage info is translated to the following commands:
> 
> % Command 0: Off 1: Set Level 99: Set Level 100: On
> 
> In the 'current' new situation the translation is as follows:
> 
> % Command 0: Close 1: Set Level 99: Set Level 100: Open
> 
> This will now result in next message when 'Open' or 'Close' action is given:
> 
> `okt 14 11:34:24 domoticz npm[2337]: Zigbee2MQTT:error 2022-10-14 11:34:24: Invalid message 'null', skipping...`
> 
> Solution is to adapt next source-file of plugin:
> 
> zigbee2mqtt\devices\switch\blind_percentage_switch.py
> 
> Change 'cmd == 'ON' into 'cmd == 'CLOSE' Change 'cmd == 'OFF' into 'cmd == 'OPEN'
> 
> Zigbee2MQTT version: v1.27.2 Python version: 3.7.3 Domoticz version: 14567 Plugin version: V3.2.0-beta

This was also the solution for me.
Only thing is the slider dont show the percentage anymore. If it's half way its showing open or close

**Comment by luismalddonado** [comment]
> With latest betas of Domoticz the Blinds behavior has been changed.:
> 
> Before the percentage info is translated to the following commands:
> 
> % Command 0: Off 1: Set Level 99: Set Level 100: On
> 
> In the 'current' new situation the translation is as follows:
> 
> % Command 0: Close 1: Set Level 99: Set Level 100: Open
> 
> This will now result in next message when 'Open' or 'Close' action is given:
> 
> `okt 14 11:34:24 domoticz npm[2337]: Zigbee2MQTT:error 2022-10-14 11:34:24: Invalid message 'null', skipping...`
> 
> Solution is to adapt next source-file of plugin:
> 
> zigbee2mqtt\devices\switch\blind_percentage_switch.py
> 
> Change 'cmd == 'ON' into 'cmd == 'CLOSE' Change 'cmd == 'OFF' into 'cmd == 'OPEN'
> 
> Zigbee2MQTT version: v1.27.2 Python version: 3.7.3 Domoticz version: 14567 Plugin version: V3.2.0-beta

Same probelm for me. Happening since Domoticz Version 2022.2 (November 5 2022).
