### ISSUE TITLE
Just wondering E1524 tradfi? Is it supported?

### ISSUE THREAD

**Issue by HJKLMN** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#83]
I see my E1524 in the log file coming up. But not in my devices:

2019-03-03 13:16:54.997 (Zigbee2mqttC2530) Device E1524 0xd0cf5efffe08e43f (KAMER_DIMMER)

In the supported devices,  it says the Ikea Wireless Dimmers is supported.

What am I doing wrong?

**Comment by stas-demydiuk** [comment]
@HJKLMN please note that plugin adds devices in Domoticz and set them to non used, so they should appear under the setup->devices tab, just not in the 'switches' tab.

**Comment by stas-demydiuk** [comment]
@HJKLMN Currently this device is not supported, please create "Support new device" issue if you'd like to have support for it
