### ISSUE TITLE
No message in dialog box of domoticz

### ISSUE THREAD

**Issue by secator76** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#830]
**Issue description**
Hi,
when I pair a sensor, it works very well but I no longer have a message in the dialog box in domoticz

**Additional information**
Zigbee2MQTT version: 1.27.2
Python version:3.8.10
Domoticz version:2022.1
Plugin version:V3.2.0-beta

![image](https://user-images.githubusercontent.com/75223289/197400676-8cd5aab7-9de2-41bd-8f0d-24cbbb0c88bd.png)

**Comment by sMartjeB** [comment]
I have the same issue.
Python 3.9.2
Zigbee2MQTT version: 1.28.4
Plugin version:V3.2.0-beta
Domoticz version:2022.2

Could it be some page refreshing problem? (F5)
