### ISSUE TITLE
JY-GZ-03AQ new device domoticz (aqara smoke sensor)

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#833]
Hi dear @stas-demydiuk ,

Can you add this new aqara smoke sensor in the plugin for domoticz?

Thanks in advanced.

https://www.zigbee2mqtt.io/devices/TS0121_plug.html](https://www.zigbee2mqtt.io/devices/JY-GZ-01AQ.html

**Comment by kitopopo** [comment]
We have news about this sensor?

Best regards and thanks in advanced

**Comment by stas-demydiuk** [comment]
I assume most of the features should work out of the box, what exactly doesn't work with this device?

**Comment by kitopopo** [comment]
Thanks for your answer dear friend, I don't have the sensor yet, it will be my next purchase. I thought you had to add it to the list of devices first for it to work correctly because I haven't seen it in the list of supported devices. When I receive it, I'll test it and report everything that doesn't work. Thanks a lot. Best regards
