### ISSUE TITLE
Last seen not appear in Domoticz

### ISSUE THREAD

**Issue by bricololo44** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#837]
Hello,
I am on the beta version 3.2.O. (Domoticz in 2022.2)
I activated the Last seen in zigbee2mqtt, I can see the time in zigbee2mqtt but nothing appears in Domoticz.
Is there a solution ?
Thanks

Zigbee2MQTT version: 1.25.1
Python version:  3.7.3
Domoticz version: 2022.2
Plugin version: 3.2.O

**Comment by AdamWeglarz** [comment]
that would be great. Right now in zigbee2mqtt we see the status online/offline. We could trigger some alerts about offline devices in domoticz. Maybe you could think about additional switch per device on/off showing status of device.
