### ISSUE TITLE
zigbee2mqtt domoticz plugin loses connection to zigbee2mqtt

### ISSUE THREAD

**Issue by sander816** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#85]
**Issue description**
I have 6 xiaomi devices connected to a rpi3 with cc2531 stick.
After some time using it, is loses the connection to the devices.
In zigbee2mqtt everything still works fine. Devices in domoticz do not update anymore
Disable and enable the plugin, and its back working

**Additional information**
Zigbee2MQTT version: zigbee2mqtt@1.1.1
Python version: Python 2.7.13
Domoticz version: 4.10427
Plugin version: 0.0.11

**Log

**Comment by stas-demydiuk** [comment]
@sander816 could you please explain what do you mean by "loses the connection to the devices"?

**Comment by sander816** [comment]
i mean that, in [zigbee2mqtt ](https://www.zigbee2mqtt.io/)from koenkk everything works fine in commandline, but the Zigbee2MQTT domoticz plugin from this page doesnt update the sensors anymore.
Restarting koenkk zigbee2mqtt solves it

Although i upgraded the zigbee2mqtt plugin 3 days ago, till now no problem

**Comment by stas-demydiuk** [comment]
@sander816 maybe it is somehow related to #84. Did you restart your MQTT server when you have an issue?

**Comment by stas-demydiuk** [comment]
@sander816 please reopen the issue if it still occurs with latest plugin version
