### ISSUE TITLE
domoticz changed in docker

### ISSUE THREAD

**Issue by secator76** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#856]
**Issue description**
the latest versions of domoticz under docker use bullseye and the python version 3.9.2. Since the "Custom" tab no longer appears in domoticz.I emptied the cache of course and I tried google chrome in private browsing but it's the same. the gateway is online in domoticz log.
(FYI: Domoticz Plugins Manager no longer works in the new domoticz docker image)

see here: https://github.com/domoticz/domoticz-docker/pull/18

**Additional information**
Zigbee2MQTT version: 1.30.1
Python version: 3.9.2
Domoticz version:2022.2.15055
Plugin version:3.2.0-beta

**Comment by odelma** [comment]
After one of the quite recent updates I needed to enable Custom tab again in settings. Also, make sure you have the api_transport in used devices.

**Comment by secator76** [comment]
ok. In settings, all tab are disable but i still see the tabs: Switches,Scenes,Temperature,Weather and Utility . if i enable all tab and i apply when i return in settings all tab are always disable and Custom tab don't appear. The api_transport is used in devices. It's a domoticz problem.

**Comment by secator76** [comment]
I solved the problem in the configuration/users tab and I checked custom
