### ISSUE TITLE
Impossible to see frontend on domoticz dashboard

### ISSUE THREAD

**Issue by diazovitch** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#869]
**Issue description**
Hi,
I install a new domoticz v2023.2 on a new rpi 3b+ with bullseye without desktop.
I install mosquito and zigbee2mqtt.
When i start npm i don't have any error. Everything are green.
I installed plugin. I can see on Hardware and I add to system.
I added api_transport device.
But i can't see the custom page of the plugin.

Zigbee2MQTT:info  2023-11-08 23:55:07: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-11-08.23-55-07' filename: log.txt
Zigbee2MQTT:info  2023-11-08 23:55:07: Starting Zigbee2MQTT version 1.33.2 (commit #ccc08a3)
Zigbee2MQTT:info  2023-11-08 23:55:07: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:info  2023-11-08 23:55:08: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-11-08 23:55:08: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20211115,"transportrev":2},"type":"zStack12"}'
Zigbee2MQTT:info  2023-11-08 23:55:08: Currently 0 devices are joined:
Zigbee2MQTT:info  2023-11-08 23:55:08: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-11-08 23:55:09: Connecting to MQTT server at mqtt://localhost:1883
Zigbee2MQTT:info  2023-11-08 23:55:09: Connected to MQTT server
**Zigbee2MQTT:info  2023-11-08 23:55:09: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2023-11-08 23:55:09: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2023-11-08 23:55:09: Zigbee2MQTT started!
Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)**

**Additional information**
Zigbee2MQTT version: 1.33.2
Python version: 3.9.2
Domoticz version: 2023.2
Plugin version: 3.2.0 (beta)

**Logs**
info  2023-11-08 23:38:34: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-11-08.23-38-34' filename: log.txt
info  2023-11-08 23:38:34: Starting Zigbee2MQTT version 1.33.2 (commit #ccc08a3)
info  2023-11-08 23:38:34: Starting zigbee-herdsman (0.21.0)
info  2023-11-08 23:38:36: zigbee-herdsman started (resumed)
info  2023-11-08 23:38:36: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20211115,"transportrev":2},"type":"zStack12"}'
info  2023-11-08 23:38:36: Currently 0 devices are joined:
info  2023-11-08 23:38:36: Zigbee: disabling joining new devices.
info  2023-11-08 23:38:36: Connecting to MQTT server at mqtt://localhost
info  2023-11-08 23:38:37: Connected to MQTT server
info  2023-11-08 23:38:37: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
info  2023-11-08 23:38:37: Started frontend on port 0.0.0.0:8080

**Comment by stas-demydiuk** [comment]
Please make sure that you enabled the "Custom" menu for your user in Domoticz (`Setup -> Users`)

<img width="369" alt="image" src="https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/assets/2734836/d37855b1-f36b-4c3a-ac08-f582da8af49b">

**Comment by diazovitch** [comment]
Sorry. I forgot the place where i can find it. It works. Thank you.
