### ISSUE TITLE
 Error: zigbee hardware (3) thread seems to have ended unexpectedly

### ISSUE THREAD

**Issue by aep** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#89]
**Issue description**
plugin doesnt add any devices, just crashes in a loop.
this is a fresh installation.
after restarting domoticz, it will no longer come up. just gets stuck in crash looping.

**Additional information**
Zigbee2MQTT version:
1.2.1

Python version:
Python 2.7.15

Domoticz version:
2019-03-11 18:41:42.864  Status: Domoticz V4.10531 (c)2012-2019 GizMoCuz
2019-03-11 18:41:42.864  Status: Build Hash: bf19d8bbb, Date: 2019-02-27 08:04:05

Plugin version:
'a9ba2405d5249ed8130230b9c9e9297ed8931519'

**Logs**

```
Mar 11 18:39:07 alarm domoticz[758]: 2019-03-11 18:39:07.753  Error: zigbee hardware (3) thread seems to have ended unexpectedly
Mar 11 18:39:21 alarm domoticz[758]: 2019-03-11 18:39:21.756  Error: zigbee hardware (3) thread seems to have ended unexpectedly
Mar 11 18:39:35 alarm domoticz[758]: 2019-03-11 18:39:35.759  Error: zigbee hardware (3) thread seems to have ended unexpectedly
```

eventually ...

```
Mar 11 18:40:59 alarm domoticz[758]: 2019-03-11 18:40:59.806  Error: WebServer:8080 thread seems to have ended unexpectedly (last update 71.000000 seconds ago)
```

**Comment by stas-demydiuk** [comment]
Did that happen with previous version or it is the first version you are using?

**Comment by aep** [comment]
That's the first time I'm using domoticz, but I suspect it might be related
to using the beta version?

**Comment by stas-demydiuk** [comment]
Oh I see, you've mentioned Python 2.7, but plugin only supports Python 3.5+

**Comment by aep** [comment]
Ah! but domoticz only starts with /bin/python linked to python2 :/

I'll toy around with giving each their own python version.

**Comment by stas-demydiuk** [comment]
@aep please reopen the issue if it still valid
