### ISSUE TITLE
Support for IKEA TRADFRI bulb E27 CWS opal 600lm

### ISSUE THREAD

**Issue by mkan1512** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#9]
**MQTT message:** 
zigbee2mqtt/0x90fd9ffffeea833d {'state': 'ON', 'device': {'type': 'Router', 'modelId': 'TRADFRI bulb E27 CWS opal 600lm', 'friendlyName': '0x90fd9ffffeea833d', 'manufId': 4476, 'ieeeAddr': '0x90fd9ffffeea833d', 'nwkAddr': 47867, 'manufName': 'IKEA of Sweden', 'powerSource': 'Mains (single phase)', 'status': 'online'}}

zigbee2mqtt/<DEVICE_ID>/set

```
{
  "state": "ON",   "brightness": 255,   "transition": 3,
  "color": {     // XY color     "x": 0.123,     "y": 0.123,
    // OR 
    // RGB color     "r": 46,     "g": 102,     "b": 193   }
}
```
_transition specifies the number of seconds the transition to this state takes (0 by default)._

When I tested this using mqtt-spy, I have to send for each attribute an single message?

**Comment by stas-demydiuk** [comment]
@mkan1512 should be added in v. 0.0.12, could you please check?

**Comment by mkan1512** [comment]
@stas-demydiuk Very nice !
This is working (almost) perfect. The lamp is reacting on all commands (on/off, color, brightness)

The only strange behavior is in Domoticz. There the state of the switch is changing to off (0%) after a few seconds.
 This is only visible when you change pages in domoticz (from switches to Dashboard for example) ?
