### ISSUE TITLE
Support for IKEA TRADFRI LED1732G11

### ISSUE THREAD

**Issue by jvbussel** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#90]
In ./node_modules/zigbee-shepherd-converters/devices.js I found the follow information about this device as it is already supported  by Koenkk/zigbee2mqtt:

    {
        zigbeeModel: ['TRADFRI bulb E27 WS opal 1000lm'],
        model: 'LED1732G11',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white',
        extend: generic.light_onoff_brightness_colortemp,
    },

**Device description**
TRADFRI bulb E27 WS opal 1000lm

**MQTT message with device information**
PUT here the device data you receive when publish message with topic
`zigbee2mqtt/bridge/config/devices`, as example
```
{"ieeeAddr":"0xd0cf5efffef2b3dc","type":"Router","model":"LED1732G11","friendly_name":"0xd0cf5efffef2b3dc"}
```

**MQTT messages from device**
Put here examples of MQTT messages with different states you've received from device, as example
```
MQTT message: zigbee2mqtt/0xd0cf5efffef2b3dc {'brightness': 254, 'color_mode': 2, 'state': 'ON', 'color_temp': 370, 'linkquality': 157, 'color': {'x': 0.46, 'y': 0.411}}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Should be available with version from latest master branch

**Comment by jvbussel** [comment]
That’s funny. I just installed the latest version last Sunday for both your plugin and for Koenkk/zigbee2mqtt with the result of having an unsupported device.

**Comment by stas-demydiuk** [comment]
I've just added the support less than hour ago

**Comment by jvbussel** [comment]
Ok, miss understanding. Thanks for your swift action. I will immediately update the plugin.

**Comment by jvbussel** [comment]
I confirm seeing new devices (expected however to see only one). Tha nks for your support and patience.

![newDevices](https://user-images.githubusercontent.com/12373643/54309420-62866600-45d0-11e9-8846-bb3b7e475fd9.png)
