### ISSUE TITLE
WXKG02LM - Xiaomi Aqara double key wireless wall switch

### ISSUE THREAD

**Issue by Mayki07** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#91]
**Issue description**
In the log I see that it recognizes all the switch states. In Domoticz, however, the switch created has only four states:
<a href="https://imgur.com/XcuM4T7"><img src="https://i.imgur.com/XcuM4T7m.jpg" title="source: imgur.com" /></a>

**Additional information**
Zigbee2MQTT version: 1.2.1
Python version: 3.5
Domoticz version: V4.10545  Rpi 3B+
Plugin version: "0.0.18"

**Logs**
`3/13/2019, 11:40:09 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":131,"click":"left"}'
3/13/2019, 11:40:12 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":134,"click":"left_double"}'
3/13/2019, 11:40:15 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":131,"click":"left_long"}'
3/13/2019, 11:40:19 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":131,"click":"right"}'
3/13/2019, 11:40:21 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":131,"click":"right_double"}'
3/13/2019, 11:40:23 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":126,"click":"right_long"}'
3/13/2019, 11:40:27 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":134,"click":"both"}'
3/13/2019, 11:40:29 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":134,"click":"both_double"}'
3/13/2019, 11:40:32 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002b48bed', payload '{"battery":100,"voltage":3055,"linkquality":128,"click":"both_long"}'`

**Comment by Mayki07** [comment]
Will he do anything about it?

**Comment by StevenBoelhouwer** [comment]
Working fine with your changes as long as you don't use tabs but spaces.

Steps:
Remove the devices created by WXKG02LM.py
Stop Domoticz
Update the WXKG02LM.py file with:

```
from adapters.adapter_with_battery import AdapterWithBattery
from devices.switch.selector_switch import SelectorSwitch


class WXKG02LM(AdapterWithBattery):
    def __init__(self, devices):
        super().__init__(devices)

        self.switch = SelectorSwitch(devices, 'switch', 'click')
        self.switch.add_level('Off', None)
        self.switch.add_level('Switch 1', 'left')
        self.switch.add_level('Switch 2', 'right')
        self.switch.add_level('Both_Click', 'both')
        self.switch.add_level('Switch 1 Double Click', 'left_double')
        self.switch.add_level('Switch 2 Double Click', 'right_double')
        self.switch.add_level('Both Double Click', 'both_double')
        self.switch.add_level('Switch 1 Long Click', 'left_long')
        self.switch.add_level('Switch 2 Long Click', 'right_long')
        self.switch.add_level('Both Long Click', 'both_long')
        self.switch.set_selector_style(SelectorSwitch.SELECTOR_TYPE_MENU)

        self.devices.append(self.switch)

    def handleCommand(self, alias, device, device_data, command, level, color):
        self.switch.handle_command(device_data, command, level, color)


```
Restart zigbee2mqtt (to be sure)
Start Domoticz

Device should be added again but now with all the possible options, I've set it to menu because the amount of options is too much to render :)

**Comment by stas-demydiuk** [comment]
@StevenBoelhouwer thanks for the workaround, but I don't know how to add native support to plugin as only some of WXKG02LM switches support new states and we need somehow recognize them from the other ones.

**Comment by StevenBoelhouwer** [comment]
Ah, I see! Too bad for hardware in different versions but keeping the same modelname...
This should be something for the zigbee2mqtt project then.

**Comment by Mayki07** [comment]
Thank you for your help, it works well.

**Comment by DamienCL** [comment]
(Hi, sorry for my english ...)
I have try to follow StevenBoelhouwer indication but i have only switch 1 , 2 and both click again.
What can i do ?

**Comment by bizziebis** [comment]
> @StevenBoelhouwer thanks for the workaround, but I don't know how to add native support to plugin as only some of WXKG02LM switches support new states and we need somehow recognize them from the other ones.

I also have one of those 'Gen 2' wall switches. I've modified the WXKG02LM file to accomodate the extra selector switches. This works just fine. 

I'm wondering if we can just make those switch options default. That way people with the new version of the switch can use all the options. Older versions of the switch do show the extra options, but will not trigger them. That can be confusing, I have to admit. Maybe create something (ugly) like this as a (temporary) fix?:

```
        self.switch.add_level('Off', None)
        self.switch.add_level('Switch 1', 'left')
        self.switch.add_level('Switch 2', 'right')
        self.switch.add_level('Both_Click', 'both')
        self.switch.add_level('Switch 1 Double Click (Gen.2)', 'left_double')
        self.switch.add_level('Switch 2 Double Click (Gen.2)', 'right_double')
        self.switch.add_level('Both Double Click (Gen.2)', 'both_double')
        self.switch.add_level('Switch 1 Long Click (Gen.2)', 'left_long')
        self.switch.add_level('Switch 2 Long Click (Gen.2)', 'right_long')
        self.switch.add_level('Both Long Click (Gen.2)', 'both_long')
```

Then every user at least has a chance to use the extra switch options until there is a way to distinguish the both versions.

**Comment by smarticz** [comment]
Why this task is closed and not added to main repo?
